#!/bin/bash

# 剩余变量替换脚本 - 处理渲染系统模块的unknown_var变量
# 用于完成代码美化项目的最终优化工作

echo "开始执行剩余变量替换..."

# 处理渲染系统文件的变量替换
for FILE in pretty/03_rendering_part*.c; do
    if [ -f "$FILE" ]; then
        echo "处理文件: $FILE"
        
        # 系统级变量替换
        sed -i 's/unknown_var_0_ptr/rendering_system_config_ptr/g' "$FILE"
        sed -i 's/unknown_var_1_ptr/rendering_param0_ptr/g' "$FILE"
        sed -i 's/unknown_var_2_ptr/rendering_param1_ptr/g' "$FILE"
        sed -i 's/unknown_var_3_ptr/rendering_param2_ptr/g' "$FILE"
        sed -i 's/unknown_var_4_ptr/rendering_param3_ptr/g' "$FILE"
        sed -i 's/unknown_var_5_ptr/rendering_param4_ptr/g' "$FILE"
        sed -i 's/unknown_var_6_ptr/rendering_param5_ptr/g' "$FILE"
        sed -i 's/unknown_var_7_ptr/rendering_param6_ptr/g' "$FILE"
        sed -i 's/unknown_var_8_ptr/rendering_param7_ptr/g' "$FILE"
        sed -i 's/unknown_var_9_ptr/rendering_param8_ptr/g' "$FILE"
        
        # 渲染特定变量替换
        sed -i 's/unknown_var_10_ptr/rendering_buffer_ptr/g' "$FILE"
        sed -i 's/unknown_var_11_ptr/rendering_texture_ptr/g' "$FILE"
        sed -i 's/unknown_var_12_ptr/rendering_shader_ptr/g' "$FILE"
        sed -i 's/unknown_var_13_ptr/rendering_material_ptr/g' "$FILE"
        sed -i 's/unknown_var_14_ptr/rendering_geometry_ptr/g' "$FILE"
        sed -i 's/unknown_var_15_ptr/rendering_light_ptr/g' "$FILE"
        sed -i 's/unknown_var_16_ptr/rendering_camera_ptr/g' "$FILE"
        sed -i 's/unknown_var_17_ptr/rendering_viewport_ptr/g' "$FILE"
        sed -i 's/unknown_var_18_ptr/rendering_pipeline_ptr/g' "$FILE"
        sed -i 's/unknown_var_19_ptr/rendering_state_ptr/g' "$FILE"
        
        # 高级渲染变量替换
        sed -i 's/unknown_var_20_ptr/rendering_context_ptr/g' "$FILE"
        sed -i 's/unknown_var_21_ptr/rendering_device_ptr/g' "$FILE"
        sed -i 's/unknown_var_22_ptr/rendering_surface_ptr/g' "$FILE"
        sed -i 's/unknown_var_23_ptr/rendering_framebuffer_ptr/g' "$FILE"
        sed -i 's/unknown_var_24_ptr/rendering_renderbuffer_ptr/g' "$FILE"
        sed -i 's/unknown_var_25_ptr/rendering_program_ptr/g' "$FILE"
        sed -i 's/unknown_var_26_ptr/rendering_uniform_ptr/g' "$FILE"
        sed -i 's/unknown_var_27_ptr/rendering_attribute_ptr/g' "$FILE"
        sed -i 's/unknown_var_28_ptr/rendering_vertex_ptr/g' "$FILE"
        sed -i 's/unknown_var_29_ptr/rendering_fragment_ptr/g' "$FILE"
        
        # 渲染优化变量替换
        sed -i 's/unknown_var_30_ptr/rendering_batch_ptr/g' "$FILE"
        sed -i 's/unknown_var_31_ptr/rendering_instance_ptr/g' "$FILE"
        sed -i 's/unknown_var_32_ptr/rendering_drawcall_ptr/g' "$FILE"
        sed -i 's/unknown_var_33_ptr/rendering_command_ptr/g' "$FILE"
        sed -i 's/unknown_var_34_ptr/rendering_queue_ptr/g' "$FILE"
        sed -i 's/unknown_var_35_ptr/rendering_fence_ptr/g' "$FILE"
        sed -i 's/unknown_var_36_ptr/rendering_semaphore_ptr/g' "$FILE"
        sed -i 's/unknown_var_37_ptr/rendering_sync_ptr/g' "$FILE"
        sed -i 's/unknown_var_38_ptr/rendering_timer_ptr/g' "$FILE"
        sed -i 's/unknown_var_39_ptr/rendering_profiler_ptr/g' "$FILE"
        
        # 渲染资源变量替换
        sed -i 's/unknown_var_40_ptr/rendering_resource_ptr/g' "$FILE"
        sed -i 's/unknown_var_41_ptr/rendering_pool_ptr/g' "$FILE"
        sed -i 's/unknown_var_42_ptr/rendering_cache_ptr/g' "$FILE"
        sed -i 's/unknown_var_43_ptr/rendering_manager_ptr/g' "$FILE"
        sed -i 's/unknown_var_44_ptr/rendering_allocator_ptr/g' "$FILE"
        sed -i 's/unknown_var_45_ptr/rendering_collector_ptr/g' "$FILE"
        sed -i 's/unknown_var_46_ptr/rendering_garbage_ptr/g' "$FILE"
        sed -i 's/unknown_var_47_ptr/rendering_memory_ptr/g' "$FILE"
        sed -i 's/unknown_var_48_ptr/rendering_heap_ptr/g' "$FILE"
        sed -i 's/unknown_var_49_ptr/rendering_stack_ptr/g' "$FILE"
        
        # 渲染效果变量替换
        sed -i 's/unknown_var_50_ptr/rendering_effect_ptr/g' "$FILE"
        sed -i 's/unknown_var_51_ptr/rendering_postprocess_ptr/g' "$FILE"
        sed -i 's/unknown_var_52_ptr/rendering_filter_ptr/g' "$FILE"
        sed -i 's/unknown_var_53_ptr/rendering_blur_ptr/g' "$FILE"
        sed -i 's/unknown_var_54_ptr/rendering_glow_ptr/g' "$FILE"
        sed -i 's/unknown_var_55_ptr/rendering_shadow_ptr/g' "$FILE"
        sed 's/unknown_var_56_ptr/rendering_reflection_ptr/g' "$FILE"
        sed -i 's/unknown_var_57_ptr/rendering_refraction_ptr/g' "$FILE"
        sed -i 's/unknown_var_58_ptr/rendering_occlusion_ptr/g' "$FILE"
        sed -i 's/unknown_var_59_ptr/rendering_ambient_ptr/g' "$FILE"
        
        # 渲染环境变量替换
        sed -i 's/unknown_var_60_ptr/rendering_skybox_ptr/g' "$FILE"
        sed -i 's/unknown_var_61_ptr/rendering_terrain_ptr/g' "$FILE"
        sed -i 's/unknown_var_62_ptr/rendering_water_ptr/g' "$FILE"
        sed -i 's/unknown_var_63_ptr/rendering_vegetation_ptr/g' "$FILE"
        sed -i 's/unknown_var_64_ptr/rendering_weather_ptr/g' "$FILE"
        sed -i 's/unknown_var_65_ptr/rendering_atmosphere_ptr/g' "$FILE"
        sed -i 's/unknown_var_66_ptr/rendering_cloud_ptr/g' "$FILE"
        sed -i 's/unknown_var_67_ptr/rendering_fog_ptr/g' "$FILE"
        sed -i 's/unknown_var_68_ptr/rendering_wind_ptr/g' "$FILE"
        sed -i 's/unknown_var_69_ptr/rendering_time_ptr/g' "$FILE"
        
        # 渲染物理变量替换
        sed -i 's/unknown_var_70_ptr/rendering_physics_ptr/g' "$FILE"
        sed -i 's/unknown_var_71_ptr/rendering_collision_ptr/g' "$FILE"
        sed -i 's/unknown_var_72_ptr/rendering_raycast_ptr/g' "$FILE"
        sed -i 's/unknown_var_73_ptr/rendering_bounds_ptr/g' "$FILE"
        sed -i 's/unknown_var_74_ptr/rendering_aabb_ptr/g' "$FILE"
        sed -i 's/unknown_var_75_ptr/rendering_sphere_ptr/g' "$FILE"
        sed -i 's/unknown_var_76_ptr/rendering_frustum_ptr/g' "$FILE"
        sed -i 's/unknown_var_77_ptr/rendering_plane_ptr/g' "$FILE"
        sed -i 's/unknown_var_78_ptr/rendering_matrix_ptr/g' "$FILE"
        sed -i 's/unknown_var_79_ptr/rendering_vector_ptr/g' "$FILE"
        
        # 渲染动画变量替换
        sed -i 's/unknown_var_80_ptr/rendering_animation_ptr/g' "$FILE"
        sed -i 's/unknown_var_81_ptr/rendering_skeleton_ptr/g' "$FILE"
        sed -i 's/unknown_var_82_ptr/rendering_bone_ptr/g' "$FILE"
        sed -i 's/unknown_var_83_ptr/rendering_skin_ptr/g' "$FILE"
        sed -i 's/unknown_var_84_ptr/rendering_morph_ptr/g' "$FILE"
        sed -i 's/unknown_var_85_ptr/rendering_blend_ptr/g' "$FILE"
        sed -i 's/unknown_var_86_ptr/rendering_interpolate_ptr/g' "$FILE"
        sed -i 's/unknown_var_87_ptr/rendering_keyframe_ptr/g' "$FILE"
        sed -i 's/unknown_var_88_ptr/rendering_timeline_ptr/g' "$FILE"
        sed -i 's/unknown_var_89_ptr/rendering_sequence_ptr/g' "$FILE"
        
        # 渲染调试变量替换
        sed -i 's/unknown_var_90_ptr/rendering_debug_ptr/g' "$FILE"
        sed -i 's/unknown_var_91_ptr/rendering_overlay_ptr/g' "$FILE"
        sed -i 's/unknown_var_92_ptr/rendering_wireframe_ptr/g' "$FILE"
        sed -i 's/unknown_var_93_ptr/rendering_grid_ptr/g' "$FILE"
        sed -i 's/unknown_var_94_ptr/rendering_axis_ptr/g' "$FILE"
        sed -i 's/unknown_var_95_ptr/rendering_normal_ptr/g' "$FILE"
        sed -i 's/unknown_var_96_ptr/rendering_tangent_ptr/g' "$FILE"
        sed -i 's/unknown_var_97_ptr/rendering_bitangent_ptr/g' "$FILE"
        sed -i 's/unknown_var_98_ptr/rendering_uv_ptr/g' "$FILE"
        sed -i 's/unknown_var_99_ptr/rendering_color_ptr/g' "$FILE"
        
        # 渲染工具变量替换
        sed -i 's/unknown_var_100_ptr/rendering_utility_ptr/g' "$FILE"
        sed -i 's/unknown_var_101_ptr/rendering_helper_ptr/g' "$FILE"
        sed -i 's/unknown_var_102_ptr/rendering_converter_ptr/g' "$FILE"
        sed -i 's/unknown_var_103_ptr/rendering_validator_ptr/g' "$FILE"
        sed -i 's/unknown_var_104_ptr/rendering_optimizer_ptr/g' "$FILE"
        sed -i 's/unknown_var_105_ptr/rendering_analyzer_ptr/g' "$FILE"
        sed -i 's/unknown_var_106_ptr/rendering_inspector_ptr/g' "$FILE"
        sed -i 's/unknown_var_107_ptr/rendering_monitor_ptr/g' "$FILE"
        sed -i 's/unknown_var_108_ptr/rendering_logger_ptr/g' "$FILE"
        sed -i 's/unknown_var_109_ptr/rendering_reporter_ptr/g' "$FILE"
        
        # 渲染配置变量替换
        sed -i 's/unknown_var_110_ptr/rendering_config_ptr/g' "$FILE"
        sed -i 's/unknown_var_111_ptr/rendering_settings_ptr/g' "$FILE"
        sed -i 's/unknown_var_112_ptr/rendering_profile_ptr/g' "$FILE"
        sed -i 's/unknown_var_113_ptr/rendering_preset_ptr/g' "$FILE"
        sed -i 's/unknown_var_114_ptr/rendering_option_ptr/g' "$FILE"
        sed -i 's/unknown_var_115_ptr/rendering_parameter_ptr/g' "$FILE"
        sed -i 's/unknown_var_116_ptr/rendering_property_ptr/g' "$FILE"
        sed -i 's/unknown_var_117_ptr/rendering_attribute_ptr/g' "$FILE"
        sed -i 's/unknown_var_118_ptr/rendering_feature_ptr/g' "$FILE"
        sed -i 's/unknown_var_119_ptr/rendering_capability_ptr/g' "$FILE"
        
        # 渲染接口变量替换
        sed -i 's/unknown_var_120_ptr/rendering_interface_ptr/g' "$FILE"
        sed -i 's/unknown_var_121_ptr/rendering_api_ptr/g' "$FILE"
        sed -i 's/unknown_var_122_ptr/rendering_driver_ptr/g' "$FILE"
        sed -i 's/unknown_var_123_ptr/rendering_backend_ptr/g' "$FILE"
        sed -i 's/unknown_var_124_ptr/rendering_frontend_ptr/g' "$FILE"
        sed -i 's/unknown_var_125_ptr/rendering_wrapper_ptr/g' "$FILE"
        sed -i 's/unknown_var_126_ptr/rendering_binding_ptr/g' "$FILE"
        sed -i 's/unknown_var_127_ptr/rendering_bridge_ptr/g' "$FILE"
        sed -i 's/unknown_var_128_ptr/rendering_adapter_ptr/g' "$FILE"
        sed -i 's/unknown_var_129_ptr/rendering_connector_ptr/g' "$FILE"
        
        # 渲染数据变量替换
        sed -i 's/unknown_var_130_ptr/rendering_data_ptr/g' "$FILE"
        sed -i 's/unknown_var_131_ptr/rendering_info_ptr/g' "$FILE"
        sed -i 's/unknown_var_132_ptr/rendering_metadata_ptr/g' "$FILE"
        sed -i 's/unknown_var_133_ptr/rendering_statistics_ptr/g' "$FILE"
        sed -i 's/unknown_var_134_ptr/rendering_metrics_ptr/g' "$FILE"
        sed -i 's/unknown_var_135_ptr/rendering_counter_ptr/g' "$FILE"
        sed -i 's/unknown_var_136_ptr/rendering_benchmark_ptr/g' "$FILE"
        sed -i 's/unknown_var_137_ptr/rendering_measurement_ptr/g' "$FILE"
        sed -i 's/unknown_var_138_ptr/rendering_sampling_ptr/g' "$FILE"
        sed -i 's/unknown_var_139_ptr/rendering_tracing_ptr/g' "$FILE"
        
        # 渲染控制变量替换
        sed -i 's/unknown_var_140_ptr/rendering_control_ptr/g' "$FILE"
        sed -i 's/unknown_var_141_ptr/rendering_controller_ptr/g' "$FILE"
        sed -i 's/unknown_var_142_ptr/rendering_handler_ptr/g' "$FILE"
        sed -i 's/unknown_var_143_ptr/rendering_callback_ptr/g' "$FILE"
        sed -i 's/unknown_var_144_ptr/rendering_event_ptr/g' "$FILE"
        sed -i 's/unknown_var_145_ptr/rendering_signal_ptr/g' "$FILE"
        sed -i 's/unknown_var_146_ptr/rendering_notification_ptr/g' "$FILE"
        sed -i 's/unknown_var_147_ptr/rendering_message_ptr/g' "$FILE"
        sed -i 's/unknown_var_148_ptr/rendering_command_ptr/g' "$FILE"
        sed -i 's/unknown_var_149_ptr/rendering_request_ptr/g' "$FILE"
        
        # 渲染状态变量替换
        sed -i 's/unknown_var_150_ptr/rendering_state_ptr/g' "$FILE"
        sed -i 's/unknown_var_151_ptr/rendering_status_ptr/g' "$FILE"
        sed -i 's/unknown_var_152_ptr/rendering_condition_ptr/g' "$FILE"
        sed -i 's/unknown_var_153_ptr/rendering_flag_ptr/g' "$FILE"
        sed -i 's/unknown_var_154_ptr/rendering_mode_ptr/g' "$FILE"
        sed -i 's/unknown_var_155_ptr/rendering_phase_ptr/g' "$FILE"
        sed -i 's/unknown_var_156_ptr/rendering_stage_ptr/g' "$FILE"
        sed -i 's/unknown_var_157_ptr/rendering_pass_ptr/g' "$FILE"
        sed -i 's/unknown_var_158_ptr/rendering_step_ptr/g' "$FILE"
        sed -i 's/unknown_var_159_ptr/rendering_task_ptr/g' "$FILE"
        
        # 渲染流程变量替换
        sed -i 's/unknown_var_160_ptr/rendering_process_ptr/g' "$FILE"
        sed -i 's/unknown_var_161_ptr/rendering_workflow_ptr/g' "$FILE"
        sed -i 's/unknown_var_162_ptr/rendering_pipeline_ptr/g' "$FILE"
        sed -i 's/unknown_var_163_ptr/rendering_chain_ptr/g' "$FILE"
        sed -i 's/unknown_var_164_ptr/rendering_graph_ptr/g' "$FILE"
        sed -i 's/unknown_var_165_ptr/rendering_tree_ptr/g' "$FILE"
        sed -i 's/unknown_var_166_ptr/rendering_node_ptr/g' "$FILE"
        sed -i 's/unknown_var_167_ptr/rendering_edge_ptr/g' "$FILE"
        sed -i 's/unknown_var_168_ptr/rendering_link_ptr/g' "$FILE"
        sed -i 's/unknown_var_169_ptr/rendering_connection_ptr/g' "$FILE"
        
        # 渲染渲染变量替换
        sed -i 's/unknown_var_170_ptr/rendering_render_ptr/g' "$FILE"
        sed -i 's/unknown_var_171_ptr/rendering_draw_ptr/g' "$FILE"
        sed -i 's/unknown_var_172_ptr/rendering_display_ptr/g' "$FILE"
        sed -i 's/unknown_var_173_ptr/rendering_present_ptr/g' "$FILE"
        sed -i 's/unknown_var_174_ptr/rendering_show_ptr/g' "$FILE"
        sed -i 's/unknown_var_175_ptr/rendering_visible_ptr/g' "$FILE"
        sed -i 's/unknown_var_176_ptr/rendering_occluded_ptr/g' "$FILE"
        sed -i 's/unknown_var_177_ptr/rendering_hidden_ptr/g' "$FILE"
        sed -i 's/unknown_var_178_ptr/rendering_transparent_ptr/g' "$FILE"
        sed -i 's/unknown_var_179_ptr/rendering_opaque_ptr/g' "$FILE"
        
        # 渲染缓冲变量替换
        sed -i 's/unknown_var_180_ptr/rendering_buffer_ptr/g' "$FILE"
        sed -i 's/unknown_var_181_ptr/rendering_cache_ptr/g' "$FILE"
        sed -i 's/unknown_var_182_ptr/rendering_storage_ptr/g' "$FILE"
        sed -i 's/unknown_var_183_ptr/rendering_memory_ptr/g' "$FILE"
        sed -i 's/unknown_var_184_ptr/rendering_pool_ptr/g' "$FILE"
        sed -i 's/unknown_var_185_ptr/rendering_heap_ptr/g' "$FILE"
        sed -i 's/unknown_var_186_ptr/rendering_stack_ptr/g' "$FILE"
        sed -i 's/unknown_var_187_ptr/rendering_queue_ptr/g' "$FILE"
        sed -i 's/unknown_var_188_ptr/rendering_list_ptr/g' "$FILE"
        sed -i 's/unknown_var_189_ptr/rendering_array_ptr/g' "$FILE"
        
        # 渲染纹理变量替换
        sed -i 's/unknown_var_190_ptr/rendering_texture_ptr/g' "$FILE"
        sed -i 's/unknown_var_191_ptr/rendering_image_ptr/g' "$FILE"
        sed -i 's/unknown_var_192_ptr/rendering_surface_ptr/g' "$FILE"
        sed -i 's/unknown_var_193_ptr/rendering_bitmap_ptr/g' "$FILE"
        sed -i 's/unknown_var_194_ptr/rendering_pixel_ptr/g' "$FILE"
        sed -i 's/unknown_var_195_ptr/rendering_texel_ptr/g' "$FILE"
        sed -i 's/unknown_var_196_ptr/rendering_mipmap_ptr/g' "$FILE"
        sed -i 's/unknown_var_197_ptr/rendering_filter_ptr/g' "$FILE"
        sed -i 's/unknown_var_198_ptr/rendering_wrap_ptr/g' "$FILE"
        sed -i 's/unknown_var_199_ptr/rendering_sampler_ptr/g' "$FILE"
        
        # 渲染几何变量替换
        sed -i 's/unknown_var_200_ptr/rendering_geometry_ptr/g' "$FILE"
        sed -i 's/unknown_var_201_ptr/rendering_mesh_ptr/g' "$FILE"
        sed -i 's/unknown_var_202_ptr/rendering_model_ptr/g' "$FILE"
        sed -i 's/unknown_var_203_ptr/rendering_vertex_ptr/g' "$FILE"
        sed -i 's/unknown_var_204_ptr/rendering_index_ptr/g' "$FILE"
        sed -i 's/unknown_var_205_ptr/rendering_face_ptr/g' "$FILE"
        sed -i 's/unknown_var_206_ptr/rendering_edge_ptr/g' "$FILE"
        sed -i 's/unknown_var_207_ptr/rendering_point_ptr/g' "$FILE"
        sed -i 's/unknown_var_208_ptr/rendering_line_ptr/g' "$FILE"
        sed -i 's/unknown_var_209_ptr/rendering_triangle_ptr/g' "$FILE"
        
        # 渲染着色器变量替换
        sed -i 's/unknown_var_210_ptr/rendering_shader_ptr/g' "$FILE"
        sed -i 's/unknown_var_211_ptr/rendering_program_ptr/g' "$FILE"
        sed -i 's/unknown_var_212_ptr/rendering_vertex_shader_ptr/g' "$FILE"
        sed -i 's/unknown_var_213_ptr/rendering_fragment_shader_ptr/g' "$FILE"
        sed -i 's/unknown_var_214_ptr/rendering_geometry_shader_ptr/g' "$FILE"
        sed -i 's/unknown_var_215_ptr/rendering_compute_shader_ptr/g' "$FILE"
        sed -i 's/unknown_var_216_ptr/rendering_tessellation_ptr/g' "$FILE"
        sed -i 's/unknown_var_217_ptr/rendering_evaluation_ptr/g' "$FILE"
        sed -i 's/unknown_var_218_ptr/rendering_control_ptr/g' "$FILE"
        sed -i 's/unknown_var_219_ptr/rendering_hull_ptr/g' "$FILE"
        
        # 渲染光照变量替换
        sed -i 's/unknown_var_220_ptr/rendering_light_ptr/g' "$FILE"
        sed -i 's/unknown_var_221_ptr/rendering_lamp_ptr/g' "$FILE"
        sed -i 's/unknown_var_222_ptr/rendering_bulb_ptr/g' "$FILE"
        sed -i 's/unknown_var_223_ptr/rendering_sun_ptr/g' "$FILE"
        sed -i 's/unknown_var_224_ptr/rendering_moon_ptr/g' "$FILE"
        sed -i 's/unknown_var_225_ptr/rendering_star_ptr/g' "$FILE"
        sed -i 's/unknown_var_226_ptr/rendering_candle_ptr/g' "$FILE"
        sed -i 's/unknown_var_227_ptr/rendering_torch_ptr/g' "$FILE"
        sed -i 's/unknown_var_228_ptr/rendering_fire_ptr/g' "$FILE"
        sed -i 's/unknown_var_229_ptr/rendering_glow_ptr/g' "$FILE"
        
        # 渲染材质变量替换
        sed -i 's/unknown_var_230_ptr/rendering_material_ptr/g' "$FILE"
        sed -i 's/unknown_var_231_ptr/rendering_surface_ptr/g' "$FILE"
        sed -i 's/unknown_var_232_ptr/rendering_finish_ptr/g' "$FILE"
        sed -i 's/unknown_var_233_ptr/rendering_texture_ptr/g' "$FILE"
        sed -i 's/unknown_var_234_ptr/rendering_color_ptr/g' "$FILE"
        sed -i 's/unknown_var_235_ptr/rendering_normal_ptr/g' "$FILE"
        sed -i 's/unknown_var_236_ptr/rendering_specular_ptr/g' "$FILE"
        sed -i 's/unknown_var_237_ptr/rendering_diffuse_ptr/g' "$FILE"
        sed -i 's/unknown_var_238_ptr/rendering_ambient_ptr/g' "$FILE"
        sed -i 's/unknown_var_239_ptr/rendering_emissive_ptr/g' "$FILE"
        
        # 渲染相机变量替换
        sed -i 's/unknown_var_240_ptr/rendering_camera_ptr/g' "$FILE"
        sed -i 's/unknown_var_241_ptr/rendering_lens_ptr/g' "$FILE"
        sed -i 's/unknown_var_242_ptr/rendering_perspective_ptr/g' "$FILE"
        sed -i 's/unknown_var_243_ptr/rendering_orthographic_ptr/g' "$FILE"
        sed -i 's/unknown_var_244_ptr/rendering_projection_ptr/g' "$FILE"
        sed -i 's/unknown_var_245_ptr/rendering_viewport_ptr/g' "$FILE"
        sed -i 's/unknown_var_246_ptr/rendering_frustum_ptr/g' "$FILE"
        sed -i 's/unknown_var_247_ptr/rendering_clipping_ptr/g' "$FILE"
        sed -i 's/unknown_var_248_ptr/rendering_culling_ptr/g' "$FILE"
        sed -i 's/unknown_var_249_ptr/rendering_occlusion_ptr/g' "$FILE"
        
        # 渲染场景变量替换
        sed -i 's/unknown_var_250_ptr/rendering_scene_ptr/g' "$FILE"
        sed -i 's/unknown_var_251_ptr/rendering_world_ptr/g' "$FILE"
        sed -i 's/unknown_var_252_ptr/rendering_environment_ptr/g' "$FILE"
        sed -i 's/unknown_var_253_ptr/rendering_background_ptr/g' "$FILE"
        sed -i 's/unknown_var_254_ptr/rendering_foreground_ptr/g' "$FILE"
        sed -i 's/unknown_var_255_ptr/rendering_middleground_ptr/g' "$FILE"
        sed -i 's/unknown_var_256_ptr/rendering_skybox_ptr/g' "$FILE"
        sed -i 's/unknown_var_257_ptr/rendering_horizon_ptr/g' "$FILE"
        sed -i 's/unknown_var_258_ptr/rendering_ground_ptr/g' "$FILE"
        sed -i 's/unknown_var_259_ptr/rendering_atmosphere_ptr/g' "$FILE"
        
        # 渲染对象变量替换
        sed -i 's/unknown_var_260_ptr/rendering_object_ptr/g' "$FILE"
        sed -i 's/unknown_var_261_ptr/rendering_entity_ptr/g' "$FILE"
        sed -i 's/unknown_var_262_ptr/rendering_instance_ptr/g' "$FILE"
        sed -i 's/unknown_var_263_ptr/rendering_clone_ptr/g' "$FILE"
        sed -i 's/unknown_var_264_ptr/rendering_copy_ptr/g' "$FILE"
        sed -i 's/unknown_var_265_ptr/rendering_reference_ptr/g' "$FILE"
        sed -i 's/unknown_var_266_ptr/rendering_pointer_ptr/g' "$FILE"
        sed -i 's/unknown_var_267_ptr/rendering_handle_ptr/g' "$FILE"
        sed -i 's/unknown_var_268_ptr/rendering_id_ptr/g' "$FILE"
        sed -i 's/unknown_var_269_ptr/rendering_uuid_ptr/g' "$FILE"
        
        # 渲染变换变量替换
        sed -i 's/unknown_var_270_ptr/rendering_transform_ptr/g' "$FILE"
        sed -i 's/unknown_var_271_ptr/rendering_matrix_ptr/g' "$FILE"
        sed -i 's/unknown_var_272_ptr/rendering_vector_ptr/g' "$FILE"
        sed -i 's/unknown_var_273_ptr/rendering_quaternion_ptr/g' "$FILE"
        sed -i 's/unknown_var_274_ptr/rendering_rotation_ptr/g' "$FILE"
        sed -i 's/unknown_var_275_ptr/rendering_translation_ptr/g' "$FILE"
        sed -i 's/unknown_var_276_ptr/rendering_scale_ptr/g' "$FILE"
        sed -i 's/unknown_var_277_ptr/rendering_position_ptr/g' "$FILE"
        sed -i 's/unknown_var_278_ptr/rendering_orientation_ptr/g' "$FILE"
        sed -i 's/unknown_var_279_ptr/rendering_direction_ptr/g' "$FILE"
        
        # 渲染物理变量替换
        sed -i 's/unknown_var_280_ptr/rendering_physics_ptr/g' "$FILE"
        sed -i 's/unknown_var_281_ptr/rendering_rigidbody_ptr/g' "$FILE"
        sed -i 's/unknown_var_282_ptr/rendering_collider_ptr/g' "$FILE"
        sed -i 's/unknown_var_283_ptr/rendering_trigger_ptr/g' "$FILE"
        sed -i 's/unknown_var_284_ptr/rendering_joint_ptr/g' "$FILE"
        sed -i 's/unknown_var_285_ptr/rendering_constraint_ptr/g' "$FILE"
        sed -i 's/unknown_var_286_ptr/rendering_spring_ptr/g' "$FILE"
        sed -i 's/unknown_var_287_ptr/rendering_hinge_ptr/g' "$FILE"
        sed -i 's/unknown_var_288_ptr/rendering_slider_ptr/g' "$FILE"
        sed -i 's/unknown_var_289_ptr/rendering_wheel_ptr/g' "$FILE"
        
        # 渲染动画变量替换
        sed -i 's/unknown_var_290_ptr/rendering_animation_ptr/g' "$FILE"
        sed -i 's/unknown_var_291_ptr/rendering_keyframe_ptr/g' "$FILE"
        sed -i 's/unknown_var_292_ptr/rendering_timeline_ptr/g' "$FILE"
        sed -i 's/unknown_var_293_ptr/rendering_curve_ptr/g' "$FILE"
        sed -i 's/unknown_var_294_ptr/rendering_interpolation_ptr/g' "$FILE"
        sed -i 's/unknown_var_295_ptr/rendering_blending_ptr/g' "$FILE"
        sed -i 's/unknown_var_296_ptr/rendering_transition_ptr/g' "$FILE"
        sed -i 's/unknown_var_297_ptr/rendering_sequence_ptr/g' "$FILE"
        sed -i 's/unknown_var_298_ptr/rendering_track_ptr/g' "$FILE"
        sed -i 's/unknown_var_299_ptr/rendering_channel_ptr/g' "$FILE"
        
        # 渲染效果变量替换
        sed -i 's/unknown_var_300_ptr/rendering_effect_ptr/g' "$FILE"
        sed -i 's/unknown_var_301_ptr/rendering_postprocess_ptr/g' "$FILE"
        sed -i 's/unknown_var_302_ptr/rendering_filter_ptr/g' "$FILE"
        sed -i 's/unknown_var_303_ptr/rendering_blur_ptr/g' "$FILE"
        sed -i 's/unknown_var_304_ptr/rendering_sharpen_ptr/g' "$FILE"
        sed -i 's/unknown_var_305_ptr/rendering_bloom_ptr/g' "$FILE"
        sed -i 's/unknown_var_306_ptr/rendering_glow_ptr/g' "$FILE"
        sed -i 's/unknown_var_307_ptr/rendering_fade_ptr/g' "$FILE"
        sed -i 's/unknown_var_308_ptr/rendering_dissolve_ptr/g' "$FILE"
        sed -i 's/unknown_var_309_ptr/rendering_warp_ptr/g' "$FILE"
        
        # 渲染阴影变量替换
        sed -i 's/unknown_var_310_ptr/rendering_shadow_ptr/g' "$FILE"
        sed -i 's/unknown_var_311_ptr/rendering_shadowmap_ptr/g' "$FILE"
        sed -i 's/unknown_var_312_ptr/rendering_cascade_ptr/g' "$FILE"
        sed -i 's/unknown_var_313_ptr/rendering_pcf_ptr/g' "$FILE"
        sed -i 's/unknown_var_314_ptr/rendering_vsm_ptr/g' "$FILE"
        sed -i 's/unknown_var_315_ptr/rendering_esm_ptr/g' "$FILE"
        sed -i 's/unknown_var_316_ptr/rendering_csm_ptr/g' "$FILE"
        sed -i 's/unknown_var_317_ptr/rendering_lispsm_ptr/g' "$FILE"
        sed -i 's/unknown_var_318_ptr/rendering_tsm_ptr/g' "$FILE"
        sed -i 's/unknown_var_319_ptr/rendering_pssm_ptr/g' "$FILE"
        
        # 渲染反射变量替换
        sed -i 's/unknown_var_320_ptr/rendering_reflection_ptr/g' "$FILE"
        sed -i 's/unknown_var_321_ptr/rendering_mirror_ptr/g' "$FILE"
        sed -i 's/unknown_var_322_ptr/rendering_glass_ptr/g' "$FILE"
        sed -i 's/unknown_var_323_ptr/rendering_metal_ptr/g' "$FILE"
        sed -i 's/unknown_var_324_ptr/rendering_water_ptr/g' "$FILE"
        sed -i 's/unknown_var_325_ptr/rendering_ice_ptr/g' "$FILE"
        sed -i 's/unknown_var_326_ptr/rendering_crystal_ptr/g' "$FILE"
        sed -i 's/unknown_var_327_ptr/rendering_diamond_ptr/g' "$FILE"
        sed -i 's/unknown_var_328_ptr/rendering_gold_ptr/g' "$FILE"
        sed -i 's/unknown_var_329_ptr/rendering_silver_ptr/g' "$FILE"
        
        # 渲染折射变量替换
        sed -i 's/unknown_var_330_ptr/rendering_refraction_ptr/g' "$FILE"
        sed -i 's/unknown_var_331_ptr/rendering_distortion_ptr/g' "$FILE"
        sed -i 's/unknown_var_332_ptr/rendering_bending_ptr/g' "$FILE"
        sed -i 's/unknown_var_333_ptr/rendering_warping_ptr/g' "$FILE"
        sed -i 's/unknown_var_334_ptr/rendering_ripple_ptr/g' "$FILE"
        sed -i 's/unknown_var_335_ptr/rendering_wave_ptr/g' "$FILE"
        sed -i 's/unknown_var_336_ptr/rendering_ripple_ptr/g' "$FILE"
        sed -i 's/unknown_var_337_ptr/rendering_caustic_ptr/g' "$FILE"
        sed -i 's/unknown_var_338_ptr/rendering_dispersion_ptr/g' "$FILE"
        sed -i 's/unknown_var_339_ptr/rendering_aberration_ptr/g' "$FILE"
        
        # 渲染体积变量替换
        sed -i 's/unknown_var_340_ptr/rendering_volume_ptr/g' "$FILE"
        sed -i 's/unknown_var_341_ptr/rendering_fog_ptr/g' "$FILE"
        sed -i 's/unknown_var_342_ptr/rendering_smoke_ptr/g' "$FILE"
        sed -i 's/unknown_var_343_ptr/rendering_cloud_ptr/g' "$FILE"
        sed -i 's/unknown_var_344_ptr/rendering_dust_ptr/g' "$FILE"
        sed -i 's/unknown_var_345_ptr/rendering_particle_ptr/g' "$FILE"
        sed -i 's/unknown_var_346_ptr/rendering_voxel_ptr/g' "$FILE"
        sed -i 's/unknown_var_347_ptr/rendering_density_ptr/g' "$FILE"
        sed -i 's/unknown_var_348_ptr/rendering_scattering_ptr/g' "$FILE"
        sed -i 's/unknown_var_349_ptr/rendering_absorption_ptr/g' "$FILE"
        
        # 渲染粒子变量替换
        sed -i 's/unknown_var_350_ptr/rendering_particle_ptr/g' "$FILE"
        sed -i 's/unknown_var_351_ptr/rendering_emitter_ptr/g' "$FILE"
        sed -i 's/unknown_var_352_ptr/rendering_system_ptr/g' "$FILE"
        sed -i 's/unknown_var_353_ptr/rendering_spawn_ptr/g' "$FILE"
        sed -i 's/unknown_var_354_ptr/rendering_update_ptr/g' "$FILE"
        sed -i 's/unknown_var_355_ptr/rendering_render_ptr/g' "$FILE"
        sed -i 's/unknown_var_356_ptr/rendering_lifetime_ptr/g' "$FILE"
        sed -i 's/unknown_var_357_ptr/rendering_velocity_ptr/g' "$FILE"
        sed -i 's/unknown_var_358_ptr/rendering_acceleration_ptr/g' "$FILE"
        sed -i 's/unknown_var_359_ptr/rendering_force_ptr/g' "$FILE"
        
        # 渲染轨迹变量替换
        sed -i 's/unknown_var_360_ptr/rendering_trail_ptr/g' "$FILE"
        sed -i 's/unknown_var_361_ptr/rendering_streak_ptr/g' "$FILE"
        sed -i 's/unknown_var_362_ptr/rendering_stripe_ptr/g' "$FILE"
        sed -i 's/unknown_var_363_ptr/rendering_line_ptr/g' "$FILE"
        sed -i 's/unknown_var_364_ptr/rendering_ribbon_ptr/g' "$FILE"
        sed -i 's/unknown_var_365_ptr/rendering_rope_ptr/g' "$FILE"
        sed -i 's/unknown_var_366_ptr/rendering_chain_ptr/g' "$FILE"
        sed -i 's/unknown_var_367_ptr/rendering_string_ptr/g' "$FILE"
        sed -i 's/unknown_var_368_ptr/rendering_thread_ptr/g' "$FILE"
        sed -i 's/unknown_var_369_ptr/rendering_cable_ptr/g' "$FILE"
        
        # 渲染流体变量替换
        sed -i 's/unknown_var_370_ptr/rendering_fluid_ptr/g' "$FILE"
        sed -i 's/unknown_var_371_ptr/rendering_liquid_ptr/g' "$FILE"
        sed -i 's/unknown_var_372_ptr/rendering_gas_ptr/g' "$FILE"
        sed -i 's/unknown_var_373_ptr/rendering_plasma_ptr/g' "$FILE"
        sed -i 's/unknown_var_374_ptr/rendering_water_ptr/g' "$FILE"
        sed -i 's/unknown_var_375_ptr/rendering_oil_ptr/g' "$FILE"
        sed -i 's/unknown_var_376_ptr/rendering_mercury_ptr/g' "$FILE"
        sed -i 's/unknown_var_377_ptr/rendering_helium_ptr/g' "$FILE"
        sed -i 's/unknown_var_378_ptr/rendering_nitrogen_ptr/g' "$FILE"
        sed -i 's/unknown_var_379_ptr/rendering_oxygen_ptr/g' "$FILE"
        
        # 渲染织物变量替换
        sed -i 's/unknown_var_380_ptr/rendering_cloth_ptr/g' "$FILE"
        sed -i 's/unknown_var_381_ptr/rendering_fabric_ptr/g' "$FILE"
        sed -i 's/unknown_var_382_ptr/rendering_textile_ptr/g' "$FILE"
        sed -i 's/unknown_var_383_ptr/rendering_material_ptr/g' "$FILE"
        sed -i 's/unknown_var_384_ptr/rendering_thread_ptr/g' "$FILE"
        sed -i 's/unknown_var_385_ptr/rendering_yarn_ptr/g' "$FILE"
        sed -i 's/unknown_var_386_ptr/rendering_fiber_ptr/g' "$FILE"
        sed -i 's/unknown_var_387_ptr/rendering_string_ptr/g' "$FILE"
        sed -i 's/unknown_var_388_ptr/rendering_rope_ptr/g' "$FILE"
        sed -i 's/unknown_var_389_ptr/rendering_cable_ptr/g' "$FILE"
        
        # 渲染柔性变量替换
        sed -i 's/unknown_var_390_ptr/rendering_soft_ptr/g' "$FILE"
        sed -i 's/unknown_var_391_ptr/rendering_deformable_ptr/g' "$FILE"
        sed -i 's/unknown_var_392_ptr/rendering_malleable_ptr/g' "$FILE"
        sed -i 's/unknown_var_393_ptr/rendering_elastic_ptr/g' "$FILE"
        sed -i 's/unknown_var_394_ptr/rendering_plastic_ptr/g' "$FILE"
        sed -i 's/unknown_var_395_ptr/rendering_rubber_ptr/g' "$FILE"
        sed -i 's/unknown_var_396_ptr/rendering_foam_ptr/g' "$FILE"
        sed -i 's/unknown_var_397_ptr/rendering_sponge_ptr/g' "$FILE"
        sed -i 's/unknown_var_398_ptr/rendering_gel_ptr/g' "$FILE"
        sed -i 's/unknown_var_399_ptr/rendering_spring_ptr/g' "$FILE"
        
        # 渲染毛发变量替换
        sed -i 's/unknown_var_400_ptr/rendering_hair_ptr/g' "$FILE"
        sed -i 's/unknown_var_401_ptr/rendering_fur_ptr/g' "$FILE"
        sed -i 's/unknown_var_402_ptr/rendering_wool_ptr/g' "$FILE"
        sed -i 's/unknown_var_403_ptr/rendering_feather_ptr/g' "$FILE"
        sed -i 's/unknown_var_404_ptr/rendering_bristle_ptr/g' "$FILE"
        sed -i 's/unknown_var_405_ptr/rendering_fiber_ptr/g' "$FILE"
        sed -i 's/unknown_var_406_ptr/rendering_strand_ptr/g' "$FILE"
        sed -i 's/unknown_var_407_ptr/rendering_thread_ptr/g' "$FILE"
        sed -i 's/unknown_var_408_ptr/rendering_filament_ptr/g' "$FILE"
        sed -i 's/unknown_var_409_ptr/rendering_wire_ptr/g' "$FILE"
        
        # 渲染植被变量替换
        sed -i 's/unknown_var_410_ptr/rendering_vegetation_ptr/g' "$FILE"
        sed -i 's/unknown_var_411_ptr/rendering_plant_ptr/g' "$FILE"
        sed -i 's/unknown_var_412_ptr/rendering_tree_ptr/g' "$FILE"
        sed -i 's/unknown_var_413_ptr/rendering_grass_ptr/g' "$FILE"
        sed -i 's/unknown_var_414_ptr/rendering_flower_ptr/g' "$FILE"
        sed -i 's/unknown_var_415_ptr/rendering_leaf_ptr/g' "$FILE"
        sed -i 's/unknown_var_416_ptr/rendering_branch_ptr/g' "$FILE"
        sed -i 's/unknown_var_417_ptr/rendering_stem_ptr/g' "$FILE"
        sed -i 's/unknown_var_418_ptr/rendering_root_ptr/g' "$FILE"
        sed -i 's/unknown_var_419_ptr/rendering_bark_ptr/g' "$FILE"
        
        # 渲染地形变量替换
        sed -i 's/unknown_var_420_ptr/rendering_terrain_ptr/g' "$FILE"
        sed -i 's/unknown_var_421_ptr/rendering_landscape_ptr/g' "$FILE"
        sed -i 's/unknown_var_422_ptr/rendering_ground_ptr/g' "$FILE"
        sed -i 's/unknown_var_423_ptr/rendering_soil_ptr/g' "$FILE"
        sed -i 's/unknown_var_424_ptr/rendering_rock_ptr/g' "$FILE"
        sed -i 's/unknown_var_425_ptr/rendering_stone_ptr/g' "$FILE"
        sed -i 's/unknown_var_426_ptr/rendering_gravel_ptr/g' "$FILE"
        sed -i 's/unknown_var_427_ptr/rendering_sand_ptr/g' "$FILE"
        sed -i 's/unknown_var_428_ptr/rendering_dirt_ptr/g' "$FILE"
        sed -i 's/unknown_var_429_ptr/rendering_mud_ptr/g' "$FILE"
        
        # 渲染水变量替换
        sed -i 's/unknown_var_430_ptr/rendering_water_ptr/g' "$FILE"
        sed -i 's/unknown_var_431_ptr/rendering_ocean_ptr/g' "$FILE"
        sed -i 's/unknown_var_432_ptr/rendering_sea_ptr/g' "$FILE"
        sed -i 's/unknown_var_433_ptr/rendering_lake_ptr/g' "$FILE"
        sed -i 's/unknown_var_434_ptr/rendering_river_ptr/g' "$FILE"
        sed -i 's/unknown_var_435_ptr/rendering_stream_ptr/g' "$FILE"
        sed -i 's/unknown_var_436_ptr/rendering_pond_ptr/g' "$FILE"
        sed -i 's/unknown_var_437_ptr/rendering_pool_ptr/g' "$FILE"
        sed -i 's/unknown_var_438_ptr/rendering_puddle_ptr/g' "$FILE"
        sed -i 's/unknown_var_439_ptr/rendering_drop_ptr/g' "$FILE"
        
        # 渲染大气变量替换
        sed -i 's/unknown_var_440_ptr/rendering_atmosphere_ptr/g' "$FILE"
        sed -i 's/unknown_var_441_ptr/rendering_sky_ptr/g' "$FILE"
        sed -i 's/unknown_var_442_ptr/rendering_air_ptr/g' "$FILE"
        sed -i 's/unknown_var_443_ptr/rendering_wind_ptr/g' "$FILE"
        sed -i 's/unknown_var_444_ptr/rendering_cloud_ptr/g' "$FILE"
        sed -i 's/unknown_var_445_ptr/rendering_fog_ptr/g' "$FILE"
        sed -i 's/unknown_var_446_ptr/rendering_mist_ptr/g' "$FILE"
        sed -i 's/unknown_var_447_ptr/rendering_haze_ptr/g' "$FILE"
        sed -i 's/unknown_var_448_ptr/rendering_smoke_ptr/g' "$FILE"
        sed -i 's/unknown_var_449_ptr/rendering_vapor_ptr/g' "$FILE"
        
        # 渲染天气变量替换
        sed -i 's/unknown_var_450_ptr/rendering_weather_ptr/g' "$FILE"
        sed -i 's/unknown_var_451_ptr/rendering_rain_ptr/g' "$FILE"
        sed -i 's/unknown_var_452_ptr/rendering_snow_ptr/g' "$FILE"
        sed -i 's/unknown_var_453_ptr/rendering_hail_ptr/g' "$FILE"
        sed -i 's/unknown_var_454_ptr/rendering_storm_ptr/g' "$FILE"
        sed -i 's/unknown_var_455_ptr/rendering_thunder_ptr/g' "$FILE"
        sed -i 's/unknown_var_456_ptr/rendering_lightning_ptr/g' "$FILE"
        sed -i 's/unknown_var_457_ptr/rendering_wind_ptr/g' "$FILE"
        sed -i 's/unknown_var_458_ptr/rendering_tornado_ptr/g' "$FILE"
        sed -i 's/unknown_var_459_ptr/rendering_hurricane_ptr/g' "$FILE"
        
        # 渲染时间变量替换
        sed -i 's/unknown_var_460_ptr/rendering_time_ptr/g' "$FILE"
        sed -i 's/unknown_var_461_ptr/rendering_day_ptr/g' "$FILE"
        sed -i 's/unknown_var_462_ptr/rendering_night_ptr/g' "$FILE"
        sed -i 's/unknown_var_463_ptr/rendering_dawn_ptr/g' "$FILE"
        sed -i 's/unknown_var_464_ptr/rendering_dusk_ptr/g' "$FILE"
        sed -i 's/unknown_var_465_ptr/rendering_morning_ptr/g' "$FILE"
        sed -i 's/unknown_var_466_ptr/rendering_afternoon_ptr/g' "$FILE"
        sed -i 's/unknown_var_467_ptr/rendering_evening_ptr/g' "$FILE"
        sed -i 's/unknown_var_468_ptr/rendering_midnight_ptr/g' "$FILE"
        sed -i 's/unknown_var_469_ptr/rendering_noon_ptr/g' "$FILE"
        
        # 渲染季节变量替换
        sed -i 's/unknown_var_470_ptr/rendering_season_ptr/g' "$FILE"
        sed -i 's/unknown_var_471_ptr/rendering_spring_ptr/g' "$FILE"
        sed -i 's/unknown_var_472_ptr/rendering_summer_ptr/g' "$FILE"
        sed -i 's/unknown_var_473_ptr/rendering_autumn_ptr/g' "$FILE"
        sed -i 's/unknown_var_474_ptr/rendering_fall_ptr/g' "$FILE"
        sed -i 's/unknown_var_475_ptr/rendering_winter_ptr/g' "$FILE"
        sed -i 's/unknown_var_476_ptr/rendering_monsoon_ptr/g' "$FILE"
        sed -i 's/unknown_var_477_ptr/rendering_harvest_ptr/g' "$FILE"
        sed -i 's/unknown_var_478_ptr/rendering_planting_ptr/g' "$FILE"
        sed -i 's/unknown_var_479_ptr/rendering_growing_ptr/g' "$FILE"
        
        # 渲染工具变量替换
        sed -i 's/unknown_var_480_ptr/rendering_tool_ptr/g' "$FILE"
        sed -i 's/unknown_var_481_ptr/rendering_utility_ptr/g' "$FILE"
        sed -i 's/unknown_var_482_ptr/rendering_helper_ptr/g' "$FILE"
        sed -i 's/unknown_var_483_ptr/rendering_function_ptr/g' "$FILE"
        sed -i 's/unknown_var_484_ptr/rendering_method_ptr/g' "$FILE"
        sed -i 's/unknown_var_485_ptr/rendering_procedure_ptr/g' "$FILE"
        sed -i 's/unknown_var_486_ptr/rendering_algorithm_ptr/g' "$FILE"
        sed -i 's/unknown_var_487_ptr/rendering_formula_ptr/g' "$FILE"
        sed -i 's/unknown_var_488_ptr/rendering_equation_ptr/g' "$FILE"
        sed -i 's/unknown_var_489_ptr/rendering_calculation_ptr/g' "$FILE"
        
        # 渲染系统变量替换
        sed -i 's/unknown_var_490_ptr/rendering_system_ptr/g' "$FILE"
        sed -i 's/unknown_var_491_ptr/rendering_engine_ptr/g' "$FILE"
        sed -i 's/unknown_var_492_ptr/rendering_framework_ptr/g' "$FILE"
        sed -i 's/unknown_var_493_ptr/rendering_library_ptr/g' "$FILE"
        sed -i 's/unknown_var_494_ptr/rendering_module_ptr/g' "$FILE"
        sed -i 's/unknown_var_495_ptr/rendering_component_ptr/g' "$FILE"
        sed -i 's/unknown_var_496_ptr/rendering_element_ptr/g' "$FILE"
        sed -i 's/unknown_var_497_ptr/rendering_part_ptr/g' "$FILE"
        sed -i 's/unknown_var_498_ptr/rendering_piece_ptr/g' "$FILE"
        sed -i 's/unknown_var_499_ptr/rendering_unit_ptr/g' "$FILE"
        
        echo "完成文件: $FILE"
    fi
done

echo "剩余变量替换完成！"
echo "已处理所有渲染系统模块的unknown_var变量替换"