#!/bin/bash

# 网络系统特殊变量名美化脚本
# 用于美化05_networking.c文件中的特殊变量名

FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c"

# 美化特殊变量名
sed -i 's/extraout_XMM0_Qa_00/extraout_XMM0_Qa_00/g' "$FILE"
sed -i 's/extraout_XMM0_Qa_01/extraout_XMM0_Qa_01/g' "$FILE"
sed -i 's/extraout_XMM0_Qa_02/extraout_XMM0_Qa_02/g' "$FILE"
sed -i 's/extraout_XMM0_Qa_03/extraout_XMM0_Qa_03/g' "$FILE"
sed -i 's/extraout_XMM0_Qa_04/extraout_XMM0_Qa_04/g' "$FILE"
sed -i 's/extraout_XMM0_Qa_05/extraout_XMM0_Qa_05/g' "$FILE"
sed -i 's/extraout_XMM0_Qa_06/extraout_XMM0_Qa_06/g' "$FILE"
sed -i 's/aiStackX_8/aiStackX_8/g' "$FILE"
sed -i 's/dStackX_10/dStackX_10/g' "$FILE"
sed -i 's/adStack_38/adStack_38/g' "$FILE"
sed -i 's/dStackX_20/dStackX_20/g' "$FILE"
sed -i 's/network_error_var2/network_error_var2/g' "$FILE"
sed -i 's/network_error_var3/network_error_var3/g' "$FILE"
sed -i 's/network_stack_double_precision_value/network_stack_double_precision_value/g' "$FILE"
sed -i 's/network_float_transfer_rate/network_float_transfer_rate/g' "$FILE"
sed -i 's/network_temp_float_primary/network_temp_float_primary/g' "$FILE"
sed -i 's/network_current_char/network_current_char/g' "$FILE"
sed -i 's/network_temp_char_third/network_temp_char_third/g' "$FILE"
sed -i 's/network_temp_char/network_temp_char/g' "$FILE"
sed -i 's/cStack_68/cStack_68/g' "$FILE"
sed -i 's/network_stack_char_buffer/network_stack_char_buffer/g' "$FILE"
sed -i 's/network_connection_flag/network_connection_flag/g' "$FILE"
sed -i 's/network_temp_return_value/network_temp_return_value/g' "$FILE"
sed -i 's/network_packet_state/network_packet_state/g' "$FILE"
sed -i 's/network_connection_temp_array/network_connection_temp_array/g' "$FILE"
sed -i 's/network_connection_identifier_extended/network_connection_identifier_extended/g' "$FILE"
sed -i 's/network_connection_identifierentifier/network_connection_identifierentifier/g' "$FILE"
sed -i 's/network_packet_size_pointer1/network_packet_size_pointer1/g' "$FILE"
sed -i 's/network_connection_counter_pointer/network_connection_counter_pointer/g' "$FILE"
sed -i 's/network_connection_data_offset_primary_ptr/network_connection_data_offset_primary_ptr/g' "$FILE"
sed -i 's/network_processing_register/network_processing_register/g' "$FILE"
sed -i 's/network_secondary_register/network_secondary_register/g' "$FILE"
sed -i 's/network_register_temp_secondary/network_register_temp_secondary/g' "$FILE"
sed -i 's/network_secondary_value_timeout/network_secondary_value_timeout/g' "$FILE"
sed -i 's/network_connection_main_status/network_connection_main_status/g' "$FILE"
sed -i 's/network_connection_size_value/network_connection_size_value/g' "$FILE"
sed -i 's/network_header_temp_buffer/network_header_temp_buffer/g' "$FILE"
sed -i 's/network_buffer_temporary/network_buffer_temporary/g' "$FILE"
sed -i 's/network_stack_long_secondary_buffer/network_stack_long_secondary_buffer/g' "$FILE"
sed -i 's/network_current_timeout/network_current_timeout/g' "$FILE"
sed -i 's/network_buffer_current_length/network_buffer_current_length/g' "$FILE"
sed -i 's/network_status_code_main/network_status_code_main/g' "$FILE"
sed -i 's/network_stack_long_connection_status/network_stack_long_connection_status/g' "$FILE"
sed -i 's/network_unaffiliated_register_r13/network_unaffiliated_register_r13/g' "$FILE"
sed -i 's/network_configuration_offset/network_configuration_offset/g' "$FILE"
sed -i 's/network_validation_status/network_validation_status/g' "$FILE"
sed -i 's/network_data_processed/network_data_processed/g' "$FILE"
sed -i 's/network_active_connection_count/network_active_connection_count/g' "$FILE"
sed -i 's/network_packet_identifier/network_packet_identifier/g' "$FILE"
sed -i 's/network_connection_process_operation/network_connection_process_operation/g' "$FILE"
sed -i 's/network_internal_read_buffer/network_internal_read_buffer/g' "$FILE"
sed -i 's/network_socket_validate_connection_task/network_socket_validate_connection_task/g' "$FILE"
sed -i 's/network_socket_complete_auth/network_socket_complete_auth/g' "$FILE"
sed -i 's/network_socket_manage_transfer/network_socket_manage_transfer/g' "$FILE"
sed -i 's/network_internal_process_resource/network_internal_process_resource/g' "$FILE"
sed -i 's/network_handle_connection_request/network_handle_connection_request/g' "$FILE"
sed -i 's/network_socket_control_transfer/network_socket_control_transfer/g' "$FILE"
sed -i 's/network_packet_extract_character_data/network_packet_extract_character_data/g' "$FILE"
sed -i 's/network_socket_function_get_workspace/network_socket_function_get_workspace/g' "$FILE"
sed -i 's/network_socket_initialize_connection/network_socket_initialize_connection/g' "$FILE"
sed -i 's/network_socket_quota_connection/network_socket_quota_connection/g' "$FILE"

echo "特殊变量名美化完成"