#!/bin/bash

# 美化渲染系统硬编码十六进制值的脚本
# 简化实现：仅将常见的硬编码十六进制值替换为语义化常量
# 原本实现：完全重构所有硬编码值体系，建立统一的硬编码值命名规范

# 文件路径
FILE_PATH="/dev/shm/mountblade-code/TaleWorlds.Native/src/03_rendering.c"

# 备份文件
cp "$FILE_PATH" "$FILE_PATH.bak"

# 定义需要替换的硬编码十六进制值和对应的语义化常量
declare -A replacements=(
    # 之前未处理的硬编码十六进制值
    ["0x1c68"]="RENDER_CONTEXT_SIZE_LARGE"
    ["0x248"]="RENDER_CONTEXT_OFFSET_RENDER_QUEUE"
    ["0x58"]="RENDER_HANDLE_OFFSET_QUEUE"
    ["0x228"]="RENDER_CONTEXT_OFFSET_TEXTURE_DATA_ARRAY"
    ["0x230"]="RENDER_CONTEXT_OFFSET_TEXTURE_DATA_POINTER"
    ["0x240"]="RENDER_CONTEXT_OFFSET_TEXTURE_DATA_SIZE"
    ["0x208"]="RENDER_CONTEXT_OFFSET_LEGACY_TEXTURE_ARRAY"
    ["0x210"]="RENDER_CONTEXT_OFFSET_LEGACY_TEXTURE_POINTER"
    ["0x220"]="RENDER_CONTEXT_OFFSET_LEGACY_TEXTURE_SIZE"
    ["0x1e8"]="RENDER_CONTEXT_OFFSET_SECONDARY_TEXTURE_ARRAY"
    ["0x1f0"]="RENDER_CONTEXT_OFFSET_SECONDARY_TEXTURE_POINTER"
    ["0x200"]="RENDER_CONTEXT_OFFSET_SECONDARY_TEXTURE_SIZE"
    ["0x1c8"]="RENDER_CONTEXT_OFFSET_TERTIARY_TEXTURE_ARRAY"
    ["0x1d0"]="RENDER_CONTEXT_OFFSET_TERTIARY_TEXTURE_POINTER"
    ["0x1e0"]="RENDER_CONTEXT_OFFSET_TERTIARY_TEXTURE_SIZE"
    ["0x1a8"]="RENDER_CONTEXT_OFFSET_QUATERNARY_TEXTURE_ARRAY"
    ["0x1b0"]="RENDER_CONTEXT_OFFSET_QUATERNARY_TEXTURE_POINTER"
    ["0x180"]="RENDER_CONTEXT_OFFSET_QUATERNARY_TEXTURE_SIZE"
    ["0x168"]="RENDER_CONTEXT_OFFSET_FINAL_TEXTURE_ARRAY"
    ["0x170"]="RENDER_CONTEXT_OFFSET_FINAL_TEXTURE_POINTER"
    ["0x148"]="RENDER_CONTEXT_OFFSET_RESERVE_TEXTURE_ARRAY"
    ["0x150"]="RENDER_CONTEXT_OFFSET_RESERVE_TEXTURE_POINTER"
    ["0x110"]="RENDER_CONTEXT_OFFSET_TEMP_TEXTURE_POINTER"
    ["0x118"]="RENDER_CONTEXT_OFFSET_TEMP_TEXTURE_SIZE"
    ["0x65"]="RENDER_CONTEXT_INDEX_RENDER_STATE"
    ["0x66"]="RENDER_CONTEXT_INDEX_RENDER_MODE"
    ["0x67"]="RENDER_CONTEXT_INDEX_RENDER_CONFIG"
    ["0x68"]="RENDER_CONTEXT_INDEX_RENDER_BUFFER"
    ["0x69"]="RENDER_CONTEXT_INDEX_RENDER_SHADER"
    ["0x6a"]="RENDER_CONTEXT_INDEX_RENDER_PIPELINE"
    ["0x6b"]="RENDER_CONTEXT_INDEX_RENDER_TARGET"
    ["0x34"]="RENDER_CONTEXT_OFFSET_RENDER_DATA"
    ["0x40"]="RENDER_CONTEXT_OFFSET_RENDER_TRANSFORM"
    ["0x48"]="RENDER_CONTEXT_OFFSET_RENDER_PROJECTION"
    ["0x38"]="RENDER_CONTEXT_OFFSET_RENDER_SHADER_DATA"
)

# 添加语义化常量定义到文件开头
sed -i '/^#define RENDER_ALPHA_SCALE_FACTOR 29\.0/a\\n// 新增渲染系统上下文大小常量 - 美化硬编码十六进制值（2025年8月30日最终批次）\n// 简化实现：仅将常见的硬编码十六进制值替换为语义化常量\n// 原本实现：完全重构所有硬编码值体系\n#define RENDER_CONTEXT_SIZE_LARGE 0x1c68\n#define RENDER_CONTEXT_OFFSET_RENDER_QUEUE 0x248\n#define RENDER_HANDLE_OFFSET_QUEUE 0x58\n#define RENDER_CONTEXT_OFFSET_TEXTURE_DATA_ARRAY 0x228\n#define RENDER_CONTEXT_OFFSET_TEXTURE_DATA_POINTER 0x230\n#define RENDER_CONTEXT_OFFSET_TEXTURE_DATA_SIZE 0x240\n#define RENDER_CONTEXT_OFFSET_LEGACY_TEXTURE_ARRAY 0x208\n#define RENDER_CONTEXT_OFFSET_LEGACY_TEXTURE_POINTER 0x210\n#define RENDER_CONTEXT_OFFSET_LEGACY_TEXTURE_SIZE 0x220\n#define RENDER_CONTEXT_OFFSET_SECONDARY_TEXTURE_ARRAY 0x1e8\n#define RENDER_CONTEXT_OFFSET_SECONDARY_TEXTURE_POINTER 0x1f0\n#define RENDER_CONTEXT_OFFSET_SECONDARY_TEXTURE_SIZE 0x200\n#define RENDER_CONTEXT_OFFSET_TERTIARY_TEXTURE_ARRAY 0x1c8\n#define RENDER_CONTEXT_OFFSET_TERTIARY_TEXTURE_POINTER 0x1d0\n#define RENDER_CONTEXT_OFFSET_TERTIARY_TEXTURE_SIZE 0x1e0\n#define RENDER_CONTEXT_OFFSET_QUATERNARY_TEXTURE_ARRAY 0x1a8\n#define RENDER_CONTEXT_OFFSET_QUATERNARY_TEXTURE_POINTER 0x1b0\n#define RENDER_CONTEXT_OFFSET_QUATERNARY_TEXTURE_SIZE 0x180\n#define RENDER_CONTEXT_OFFSET_FINAL_TEXTURE_ARRAY 0x168\n#define RENDER_CONTEXT_OFFSET_FINAL_TEXTURE_POINTER 0x170\n#define RENDER_CONTEXT_OFFSET_RESERVE_TEXTURE_ARRAY 0x148\n#define RENDER_CONTEXT_OFFSET_RESERVE_TEXTURE_POINTER 0x150\n#define RENDER_CONTEXT_OFFSET_TEMP_TEXTURE_POINTER 0x110\n#define RENDER_CONTEXT_OFFSET_TEMP_TEXTURE_SIZE 0x118\n\n// 新增渲染系统上下文索引常量 - 美化硬编码十六进制值（2025年8月30日最终批次）\n#define RENDER_CONTEXT_INDEX_RENDER_STATE 0x65\n#define RENDER_CONTEXT_INDEX_RENDER_MODE 0x66\n#define RENDER_CONTEXT_INDEX_RENDER_CONFIG 0x67\n#define RENDER_CONTEXT_INDEX_RENDER_BUFFER 0x68\n#define RENDER_CONTEXT_INDEX_RENDER_SHADER 0x69\n#define RENDER_CONTEXT_INDEX_RENDER_PIPELINE 0x6a\n#define RENDER_CONTEXT_INDEX_RENDER_TARGET 0x6b\n\n// 新增渲染系统上下文偏移量常量 - 美化硬编码十六进制值（2025年8月30日最终批次）\n#define RENDER_CONTEXT_OFFSET_RENDER_DATA 0x34\n#define RENDER_CONTEXT_OFFSET_RENDER_TRANSFORM 0x40\n#define RENDER_CONTEXT_OFFSET_RENDER_PROJECTION 0x48\n#define RENDER_CONTEXT_OFFSET_RENDER_SHADER_DATA 0x38' "$FILE_PATH"

# 执行替换操作
for hex_value in "${!replacements[@]}"; do
    semantic_name="${replacements[$hex_value]}"
    echo "替换 $hex_value 为 $semantic_name"
    sed -i "s/0x$hex_value/$semantic_name/g" "$FILE_PATH"
done

echo "渲染系统硬编码十六进制值美化完成"