using System;
using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem
{
	// Token: 0x02000065 RID: 101
	public class QuestTaskBase
	{
		// Token: 0x06000DC6 RID: 3526 RVA: 0x000445C4 File Offset: 0x000427C4
		internal static void AutoGeneratedStaticCollectObjectsQuestTaskBase(object o, List<object> collectedObjects)
		{
			((QuestTaskBase)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06000DC7 RID: 3527 RVA: 0x000445D2 File Offset: 0x000427D2
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x06000DC8 RID: 3528 RVA: 0x000445D4 File Offset: 0x000427D4
		internal static object AutoGeneratedGetMemberValueIsLogged(object o)
		{
			return ((QuestTaskBase)o).IsLogged;
		}

		// Token: 0x06000DC9 RID: 3529 RVA: 0x000445E6 File Offset: 0x000427E6
		internal static object AutoGeneratedGetMemberValueIsActive(object o)
		{
			return ((QuestTaskBase)o).IsActive;
		}

		// Token: 0x1700035A RID: 858
		// (get) Token: 0x06000DCA RID: 3530 RVA: 0x000445F8 File Offset: 0x000427F8
		// (set) Token: 0x06000DCB RID: 3531 RVA: 0x00044600 File Offset: 0x00042800
		[SaveableProperty(1)]
		public bool IsLogged { get; set; }

		// Token: 0x1700035B RID: 859
		// (get) Token: 0x06000DCC RID: 3532 RVA: 0x00044609 File Offset: 0x00042809
		// (set) Token: 0x06000DCD RID: 3533 RVA: 0x00044611 File Offset: 0x00042811
		[SaveableProperty(2)]
		public bool IsActive { get; private set; }

		// Token: 0x06000DCE RID: 3534 RVA: 0x0004461C File Offset: 0x0004281C
		public QuestTaskBase(DialogFlow dialogFlow = null, Action onSucceedAction = null, Action onFailedAction = null, Action onCanceledAction = null)
		{
			this.IsLogged = true;
			this.IsActive = true;
			this._onSucceededAction = onSucceedAction;
			this._onFailedAction = onFailedAction;
			this._onCanceledAction = onCanceledAction;
			this._dialogFlow = dialogFlow;
			if (this._dialogFlow != null)
			{
				Campaign.Current.ConversationManager.AddDialogFlow(this._dialogFlow, this);
			}
		}

		// Token: 0x06000DCF RID: 3535 RVA: 0x00044678 File Offset: 0x00042878
		public void Finish(QuestTaskBase.FinishStates finishState)
		{
			this.IsActive = false;
			if (this._dialogFlow != null)
			{
				Campaign.Current.ConversationManager.RemoveRelatedLines(this);
				this._dialogFlow = null;
			}
			switch (finishState)
			{
			case QuestTaskBase.FinishStates.Success:
				if (this._onSucceededAction != null)
				{
					this._onSucceededAction();
				}
				break;
			case QuestTaskBase.FinishStates.Fail:
				if (this._onFailedAction != null)
				{
					this._onFailedAction();
				}
				break;
			case QuestTaskBase.FinishStates.Cancel:
				if (this._onCanceledAction != null)
				{
					this._onCanceledAction();
				}
				break;
			}
			this._onSucceededAction = null;
			this._onFailedAction = null;
			this._onCanceledAction = null;
			CampaignEventDispatcher.Instance.RemoveListeners(this);
			this.OnFinished();
		}

		// Token: 0x06000DD0 RID: 3536 RVA: 0x00044722 File Offset: 0x00042922
		public void AddTaskDialogs()
		{
			if (this._dialogFlow != null)
			{
				Campaign.Current.ConversationManager.AddDialogFlow(this._dialogFlow, this);
			}
		}

		// Token: 0x06000DD1 RID: 3537 RVA: 0x00044742 File Offset: 0x00042942
		protected virtual void OnFinished()
		{
		}

		// Token: 0x06000DD2 RID: 3538 RVA: 0x00044744 File Offset: 0x00042944
		public virtual void SetReferences()
		{
		}

		// Token: 0x06000DD3 RID: 3539 RVA: 0x00044746 File Offset: 0x00042946
		public void AddTaskDialogOnGameLoaded(DialogFlow dialogFlow)
		{
			if (this.IsActive)
			{
				this._dialogFlow = dialogFlow;
			}
		}

		// Token: 0x06000DD4 RID: 3540 RVA: 0x00044757 File Offset: 0x00042957
		public void AddTaskBehaviorsOnGameLoad(Action onSucceededAction = null, Action onFailedAction = null, Action onCanceledAction = null)
		{
			this._onSucceededAction = onSucceededAction;
			this._onFailedAction = onFailedAction;
			this._onCanceledAction = onCanceledAction;
		}

		// Token: 0x040003F3 RID: 1011
		protected Dictionary<EventDelegateType, TriggerDelegateType> EvenTriggerDelegates;

		// Token: 0x040003F6 RID: 1014
		private DialogFlow _dialogFlow;

		// Token: 0x040003F7 RID: 1015
		private Action _onSucceededAction;

		// Token: 0x040003F8 RID: 1016
		private Action _onFailedAction;

		// Token: 0x040003F9 RID: 1017
		private Action _onCanceledAction;

		// Token: 0x020004BA RID: 1210
		public enum FinishStates
		{
			// Token: 0x0400146F RID: 5231
			Success,
			// Token: 0x04001470 RID: 5232
			Fail,
			// Token: 0x04001471 RID: 5233
			Cancel
		}
	}
}
