// Decompiled with JetBrains decompiler
// Type: TaleWorlds.CampaignSystem.Siege.SiegeStrategy
// Assembly: TaleWorlds.CampaignSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E85F8C15-4DF6-4E9C-A58A-29177E40D07A
// Assembly location: D:\steam\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll

using System.Collections.Generic;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

#nullable disable
namespace TaleWorlds.CampaignSystem.Siege
{
  public class SiegeStrategy : MBObjectBase
  {
    internal static void AutoGeneratedStaticCollectObjectsSiegeStrategy(
      object o,
      List<object> collectedObjects)
    {
      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
      base.AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    public static MBReadOnlyList<SiegeStrategy> All => Campaign.Current.AllSiegeStrategies;

    public TextObject Name { get; private set; }

    public TextObject Description { get; private set; }

    public SiegeStrategy(string stringId)
      : base(stringId)
    {
    }

    public void Initialize(TextObject name, TextObject description)
    {
      this.Initialize();
      this.Name = name;
      this.Description = description;
      this.AfterInitialized();
    }
  }
}
