using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.ViewModelCollection.InitialMenu;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x02000023 RID: 35
	public class InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM : Widget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x060006E9 RID: 1769 RVA: 0x00035F4B File Offset: 0x0003414B
		public InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM(UIContext context) : base(context)
		{
		}

		// Token: 0x060006EA RID: 1770 RVA: 0x00035F54 File Offset: 0x00034154
		private VisualDefinition CreateVisualDefinitionMainMenu()
		{
			VisualDefinition visualDefinition = new VisualDefinition("MainMenu", 0.4f, 0f, true);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				PositionYOffset = 0f
			});
			visualDefinition.AddVisualState(new VisualState("Activated")
			{
				PositionYOffset = 0f
			});
			return visualDefinition;
		}

		// Token: 0x060006EB RID: 1771 RVA: 0x00035FB0 File Offset: 0x000341B0
		private VisualDefinition CreateVisualDefinitionOptionFadeIn()
		{
			VisualDefinition visualDefinition = new VisualDefinition("OptionFadeIn", 0.3f, 0f, true);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				PositionXOffset = -20f
			});
			visualDefinition.AddVisualState(new VisualState("Activated")
			{
				PositionXOffset = 0f
			});
			return visualDefinition;
		}

		// Token: 0x060006EC RID: 1772 RVA: 0x0003600C File Offset: 0x0003420C
		private VisualDefinition CreateVisualDefinitionWarSailsComingSoonButton()
		{
			VisualDefinition visualDefinition = new VisualDefinition("WarSailsComingSoonButton", 0.22f, 0f, true);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				SuggestedWidth = 400f,
				SuggestedHeight = 233f
			});
			visualDefinition.AddVisualState(new VisualState("Hovered")
			{
				SuggestedWidth = 402f,
				SuggestedHeight = 235f
			});
			visualDefinition.AddVisualState(new VisualState("Pressed")
			{
				SuggestedWidth = 398f,
				SuggestedHeight = 231f
			});
			return visualDefinition;
		}

		// Token: 0x060006ED RID: 1773 RVA: 0x000360A8 File Offset: 0x000342A8
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0_0 = new Widget(base.Context);
			this._widget_0.AddChild(this._widget_0_0);
			this._widget_0_0_0 = new InitialMenuAnimControllerWidget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_0);
			this._widget_0_0_1 = new Widget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_1);
			this._widget_0_0_2 = new Widget(base.Context);
			this._widget_0_0.AddChild(this._widget_0_0_2);
			this._widget_0_0_2_0 = new ScrollablePanel(base.Context);
			this._widget_0_0_2.AddChild(this._widget_0_0_2_0);
			this._widget_0_0_2_0_0 = new Widget(base.Context);
			this._widget_0_0_2_0.AddChild(this._widget_0_0_2_0_0);
			this._widget_0_0_2_0_0_0 = new NavigationScopeTargeter(base.Context);
			this._widget_0_0_2_0_0.AddChild(this._widget_0_0_2_0_0_0);
			this._widget_0_0_2_0_0_1 = new NavigatableListPanel(base.Context);
			this._widget_0_0_2_0_0.AddChild(this._widget_0_0_2_0_0_1);
			this._widget_0_0_2_1 = new ScrollbarWidget(base.Context);
			this._widget_0_0_2.AddChild(this._widget_0_0_2_1);
			this._widget_0_0_2_1_0 = new Widget(base.Context);
			this._widget_0_0_2_1.AddChild(this._widget_0_0_2_1_0);
			this._widget_0_0_2_1_1 = new ImageWidget(base.Context);
			this._widget_0_0_2_1.AddChild(this._widget_0_0_2_1_1);
			this._widget_1 = new ListPanel(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new TextWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_2 = new Widget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2_0 = new TextWidget(base.Context);
			this._widget_2.AddChild(this._widget_2_0);
			this._widget_3 = new TextWidget(base.Context);
			this._widget.AddChild(this._widget_3);
			this._widget_4 = new NavigationScopeTargeter(base.Context);
			this._widget.AddChild(this._widget_4);
			this._widget_5 = new ButtonWidget(base.Context);
			this._widget.AddChild(this._widget_5);
			this._widget_5_0 = new BrushWidget(base.Context);
			this._widget_5.AddChild(this._widget_5_0);
			this._widget_5_1 = new BrushWidget(base.Context);
			this._widget_5.AddChild(this._widget_5_1);
			this._widget_5_2 = new BrushWidget(base.Context);
			this._widget_5.AddChild(this._widget_5_2);
		}

		// Token: 0x060006EE RID: 1774 RVA: 0x000363A8 File Offset: 0x000345A8
		public void SetIds()
		{
			this._widget_0_0_2.Id = "MenuItemsParent";
			this._widget_0_0_2_0.Id = "ScrollablePanel";
			this._widget_0_0_2_0_0.Id = "ClipRect";
			this._widget_0_0_2_0_0_1.Id = "MenuItems";
			this._widget_0_0_2_1.Id = "VerticalScrollbar";
			this._widget_0_0_2_1_1.Id = "VerticalScrollbarHandle";
			this._widget_5.Id = "WarSailsComingSoonButton";
		}

		// Token: 0x060006EF RID: 1775 RVA: 0x00036428 File Offset: 0x00034628
		public void SetAttributes()
		{
			base.WidthSizePolicy = 1;
			base.HeightSizePolicy = 1;
			base.DoNotAcceptEvents = true;
			this._widget_0.WidthSizePolicy = 0;
			this._widget_0.HeightSizePolicy = 1;
			this._widget_0.SuggestedWidth = 445f;
			this._widget_0.MarginLeft = 85f;
			this._widget_0.Sprite = base.Context.SpriteData.GetSprite("General\\InitialMenu\\main_menu_texture");
			this._widget_0_0.WidthSizePolicy = 1;
			this._widget_0_0.HeightSizePolicy = 1;
			this._widget_0_0.VerticalAlignment = 1;
			this._widget_0_0_0.OptionsList = this._widget_0_0.FindChild(new BindingPath("ScrollablePanel\\ClipRect\\MenuItems"));
			this._widget_0_0_0.InitialWaitTime = 0.2f;
			this._widget_0_0_0.WaitTimeBetweenOptions = 0.1f;
			this._widget_0_0_0.OptionFadeInTime = 0.2f;
			this._widget_0_0_0.IsAnimEnabled = false;
			this._widget_0_0_1.WidthSizePolicy = 0;
			this._widget_0_0_1.HeightSizePolicy = 0;
			this._widget_0_0_1.SuggestedWidth = 380f;
			this._widget_0_0_1.SuggestedHeight = 103f;
			this._widget_0_0_1.HorizontalAlignment = 1;
			this._widget_0_0_1.VerticalAlignment = 0;
			this._widget_0_0_1.MarginTop = 100f;
			this._widget_0_0_1.Sprite = base.Context.SpriteData.GetSprite("General\\InitialMenu\\main_menu_logo");
			this._widget_0_0_1.ForcePixelPerfectRenderPlacement = true;
			this._widget_0_0_2.WidthSizePolicy = 1;
			this._widget_0_0_2.HeightSizePolicy = 1;
			this._widget_0_0_2.MarginTop = 280f;
			this._widget_0_0_2.MarginBottom = 30f;
			this._widget_0_0_2.MarginLeft = 10f;
			this._widget_0_0_2.MarginRight = 10f;
			this._widget_0_0_2_0.WidthSizePolicy = 1;
			this._widget_0_0_2_0.HeightSizePolicy = 1;
			this._widget_0_0_2_0.AutoHideScrollBars = true;
			this._widget_0_0_2_0.ClipRect = this._widget_0_0_2_0_0;
			this._widget_0_0_2_0.InnerPanel = this._widget_0_0_2_0_0_1;
			this._widget_0_0_2_0.VerticalScrollbar = this._widget_0_0_2_1;
			this._widget_0_0_2_0_0.WidthSizePolicy = 1;
			this._widget_0_0_2_0_0.HeightSizePolicy = 1;
			this._widget_0_0_2_0_0.ClipContents = true;
			this._widget_0_0_2_0_0_0.ScopeID = "InitialScreen";
			this._widget_0_0_2_0_0_0.ScopeParent = this._widget_0_0_2_0_0_1;
			this._widget_0_0_2_0_0_0.ScopeMovements = 3;
			this._widget_0_0_2_0_0_0.HasCircularMovement = true;
			this._widget_0_0_2_0_0_1.WidthSizePolicy = 1;
			this._widget_0_0_2_0_0_1.HeightSizePolicy = 2;
			this._widget_0_0_2_0_0_1.MinHeight = 630f;
			this._widget_0_0_2_0_0_1.HorizontalAlignment = 1;
			this._widget_0_0_2_0_0_1.VerticalAlignment = 0;
			this._widget_0_0_2_0_0_1.MarginLeft = 20f;
			this._widget_0_0_2_0_0_1.MarginRight = 20f;
			this._widget_0_0_2_0_0_1.StackLayout.LayoutMethod = 4;
			this._widget_0_0_2_1.WidthSizePolicy = 0;
			this._widget_0_0_2_1.HeightSizePolicy = 1;
			this._widget_0_0_2_1.SuggestedWidth = 8f;
			this._widget_0_0_2_1.HorizontalAlignment = 2;
			this._widget_0_0_2_1.VerticalAlignment = 0;
			this._widget_0_0_2_1.MarginTop = 10f;
			this._widget_0_0_2_1.MarginBottom = 10f;
			this._widget_0_0_2_1.MarginRight = 10f;
			this._widget_0_0_2_1.AlignmentAxis = 1;
			this._widget_0_0_2_1.Handle = this._widget_0_0_2_1_1;
			this._widget_0_0_2_1.MaxValue = 100f;
			this._widget_0_0_2_1.MinValue = 0f;
			this._widget_0_0_2_1_0.WidthSizePolicy = 0;
			this._widget_0_0_2_1_0.HeightSizePolicy = 1;
			this._widget_0_0_2_1_0.SuggestedWidth = 2f;
			this._widget_0_0_2_1_0.HorizontalAlignment = 1;
			this._widget_0_0_2_1_0.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_0_0_2_1_0.Color = new Color(0.3529412f, 0.2509804f, 0.2f, 1f);
			this._widget_0_0_2_1_0.AlphaFactor = 0.2f;
			this._widget_0_0_2_1_1.WidthSizePolicy = 0;
			this._widget_0_0_2_1_1.HeightSizePolicy = 0;
			this._widget_0_0_2_1_1.SuggestedHeight = 10f;
			this._widget_0_0_2_1_1.SuggestedWidth = 4f;
			this._widget_0_0_2_1_1.HorizontalAlignment = 1;
			this._widget_0_0_2_1_1.Brush = base.Context.GetBrush("FaceGen.Scrollbar.Handle");
			this._widget_0_0_2_1_1.Brush.AlphaFactor = 0.7f;
			this._widget_1.WidthSizePolicy = 2;
			this._widget_1.HeightSizePolicy = 2;
			this._widget_1.HorizontalAlignment = 2;
			this._widget_1.VerticalAlignment = 2;
			this._widget_1.MarginBottom = 50f;
			this._widget_1.MarginRight = 50f;
			this._widget_1.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_1.Color = new Color(0f, 0f, 0f, 0.6666667f);
			this._widget_1.AlphaFactor = 0.7f;
			this._widget_1_0.WidthSizePolicy = 2;
			this._widget_1_0.HeightSizePolicy = 2;
			this._widget_1_0.Brush = base.Context.GetBrush("InitialMenuButtonBrush");
			this._widget_1_0.HorizontalAlignment = 1;
			this._widget_1_0.DoNotAcceptEvents = true;
			this._widget_1_0.MarginTop = 10f;
			this._widget_2.WidthSizePolicy = 2;
			this._widget_2.HeightSizePolicy = 2;
			this._widget_2.HorizontalAlignment = 2;
			this._widget_2.VerticalAlignment = 2;
			this._widget_2.MarginBottom = 250f;
			this._widget_2.MarginRight = 50f;
			this._widget_2.Sprite = base.Context.SpriteData.GetSprite("BlankWhiteSquare_9");
			this._widget_2.Color = new Color(0f, 0f, 0f, 0.6666667f);
			this._widget_2_0.WidthSizePolicy = 2;
			this._widget_2_0.HeightSizePolicy = 2;
			this._widget_2_0.MarginLeft = 10f;
			this._widget_2_0.MarginRight = 10f;
			this._widget_2_0.MarginTop = 5f;
			this._widget_2_0.MarginBottom = 5f;
			this._widget_3.WidthSizePolicy = 2;
			this._widget_3.HeightSizePolicy = 2;
			this._widget_3.HorizontalAlignment = 2;
			this._widget_3.VerticalAlignment = 2;
			this._widget_3.MarginBottom = 15f;
			this._widget_3.MarginRight = 15f;
			this._widget_3.Brush = base.Context.GetBrush("GameVersion.Text");
			this._widget_4.ScopeID = "WarSailsComingSoonButtonScope";
			this._widget_4.ScopeParent = this._widget_5;
			this._widget_5.DoNotPassEventsToChildren = true;
			this._widget_5.UpdateChildrenStates = true;
			this._widget_5.WidthSizePolicy = 0;
			this._widget_5.HeightSizePolicy = 0;
			this._widget_5.SuggestedWidth = 400f;
			this._widget_5.SuggestedHeight = 233f;
			this._widget_5.HorizontalAlignment = 0;
			this._widget_5.VerticalAlignment = 2;
			this._widget_5.MarginLeft = 550f;
			this._widget_5.MarginBottom = 10f;
			this._widget_5.ExtendCursorAreaLeft = -4f;
			this._widget_5.ExtendCursorAreaRight = -4f;
			this._widget_5.ExtendCursorAreaBottom = -4f;
			this._widget_5.ExtendCursorAreaTop = -28f;
			this._widget_5.GamepadNavigationIndex = 0;
			this._widget_5_0.VisualDefinition = this.CreateVisualDefinitionWarSailsComingSoonButton();
			this._widget_5_0.WidthSizePolicy = 0;
			this._widget_5_0.HeightSizePolicy = 0;
			this._widget_5_0.SuggestedWidth = 400f;
			this._widget_5_0.SuggestedHeight = 233f;
			this._widget_5_0.HorizontalAlignment = 1;
			this._widget_5_0.VerticalAlignment = 1;
			this._widget_5_0.Brush = base.Context.GetBrush("WarSails.ComingSoon.Button");
			this._widget_5_1.VisualDefinition = this.CreateVisualDefinitionWarSailsComingSoonButton();
			this._widget_5_1.WidthSizePolicy = 0;
			this._widget_5_1.HeightSizePolicy = 0;
			this._widget_5_1.SuggestedWidth = 400f;
			this._widget_5_1.SuggestedHeight = 233f;
			this._widget_5_1.HorizontalAlignment = 1;
			this._widget_5_1.VerticalAlignment = 1;
			this._widget_5_1.Brush = base.Context.GetBrush("WarSails.ComingSoon.Text");
			this._widget_5_2.VisualDefinition = this.CreateVisualDefinitionWarSailsComingSoonButton();
			this._widget_5_2.WidthSizePolicy = 0;
			this._widget_5_2.HeightSizePolicy = 0;
			this._widget_5_2.SuggestedWidth = 400f;
			this._widget_5_2.SuggestedHeight = 233f;
			this._widget_5_2.HorizontalAlignment = 1;
			this._widget_5_2.VerticalAlignment = 1;
			this._widget_5_2.Brush = base.Context.GetBrush("WarSails.ComingSoon.WishlistText");
		}

		// Token: 0x060006F0 RID: 1776 RVA: 0x00036D94 File Offset: 0x00034F94
		public void RefreshBindingWithChildren()
		{
			InitialMenuVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x060006F1 RID: 1777 RVA: 0x00036DB8 File Offset: 0x00034FB8
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0;
				this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
				this._widget_4.PropertyChanged -= this.PropertyChangedListenerOf_widget_4;
				this._widget_4.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_4;
				this._widget_4.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_4;
				this._widget_4.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_4;
				this._widget_4.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_4;
				this._widget_4.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_4;
				this._widget_4.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_4;
				this._widget_4.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_4;
				this._widget_4.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_4;
				this._widget_5.EventFire -= this.EventListenerOf_widget_5;
				this._widget_5.PropertyChanged -= this.PropertyChangedListenerOf_widget_5;
				this._widget_5.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5;
				this._widget_5.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5;
				this._widget_5.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5;
				this._widget_5.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5;
				this._widget_5.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5;
				this._widget_5.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5;
				this._widget_5.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5;
				this._widget_5.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5;
				this._widget_5_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5_1;
				this._widget_5_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5_2;
				if (this._datasource_Root_MenuOptions != null)
				{
					this._datasource_Root_MenuOptions.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_MenuOptionsChanged);
					for (int i = this._widget_0_0_2_0_0_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0_2_0_0_1.GetChild(i);
						((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)this._widget_0_0_2_0_0_1.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_MenuOptions = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x060006F2 RID: 1778 RVA: 0x00037671 File Offset: 0x00035871
		public void SetDataSource(InitialMenuVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060006F3 RID: 1779 RVA: 0x0003767A File Offset: 0x0003587A
		private void EventListenerOf_widget_5(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteNavigateToDLCStorePage();
			}
		}

		// Token: 0x060006F4 RID: 1780 RVA: 0x00037694 File Offset: 0x00035894
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006F5 RID: 1781 RVA: 0x0003769D File Offset: 0x0003589D
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006F6 RID: 1782 RVA: 0x000376A6 File Offset: 0x000358A6
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006F7 RID: 1783 RVA: 0x000376AF File Offset: 0x000358AF
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006F8 RID: 1784 RVA: 0x000376B8 File Offset: 0x000358B8
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006F9 RID: 1785 RVA: 0x000376C1 File Offset: 0x000358C1
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006FA RID: 1786 RVA: 0x000376CA File Offset: 0x000358CA
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006FB RID: 1787 RVA: 0x000376D3 File Offset: 0x000358D3
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006FC RID: 1788 RVA: 0x000376DC File Offset: 0x000358DC
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060006FD RID: 1789 RVA: 0x000376E5 File Offset: 0x000358E5
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsProfileSelectionEnabled = this._widget_1.IsVisible;
				return;
			}
		}

		// Token: 0x060006FE RID: 1790 RVA: 0x0003770B File Offset: 0x0003590B
		private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x060006FF RID: 1791 RVA: 0x00037714 File Offset: 0x00035914
		private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000700 RID: 1792 RVA: 0x0003771D File Offset: 0x0003591D
		private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000701 RID: 1793 RVA: 0x00037726 File Offset: 0x00035926
		private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000702 RID: 1794 RVA: 0x0003772F File Offset: 0x0003592F
		private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000703 RID: 1795 RVA: 0x00037738 File Offset: 0x00035938
		private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000704 RID: 1796 RVA: 0x00037741 File Offset: 0x00035941
		private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000705 RID: 1797 RVA: 0x0003774A File Offset: 0x0003594A
		private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000706 RID: 1798 RVA: 0x00037753 File Offset: 0x00035953
		private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000707 RID: 1799 RVA: 0x0003775C File Offset: 0x0003595C
		private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.ProfileName = this._widget_1_0.Text;
				return;
			}
		}

		// Token: 0x06000708 RID: 1800 RVA: 0x00037782 File Offset: 0x00035982
		private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000709 RID: 1801 RVA: 0x0003778B File Offset: 0x0003598B
		private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x0600070A RID: 1802 RVA: 0x00037794 File Offset: 0x00035994
		private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x0600070B RID: 1803 RVA: 0x0003779D File Offset: 0x0003599D
		private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x0600070C RID: 1804 RVA: 0x000377A6 File Offset: 0x000359A6
		private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x0600070D RID: 1805 RVA: 0x000377AF File Offset: 0x000359AF
		private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x0600070E RID: 1806 RVA: 0x000377B8 File Offset: 0x000359B8
		private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x0600070F RID: 1807 RVA: 0x000377C1 File Offset: 0x000359C1
		private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000710 RID: 1808 RVA: 0x000377CA File Offset: 0x000359CA
		private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000711 RID: 1809 RVA: 0x000377D3 File Offset: 0x000359D3
		private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsDownloadingContent = this._widget_2.IsVisible;
				return;
			}
		}

		// Token: 0x06000712 RID: 1810 RVA: 0x000377F9 File Offset: 0x000359F9
		private void PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000713 RID: 1811 RVA: 0x00037802 File Offset: 0x00035A02
		private void boolPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000714 RID: 1812 RVA: 0x0003780B File Offset: 0x00035A0B
		private void floatPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000715 RID: 1813 RVA: 0x00037814 File Offset: 0x00035A14
		private void Vec2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000716 RID: 1814 RVA: 0x0003781D File Offset: 0x00035A1D
		private void Vector2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000717 RID: 1815 RVA: 0x00037826 File Offset: 0x00035A26
		private void doublePropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000718 RID: 1816 RVA: 0x0003782F File Offset: 0x00035A2F
		private void intPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x06000719 RID: 1817 RVA: 0x00037838 File Offset: 0x00035A38
		private void uintPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x0600071A RID: 1818 RVA: 0x00037841 File Offset: 0x00035A41
		private void ColorPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
		}

		// Token: 0x0600071B RID: 1819 RVA: 0x0003784A File Offset: 0x00035A4A
		private void HandleWidgetPropertyChangeOf_widget_2_0(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.DownloadingText = this._widget_2_0.Text;
				return;
			}
		}

		// Token: 0x0600071C RID: 1820 RVA: 0x00037870 File Offset: 0x00035A70
		private void PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x0600071D RID: 1821 RVA: 0x00037879 File Offset: 0x00035A79
		private void boolPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x0600071E RID: 1822 RVA: 0x00037882 File Offset: 0x00035A82
		private void floatPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x0600071F RID: 1823 RVA: 0x0003788B File Offset: 0x00035A8B
		private void Vec2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000720 RID: 1824 RVA: 0x00037894 File Offset: 0x00035A94
		private void Vector2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000721 RID: 1825 RVA: 0x0003789D File Offset: 0x00035A9D
		private void doublePropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000722 RID: 1826 RVA: 0x000378A6 File Offset: 0x00035AA6
		private void intPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000723 RID: 1827 RVA: 0x000378AF File Offset: 0x00035AAF
		private void uintPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000724 RID: 1828 RVA: 0x000378B8 File Offset: 0x00035AB8
		private void ColorPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000725 RID: 1829 RVA: 0x000378C1 File Offset: 0x00035AC1
		private void HandleWidgetPropertyChangeOf_widget_3(string propertyName)
		{
			if (propertyName == "Text")
			{
				this._datasource_Root.GameVersionText = this._widget_3.Text;
				return;
			}
		}

		// Token: 0x06000726 RID: 1830 RVA: 0x000378E7 File Offset: 0x00035AE7
		private void PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000727 RID: 1831 RVA: 0x000378F0 File Offset: 0x00035AF0
		private void boolPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000728 RID: 1832 RVA: 0x000378F9 File Offset: 0x00035AF9
		private void floatPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000729 RID: 1833 RVA: 0x00037902 File Offset: 0x00035B02
		private void Vec2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x0600072A RID: 1834 RVA: 0x0003790B File Offset: 0x00035B0B
		private void Vector2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x0600072B RID: 1835 RVA: 0x00037914 File Offset: 0x00035B14
		private void doublePropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x0600072C RID: 1836 RVA: 0x0003791D File Offset: 0x00035B1D
		private void intPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x0600072D RID: 1837 RVA: 0x00037926 File Offset: 0x00035B26
		private void uintPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x0600072E RID: 1838 RVA: 0x0003792F File Offset: 0x00035B2F
		private void ColorPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x0600072F RID: 1839 RVA: 0x00037938 File Offset: 0x00035B38
		private void HandleWidgetPropertyChangeOf_widget_4(string propertyName)
		{
			if (propertyName == "IsScopeEnabled")
			{
				this._datasource_Root.IsComingSoonButtonActive = this._widget_4.IsScopeEnabled;
				return;
			}
		}

		// Token: 0x06000730 RID: 1840 RVA: 0x0003795E File Offset: 0x00035B5E
		private void PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000731 RID: 1841 RVA: 0x00037967 File Offset: 0x00035B67
		private void boolPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000732 RID: 1842 RVA: 0x00037970 File Offset: 0x00035B70
		private void floatPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000733 RID: 1843 RVA: 0x00037979 File Offset: 0x00035B79
		private void Vec2PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000734 RID: 1844 RVA: 0x00037982 File Offset: 0x00035B82
		private void Vector2PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000735 RID: 1845 RVA: 0x0003798B File Offset: 0x00035B8B
		private void doublePropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000736 RID: 1846 RVA: 0x00037994 File Offset: 0x00035B94
		private void intPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000737 RID: 1847 RVA: 0x0003799D File Offset: 0x00035B9D
		private void uintPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000738 RID: 1848 RVA: 0x000379A6 File Offset: 0x00035BA6
		private void ColorPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000739 RID: 1849 RVA: 0x000379B0 File Offset: 0x00035BB0
		private void HandleWidgetPropertyChangeOf_widget_5(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsComingSoonButtonVisible = this._widget_5.IsVisible;
				return;
			}
			if (propertyName == "IsEnabled")
			{
				this._datasource_Root.IsComingSoonButtonActive = this._widget_5.IsEnabled;
				return;
			}
		}

		// Token: 0x0600073A RID: 1850 RVA: 0x00037A05 File Offset: 0x00035C05
		private void PropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x0600073B RID: 1851 RVA: 0x00037A0E File Offset: 0x00035C0E
		private void boolPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x0600073C RID: 1852 RVA: 0x00037A17 File Offset: 0x00035C17
		private void floatPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x0600073D RID: 1853 RVA: 0x00037A20 File Offset: 0x00035C20
		private void Vec2PropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x0600073E RID: 1854 RVA: 0x00037A29 File Offset: 0x00035C29
		private void Vector2PropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x0600073F RID: 1855 RVA: 0x00037A32 File Offset: 0x00035C32
		private void doublePropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x06000740 RID: 1856 RVA: 0x00037A3B File Offset: 0x00035C3B
		private void intPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x06000741 RID: 1857 RVA: 0x00037A44 File Offset: 0x00035C44
		private void uintPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x06000742 RID: 1858 RVA: 0x00037A4D File Offset: 0x00035C4D
		private void ColorPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
		}

		// Token: 0x06000743 RID: 1859 RVA: 0x00037A56 File Offset: 0x00035C56
		private void HandleWidgetPropertyChangeOf_widget_5_1(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsComingSoonButtonWishlistVisible = this._widget_5_1.IsHidden;
				return;
			}
		}

		// Token: 0x06000744 RID: 1860 RVA: 0x00037A7C File Offset: 0x00035C7C
		private void PropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x06000745 RID: 1861 RVA: 0x00037A85 File Offset: 0x00035C85
		private void boolPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x06000746 RID: 1862 RVA: 0x00037A8E File Offset: 0x00035C8E
		private void floatPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x06000747 RID: 1863 RVA: 0x00037A97 File Offset: 0x00035C97
		private void Vec2PropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x06000748 RID: 1864 RVA: 0x00037AA0 File Offset: 0x00035CA0
		private void Vector2PropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x06000749 RID: 1865 RVA: 0x00037AA9 File Offset: 0x00035CA9
		private void doublePropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x0600074A RID: 1866 RVA: 0x00037AB2 File Offset: 0x00035CB2
		private void intPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x0600074B RID: 1867 RVA: 0x00037ABB File Offset: 0x00035CBB
		private void uintPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x0600074C RID: 1868 RVA: 0x00037AC4 File Offset: 0x00035CC4
		private void ColorPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
		}

		// Token: 0x0600074D RID: 1869 RVA: 0x00037ACD File Offset: 0x00035CCD
		private void HandleWidgetPropertyChangeOf_widget_5_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsComingSoonButtonWishlistVisible = this._widget_5_2.IsVisible;
				return;
			}
		}

		// Token: 0x0600074E RID: 1870 RVA: 0x00037AF3 File Offset: 0x00035CF3
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600074F RID: 1871 RVA: 0x00037B01 File Offset: 0x00035D01
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000750 RID: 1872 RVA: 0x00037B0F File Offset: 0x00035D0F
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000751 RID: 1873 RVA: 0x00037B1D File Offset: 0x00035D1D
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000752 RID: 1874 RVA: 0x00037B2B File Offset: 0x00035D2B
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000753 RID: 1875 RVA: 0x00037B39 File Offset: 0x00035D39
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000754 RID: 1876 RVA: 0x00037B47 File Offset: 0x00035D47
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000755 RID: 1877 RVA: 0x00037B55 File Offset: 0x00035D55
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000756 RID: 1878 RVA: 0x00037B63 File Offset: 0x00035D63
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000757 RID: 1879 RVA: 0x00037B74 File Offset: 0x00035D74
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "MenuOptions")
			{
				this.RefreshDataSource_datasource_Root_MenuOptions(this._datasource_Root.MenuOptions);
				return;
			}
			if (propertyName == "IsProfileSelectionEnabled")
			{
				this._widget_1.IsVisible = this._datasource_Root.IsProfileSelectionEnabled;
				return;
			}
			if (propertyName == "ProfileName")
			{
				this._widget_1_0.Text = this._datasource_Root.ProfileName;
				return;
			}
			if (propertyName == "IsDownloadingContent")
			{
				this._widget_2.IsVisible = this._datasource_Root.IsDownloadingContent;
				return;
			}
			if (propertyName == "DownloadingText")
			{
				this._widget_2_0.Text = this._datasource_Root.DownloadingText;
				return;
			}
			if (propertyName == "GameVersionText")
			{
				this._widget_3.Text = this._datasource_Root.GameVersionText;
				return;
			}
			if (propertyName == "IsComingSoonButtonActive")
			{
				this._widget_4.IsScopeEnabled = this._datasource_Root.IsComingSoonButtonActive;
				this._widget_5.IsEnabled = this._datasource_Root.IsComingSoonButtonActive;
				return;
			}
			if (propertyName == "IsComingSoonButtonVisible")
			{
				this._widget_5.IsVisible = this._datasource_Root.IsComingSoonButtonVisible;
				return;
			}
			if (propertyName == "IsComingSoonButtonWishlistVisible")
			{
				this._widget_5_1.IsHidden = this._datasource_Root.IsComingSoonButtonWishlistVisible;
				this._widget_5_2.IsVisible = this._datasource_Root.IsComingSoonButtonWishlistVisible;
				return;
			}
		}

		// Token: 0x06000758 RID: 1880 RVA: 0x00037CEC File Offset: 0x00035EEC
		public void OnList_datasource_Root_MenuOptionsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case 0:
				for (int i = this._widget_0_0_2_0_0_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0_2_0_0_1.GetChild(i);
					((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0_2_0_0_1.GetChild(i);
					((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0_2_0_0_1.RemoveChild(child2);
				}
				return;
			case 1:
				for (int j = 0; j < this._datasource_Root_MenuOptions.Count; j++)
				{
					InitialMenuOptionVM bindingObject = this._datasource_Root_MenuOptions[j];
					this._widget_0_0_2_0_0_1.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case 2:
			{
				InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate = new InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate);
				InitialMenuOptionVM initialMenuOptionVM = this._datasource_Root_MenuOptions[e.NewIndex];
				generatedWidgetData.Data = initialMenuOptionVM;
				initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0_0_2_0_0_1.AddChildAtIndex(initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate, e.NewIndex);
				initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.CreateWidgets();
				initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetIds();
				initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetAttributes();
				initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetDataSource(initialMenuOptionVM);
				return;
			}
			case 3:
			{
				Widget child3 = this._widget_0_0_2_0_0_1.GetChild(e.NewIndex);
				((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case 4:
			{
				Widget child4 = this._widget_0_0_2_0_0_1.GetChild(e.NewIndex);
				((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				this._widget_0_0_2_0_0_1.RemoveChild(child4);
				break;
			}
			case 5:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000759 RID: 1881 RVA: 0x00037E88 File Offset: 0x00036088
		private void RefreshDataSource_datasource_Root(InitialMenuVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2_0;
				this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
				this._widget_4.PropertyChanged -= this.PropertyChangedListenerOf_widget_4;
				this._widget_4.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_4;
				this._widget_4.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_4;
				this._widget_4.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_4;
				this._widget_4.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_4;
				this._widget_4.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_4;
				this._widget_4.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_4;
				this._widget_4.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_4;
				this._widget_4.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_4;
				this._widget_5.EventFire -= this.EventListenerOf_widget_5;
				this._widget_5.PropertyChanged -= this.PropertyChangedListenerOf_widget_5;
				this._widget_5.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5;
				this._widget_5.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5;
				this._widget_5.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5;
				this._widget_5.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5;
				this._widget_5.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5;
				this._widget_5.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5;
				this._widget_5.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5;
				this._widget_5.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5;
				this._widget_5_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5_1;
				this._widget_5_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5_2;
				if (this._datasource_Root_MenuOptions != null)
				{
					this._datasource_Root_MenuOptions.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_MenuOptionsChanged);
					for (int i = this._widget_0_0_2_0_0_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0_0_2_0_0_1.GetChild(i);
						((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0_0_2_0_0_1.GetChild(i);
						((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
						this._widget_0_0_2_0_0_1.RemoveChild(child2);
					}
					this._datasource_Root_MenuOptions = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.IsVisible = this._datasource_Root.IsProfileSelectionEnabled;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.Text = this._datasource_Root.ProfileName;
				this._widget_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.IsVisible = this._datasource_Root.IsDownloadingContent;
				this._widget_2.PropertyChanged += this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_2_0.Text = this._datasource_Root.DownloadingText;
				this._widget_2_0.PropertyChanged += this.PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2_0;
				this._widget_2_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2_0;
				this._widget_3.Text = this._datasource_Root.GameVersionText;
				this._widget_3.PropertyChanged += this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3;
				this._widget_4.IsScopeEnabled = this._datasource_Root.IsComingSoonButtonActive;
				this._widget_4.PropertyChanged += this.PropertyChangedListenerOf_widget_4;
				this._widget_4.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_4;
				this._widget_4.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_4;
				this._widget_4.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_4;
				this._widget_4.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_4;
				this._widget_4.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_4;
				this._widget_4.intPropertyChanged += this.intPropertyChangedListenerOf_widget_4;
				this._widget_4.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_4;
				this._widget_4.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_4;
				this._widget_5.IsVisible = this._datasource_Root.IsComingSoonButtonVisible;
				this._widget_5.IsEnabled = this._datasource_Root.IsComingSoonButtonActive;
				this._widget_5.EventFire += this.EventListenerOf_widget_5;
				this._widget_5.PropertyChanged += this.PropertyChangedListenerOf_widget_5;
				this._widget_5.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_5;
				this._widget_5.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_5;
				this._widget_5.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_5;
				this._widget_5.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_5;
				this._widget_5.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_5;
				this._widget_5.intPropertyChanged += this.intPropertyChangedListenerOf_widget_5;
				this._widget_5.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_5;
				this._widget_5.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_5;
				this._widget_5_1.IsHidden = this._datasource_Root.IsComingSoonButtonWishlistVisible;
				this._widget_5_1.PropertyChanged += this.PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_5_1;
				this._widget_5_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_5_1;
				this._widget_5_2.IsVisible = this._datasource_Root.IsComingSoonButtonWishlistVisible;
				this._widget_5_2.PropertyChanged += this.PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_5_2;
				this._widget_5_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_5_2;
				this._datasource_Root_MenuOptions = this._datasource_Root.MenuOptions;
				if (this._datasource_Root_MenuOptions != null)
				{
					this._datasource_Root_MenuOptions.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_MenuOptionsChanged);
					for (int j = 0; j < this._datasource_Root_MenuOptions.Count; j++)
					{
						InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate = new InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate);
						InitialMenuOptionVM initialMenuOptionVM = this._datasource_Root_MenuOptions[j];
						generatedWidgetData.Data = initialMenuOptionVM;
						initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0_0_2_0_0_1.AddChildAtIndex(initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate, j);
						initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.CreateWidgets();
						initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetIds();
						initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetAttributes();
						initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetDataSource(initialMenuOptionVM);
					}
				}
			}
		}

		// Token: 0x0600075A RID: 1882 RVA: 0x00039118 File Offset: 0x00037318
		private void RefreshDataSource_datasource_Root_MenuOptions(MBBindingList<InitialMenuOptionVM> newDataSource)
		{
			if (this._datasource_Root_MenuOptions != null)
			{
				this._datasource_Root_MenuOptions.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_MenuOptionsChanged);
				for (int i = this._widget_0_0_2_0_0_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0_0_2_0_0_1.GetChild(i);
					((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0_0_2_0_0_1.GetChild(i);
					((InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_0_0_2_0_0_1.RemoveChild(child2);
				}
				this._datasource_Root_MenuOptions = null;
			}
			this._datasource_Root_MenuOptions = newDataSource;
			this._datasource_Root_MenuOptions = this._datasource_Root.MenuOptions;
			if (this._datasource_Root_MenuOptions != null)
			{
				this._datasource_Root_MenuOptions.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_MenuOptionsChanged);
				for (int j = 0; j < this._datasource_Root_MenuOptions.Count; j++)
				{
					InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate = new InitialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate);
					InitialMenuOptionVM initialMenuOptionVM = this._datasource_Root_MenuOptions[j];
					generatedWidgetData.Data = initialMenuOptionVM;
					initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0_0_2_0_0_1.AddChildAtIndex(initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate, j);
					initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.CreateWidgets();
					initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetIds();
					initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetAttributes();
					initialScreen__TaleWorlds_MountAndBlade_ViewModelCollection_InitialMenu_InitialMenuVM_Dependency_1_ItemTemplate.SetDataSource(initialMenuOptionVM);
				}
			}
		}

		// Token: 0x0400019B RID: 411
		private Widget _widget;

		// Token: 0x0400019C RID: 412
		private Widget _widget_0;

		// Token: 0x0400019D RID: 413
		private Widget _widget_0_0;

		// Token: 0x0400019E RID: 414
		private InitialMenuAnimControllerWidget _widget_0_0_0;

		// Token: 0x0400019F RID: 415
		private Widget _widget_0_0_1;

		// Token: 0x040001A0 RID: 416
		private Widget _widget_0_0_2;

		// Token: 0x040001A1 RID: 417
		private ScrollablePanel _widget_0_0_2_0;

		// Token: 0x040001A2 RID: 418
		private Widget _widget_0_0_2_0_0;

		// Token: 0x040001A3 RID: 419
		private NavigationScopeTargeter _widget_0_0_2_0_0_0;

		// Token: 0x040001A4 RID: 420
		private NavigatableListPanel _widget_0_0_2_0_0_1;

		// Token: 0x040001A5 RID: 421
		private ScrollbarWidget _widget_0_0_2_1;

		// Token: 0x040001A6 RID: 422
		private Widget _widget_0_0_2_1_0;

		// Token: 0x040001A7 RID: 423
		private ImageWidget _widget_0_0_2_1_1;

		// Token: 0x040001A8 RID: 424
		private ListPanel _widget_1;

		// Token: 0x040001A9 RID: 425
		private TextWidget _widget_1_0;

		// Token: 0x040001AA RID: 426
		private Widget _widget_2;

		// Token: 0x040001AB RID: 427
		private TextWidget _widget_2_0;

		// Token: 0x040001AC RID: 428
		private TextWidget _widget_3;

		// Token: 0x040001AD RID: 429
		private NavigationScopeTargeter _widget_4;

		// Token: 0x040001AE RID: 430
		private ButtonWidget _widget_5;

		// Token: 0x040001AF RID: 431
		private BrushWidget _widget_5_0;

		// Token: 0x040001B0 RID: 432
		private BrushWidget _widget_5_1;

		// Token: 0x040001B1 RID: 433
		private BrushWidget _widget_5_2;

		// Token: 0x040001B2 RID: 434
		private InitialMenuVM _datasource_Root;

		// Token: 0x040001B3 RID: 435
		private MBBindingList<InitialMenuOptionVM> _datasource_Root_MenuOptions;
	}
}
