using System;
using System.ComponentModel;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.ViewModelCollection;
using TaleWorlds.MountAndBlade.ViewModelCollection.HUD;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x02000029 RID: 41
	public class MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_4_AgentTakenDamage__DependendPrefab : Widget
	{
		// Token: 0x0600091E RID: 2334 RVA: 0x00046389 File Offset: 0x00044589
		public MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_4_AgentTakenDamage__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x0600091F RID: 2335 RVA: 0x00046392 File Offset: 0x00044592
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
		}

		// Token: 0x06000920 RID: 2336 RVA: 0x000463BD File Offset: 0x000445BD
		public void SetIds()
		{
		}

		// Token: 0x06000921 RID: 2337 RVA: 0x000463BF File Offset: 0x000445BF
		public void SetAttributes()
		{
			base.WidthSizePolicy = 1;
			base.HeightSizePolicy = 1;
			base.IsEnabled = false;
			this._widget_0.WidthSizePolicy = 1;
			this._widget_0.HeightSizePolicy = 1;
		}

		// Token: 0x06000922 RID: 2338 RVA: 0x000463F0 File Offset: 0x000445F0
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				if (this._datasource_Root_TakenDamageController != null)
				{
					this._datasource_Root_TakenDamageController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TakenDamageController;
					this._datasource_Root_TakenDamageController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TakenDamageController);
					if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
					{
						this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
						for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
						{
							Widget child = this._widget_0.GetChild(i);
							((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
							((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)this._widget_0.GetChild(i)).DestroyDataSource();
						}
						this._datasource_Root_TakenDamageController_TakenDamageList = null;
					}
					this._datasource_Root_TakenDamageController = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000923 RID: 2339 RVA: 0x0004662C File Offset: 0x0004482C
		public void SetDataSource(MissionAgentStatusVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000924 RID: 2340 RVA: 0x00046635 File Offset: 0x00044835
		private void ViewModelPropertyChangedListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x06000925 RID: 2341 RVA: 0x00046643 File Offset: 0x00044843
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x06000926 RID: 2342 RVA: 0x00046651 File Offset: 0x00044851
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x06000927 RID: 2343 RVA: 0x0004665F File Offset: 0x0004485F
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x06000928 RID: 2344 RVA: 0x0004666D File Offset: 0x0004486D
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x06000929 RID: 2345 RVA: 0x0004667B File Offset: 0x0004487B
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x0600092A RID: 2346 RVA: 0x00046689 File Offset: 0x00044889
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x0600092B RID: 2347 RVA: 0x00046697 File Offset: 0x00044897
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x0600092C RID: 2348 RVA: 0x000466A5 File Offset: 0x000448A5
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TakenDamageController(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(e.PropertyName);
		}

		// Token: 0x0600092D RID: 2349 RVA: 0x000466B3 File Offset: 0x000448B3
		private void HandleViewModelPropertyChangeOf_datasource_Root_TakenDamageController(string propertyName)
		{
			if (propertyName == "TakenDamageList")
			{
				this.RefreshDataSource_datasource_Root_TakenDamageController_TakenDamageList(this._datasource_Root_TakenDamageController.TakenDamageList);
				return;
			}
		}

		// Token: 0x0600092E RID: 2350 RVA: 0x000466D4 File Offset: 0x000448D4
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600092F RID: 2351 RVA: 0x000466E2 File Offset: 0x000448E2
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000930 RID: 2352 RVA: 0x000466F0 File Offset: 0x000448F0
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000931 RID: 2353 RVA: 0x000466FE File Offset: 0x000448FE
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000932 RID: 2354 RVA: 0x0004670C File Offset: 0x0004490C
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000933 RID: 2355 RVA: 0x0004671A File Offset: 0x0004491A
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000934 RID: 2356 RVA: 0x00046728 File Offset: 0x00044928
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000935 RID: 2357 RVA: 0x00046736 File Offset: 0x00044936
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000936 RID: 2358 RVA: 0x00046744 File Offset: 0x00044944
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000937 RID: 2359 RVA: 0x00046752 File Offset: 0x00044952
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "TakenDamageController")
			{
				this.RefreshDataSource_datasource_Root_TakenDamageController(this._datasource_Root.TakenDamageController);
				return;
			}
		}

		// Token: 0x06000938 RID: 2360 RVA: 0x00046774 File Offset: 0x00044974
		public void OnList_datasource_Root_TakenDamageController_TakenDamageListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case 0:
				for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0.GetChild(i);
					((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0.GetChild(i);
					((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
					this._widget_0.RemoveChild(child2);
				}
				return;
			case 1:
				for (int j = 0; j < this._datasource_Root_TakenDamageController_TakenDamageList.Count; j++)
				{
					MissionAgentTakenDamageItemVM bindingObject = this._datasource_Root_TakenDamageController_TakenDamageList[j];
					this._widget_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case 2:
			{
				MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate = new MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate);
				MissionAgentTakenDamageItemVM missionAgentTakenDamageItemVM = this._datasource_Root_TakenDamageController_TakenDamageList[e.NewIndex];
				generatedWidgetData.Data = missionAgentTakenDamageItemVM;
				mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0.AddChildAtIndex(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate, e.NewIndex);
				mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.CreateWidgets();
				mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetIds();
				mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetAttributes();
				mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetDataSource(missionAgentTakenDamageItemVM);
				return;
			}
			case 3:
			{
				Widget child3 = this._widget_0.GetChild(e.NewIndex);
				((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case 4:
			{
				Widget child4 = this._widget_0.GetChild(e.NewIndex);
				((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child4).SetDataSource(null);
				this._widget_0.RemoveChild(child4);
				break;
			}
			case 5:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000939 RID: 2361 RVA: 0x00046910 File Offset: 0x00044B10
		private void RefreshDataSource_datasource_Root_TakenDamageController(MissionAgentTakenDamageVM newDataSource)
		{
			if (this._datasource_Root_TakenDamageController != null)
			{
				this._datasource_Root_TakenDamageController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TakenDamageController;
				this._datasource_Root_TakenDamageController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TakenDamageController);
				if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
				{
					this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
					for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0.GetChild(i);
						((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0.GetChild(i);
						((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
						this._widget_0.RemoveChild(child2);
					}
					this._datasource_Root_TakenDamageController_TakenDamageList = null;
				}
				this._datasource_Root_TakenDamageController = null;
			}
			this._datasource_Root_TakenDamageController = newDataSource;
			this._datasource_Root_TakenDamageController = this._datasource_Root.TakenDamageController;
			if (this._datasource_Root_TakenDamageController != null)
			{
				this._datasource_Root_TakenDamageController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_TakenDamageController;
				this._datasource_Root_TakenDamageController.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TakenDamageController);
				this._datasource_Root_TakenDamageController_TakenDamageList = this._datasource_Root_TakenDamageController.TakenDamageList;
				if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
				{
					this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
					for (int j = 0; j < this._datasource_Root_TakenDamageController_TakenDamageList.Count; j++)
					{
						MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate = new MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate);
						MissionAgentTakenDamageItemVM missionAgentTakenDamageItemVM = this._datasource_Root_TakenDamageController_TakenDamageList[j];
						generatedWidgetData.Data = missionAgentTakenDamageItemVM;
						mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0.AddChildAtIndex(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate, j);
						mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.CreateWidgets();
						mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetIds();
						mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetAttributes();
						mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetDataSource(missionAgentTakenDamageItemVM);
					}
				}
			}
		}

		// Token: 0x0600093A RID: 2362 RVA: 0x00046C18 File Offset: 0x00044E18
		private void RefreshDataSource_datasource_Root_TakenDamageController_TakenDamageList(MBBindingList<MissionAgentTakenDamageItemVM> newDataSource)
		{
			if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
			{
				this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
				for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0.GetChild(i);
					((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0.GetChild(i);
					((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
					this._widget_0.RemoveChild(child2);
				}
				this._datasource_Root_TakenDamageController_TakenDamageList = null;
			}
			this._datasource_Root_TakenDamageController_TakenDamageList = newDataSource;
			this._datasource_Root_TakenDamageController_TakenDamageList = this._datasource_Root_TakenDamageController.TakenDamageList;
			if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
			{
				this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
				for (int j = 0; j < this._datasource_Root_TakenDamageController_TakenDamageList.Count; j++)
				{
					MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate = new MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate);
					MissionAgentTakenDamageItemVM missionAgentTakenDamageItemVM = this._datasource_Root_TakenDamageController_TakenDamageList[j];
					generatedWidgetData.Data = missionAgentTakenDamageItemVM;
					mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0.AddChildAtIndex(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate, j);
					mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.CreateWidgets();
					mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetIds();
					mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetAttributes();
					mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetDataSource(missionAgentTakenDamageItemVM);
				}
			}
		}

		// Token: 0x0600093B RID: 2363 RVA: 0x00046D54 File Offset: 0x00044F54
		private void RefreshDataSource_datasource_Root(MissionAgentStatusVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				if (this._datasource_Root_TakenDamageController != null)
				{
					this._datasource_Root_TakenDamageController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TakenDamageController;
					this._datasource_Root_TakenDamageController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TakenDamageController);
					if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
					{
						this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
						for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
						{
							Widget child = this._widget_0.GetChild(i);
							((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child).OnBeforeRemovedChild(child);
							Widget child2 = this._widget_0.GetChild(i);
							((MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate)child2).SetDataSource(null);
							this._widget_0.RemoveChild(child2);
						}
						this._datasource_Root_TakenDamageController_TakenDamageList = null;
					}
					this._datasource_Root_TakenDamageController = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._datasource_Root_TakenDamageController = this._datasource_Root.TakenDamageController;
				if (this._datasource_Root_TakenDamageController != null)
				{
					this._datasource_Root_TakenDamageController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_TakenDamageController;
					this._datasource_Root_TakenDamageController.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TakenDamageController);
					this._datasource_Root_TakenDamageController_TakenDamageList = this._datasource_Root_TakenDamageController.TakenDamageList;
					if (this._datasource_Root_TakenDamageController_TakenDamageList != null)
					{
						this._datasource_Root_TakenDamageController_TakenDamageList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_TakenDamageController_TakenDamageListChanged);
						for (int j = 0; j < this._datasource_Root_TakenDamageController_TakenDamageList.Count; j++)
						{
							MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate = new MainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate(base.Context);
							GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate);
							MissionAgentTakenDamageItemVM missionAgentTakenDamageItemVM = this._datasource_Root_TakenDamageController_TakenDamageList[j];
							generatedWidgetData.Data = missionAgentTakenDamageItemVM;
							mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.AddComponent(generatedWidgetData);
							this._widget_0.AddChildAtIndex(mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate, j);
							mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.CreateWidgets();
							mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetIds();
							mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetAttributes();
							mainAgentHUD__TaleWorlds_MountAndBlade_ViewModelCollection_MissionAgentStatusVM_Dependency_5_ItemTemplate.SetDataSource(missionAgentTakenDamageItemVM);
						}
					}
				}
			}
		}

		// Token: 0x04000211 RID: 529
		private Widget _widget;

		// Token: 0x04000212 RID: 530
		private Widget _widget_0;

		// Token: 0x04000213 RID: 531
		private MissionAgentStatusVM _datasource_Root;

		// Token: 0x04000214 RID: 532
		private MissionAgentTakenDamageVM _datasource_Root_TakenDamageController;

		// Token: 0x04000215 RID: 533
		private MBBindingList<MissionAgentTakenDamageItemVM> _datasource_Root_TakenDamageController_TakenDamageList;
	}
}
