using System;
using System.ComponentModel;
using TaleWorlds.GauntletUI;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.ViewModelCollection.Order;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x0200002D RID: 45
	public class OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate : OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_6_OrderSetBar__InheritedPrefab
	{
		// Token: 0x0600099E RID: 2462 RVA: 0x00049BAB File Offset: 0x00047DAB
		public OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate(UIContext context) : base(context)
		{
		}

		// Token: 0x0600099F RID: 2463 RVA: 0x00049BB4 File Offset: 0x00047DB4
		public override void CreateWidgets()
		{
			base.CreateWidgets();
			this._widget = this;
		}

		// Token: 0x060009A0 RID: 2464 RVA: 0x00049BC3 File Offset: 0x00047DC3
		public override void SetIds()
		{
			base.SetIds();
		}

		// Token: 0x060009A1 RID: 2465 RVA: 0x00049BCB File Offset: 0x00047DCB
		public override void SetAttributes()
		{
			base.SetAttributes();
			base.MarginBottom = 8f;
		}

		// Token: 0x060009A2 RID: 2466 RVA: 0x00049BE0 File Offset: 0x00047DE0
		public override void DestroyDataSource()
		{
			base.DestroyDataSource();
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._datasource_Root = null;
			}
		}

		// Token: 0x060009A3 RID: 2467 RVA: 0x00049CD4 File Offset: 0x00047ED4
		public override void SetDataSource(OrderSetVM dataSource)
		{
			base.SetDataSource(dataSource);
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060009A4 RID: 2468 RVA: 0x00049CE4 File Offset: 0x00047EE4
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009A5 RID: 2469 RVA: 0x00049CF2 File Offset: 0x00047EF2
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009A6 RID: 2470 RVA: 0x00049D00 File Offset: 0x00047F00
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009A7 RID: 2471 RVA: 0x00049D0E File Offset: 0x00047F0E
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009A8 RID: 2472 RVA: 0x00049D1C File Offset: 0x00047F1C
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009A9 RID: 2473 RVA: 0x00049D2A File Offset: 0x00047F2A
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009AA RID: 2474 RVA: 0x00049D38 File Offset: 0x00047F38
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009AB RID: 2475 RVA: 0x00049D46 File Offset: 0x00047F46
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009AC RID: 2476 RVA: 0x00049D54 File Offset: 0x00047F54
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009AD RID: 2477 RVA: 0x00049D62 File Offset: 0x00047F62
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
		}

		// Token: 0x060009AE RID: 2478 RVA: 0x00049D64 File Offset: 0x00047F64
		private void RefreshDataSource_datasource_Root(OrderSetVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			}
		}

		// Token: 0x04000229 RID: 553
		private OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_6_OrderSetBar__InheritedPrefab _widget;

		// Token: 0x0400022A RID: 554
		private OrderSetVM _datasource_Root;
	}
}
