using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.ViewModelCollection.Order;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x0200002B RID: 43
	public class OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM : Widget, IGeneratedGauntletMovieRoot
	{
		// Token: 0x06000958 RID: 2392 RVA: 0x00047C77 File Offset: 0x00045E77
		public OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM(UIContext context) : base(context)
		{
		}

		// Token: 0x06000959 RID: 2393 RVA: 0x00047C80 File Offset: 0x00045E80
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_3_Siege__DependendPrefab(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_0.CreateWidgets();
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_0_0 = new ListPanel(base.Context);
			this._widget_1_0.AddChild(this._widget_1_0_0);
			this._widget_1_1 = new ListPanel(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
			this._widget_2 = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_4_OrderTransferPopup__DependendPrefab(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_2.CreateWidgets();
		}

		// Token: 0x0600095A RID: 2394 RVA: 0x00047D76 File Offset: 0x00045F76
		public void SetIds()
		{
			this._widget_0.SetIds();
			this._widget_2.SetIds();
		}

		// Token: 0x0600095B RID: 2395 RVA: 0x00047D90 File Offset: 0x00045F90
		public void SetAttributes()
		{
			base.DoNotAcceptEvents = true;
			base.WidthSizePolicy = 1;
			base.HeightSizePolicy = 1;
			this._widget_0.SetAttributes();
			this._widget_1.DoNotAcceptEvents = true;
			this._widget_1.WidthSizePolicy = 1;
			this._widget_1.HeightSizePolicy = 1;
			this._widget_1_0.WidthSizePolicy = 2;
			this._widget_1_0.HeightSizePolicy = 2;
			this._widget_1_0.HorizontalAlignment = 1;
			this._widget_1_0.VerticalAlignment = 0;
			this._widget_1_0.MarginTop = 25f;
			this._widget_1_0_0.WidthSizePolicy = 2;
			this._widget_1_0_0.HeightSizePolicy = 2;
			this._widget_1_1.WidthSizePolicy = 2;
			this._widget_1_1.HeightSizePolicy = 2;
			this._widget_1_1.MarginLeft = 20f;
			this._widget_1_1.MarginTop = 120f;
			this._widget_1_1.StackLayout.LayoutMethod = 4;
			this._widget_2.SetAttributes();
		}

		// Token: 0x0600095C RID: 2396 RVA: 0x00047E90 File Offset: 0x00046090
		public void RefreshBindingWithChildren()
		{
			MissionOrderVM datasource_Root = this._datasource_Root;
			this.SetDataSource(null);
			this.SetDataSource(datasource_Root);
		}

		// Token: 0x0600095D RID: 2397 RVA: 0x00047EB4 File Offset: 0x000460B4
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._widget_0.DestroyDataSource();
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				if (this._datasource_Root_OrderSets != null)
				{
					this._datasource_Root_OrderSets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_OrderSetsChanged);
					for (int i = this._widget_1_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_1.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)this._widget_1_1.GetChild(i)).DestroyDataSource();
					}
					this._datasource_Root_OrderSets = null;
				}
				if (this._datasource_Root_TroopController != null)
				{
					this._widget_2.DestroyDataSource();
					this._datasource_Root_TroopController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TroopController;
					this._datasource_Root_TroopController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TroopController);
					if (this._datasource_Root_TroopController_TroopList != null)
					{
						this._datasource_Root_TroopController_TroopList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
						for (int j = this._widget_1_0_0.ChildCount - 1; j >= 0; j--)
						{
							Widget child2 = this._widget_1_0_0.GetChild(j);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child2).OnBeforeRemovedChild(child2);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)this._widget_1_0_0.GetChild(j)).DestroyDataSource();
						}
						this._datasource_Root_TroopController_TroopList = null;
					}
					this._datasource_Root_TroopController = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x0600095E RID: 2398 RVA: 0x00048311 File Offset: 0x00046511
		public void SetDataSource(MissionOrderVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x0600095F RID: 2399 RVA: 0x0004831A File Offset: 0x0004651A
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000960 RID: 2400 RVA: 0x00048323 File Offset: 0x00046523
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000961 RID: 2401 RVA: 0x0004832C File Offset: 0x0004652C
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000962 RID: 2402 RVA: 0x00048335 File Offset: 0x00046535
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000963 RID: 2403 RVA: 0x0004833E File Offset: 0x0004653E
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000964 RID: 2404 RVA: 0x00048347 File Offset: 0x00046547
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000965 RID: 2405 RVA: 0x00048350 File Offset: 0x00046550
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000966 RID: 2406 RVA: 0x00048359 File Offset: 0x00046559
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000967 RID: 2407 RVA: 0x00048362 File Offset: 0x00046562
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000968 RID: 2408 RVA: 0x0004836B File Offset: 0x0004656B
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsToggleOrderShown = this._widget_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000969 RID: 2409 RVA: 0x00048391 File Offset: 0x00046591
		private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600096A RID: 2410 RVA: 0x0004839A File Offset: 0x0004659A
		private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600096B RID: 2411 RVA: 0x000483A3 File Offset: 0x000465A3
		private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600096C RID: 2412 RVA: 0x000483AC File Offset: 0x000465AC
		private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600096D RID: 2413 RVA: 0x000483B5 File Offset: 0x000465B5
		private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600096E RID: 2414 RVA: 0x000483BE File Offset: 0x000465BE
		private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x0600096F RID: 2415 RVA: 0x000483C7 File Offset: 0x000465C7
		private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000970 RID: 2416 RVA: 0x000483D0 File Offset: 0x000465D0
		private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000971 RID: 2417 RVA: 0x000483D9 File Offset: 0x000465D9
		private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000972 RID: 2418 RVA: 0x000483E2 File Offset: 0x000465E2
		private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsTroopListShown = this._widget_1_0.IsVisible;
				return;
			}
		}

		// Token: 0x06000973 RID: 2419 RVA: 0x00048408 File Offset: 0x00046608
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000974 RID: 2420 RVA: 0x00048416 File Offset: 0x00046616
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000975 RID: 2421 RVA: 0x00048424 File Offset: 0x00046624
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000976 RID: 2422 RVA: 0x00048432 File Offset: 0x00046632
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000977 RID: 2423 RVA: 0x00048440 File Offset: 0x00046640
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000978 RID: 2424 RVA: 0x0004844E File Offset: 0x0004664E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000979 RID: 2425 RVA: 0x0004845C File Offset: 0x0004665C
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600097A RID: 2426 RVA: 0x0004846A File Offset: 0x0004666A
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600097B RID: 2427 RVA: 0x00048478 File Offset: 0x00046678
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x0600097C RID: 2428 RVA: 0x00048488 File Offset: 0x00046688
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "OrderSets")
			{
				this.RefreshDataSource_datasource_Root_OrderSets(this._datasource_Root.OrderSets);
				return;
			}
			if (propertyName == "TroopController")
			{
				this.RefreshDataSource_datasource_Root_TroopController(this._datasource_Root.TroopController);
				return;
			}
			if (propertyName == "IsToggleOrderShown")
			{
				this._widget_1.IsVisible = this._datasource_Root.IsToggleOrderShown;
				return;
			}
			if (propertyName == "IsTroopListShown")
			{
				this._widget_1_0.IsVisible = this._datasource_Root.IsTroopListShown;
				return;
			}
		}

		// Token: 0x0600097D RID: 2429 RVA: 0x0004851B File Offset: 0x0004671B
		private void ViewModelPropertyChangedListenerOf_datasource_Root_TroopController(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x0600097E RID: 2430 RVA: 0x00048529 File Offset: 0x00046729
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x0600097F RID: 2431 RVA: 0x00048537 File Offset: 0x00046737
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000980 RID: 2432 RVA: 0x00048545 File Offset: 0x00046745
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000981 RID: 2433 RVA: 0x00048553 File Offset: 0x00046753
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000982 RID: 2434 RVA: 0x00048561 File Offset: 0x00046761
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000983 RID: 2435 RVA: 0x0004856F File Offset: 0x0004676F
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000984 RID: 2436 RVA: 0x0004857D File Offset: 0x0004677D
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000985 RID: 2437 RVA: 0x0004858B File Offset: 0x0004678B
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TroopController(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_TroopController(e.PropertyName);
		}

		// Token: 0x06000986 RID: 2438 RVA: 0x00048599 File Offset: 0x00046799
		private void HandleViewModelPropertyChangeOf_datasource_Root_TroopController(string propertyName)
		{
			if (propertyName == "TroopList")
			{
				this.RefreshDataSource_datasource_Root_TroopController_TroopList(this._datasource_Root_TroopController.TroopList);
				return;
			}
		}

		// Token: 0x06000987 RID: 2439 RVA: 0x000485BC File Offset: 0x000467BC
		public void OnList_datasource_Root_TroopController_TroopListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case 0:
				for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_0_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_0_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_0_0.RemoveChild(child2);
				}
				return;
			case 1:
				for (int j = 0; j < this._datasource_Root_TroopController_TroopList.Count; j++)
				{
					OrderTroopItemVM bindingObject = this._datasource_Root_TroopController_TroopList[j];
					this._widget_1_0_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case 2:
			{
				OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate);
				OrderTroopItemVM orderTroopItemVM = this._datasource_Root_TroopController_TroopList[e.NewIndex];
				generatedWidgetData.Data = orderTroopItemVM;
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_1_0_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate, e.NewIndex);
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.CreateWidgets();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetIds();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetAttributes();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetDataSource(orderTroopItemVM);
				return;
			}
			case 3:
			{
				Widget child3 = this._widget_1_0_0.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case 4:
			{
				Widget child4 = this._widget_1_0_0.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
				this._widget_1_0_0.RemoveChild(child4);
				break;
			}
			case 5:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000988 RID: 2440 RVA: 0x00048758 File Offset: 0x00046958
		public void OnList_datasource_Root_OrderSetsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case 0:
				for (int i = this._widget_1_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_1.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_1.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_1.RemoveChild(child2);
				}
				return;
			case 1:
				for (int j = 0; j < this._datasource_Root_OrderSets.Count; j++)
				{
					OrderSetVM bindingObject = this._datasource_Root_OrderSets[j];
					this._widget_1_1.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case 2:
			{
				OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate);
				OrderSetVM orderSetVM = this._datasource_Root_OrderSets[e.NewIndex];
				generatedWidgetData.Data = orderSetVM;
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_1_1.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate, e.NewIndex);
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.CreateWidgets();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetIds();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetAttributes();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetDataSource(orderSetVM);
				return;
			}
			case 3:
			{
				Widget child3 = this._widget_1_1.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case 4:
			{
				Widget child4 = this._widget_1_1.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child4).SetDataSource(null);
				this._widget_1_1.RemoveChild(child4);
				break;
			}
			case 5:
				break;
			default:
				return;
			}
		}

		// Token: 0x06000989 RID: 2441 RVA: 0x000488F4 File Offset: 0x00046AF4
		private void RefreshDataSource_datasource_Root(MissionOrderVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._widget_0.SetDataSource(null);
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				if (this._datasource_Root_OrderSets != null)
				{
					this._datasource_Root_OrderSets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_OrderSetsChanged);
					for (int i = this._widget_1_1.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_1.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_1_1.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
						this._widget_1_1.RemoveChild(child2);
					}
					this._datasource_Root_OrderSets = null;
				}
				if (this._datasource_Root_TroopController != null)
				{
					this._widget_2.SetDataSource(null);
					this._datasource_Root_TroopController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TroopController;
					this._datasource_Root_TroopController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TroopController);
					if (this._datasource_Root_TroopController_TroopList != null)
					{
						this._datasource_Root_TroopController_TroopList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
						for (int j = this._widget_1_0_0.ChildCount - 1; j >= 0; j--)
						{
							Widget child3 = this._widget_1_0_0.GetChild(j);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child3).OnBeforeRemovedChild(child3);
							Widget child4 = this._widget_1_0_0.GetChild(j);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child4).SetDataSource(null);
							this._widget_1_0_0.RemoveChild(child4);
						}
						this._datasource_Root_TroopController_TroopList = null;
					}
					this._datasource_Root_TroopController = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.IsVisible = this._datasource_Root.IsToggleOrderShown;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.IsVisible = this._datasource_Root.IsTroopListShown;
				this._widget_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0;
				this._datasource_Root_OrderSets = this._datasource_Root.OrderSets;
				if (this._datasource_Root_OrderSets != null)
				{
					this._datasource_Root_OrderSets.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_OrderSetsChanged);
					for (int k = 0; k < this._datasource_Root_OrderSets.Count; k++)
					{
						OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate);
						OrderSetVM orderSetVM = this._datasource_Root_OrderSets[k];
						generatedWidgetData.Data = orderSetVM;
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_1_1.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate, k);
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.CreateWidgets();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetIds();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetAttributes();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetDataSource(orderSetVM);
					}
				}
				this._datasource_Root_TroopController = this._datasource_Root.TroopController;
				if (this._datasource_Root_TroopController != null)
				{
					this._datasource_Root_TroopController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_TroopController;
					this._datasource_Root_TroopController.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TroopController);
					this._datasource_Root_TroopController_TroopList = this._datasource_Root_TroopController.TroopList;
					if (this._datasource_Root_TroopController_TroopList != null)
					{
						this._datasource_Root_TroopController_TroopList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
						for (int l = 0; l < this._datasource_Root_TroopController_TroopList.Count; l++)
						{
							OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate(base.Context);
							GeneratedWidgetData generatedWidgetData2 = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate);
							OrderTroopItemVM orderTroopItemVM = this._datasource_Root_TroopController_TroopList[l];
							generatedWidgetData2.Data = orderTroopItemVM;
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData2);
							this._widget_1_0_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate, l);
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.CreateWidgets();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetIds();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetAttributes();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetDataSource(orderTroopItemVM);
						}
					}
					this._widget_2.SetDataSource(this._datasource_Root_TroopController);
				}
				this._widget_0.SetDataSource(this._datasource_Root);
			}
		}

		// Token: 0x0600098A RID: 2442 RVA: 0x00049294 File Offset: 0x00047494
		private void RefreshDataSource_datasource_Root_TroopController_TroopList(MBBindingList<OrderTroopItemVM> newDataSource)
		{
			if (this._datasource_Root_TroopController_TroopList != null)
			{
				this._datasource_Root_TroopController_TroopList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
				for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_0_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_0_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_0_0.RemoveChild(child2);
				}
				this._datasource_Root_TroopController_TroopList = null;
			}
			this._datasource_Root_TroopController_TroopList = newDataSource;
			this._datasource_Root_TroopController_TroopList = this._datasource_Root_TroopController.TroopList;
			if (this._datasource_Root_TroopController_TroopList != null)
			{
				this._datasource_Root_TroopController_TroopList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
				for (int j = 0; j < this._datasource_Root_TroopController_TroopList.Count; j++)
				{
					OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate);
					OrderTroopItemVM orderTroopItemVM = this._datasource_Root_TroopController_TroopList[j];
					generatedWidgetData.Data = orderTroopItemVM;
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_1_0_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate, j);
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.CreateWidgets();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetIds();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetAttributes();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetDataSource(orderTroopItemVM);
				}
			}
		}

		// Token: 0x0600098B RID: 2443 RVA: 0x000493D0 File Offset: 0x000475D0
		private void RefreshDataSource_datasource_Root_OrderSets(MBBindingList<OrderSetVM> newDataSource)
		{
			if (this._datasource_Root_OrderSets != null)
			{
				this._datasource_Root_OrderSets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_OrderSetsChanged);
				for (int i = this._widget_1_1.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_1.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_1.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_1.RemoveChild(child2);
				}
				this._datasource_Root_OrderSets = null;
			}
			this._datasource_Root_OrderSets = newDataSource;
			this._datasource_Root_OrderSets = this._datasource_Root.OrderSets;
			if (this._datasource_Root_OrderSets != null)
			{
				this._datasource_Root_OrderSets.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_OrderSetsChanged);
				for (int j = 0; j < this._datasource_Root_OrderSets.Count; j++)
				{
					OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate);
					OrderSetVM orderSetVM = this._datasource_Root_OrderSets[j];
					generatedWidgetData.Data = orderSetVM;
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_1_1.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate, j);
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.CreateWidgets();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetIds();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetAttributes();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_2_ItemTemplate.SetDataSource(orderSetVM);
				}
			}
		}

		// Token: 0x0600098C RID: 2444 RVA: 0x0004950C File Offset: 0x0004770C
		private void RefreshDataSource_datasource_Root_TroopController(MissionOrderTroopControllerVM newDataSource)
		{
			if (this._datasource_Root_TroopController != null)
			{
				this._widget_2.SetDataSource(null);
				this._datasource_Root_TroopController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_TroopController;
				this._datasource_Root_TroopController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TroopController);
				if (this._datasource_Root_TroopController_TroopList != null)
				{
					this._datasource_Root_TroopController_TroopList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
					for (int i = this._widget_1_0_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_1_0_0.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_1_0_0.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate)child2).SetDataSource(null);
						this._widget_1_0_0.RemoveChild(child2);
					}
					this._datasource_Root_TroopController_TroopList = null;
				}
				this._datasource_Root_TroopController = null;
			}
			this._datasource_Root_TroopController = newDataSource;
			this._datasource_Root_TroopController = this._datasource_Root.TroopController;
			if (this._datasource_Root_TroopController != null)
			{
				this._datasource_Root_TroopController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_TroopController;
				this._datasource_Root_TroopController.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_TroopController);
				this._datasource_Root_TroopController_TroopList = this._datasource_Root_TroopController.TroopList;
				if (this._datasource_Root_TroopController_TroopList != null)
				{
					this._datasource_Root_TroopController_TroopList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_TroopController_TroopListChanged);
					for (int j = 0; j < this._datasource_Root_TroopController_TroopList.Count; j++)
					{
						OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate);
						OrderTroopItemVM orderTroopItemVM = this._datasource_Root_TroopController_TroopList[j];
						generatedWidgetData.Data = orderTroopItemVM;
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_1_0_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate, j);
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.CreateWidgets();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetIds();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetAttributes();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_1_ItemTemplate.SetDataSource(orderTroopItemVM);
					}
				}
				this._widget_2.SetDataSource(this._datasource_Root_TroopController);
			}
		}

		// Token: 0x0400021C RID: 540
		private Widget _widget;

		// Token: 0x0400021D RID: 541
		private OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_3_Siege__DependendPrefab _widget_0;

		// Token: 0x0400021E RID: 542
		private Widget _widget_1;

		// Token: 0x0400021F RID: 543
		private Widget _widget_1_0;

		// Token: 0x04000220 RID: 544
		private ListPanel _widget_1_0_0;

		// Token: 0x04000221 RID: 545
		private ListPanel _widget_1_1;

		// Token: 0x04000222 RID: 546
		private OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_4_OrderTransferPopup__DependendPrefab _widget_2;

		// Token: 0x04000223 RID: 547
		private MissionOrderVM _datasource_Root;

		// Token: 0x04000224 RID: 548
		private MBBindingList<OrderSetVM> _datasource_Root_OrderSets;

		// Token: 0x04000225 RID: 549
		private MissionOrderTroopControllerVM _datasource_Root_TroopController;

		// Token: 0x04000226 RID: 550
		private MBBindingList<OrderTroopItemVM> _datasource_Root_TroopController_TroopList;
	}
}
