using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Order;
using TaleWorlds.MountAndBlade.ViewModelCollection.Order;

namespace TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1
{
	// Token: 0x0200002E RID: 46
	public class OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_3_Siege__DependendPrefab : OrderSiegeDeploymentScreenWidget
	{
		// Token: 0x060009AF RID: 2479 RVA: 0x00049F33 File Offset: 0x00048133
		public OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_3_Siege__DependendPrefab(UIContext context) : base(context)
		{
		}

		// Token: 0x060009B0 RID: 2480 RVA: 0x00049F3C File Offset: 0x0004813C
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new ListPanel(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
		}

		// Token: 0x060009B1 RID: 2481 RVA: 0x00049FB6 File Offset: 0x000481B6
		public void SetIds()
		{
			base.Id = "Screen";
			this._widget_0.Id = "DeploymentTargetsParent";
			this._widget_1.Id = "DeploymentConatiner";
			this._widget_1_0.Id = "DeploymentList";
		}

		// Token: 0x060009B2 RID: 2482 RVA: 0x00049FF4 File Offset: 0x000481F4
		public void SetAttributes()
		{
			base.DoNotAcceptEvents = true;
			base.WidthSizePolicy = 1;
			base.HeightSizePolicy = 1;
			base.DeploymentTargetsParent = this._widget_0;
			base.DeploymentListPanel = this._widget_1_0;
			this._widget_0.DoNotAcceptEvents = true;
			this._widget_0.WidthSizePolicy = 1;
			this._widget_0.HeightSizePolicy = 1;
			this._widget_0.HorizontalAlignment = 1;
			this._widget_0.VerticalAlignment = 1;
			this._widget_1.DoNotAcceptEvents = true;
			this._widget_1.WidthSizePolicy = 2;
			this._widget_1.HeightSizePolicy = 2;
			this._widget_1_0.DoNotAcceptEvents = true;
			this._widget_1_0.WidthSizePolicy = 2;
			this._widget_1_0.HeightSizePolicy = 2;
			this._widget_1_0.PositionXOffset = -7f;
		}

		// Token: 0x060009B3 RID: 2483 RVA: 0x0004A0C4 File Offset: 0x000482C4
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				if (this._datasource_Root_DeploymentController != null)
				{
					this._datasource_Root_DeploymentController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DeploymentController;
					this._datasource_Root_DeploymentController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DeploymentController);
					this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
					this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
					this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
					this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
					this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
					this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
					this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
					this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
					this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
					if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
					{
						this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
						for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
						{
							Widget child = this._widget_0.GetChild(i);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)this._widget_0.GetChild(i)).DestroyDataSource();
						}
						this._datasource_Root_DeploymentController_DeploymentTargets = null;
					}
					if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
					{
						this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
						for (int j = this._widget_1_0.ChildCount - 1; j >= 0; j--)
						{
							Widget child2 = this._widget_1_0.GetChild(j);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child2).OnBeforeRemovedChild(child2);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)this._widget_1_0.GetChild(j)).DestroyDataSource();
						}
						this._datasource_Root_DeploymentController_SiegeDeploymentList = null;
					}
					this._datasource_Root_DeploymentController = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x060009B4 RID: 2484 RVA: 0x0004A522 File Offset: 0x00048722
		public void SetDataSource(MissionOrderVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060009B5 RID: 2485 RVA: 0x0004A52B File Offset: 0x0004872B
		private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
		{
			commandName == "SelectNone";
		}

		// Token: 0x060009B6 RID: 2486 RVA: 0x0004A539 File Offset: 0x00048739
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009B7 RID: 2487 RVA: 0x0004A542 File Offset: 0x00048742
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009B8 RID: 2488 RVA: 0x0004A54B File Offset: 0x0004874B
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009B9 RID: 2489 RVA: 0x0004A554 File Offset: 0x00048754
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009BA RID: 2490 RVA: 0x0004A55D File Offset: 0x0004875D
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009BB RID: 2491 RVA: 0x0004A566 File Offset: 0x00048766
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009BC RID: 2492 RVA: 0x0004A56F File Offset: 0x0004876F
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009BD RID: 2493 RVA: 0x0004A578 File Offset: 0x00048778
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009BE RID: 2494 RVA: 0x0004A581 File Offset: 0x00048781
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060009BF RID: 2495 RVA: 0x0004A58C File Offset: 0x0004878C
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "IsSiegeDeploymentDisabled")
			{
				this._datasource_Root.IsToggleOrderShown = this._widget.IsSiegeDeploymentDisabled;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsDeployment = this._widget.IsVisible;
				return;
			}
		}

		// Token: 0x060009C0 RID: 2496 RVA: 0x0004A5E1 File Offset: 0x000487E1
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C1 RID: 2497 RVA: 0x0004A5EA File Offset: 0x000487EA
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C2 RID: 2498 RVA: 0x0004A5F3 File Offset: 0x000487F3
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C3 RID: 2499 RVA: 0x0004A5FC File Offset: 0x000487FC
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C4 RID: 2500 RVA: 0x0004A605 File Offset: 0x00048805
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C5 RID: 2501 RVA: 0x0004A60E File Offset: 0x0004880E
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C6 RID: 2502 RVA: 0x0004A617 File Offset: 0x00048817
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C7 RID: 2503 RVA: 0x0004A620 File Offset: 0x00048820
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C8 RID: 2504 RVA: 0x0004A629 File Offset: 0x00048829
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x060009C9 RID: 2505 RVA: 0x0004A632 File Offset: 0x00048832
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_DeploymentController.IsSiegeDeploymentListActive = this._widget_1.IsVisible;
				return;
			}
		}

		// Token: 0x060009CA RID: 2506 RVA: 0x0004A658 File Offset: 0x00048858
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009CB RID: 2507 RVA: 0x0004A666 File Offset: 0x00048866
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009CC RID: 2508 RVA: 0x0004A674 File Offset: 0x00048874
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009CD RID: 2509 RVA: 0x0004A682 File Offset: 0x00048882
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009CE RID: 2510 RVA: 0x0004A690 File Offset: 0x00048890
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009CF RID: 2511 RVA: 0x0004A69E File Offset: 0x0004889E
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009D0 RID: 2512 RVA: 0x0004A6AC File Offset: 0x000488AC
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009D1 RID: 2513 RVA: 0x0004A6BA File Offset: 0x000488BA
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009D2 RID: 2514 RVA: 0x0004A6C8 File Offset: 0x000488C8
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060009D3 RID: 2515 RVA: 0x0004A6D8 File Offset: 0x000488D8
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "DeploymentController")
			{
				this.RefreshDataSource_datasource_Root_DeploymentController(this._datasource_Root.DeploymentController);
				return;
			}
			if (propertyName == "IsToggleOrderShown")
			{
				this._widget.IsSiegeDeploymentDisabled = this._datasource_Root.IsToggleOrderShown;
				return;
			}
			if (propertyName == "IsDeployment")
			{
				this._widget.IsVisible = this._datasource_Root.IsDeployment;
				return;
			}
		}

		// Token: 0x060009D4 RID: 2516 RVA: 0x0004A74C File Offset: 0x0004894C
		private void ViewModelPropertyChangedListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009D5 RID: 2517 RVA: 0x0004A75A File Offset: 0x0004895A
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009D6 RID: 2518 RVA: 0x0004A768 File Offset: 0x00048968
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009D7 RID: 2519 RVA: 0x0004A776 File Offset: 0x00048976
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009D8 RID: 2520 RVA: 0x0004A784 File Offset: 0x00048984
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009D9 RID: 2521 RVA: 0x0004A792 File Offset: 0x00048992
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009DA RID: 2522 RVA: 0x0004A7A0 File Offset: 0x000489A0
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009DB RID: 2523 RVA: 0x0004A7AE File Offset: 0x000489AE
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009DC RID: 2524 RVA: 0x0004A7BC File Offset: 0x000489BC
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DeploymentController(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(e.PropertyName);
		}

		// Token: 0x060009DD RID: 2525 RVA: 0x0004A7CC File Offset: 0x000489CC
		private void HandleViewModelPropertyChangeOf_datasource_Root_DeploymentController(string propertyName)
		{
			if (propertyName == "DeploymentTargets")
			{
				this.RefreshDataSource_datasource_Root_DeploymentController_DeploymentTargets(this._datasource_Root_DeploymentController.DeploymentTargets);
				return;
			}
			if (propertyName == "SiegeDeploymentList")
			{
				this.RefreshDataSource_datasource_Root_DeploymentController_SiegeDeploymentList(this._datasource_Root_DeploymentController.SiegeDeploymentList);
				return;
			}
			if (propertyName == "IsSiegeDeploymentListActive")
			{
				this._widget_1.IsVisible = this._datasource_Root_DeploymentController.IsSiegeDeploymentListActive;
				return;
			}
		}

		// Token: 0x060009DE RID: 2526 RVA: 0x0004A83C File Offset: 0x00048A3C
		public void OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case 0:
				for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
					this._widget_0.RemoveChild(child2);
				}
				return;
			case 1:
				for (int j = 0; j < this._datasource_Root_DeploymentController_DeploymentTargets.Count; j++)
				{
					DeploymentSiegeMachineVM bindingObject = this._datasource_Root_DeploymentController_DeploymentTargets[j];
					this._widget_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case 2:
			{
				OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate);
				DeploymentSiegeMachineVM deploymentSiegeMachineVM = this._datasource_Root_DeploymentController_DeploymentTargets[e.NewIndex];
				generatedWidgetData.Data = deploymentSiegeMachineVM;
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate, e.NewIndex);
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.CreateWidgets();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetIds();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetAttributes();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetDataSource(deploymentSiegeMachineVM);
				return;
			}
			case 3:
			{
				Widget child3 = this._widget_0.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case 4:
			{
				Widget child4 = this._widget_0.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child4).SetDataSource(null);
				this._widget_0.RemoveChild(child4);
				break;
			}
			case 5:
				break;
			default:
				return;
			}
		}

		// Token: 0x060009DF RID: 2527 RVA: 0x0004A9D8 File Offset: 0x00048BD8
		public void OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged(object sender, ListChangedEventArgs e)
		{
			switch (e.ListChangedType)
			{
			case 0:
				for (int i = this._widget_1_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_0.RemoveChild(child2);
				}
				return;
			case 1:
				for (int j = 0; j < this._datasource_Root_DeploymentController_SiegeDeploymentList.Count; j++)
				{
					DeploymentSiegeMachineVM bindingObject = this._datasource_Root_DeploymentController_SiegeDeploymentList[j];
					this._widget_1_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(j, false);
				}
				return;
			case 2:
			{
				OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate);
				DeploymentSiegeMachineVM deploymentSiegeMachineVM = this._datasource_Root_DeploymentController_SiegeDeploymentList[e.NewIndex];
				generatedWidgetData.Data = deploymentSiegeMachineVM;
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.AddComponent(generatedWidgetData);
				this._widget_1_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate, e.NewIndex);
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.CreateWidgets();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetIds();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetAttributes();
				orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetDataSource(deploymentSiegeMachineVM);
				return;
			}
			case 3:
			{
				Widget child3 = this._widget_1_0.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				return;
			}
			case 4:
			{
				Widget child4 = this._widget_1_0.GetChild(e.NewIndex);
				((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child4).SetDataSource(null);
				this._widget_1_0.RemoveChild(child4);
				break;
			}
			case 5:
				break;
			default:
				return;
			}
		}

		// Token: 0x060009E0 RID: 2528 RVA: 0x0004AB74 File Offset: 0x00048D74
		private void RefreshDataSource_datasource_Root(MissionOrderVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				if (this._datasource_Root_DeploymentController != null)
				{
					this._datasource_Root_DeploymentController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DeploymentController;
					this._datasource_Root_DeploymentController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DeploymentController);
					this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
					this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
					this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
					this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
					this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
					this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
					this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
					this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
					this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
					if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
					{
						this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
						for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
						{
							Widget child = this._widget_0.GetChild(i);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
							Widget child2 = this._widget_0.GetChild(i);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
							this._widget_0.RemoveChild(child2);
						}
						this._datasource_Root_DeploymentController_DeploymentTargets = null;
					}
					if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
					{
						this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
						for (int j = this._widget_1_0.ChildCount - 1; j >= 0; j--)
						{
							Widget child3 = this._widget_1_0.GetChild(j);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child3).OnBeforeRemovedChild(child3);
							Widget child4 = this._widget_1_0.GetChild(j);
							((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child4).SetDataSource(null);
							this._widget_1_0.RemoveChild(child4);
						}
						this._datasource_Root_DeploymentController_SiegeDeploymentList = null;
					}
					this._datasource_Root_DeploymentController = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.IsSiegeDeploymentDisabled = this._datasource_Root.IsToggleOrderShown;
				this._widget.IsVisible = this._datasource_Root.IsDeployment;
				this._widget.EventFire += this.EventListenerOf_widget;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
				this._datasource_Root_DeploymentController = this._datasource_Root.DeploymentController;
				if (this._datasource_Root_DeploymentController != null)
				{
					this._datasource_Root_DeploymentController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DeploymentController;
					this._datasource_Root_DeploymentController.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DeploymentController);
					this._datasource_Root_DeploymentController.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DeploymentController);
					this._widget_1.IsVisible = this._datasource_Root_DeploymentController.IsSiegeDeploymentListActive;
					this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
					this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
					this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
					this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
					this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
					this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
					this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
					this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
					this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
					this._datasource_Root_DeploymentController_DeploymentTargets = this._datasource_Root_DeploymentController.DeploymentTargets;
					if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
					{
						this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
						for (int k = 0; k < this._datasource_Root_DeploymentController_DeploymentTargets.Count; k++)
						{
							OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate(base.Context);
							GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate);
							DeploymentSiegeMachineVM deploymentSiegeMachineVM = this._datasource_Root_DeploymentController_DeploymentTargets[k];
							generatedWidgetData.Data = deploymentSiegeMachineVM;
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
							this._widget_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate, k);
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.CreateWidgets();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetIds();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetAttributes();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetDataSource(deploymentSiegeMachineVM);
						}
					}
					this._datasource_Root_DeploymentController_SiegeDeploymentList = this._datasource_Root_DeploymentController.SiegeDeploymentList;
					if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
					{
						this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
						for (int l = 0; l < this._datasource_Root_DeploymentController_SiegeDeploymentList.Count; l++)
						{
							OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate(base.Context);
							GeneratedWidgetData generatedWidgetData2 = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate);
							DeploymentSiegeMachineVM deploymentSiegeMachineVM2 = this._datasource_Root_DeploymentController_SiegeDeploymentList[l];
							generatedWidgetData2.Data = deploymentSiegeMachineVM2;
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.AddComponent(generatedWidgetData2);
							this._widget_1_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate, l);
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.CreateWidgets();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetIds();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetAttributes();
							orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetDataSource(deploymentSiegeMachineVM2);
						}
					}
				}
			}
		}

		// Token: 0x060009E1 RID: 2529 RVA: 0x0004B51C File Offset: 0x0004971C
		private void RefreshDataSource_datasource_Root_DeploymentController_DeploymentTargets(MBBindingList<DeploymentSiegeMachineVM> newDataSource)
		{
			if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
			{
				this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
				for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
					this._widget_0.RemoveChild(child2);
				}
				this._datasource_Root_DeploymentController_DeploymentTargets = null;
			}
			this._datasource_Root_DeploymentController_DeploymentTargets = newDataSource;
			this._datasource_Root_DeploymentController_DeploymentTargets = this._datasource_Root_DeploymentController.DeploymentTargets;
			if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
			{
				this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
				for (int j = 0; j < this._datasource_Root_DeploymentController_DeploymentTargets.Count; j++)
				{
					OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate);
					DeploymentSiegeMachineVM deploymentSiegeMachineVM = this._datasource_Root_DeploymentController_DeploymentTargets[j];
					generatedWidgetData.Data = deploymentSiegeMachineVM;
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate, j);
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.CreateWidgets();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetIds();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetAttributes();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetDataSource(deploymentSiegeMachineVM);
				}
			}
		}

		// Token: 0x060009E2 RID: 2530 RVA: 0x0004B658 File Offset: 0x00049858
		private void RefreshDataSource_datasource_Root_DeploymentController(MissionOrderDeploymentControllerVM newDataSource)
		{
			if (this._datasource_Root_DeploymentController != null)
			{
				this._datasource_Root_DeploymentController.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_DeploymentController;
				this._datasource_Root_DeploymentController.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DeploymentController);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
				{
					this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
					for (int i = this._widget_0.ChildCount - 1; i >= 0; i--)
					{
						Widget child = this._widget_0.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = this._widget_0.GetChild(i);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate)child2).SetDataSource(null);
						this._widget_0.RemoveChild(child2);
					}
					this._datasource_Root_DeploymentController_DeploymentTargets = null;
				}
				if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
				{
					this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
					for (int j = this._widget_1_0.ChildCount - 1; j >= 0; j--)
					{
						Widget child3 = this._widget_1_0.GetChild(j);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child3).OnBeforeRemovedChild(child3);
						Widget child4 = this._widget_1_0.GetChild(j);
						((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child4).SetDataSource(null);
						this._widget_1_0.RemoveChild(child4);
					}
					this._datasource_Root_DeploymentController_SiegeDeploymentList = null;
				}
				this._datasource_Root_DeploymentController = null;
			}
			this._datasource_Root_DeploymentController = newDataSource;
			this._datasource_Root_DeploymentController = this._datasource_Root.DeploymentController;
			if (this._datasource_Root_DeploymentController != null)
			{
				this._datasource_Root_DeploymentController.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_DeploymentController;
				this._datasource_Root_DeploymentController.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_DeploymentController);
				this._datasource_Root_DeploymentController.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_DeploymentController);
				this._widget_1.IsVisible = this._datasource_Root_DeploymentController.IsSiegeDeploymentListActive;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._datasource_Root_DeploymentController_DeploymentTargets = this._datasource_Root_DeploymentController.DeploymentTargets;
				if (this._datasource_Root_DeploymentController_DeploymentTargets != null)
				{
					this._datasource_Root_DeploymentController_DeploymentTargets.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_DeploymentTargetsChanged);
					for (int k = 0; k < this._datasource_Root_DeploymentController_DeploymentTargets.Count; k++)
					{
						OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate);
						DeploymentSiegeMachineVM deploymentSiegeMachineVM = this._datasource_Root_DeploymentController_DeploymentTargets[k];
						generatedWidgetData.Data = deploymentSiegeMachineVM;
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.AddComponent(generatedWidgetData);
						this._widget_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate, k);
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.CreateWidgets();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetIds();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetAttributes();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_7_ItemTemplate.SetDataSource(deploymentSiegeMachineVM);
					}
				}
				this._datasource_Root_DeploymentController_SiegeDeploymentList = this._datasource_Root_DeploymentController.SiegeDeploymentList;
				if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
				{
					this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
					for (int l = 0; l < this._datasource_Root_DeploymentController_SiegeDeploymentList.Count; l++)
					{
						OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData2 = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate);
						DeploymentSiegeMachineVM deploymentSiegeMachineVM2 = this._datasource_Root_DeploymentController_SiegeDeploymentList[l];
						generatedWidgetData2.Data = deploymentSiegeMachineVM2;
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.AddComponent(generatedWidgetData2);
						this._widget_1_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate, l);
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.CreateWidgets();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetIds();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetAttributes();
						orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetDataSource(deploymentSiegeMachineVM2);
					}
				}
			}
		}

		// Token: 0x060009E3 RID: 2531 RVA: 0x0004BC4C File Offset: 0x00049E4C
		private void RefreshDataSource_datasource_Root_DeploymentController_SiegeDeploymentList(MBBindingList<DeploymentSiegeMachineVM> newDataSource)
		{
			if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
			{
				this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged -= new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
				for (int i = this._widget_1_0.ChildCount - 1; i >= 0; i--)
				{
					Widget child = this._widget_1_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = this._widget_1_0.GetChild(i);
					((OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate)child2).SetDataSource(null);
					this._widget_1_0.RemoveChild(child2);
				}
				this._datasource_Root_DeploymentController_SiegeDeploymentList = null;
			}
			this._datasource_Root_DeploymentController_SiegeDeploymentList = newDataSource;
			this._datasource_Root_DeploymentController_SiegeDeploymentList = this._datasource_Root_DeploymentController.SiegeDeploymentList;
			if (this._datasource_Root_DeploymentController_SiegeDeploymentList != null)
			{
				this._datasource_Root_DeploymentController_SiegeDeploymentList.ListChanged += new ListChangedEventHandler(this.OnList_datasource_Root_DeploymentController_SiegeDeploymentListChanged);
				for (int j = 0; j < this._datasource_Root_DeploymentController_SiegeDeploymentList.Count; j++)
				{
					OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate = new OrderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate(base.Context);
					GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate);
					DeploymentSiegeMachineVM deploymentSiegeMachineVM = this._datasource_Root_DeploymentController_SiegeDeploymentList[j];
					generatedWidgetData.Data = deploymentSiegeMachineVM;
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.AddComponent(generatedWidgetData);
					this._widget_1_0.AddChildAtIndex(orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate, j);
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.CreateWidgets();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetIds();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetAttributes();
					orderBar__TaleWorlds_MountAndBlade_ViewModelCollection_Order_MissionOrderVM_Dependency_8_ItemTemplate.SetDataSource(deploymentSiegeMachineVM);
				}
			}
		}

		// Token: 0x0400022B RID: 555
		private OrderSiegeDeploymentScreenWidget _widget;

		// Token: 0x0400022C RID: 556
		private Widget _widget_0;

		// Token: 0x0400022D RID: 557
		private Widget _widget_1;

		// Token: 0x0400022E RID: 558
		private ListPanel _widget_1_0;

		// Token: 0x0400022F RID: 559
		private MissionOrderVM _datasource_Root;

		// Token: 0x04000230 RID: 560
		private MissionOrderDeploymentControllerVM _datasource_Root_DeploymentController;

		// Token: 0x04000231 RID: 561
		private MBBindingList<DeploymentSiegeMachineVM> _datasource_Root_DeploymentController_DeploymentTargets;

		// Token: 0x04000232 RID: 562
		private MBBindingList<DeploymentSiegeMachineVM> _datasource_Root_DeploymentController_SiegeDeploymentList;
	}
}
