#!/usr/bin/env python3
"""
批量美化01_initialization.c文件中的函数名
"""

import re
import sys

def read_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(file_path, content):
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

def beautify_functions(content):
    # 函数名映射表
    function_mappings = {
        'FUN_180060080': 'ProcessSystemResourceMemory',
        'FUN_1800603e0': 'InitializeSystemResourceContext',
        'FUN_180060420': 'InitializeSystemResourceManager',
        'FUN_1800605d0': 'ConfigureSystemResourceData',
        'FUN_180060610': 'ProcessSystemResourceConfiguration',
        'FUN_180060630': 'ReleaseSystemResourceMemory',
        'FUN_1800606e0': 'AllocateSystemMemoryBlock',
        'FUN_1800607f0': 'ProcessSystemResourceAllocationRequest',
        'FUN_1800609c0': 'ValidateSystemResourceAllocation',
        'FUN_180060a50': 'GetSystemResourceStatus',
        'FUN_180060b80': 'ConfigureSystemResourcePointer',
        'FUN_180060bd0': 'GetSystemResourcePointer',
        'FUN_180060c60': 'InitializeSystemResourceData',
        'FUN_180060d76': 'GetSystemResourceData',
        'FUN_180060e22': 'CheckSystemResourceStatus',
        'FUN_180060e40': 'ProcessSystemResourceOperation',
        'FUN_180060f50': 'ValidateSystemResourceOperation',
        'FUN_180060fc0': 'ConfigureSystemMemoryAllocation',
        'FUN_1800611a0': 'ProcessSystemMemoryAllocation',
        'FUN_180061290': 'InitializeSystemMemoryContext',
        'FUN_1800612b0': 'ConfigureSystemMemoryContext',
        'FUN_180061300': 'ProcessSystemMemoryConfiguration',
        'FUN_1800622d0': 'ExecuteSystemResourceOperation',
        'FUN_180062340': 'UpdateSystemResourceManager',
        'FUN_180062380': 'ConfigureSystemManager',
        'FUN_180062920': 'ProcessSystemResourceCounter',
        'FUN_180062ee0': 'InitializeSystemResourceContext',
        'FUN_180062fd0': 'DispatchSystemResourcesAndCreateThreads',
        'FUN_1800634b0': 'ProcessSystemResourceRequest',
        'FUN_180063510': 'SearchSystemResource',
        'FUN_1800635c0': 'InitializeSystemStringFormatting',
        'FUN_1800635e0': 'ProcessSystemStringFormatting',
        'FUN_180063650': 'ConfigureSystemStringFormatting',
        'FUN_1800637c0': 'InitializeSecurityCallbackStructure',
        'FUN_1800637f0': 'InitializeGuardCallbackStructure',
        'FUN_180063820': 'InitializeSecurityContext',
        'FUN_180063b30': 'ConfigureSecurityParameters',
        'FUN_180063cf0': 'InitializeSystemSecurityManager',
        'FUN_180064010': 'ConfigureSystemSecurityManager',
        'FUN_180064400': 'ProcessSystemSecurityOperation',
        'FUN_1800649d0': 'GetSystemSecurityStatus',
        'FUN_180064c00': 'ConfigureSystemSecurityParameters',
        'FUN_180065160': 'InitializeSystemSecurityContext',
        'FUN_180065d50': 'InitializeSystemResourceAllocator',
        'FUN_180065f00': 'ConfigureSystemResourceAllocator',
        'FUN_180066140': 'ProcessSystemResourceAllocation',
        'FUN_180066dd0': 'ReleaseSystemResourceAllocator',
        'FUN_180066df0': 'CleanupSystemResourceAllocator',
        'FUN_180067050': 'ResetSystemResourceAllocator',
        'FUN_180067070': 'ValidateSystemResourceAllocator',
        'FUN_1800670d0': 'CheckSystemResourceAllocatorStatus',
        'FUN_180067110': 'ProcessSystemResourceAllocatorOperation',
        'FUN_180067170': 'ConfigureSystemResourceAllocatorParameters',
        'FUN_1800671b0': 'InitializeSystemResourceAllocatorContext',
        'FUN_18006720b': 'ProcessSystemResourceAllocatorRequest',
        'FUN_1800672b0': 'ReleaseSystemResourceAllocatorContext',
        'FUN_1800672b7': 'ResetSystemResourceAllocatorContext',
        'FUN_1800672c0': 'ConfigureSystemResourceAllocatorMemory',
        'FUN_180067480': 'InitializeSystemResourceAllocatorMemory',
        'FUN_180067810': 'ProcessSystemResourceAllocatorMemoryOperation',
        'FUN_180067840': 'ValidateSystemResourceAllocatorMemory',
        'FUN_180067bc0': 'ConfigureSystemResourceAllocatorMemoryContext',
        'FUN_180067f00': 'ReleaseSystemResourceAllocatorMemoryContext',
        'FUN_180067f30': 'ResetSystemResourceAllocatorMemoryContext',
        'FUN_180067f60': 'ProcessSystemResourceAllocatorMemoryConfiguration',
        'FUN_180068250': 'InitializeSystemResourceAllocatorMemoryData',
        'FUN_180068620': 'ConfigureSystemResourceAllocatorMemoryData',
        'FUN_1800686b0': 'ProcessSystemResourceAllocatorMemoryDataOperation',
        'FUN_1800687d0': 'ValidateSystemResourceAllocatorMemoryData',
        'FUN_180068a90': 'GetSystemResourceAllocatorMemoryData',
        'FUN_180068ce0': 'ConfigureSystemResourceAllocatorMemoryDataContext',
        'FUN_180068ec0': 'ProcessSystemResourceAllocatorMemoryDataOperation',
        'FUN_180069070': 'ValidateSystemResourceAllocatorMemoryDataContext',
        'FUN_180069130': 'ProcessSystemResourceAllocatorMemoryDataConfiguration',
        'FUN_180069190': 'ConfigureSystemResourceAllocatorMemoryDataParameters',
        'FUN_180069220': 'ProcessSystemResourceAllocatorMemoryDataParameters',
        'FUN_180069241': 'ResetSystemResourceAllocatorMemoryDataParameters',
        'FUN_180069266': 'ValidateSystemResourceAllocatorMemoryDataParameters',
        'FUN_180069280': 'ProcessSystemResourceAllocatorMemoryDataParameterConfiguration',
        'FUN_1800693f0': 'ConfigureSystemResourceAllocatorMemoryDataParameterContext',
        'FUN_180069470': 'ProcessSystemResourceAllocatorMemoryDataParameterOperation',
        'FUN_180069530': 'InitializeSystemResourceAllocatorMemoryDataParameterContext',
        'FUN_1800695a0': 'ReleaseSystemResourceAllocatorMemoryDataParameterContext',
        'FUN_180069720': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemory',
        'FUN_180069760': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryOperation',
        'FUN_1800697a0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemory',
        'FUN_180069920': 'GetSystemResourceAllocatorMemoryDataParameterMemoryData',
        'FUN_180069cc0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataContext',
        'FUN_180069f60': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataOperation',
        'FUN_180069fb0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryData',
        'FUN_180069fe0': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataContext',
        'FUN_18006a050': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataConfiguration',
        'FUN_18006a090': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataParameters',
        'FUN_18006a130': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataContext',
        'FUN_18006b220': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataContext',
        'FUN_18006b350': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataOperation',
        'FUN_18006b440': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryData',
        'FUN_18006b4c0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataContext',
        'FUN_18006b540': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataConfiguration',
        'FUN_18006b6f0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataConfiguration',
        'FUN_18006b760': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidation',
        'FUN_18006b780': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationContext',
        'FUN_18006b8f0': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationContext',
        'FUN_18006b940': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationParameters',
        'FUN_18006bd20': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationContext',
        'FUN_18006bd60': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationOperation',
        'FUN_18006bd80': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationParameters',
        'FUN_18006c070': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationParameters',
        'FUN_18006cb90': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfiguration',
        'FUN_18006cc50': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006cc8d': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006cd43': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006cd80': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006cf00': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006d0b0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006d450': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006d4e0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006d6c0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006d810': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006d920': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006da50': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006da90': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006dc10': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006dcb0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e000': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e0b0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006e140': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006e460': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e4a0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e4a4': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006e4b9': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006e50f': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006e570': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e580': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e5d0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006e640': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006e660': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006e990': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006edf0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006eec0': 'GetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationStatus',
        'FUN_18006ef80': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationStatus',
        'FUN_18006efc0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006f160': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006f310': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006f4cd': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006f4fc': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18006f500': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006f530': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006f620': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18006f940': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18006ff80': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180070680': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180070930': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180071940': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180072000': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180072e80': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180072f00': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180073630': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180073730': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180073830': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_1800739f0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180073adc': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180073b64': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180073e0b': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_1800740a2': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1800742ea': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_1800746c0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180074840': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1800748d0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180074a80': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180074b30': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180074c20': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180074ed0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180074f70': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180075030': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180075580': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180075630': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1800756e0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180075990': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180075af0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180075ff0': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_1800763c0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180076760': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180076910': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180076a20': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180076b90': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180076c50': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180077020': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180077040': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180077150': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180077420': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180077710': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180077750': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007799c': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180077ad8': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180077c96': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180077dc6': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180077dec': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180077f20': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180078051': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180078143': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_1800781e0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1800781f4': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180078239': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_1800782a8': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1800783b0': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_1800784e0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180078550': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1800786e0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180078c10': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180078c70': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_1800791a0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_180079270': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_180079284': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_1800792ea': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_180079309': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007940e': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_1800796b0': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007b1a0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007b1c0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007b240': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007b930': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007ba60': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007baa0': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007bb70': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007c790': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007c7f0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007c860': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007cbb0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007df50': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007e080': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007e2b0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007e5b0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007e880': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007e930': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007e95f': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007e988': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007e990': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007ea10': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007edd0': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007ee70': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007eea1': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007ef9a': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007f0b5': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f0bf': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f0ca': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007f0e0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007f11f': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f176': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f27a': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007f2cf': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007f2f0': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007f3b0': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007f4c0': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f6a0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007f820': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f8f0': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007f90f': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007f933': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f976': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007f983': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007fb5f': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007fc19': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007fc35': 'ValidateSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007fc63': 'ReleaseSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007fc68': 'ResetSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_18007fc6d': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_18007fc73': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters',
        'FUN_18007fca8': 'InitializeSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationContext',
        'FUN_1807794c5': 'ProcessSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationOperation',
        'FUN_1807794dd': 'ConfigureSystemResourceAllocatorMemoryDataParameterMemoryDataValidationConfigurationParameters'
    }
    
    # 批量替换函数名
    for old_name, new_name in function_mappings.items():
        # 匹配函数定义
        pattern = r'(\b(?:void|int|char|long|ulong|bool|\*|\s)+)' + re.escape(old_name) + r'\('
        replacement = r'\1' + new_name + '('
        content = re.sub(pattern, replacement, content)
        
        # 匹配函数调用
        pattern = r'\b' + re.escape(old_name) + r'\('
        replacement = new_name + '('
        content = re.sub(pattern, replacement, content)
    
    return content

def main():
    file_path = '/dev/shm/mountblade-code/TaleWorlds.Native/src/01_initialization.c'
    
    print("正在读取文件...")
    content = read_file(file_path)
    
    print("正在美化函数名...")
    content = beautify_functions(content)
    
    print("正在写入文件...")
    write_file(file_path, content)
    
    print("完成！")

if __name__ == '__main__':
    main()