#!/usr/bin/env python3
"""
网络模块函数美化脚本
用于批量重命名05_networking.c中的FUN_函数
"""

import re
import sys

def read_file(file_path):
    """读取文件内容"""
    with open(file_path, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(file_path, content):
    """写入文件内容"""
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

def beautify_functions(content):
    """美化函数名称"""
    
    # 函数名称映射表
    function_mappings = {
        'FUN_18086d2af': 'ProcessConnectionDataTransferThirdInstance',
        'FUN_18086d2cc': 'ProcessConnectionDataTransferFourthInstance',
        'FUN_180870500': 'ProcessNetworkPacketValidation',
        'FUN_1808705f0': 'ProcessNetworkPacketAuthentication',
        'FUN_1808706e0': 'ProcessNetworkPacketEncryption',
        'FUN_180874afe': 'InitializeNetworkConnectionPool',
        'FUN_180875d28': 'CleanupNetworkConnectionPool',
        'FUN_180877970': 'HandleNetworkConnectionRequest',
        'FUN_180877f00': 'ProcessNetworkConnectionResponse',
        'FUN_1808780d0': 'ValidateNetworkConnectionData',
        'FUN_1808787d0': 'ExecuteNetworkOperation',
        'FUN_18087e0b0': 'ProcessNetworkTransferOperation',
        'FUN_1808690e0': 'InitializeNetworkContext',
        'FUN_180869400': 'SetupNetworkConnection',
        'FUN_1808740c0': 'FinalizeNetworkTransfer',
        'FUN_1808c2060': 'CreateNetworkIterationContext',
        'FUN_1808c5220': 'ProcessNetworkStackData',
        'FUN_1808bfbe0': 'ValidateNetworkConnectionHandle',
        'FUN_18086f460': 'ExecuteNetworkConnectionOperation',
        'FUN_18087c9b0': 'ProcessNetworkConnectionIteration',
        'FUN_1808dea80': 'CheckNetworkConnectionStatus',
        'FUN_1808c7ff0': 'CleanupNetworkContext'
    }
    
    # 替换函数定义
    for old_name, new_name in function_mappings.items():
        # 替换函数注释行
        content = re.sub(
            rf'// 函数: void {old_name}\((.*?)\)',
            rf'// 函数: void {new_name}(\1)',
            content
        )
        
        # 替换函数调用
        content = re.sub(
            rf'\b{old_name}\b',
            new_name,
            content
        )
    
    return content

def beautify_variables(content):
    """美化变量名称"""
    
    # 变量名称映射表
    variable_mappings = {
        'plStack_948': 'NetworkStackBuffer',
        'extraout_XMM0_Da_04': 'NetworkOperationResult',
        'puVar1': 'PrimaryNetworkVariable',
        'puVar2': 'SecondaryNetworkVariable',
        'puVar3': 'TertiaryNetworkVariable',
        'local_10': 'NetworkContextLocal',
        'local_18': 'NetworkConnectionLocal',
        'local_20': 'NetworkBufferLocal',
        'local_28': 'NetworkStatusLocal',
        'local_30': 'NetworkOperationLocal',
        'local_38': 'NetworkTransferLocal',
        'local_40': 'NetworkPacketLocal',
        'local_48': 'NetworkSocketLocal',
        'local_50': 'NetworkHandleLocal',
        'local_58': 'NetworkProtocolLocal',
        'local_60': 'NetworkAddressLocal',
        'local_68': 'NetworkPortLocal',
        'local_70': 'NetworkFlagLocal',
        'local_78': 'NetworkErrorLocal',
        'local_80': 'NetworkTimeoutLocal',
        'local_88': 'NetworkRetryLocal',
        'local_90': 'NetworkBufferLocal',
        'local_98': 'NetworkContextLocal',
        'local_a0': 'NetworkConnectionLocal',
        'local_a8': 'NetworkBufferLocal',
        'local_b0': 'NetworkStatusLocal',
        'local_b8': 'NetworkOperationLocal',
        'local_c0': 'NetworkTransferLocal',
        'local_c8': 'NetworkPacketLocal',
        'local_d0': 'NetworkSocketLocal',
        'local_d8': 'NetworkHandleLocal',
        'local_e0': 'NetworkProtocolLocal',
        'local_e8': 'NetworkAddressLocal',
        'local_f0': 'NetworkPortLocal',
        'local_f8': 'NetworkFlagLocal',
        'local_100': 'NetworkErrorLocal',
        'local_108': 'NetworkTimeoutLocal',
        'local_110': 'NetworkRetryLocal',
        'local_118': 'NetworkBufferLocal',
        'local_120': 'NetworkContextLocal',
        'local_128': 'NetworkConnectionLocal',
        'local_130': 'NetworkBufferLocal',
        'local_138': 'NetworkStatusLocal',
        'local_140': 'NetworkOperationLocal',
        'local_148': 'NetworkTransferLocal',
        'local_150': 'NetworkPacketLocal',
        'local_158': 'NetworkSocketLocal',
        'local_160': 'NetworkHandleLocal',
        'local_168': 'NetworkProtocolLocal',
        'local_170': 'NetworkAddressLocal',
        'local_178': 'NetworkPortLocal',
        'local_180': 'NetworkFlagLocal',
        'local_188': 'NetworkErrorLocal',
        'local_190': 'NetworkTimeoutLocal',
        'local_198': 'NetworkRetryLocal',
        'local_1a0': 'NetworkBufferLocal',
        'local_1a8': 'NetworkContextLocal',
        'local_1b0': 'NetworkConnectionLocal',
        'local_1b8': 'NetworkBufferLocal',
        'local_1c0': 'NetworkStatusLocal',
        'local_1c8': 'NetworkOperationLocal',
        'local_1d0': 'NetworkTransferLocal',
        'local_1d8': 'NetworkPacketLocal',
        'local_1e0': 'NetworkSocketLocal',
        'local_1e8': 'NetworkHandleLocal',
        'local_1f0': 'NetworkProtocolLocal',
        'local_1f8': 'NetworkAddressLocal',
        'local_200': 'NetworkPortLocal',
        'local_208': 'NetworkFlagLocal',
        'local_210': 'NetworkErrorLocal',
        'local_218': 'NetworkTimeoutLocal',
        'local_220': 'NetworkRetryLocal',
        'local_228': 'NetworkBufferLocal',
        'local_230': 'NetworkContextLocal',
        'local_238': 'NetworkConnectionLocal',
        'local_240': 'NetworkBufferLocal',
        'local_248': 'NetworkStatusLocal',
        'local_250': 'NetworkOperationLocal',
        'local_258': 'NetworkTransferLocal',
        'local_260': 'NetworkPacketLocal',
        'local_268': 'NetworkSocketLocal',
        'local_270': 'NetworkHandleLocal',
        'local_278': 'NetworkProtocolLocal',
        'local_280': 'NetworkAddressLocal',
        'local_288': 'NetworkPortLocal',
        'local_290': 'NetworkFlagLocal',
        'local_298': 'NetworkErrorLocal',
        'local_2a0': 'NetworkTimeoutLocal',
        'local_2a8': 'NetworkRetryLocal',
        'local_2b0': 'NetworkBufferLocal',
        'local_2b8': 'NetworkContextLocal',
        'local_2c0': 'NetworkConnectionLocal',
        'local_2c8': 'NetworkBufferLocal',
        'local_2d0': 'NetworkStatusLocal',
        'local_2d8': 'NetworkOperationLocal',
        'local_2e0': 'NetworkTransferLocal',
        'local_2e8': 'NetworkPacketLocal',
        'local_2f0': 'NetworkSocketLocal',
        'local_2f8': 'NetworkHandleLocal',
        'local_300': 'NetworkProtocolLocal',
        'local_308': 'NetworkAddressLocal',
        'local_310': 'NetworkPortLocal',
        'local_318': 'NetworkFlagLocal',
        'local_320': 'NetworkErrorLocal',
        'local_328': 'NetworkTimeoutLocal',
        'local_330': 'NetworkRetryLocal',
        'local_338': 'NetworkBufferLocal',
        'local_340': 'NetworkContextLocal',
        'local_348': 'NetworkConnectionLocal',
        'local_350': 'NetworkBufferLocal',
        'local_358': 'NetworkStatusLocal',
        'local_360': 'NetworkOperationLocal',
        'local_368': 'NetworkTransferLocal',
        'local_370': 'NetworkPacketLocal',
        'local_378': 'NetworkSocketLocal',
        'local_380': 'NetworkHandleLocal',
        'local_388': 'NetworkProtocolLocal',
        'local_390': 'NetworkAddressLocal',
        'local_398': 'NetworkPortLocal',
        'local_3a0': 'NetworkFlagLocal',
        'local_3a8': 'NetworkErrorLocal',
        'local_3b0': 'NetworkTimeoutLocal',
        'local_3b8': 'NetworkRetryLocal',
        'local_3c0': 'NetworkBufferLocal',
        'local_3c8': 'NetworkContextLocal',
        'local_3d0': 'NetworkConnectionLocal',
        'local_3d8': 'NetworkBufferLocal',
        'local_3e0': 'NetworkStatusLocal',
        'local_3e8': 'NetworkOperationLocal',
        'local_3f0': 'NetworkTransferLocal',
        'local_3f8': 'NetworkPacketLocal',
        'local_400': 'NetworkSocketLocal',
        'local_408': 'NetworkHandleLocal',
        'local_410': 'NetworkProtocolLocal',
        'local_418': 'NetworkAddressLocal',
        'local_420': 'NetworkPortLocal',
        'local_428': 'NetworkFlagLocal',
        'local_430': 'NetworkErrorLocal',
        'local_438': 'NetworkTimeoutLocal',
        'local_440': 'NetworkRetryLocal',
        'local_448': 'NetworkBufferLocal',
        'local_450': 'NetworkContextLocal',
        'local_458': 'NetworkConnectionLocal',
        'local_460': 'NetworkBufferLocal',
        'local_468': 'NetworkStatusLocal',
        'local_470': 'NetworkOperationLocal',
        'local_478': 'NetworkTransferLocal',
        'local_480': 'NetworkPacketLocal',
        'local_488': 'NetworkSocketLocal',
        'local_490': 'NetworkHandleLocal',
        'local_498': 'NetworkProtocolLocal',
        'local_4a0': 'NetworkAddressLocal',
        'local_4a8': 'NetworkPortLocal',
        'local_4b0': 'NetworkFlagLocal',
        'local_4b8': 'NetworkErrorLocal',
        'local_4c0': 'NetworkTimeoutLocal',
        'local_4c8': 'NetworkRetryLocal',
        'local_4d0': 'NetworkBufferLocal',
        'local_4d8': 'NetworkContextLocal',
        'local_4e0': 'NetworkConnectionLocal',
        'local_4e8': 'NetworkBufferLocal',
        'local_4f0': 'NetworkStatusLocal',
        'local_4f8': 'NetworkOperationLocal',
        'local_500': 'NetworkTransferLocal',
        'local_508': 'NetworkPacketLocal',
        'local_510': 'NetworkSocketLocal',
        'local_518': 'NetworkHandleLocal',
        'local_520': 'NetworkProtocolLocal',
        'local_528': 'NetworkAddressLocal',
        'local_530': 'NetworkPortLocal',
        'local_538': 'NetworkFlagLocal',
        'local_540': 'NetworkErrorLocal',
        'local_548': 'NetworkTimeoutLocal',
        'local_550': 'NetworkRetryLocal',
        'local_558': 'NetworkBufferLocal',
        'local_560': 'NetworkContextLocal',
        'local_568': 'NetworkConnectionLocal',
        'local_570': 'NetworkBufferLocal',
        'local_578': 'NetworkStatusLocal',
        'local_580': 'NetworkOperationLocal',
        'local_588': 'NetworkTransferLocal',
        'local_590': 'NetworkPacketLocal',
        'local_598': 'NetworkSocketLocal',
        'local_5a0': 'NetworkHandleLocal',
        'local_5a8': 'NetworkProtocolLocal',
        'local_5b0': 'NetworkAddressLocal',
        'local_5b8': 'NetworkPortLocal',
        'local_5c0': 'NetworkFlagLocal',
        'local_5c8': 'NetworkErrorLocal',
        'local_5d0': 'NetworkTimeoutLocal',
        'local_5d8': 'NetworkRetryLocal',
        'local_5e0': 'NetworkBufferLocal',
        'local_5e8': 'NetworkContextLocal',
        'local_5f0': 'NetworkConnectionLocal',
        'local_5f8': 'NetworkBufferLocal',
        'local_600': 'NetworkStatusLocal',
        'local_608': 'NetworkOperationLocal',
        'local_610': 'NetworkTransferLocal',
        'local_618': 'NetworkPacketLocal',
        'local_620': 'NetworkSocketLocal',
        'local_628': 'NetworkHandleLocal',
        'local_630': 'NetworkProtocolLocal',
        'local_638': 'NetworkAddressLocal',
        'local_640': 'NetworkPortLocal',
        'local_648': 'NetworkFlagLocal',
        'local_650': 'NetworkErrorLocal',
        'local_658': 'NetworkTimeoutLocal',
        'local_660': 'NetworkRetryLocal',
        'local_668': 'NetworkBufferLocal',
        'local_670': 'NetworkContextLocal',
        'local_678': 'NetworkConnectionLocal',
        'local_680': 'NetworkBufferLocal',
        'local_688': 'NetworkStatusLocal',
        'local_690': 'NetworkOperationLocal',
        'local_698': 'NetworkTransferLocal',
        'local_6a0': 'NetworkPacketLocal',
        'local_6a8': 'NetworkSocketLocal',
        'local_6b0': 'NetworkHandleLocal',
        'local_6b8': 'NetworkProtocolLocal',
        'local_6c0': 'NetworkAddressLocal',
        'local_6c8': 'NetworkPortLocal',
        'local_6d0': 'NetworkFlagLocal',
        'local_6d8': 'NetworkErrorLocal',
        'local_6e0': 'NetworkTimeoutLocal',
        'local_6e8': 'NetworkRetryLocal',
        'local_6f0': 'NetworkBufferLocal',
        'local_6f8': 'NetworkContextLocal',
        'local_700': 'NetworkConnectionLocal',
        'local_708': 'NetworkBufferLocal',
        'local_710': 'NetworkStatusLocal',
        'local_718': 'NetworkOperationLocal',
        'local_720': 'NetworkTransferLocal',
        'local_728': 'NetworkPacketLocal',
        'local_730': 'NetworkSocketLocal',
        'local_738': 'NetworkHandleLocal',
        'local_740': 'NetworkProtocolLocal',
        'local_748': 'NetworkAddressLocal',
        'local_750': 'NetworkPortLocal',
        'local_758': 'NetworkFlagLocal',
        'local_760': 'NetworkErrorLocal',
        'local_768': 'NetworkTimeoutLocal',
        'local_770': 'NetworkRetryLocal',
        'local_778': 'NetworkBufferLocal',
        'local_780': 'NetworkContextLocal',
        'local_788': 'NetworkConnectionLocal',
        'local_790': 'NetworkBufferLocal',
        'local_798': 'NetworkStatusLocal',
        'local_7a0': 'NetworkOperationLocal',
        'local_7a8': 'NetworkTransferLocal',
        'local_7b0': 'NetworkPacketLocal',
        'local_7b8': 'NetworkSocketLocal',
        'local_7c0': 'NetworkHandleLocal',
        'local_7c8': 'NetworkProtocolLocal',
        'local_7d0': 'NetworkAddressLocal',
        'local_7d8': 'NetworkPortLocal',
        'local_7e0': 'NetworkFlagLocal',
        'local_7e8': 'NetworkErrorLocal',
        'local_7f0': 'NetworkTimeoutLocal',
        'local_7f8': 'NetworkRetryLocal',
        'local_800': 'NetworkBufferLocal',
        'local_808': 'NetworkContextLocal',
        'local_810': 'NetworkConnectionLocal',
        'local_818': 'NetworkBufferLocal',
        'local_820': 'NetworkStatusLocal',
        'local_828': 'NetworkOperationLocal',
        'local_830': 'NetworkTransferLocal',
        'local_838': 'NetworkPacketLocal',
        'local_840': 'NetworkSocketLocal',
        'local_848': 'NetworkHandleLocal',
        'local_850': 'NetworkProtocolLocal',
        'local_858': 'NetworkAddressLocal',
        'local_860': 'NetworkPortLocal',
        'local_868': 'NetworkFlagLocal',
        'local_870': 'NetworkErrorLocal',
        'local_878': 'NetworkTimeoutLocal',
        'local_880': 'NetworkRetryLocal',
        'local_888': 'NetworkBufferLocal',
        'local_890': 'NetworkContextLocal',
        'local_898': 'NetworkConnectionLocal',
        'local_8a0': 'NetworkBufferLocal',
        'local_8a8': 'NetworkStatusLocal',
        'local_8b0': 'NetworkOperationLocal',
        'local_8b8': 'NetworkTransferLocal',
        'local_8c0': 'NetworkPacketLocal',
        'local_8c8': 'NetworkSocketLocal',
        'local_8d0': 'NetworkHandleLocal',
        'local_8d8': 'NetworkProtocolLocal',
        'local_8e0': 'NetworkAddressLocal',
        'local_8e8': 'NetworkPortLocal',
        'local_8f0': 'NetworkFlagLocal',
        'local_8f8': 'NetworkErrorLocal',
        'local_900': 'NetworkTimeoutLocal',
        'local_908': 'NetworkRetryLocal',
        'local_910': 'NetworkBufferLocal',
        'local_918': 'NetworkContextLocal',
        'local_920': 'NetworkConnectionLocal',
        'local_928': 'NetworkBufferLocal',
        'local_930': 'NetworkStatusLocal',
        'local_938': 'NetworkOperationLocal',
        'local_940': 'NetworkTransferLocal',
        'local_948': 'NetworkStackBuffer',
        'local_950': 'NetworkContextLocal',
        'local_958': 'NetworkConnectionLocal',
        'local_960': 'NetworkBufferLocal',
        'local_968': 'NetworkStatusLocal',
        'local_970': 'NetworkOperationLocal',
        'local_978': 'NetworkTransferLocal',
        'local_980': 'NetworkPacketLocal',
        'local_988': 'NetworkSocketLocal',
        'local_990': 'NetworkHandleLocal',
        'local_998': 'NetworkProtocolLocal',
        'local_9a0': 'NetworkAddressLocal',
        'local_9a8': 'NetworkPortLocal',
        'local_9b0': 'NetworkFlagLocal',
        'local_9b8': 'NetworkErrorLocal',
        'local_9c0': 'NetworkTimeoutLocal',
        'local_9c8': 'NetworkRetryLocal',
        'local_9d0': 'NetworkBufferLocal',
        'local_9d8': 'NetworkContextLocal',
        'local_9e0': 'NetworkConnectionLocal',
        'local_9e8': 'NetworkBufferLocal',
        'local_9f0': 'NetworkStatusLocal',
        'local_9f8': 'NetworkOperationLocal',
        'local_a00': 'NetworkTransferLocal',
        'local_a08': 'NetworkPacketLocal',
        'local_a10': 'NetworkSocketLocal',
        'local_a18': 'NetworkHandleLocal',
        'local_a20': 'NetworkProtocolLocal',
        'local_a28': 'NetworkAddressLocal',
        'local_a30': 'NetworkPortLocal',
        'local_a38': 'NetworkFlagLocal',
        'local_a40': 'NetworkErrorLocal',
        'local_a48': 'NetworkTimeoutLocal',
        'local_a50': 'NetworkRetryLocal',
        'local_a58': 'NetworkBufferLocal',
        'local_a60': 'NetworkContextLocal',
        'local_a68': 'NetworkConnectionLocal',
        'local_a70': 'NetworkBufferLocal',
        'local_a78': 'NetworkStatusLocal',
        'local_a80': 'NetworkOperationLocal',
        'local_a88': 'NetworkTransferLocal',
        'local_a90': 'NetworkPacketLocal',
        'local_a98': 'NetworkSocketLocal',
        'local_aa0': 'NetworkHandleLocal',
        'local_aa8': 'NetworkProtocolLocal',
        'local_ab0': 'NetworkAddressLocal',
        'local_ab8': 'NetworkPortLocal',
        'local_ac0': 'NetworkFlagLocal',
        'local_ac8': 'NetworkErrorLocal',
        'local_ad0': 'NetworkTimeoutLocal',
        'local_ad8': 'NetworkRetryLocal',
        'local_ae0': 'NetworkBufferLocal',
        'local_ae8': 'NetworkContextLocal',
        'local_af0': 'NetworkConnectionLocal',
        'local_af8': 'NetworkBufferLocal',
        'local_b00': 'NetworkStatusLocal',
        'local_b08': 'NetworkOperationLocal',
        'local_b10': 'NetworkTransferLocal',
        'local_b18': 'NetworkPacketLocal',
        'local_b20': 'NetworkSocketLocal',
        'local_b28': 'NetworkHandleLocal',
        'local_b30': 'NetworkProtocolLocal',
        'local_b38': 'NetworkAddressLocal',
        'local_b40': 'NetworkPortLocal',
        'local_b48': 'NetworkFlagLocal',
        'local_b50': 'NetworkErrorLocal',
        'local_b58': 'NetworkTimeoutLocal',
        'local_b60': 'NetworkRetryLocal',
        'local_b68': 'NetworkBufferLocal',
        'local_b70': 'NetworkContextLocal',
        'local_b78': 'NetworkConnectionLocal',
        'local_b80': 'NetworkBufferLocal',
        'local_b88': 'NetworkStatusLocal',
        'local_b90': 'NetworkOperationLocal',
        'local_b98': 'NetworkTransferLocal',
        'local_ba0': 'NetworkPacketLocal',
        'local_ba8': 'NetworkSocketLocal',
        'local_bb0': 'NetworkHandleLocal',
        'local_bb8': 'NetworkProtocolLocal',
        'local_bc0': 'NetworkAddressLocal',
        'local_bc8': 'NetworkPortLocal',
        'local_bd0': 'NetworkFlagLocal',
        'local_bd8': 'NetworkErrorLocal',
        'local_be0': 'NetworkTimeoutLocal',
        'local_be8': 'NetworkRetryLocal',
        'local_bf0': 'NetworkBufferLocal',
        'local_bf8': 'NetworkContextLocal',
        'local_c00': 'NetworkConnectionLocal',
        'local_c08': 'NetworkBufferLocal',
        'local_c10': 'NetworkStatusLocal',
        'local_c18': 'NetworkOperationLocal',
        'local_c20': 'NetworkTransferLocal',
        'local_c28': 'NetworkPacketLocal',
        'local_c30': 'NetworkSocketLocal',
        'local_c38': 'NetworkHandleLocal',
        'local_c40': 'NetworkProtocolLocal',
        'local_c48': 'NetworkAddressLocal',
        'local_c50': 'NetworkPortLocal',
        'local_c58': 'NetworkFlagLocal',
        'local_c60': 'NetworkErrorLocal',
        'local_c68': 'NetworkTimeoutLocal',
        'local_c70': 'NetworkRetryLocal',
        'local_c78': 'NetworkBufferLocal',
        'local_c80': 'NetworkContextLocal',
        'local_c88': 'NetworkConnectionLocal',
        'local_c90': 'NetworkBufferLocal',
        'local_c98': 'NetworkStatusLocal',
        'local_ca0': 'NetworkOperationLocal',
        'local_ca8': 'NetworkTransferLocal',
        'local_cb0': 'NetworkPacketLocal',
        'local_cb8': 'NetworkSocketLocal',
        'local_cc0': 'NetworkHandleLocal',
        'local_cc8': 'NetworkProtocolLocal',
        'local_cd0': 'NetworkAddressLocal',
        'local_cd8': 'NetworkPortLocal',
        'local_ce0': 'NetworkFlagLocal',
        'local_ce8': 'NetworkErrorLocal',
        'local_cf0': 'NetworkTimeoutLocal',
        'local_cf8': 'NetworkRetryLocal',
        'local_d00': 'NetworkBufferLocal',
        'local_d08': 'NetworkContextLocal',
        'local_d10': 'NetworkConnectionLocal',
        'local_d18': 'NetworkBufferLocal',
        'local_d20': 'NetworkStatusLocal',
        'local_d28': 'NetworkOperationLocal',
        'local_d30': 'NetworkTransferLocal',
        'local_d38': 'NetworkPacketLocal',
        'local_d40': 'NetworkSocketLocal',
        'local_d48': 'NetworkHandleLocal',
        'local_d50': 'NetworkProtocolLocal',
        'local_d58': 'NetworkAddressLocal',
        'local_d60': 'NetworkPortLocal',
        'local_d68': 'NetworkFlagLocal',
        'local_d70': 'NetworkErrorLocal',
        'local_d78': 'NetworkTimeoutLocal',
        'local_d80': 'NetworkRetryLocal',
        'local_d88': 'NetworkBufferLocal',
        'local_d90': 'NetworkContextLocal',
        'local_d98': 'NetworkConnectionLocal',
        'local_da0': 'NetworkBufferLocal',
        'local_da8': 'NetworkStatusLocal',
        'local_db0': 'NetworkOperationLocal',
        'local_db8': 'NetworkTransferLocal',
        'local_dc0': 'NetworkPacketLocal',
        'local_dc8': 'NetworkSocketLocal',
        'local_dd0': 'NetworkHandleLocal',
        'local_dd8': 'NetworkProtocolLocal',
        'local_de0': 'NetworkAddressLocal',
        'local_de8': 'NetworkPortLocal',
        'local_df0': 'NetworkFlagLocal',
        'local_df8': 'NetworkErrorLocal',
        'local_e00': 'NetworkTimeoutLocal',
        'local_e08': 'NetworkRetryLocal',
        'local_e10': 'NetworkBufferLocal',
        'local_e18': 'NetworkContextLocal',
        'local_e20': 'NetworkConnectionLocal',
        'local_e28': 'NetworkBufferLocal',
        'local_e30': 'NetworkStatusLocal',
        'local_e38': 'NetworkOperationLocal',
        'local_e40': 'NetworkTransferLocal',
        'local_e48': 'NetworkPacketLocal',
        'local_e50': 'NetworkSocketLocal',
        'local_e58': 'NetworkHandleLocal',
        'local_e60': 'NetworkProtocolLocal',
        'local_e68': 'NetworkAddressLocal',
        'local_e70': 'NetworkPortLocal',
        'local_e78': 'NetworkFlagLocal',
        'local_e80': 'NetworkErrorLocal',
        'local_e88': 'NetworkTimeoutLocal',
        'local_e90': 'NetworkRetryLocal',
        'local_e98': 'NetworkBufferLocal',
        'local_ea0': 'NetworkContextLocal',
        'local_ea8': 'NetworkConnectionLocal',
        'local_eb0': 'NetworkBufferLocal',
        'local_eb8': 'NetworkStatusLocal',
        'local_ec0': 'NetworkOperationLocal',
        'local_ec8': 'NetworkTransferLocal',
        'local_ed0': 'NetworkPacketLocal',
        'local_ed8': 'NetworkSocketLocal',
        'local_ee0': 'NetworkHandleLocal',
        'local_ee8': 'NetworkProtocolLocal',
        'local_ef0': 'NetworkAddressLocal',
        'local_ef8': 'NetworkPortLocal',
        'local_f00': 'NetworkFlagLocal',
        'local_f08': 'NetworkErrorLocal',
        'local_f10': 'NetworkTimeoutLocal',
        'local_f18': 'NetworkRetryLocal',
        'local_f20': 'NetworkBufferLocal',
        'local_f28': 'NetworkContextLocal',
        'local_f30': 'NetworkConnectionLocal',
        'local_f38': 'NetworkBufferLocal',
        'local_f40': 'NetworkStatusLocal',
        'local_f48': 'NetworkOperationLocal',
        'local_f50': 'NetworkTransferLocal',
        'local_f58': 'NetworkPacketLocal',
        'local_f60': 'NetworkSocketLocal',
        'local_f68': 'NetworkHandleLocal',
        'local_f70': 'NetworkProtocolLocal',
        'local_f78': 'NetworkAddressLocal',
        'local_f80': 'NetworkPortLocal',
        'local_f88': 'NetworkFlagLocal',
        'local_f90': 'NetworkErrorLocal',
        'local_f98': 'NetworkTimeoutLocal',
        'local_fa0': 'NetworkRetryLocal',
        'local_fa8': 'NetworkBufferLocal',
        'local_fb0': 'NetworkContextLocal',
        'local_fb8': 'NetworkConnectionLocal',
        'local_fc0': 'NetworkBufferLocal',
        'local_fc8': 'NetworkStatusLocal',
        'local_fd0': 'NetworkOperationLocal',
        'local_fd8': 'NetworkTransferLocal',
        'local_fe0': 'NetworkPacketLocal',
        'local_fe8': 'NetworkSocketLocal',
        'local_ff0': 'NetworkHandleLocal',
        'local_ff8': 'NetworkProtocolLocal'
    }
    
    # 替换变量名称
    for old_name, new_name in variable_mappings.items():
        content = re.sub(
            rf'\b{old_name}\b',
            new_name,
            content
        )
    
    return content

def main():
    """主函数"""
    if len(sys.argv) != 2:
        print("用法: python beautify_networking.py <文件路径>")
        sys.exit(1)
    
    file_path = sys.argv[1]
    
    # 读取文件内容
    content = read_file(file_path)
    
    # 美化函数名称
    content = beautify_functions(content)
    
    # 美化变量名称
    content = beautify_variables(content)
    
    # 写入文件内容
    write_file(file_path, content)
    
    print(f"文件 {file_path} 美化完成")

if __name__ == "__main__":
    main()