#!/bin/bash

# 批量替换06_utilities.c中的变量名

# 首先备份原文件
cp TaleWorlds.Native/src/06_utilities.c TaleWorlds.Native/src/06_utilities.c.backup

# 批量替换变量名
sed -i 's/localContextPointer\([0-9]*\)/LocalContext\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/plocalContextPointer\([0-9]*\)/LocalContextPtr\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/bytePointer\([0-9]*\)/BytePtr\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourcePointer\([0-9]*\)/ResourcePtr\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validationContextParam/ValidationContextParam/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/objectContextParam/ObjectContextParam/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/byteValue\([0-9]*\)/ByteValue\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/unsignedResult\([0-9]*\)/UnsignedResult\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/processedResult\([0-9]*\)/ProcessedResult\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/integerValue\([0-9]*\)/IntegerValue\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/floatValue\([0-9]*\)/FloatValue\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/parameterRegister/ParameterRegister/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/eaxRegister/EaxRegister/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/rangeMinValue/RangeMinValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/inputValue/InputValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationResult/OperationResult/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validationResult/ValidationResult/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/systemOperationResult/SystemOperationResult/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceValidationResult/ResourceValidationResult/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceIndex/ResourceIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/minValue/MinValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/maxValue/MaxValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/currentValue/CurrentValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/dataLength/DataLength/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/hashValue/HashValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/newSize/NewSize/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/cleanupFlags/CleanupFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationFlags/OperationFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/entryIndex/EntryIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/reservedParam/ReservedParam/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/poolDataPointer/PoolDataPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/arrayPointer/ArrayPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/bufferContext/BufferContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/additionalData/AdditionalData/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/options/Options/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/systemContext/SystemContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/searchKey/SearchKey/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/extendedResourcePool/ExtendedResourcePool/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourcePool/ResourcePool/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceDataPointer/ResourceDataPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceHashPointer/ResourceHashPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/hashTablePointer/HashTablePtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/callbackIndex/CallbackIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/contextContext/ContextContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceArray/ResourceArray/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/contextFlags/ContextFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationIndex/OperationIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/extendedContext/ExtendedContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validationFlags/ValidationFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationType/OperationType/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/dataContext/DataContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/statusPointer/StatusPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/moduleContext/ModuleContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/moduleHandle/ModuleHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/parameterPointer/ParameterPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceContext/ResourceContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/objectHandle/ObjectHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/extendedObjectHandle/ExtendedObjectHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/advancedObjectHandle/AdvancedObjectHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/objectPointer/ObjectPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configData/ConfigData/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/parameterObject/ParameterObject/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/managerHandle/ManagerHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/messageQueueHandle/MessageQueueHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configurationData/ConfigurationData/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resourceHandle/ResourceHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationFlag/OperationFlag/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configParameter/ConfigParameter/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/packetHandle/PacketHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/transmissionConfig/TransmissionConfig/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/lifecycleConfig/LifecycleConfig/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/dataBuffer/DataBuffer/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validationConfig/ValidationConfig/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/queueContext/QueueContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configHandle/ConfigHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/schedulerContext/SchedulerContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/processContext/ProcessContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/bufferContext/BufferContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configIndex/ConfigIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configSize/ConfigSize/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/matrixDataPointer/MatrixDataPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/contextPointer/ContextPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/matrixTypeValue/MatrixTypeValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/matrixFlagsValue\([0-9]*\)/MatrixFlagsValue\1/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validationStackBuffer/ValidationStackBuffer/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/securityContextBuffer/SecurityContextBuffer/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/unaff_RDI/UnaffRdi/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationHandle/OperationHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configObject/ConfigObject/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/securityFlags/SecurityFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operationMode/OperationMode/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/integerValue/IntegerValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/floatValue/FloatValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/parameter3/Parameter3/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/parameter4/Parameter4/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/data_context/DataContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operation_context/OperationContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validation_context/ValidationContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/system_context/SystemContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/min_value/MinValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/max_value/MaxValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/current_value/CurrentValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_handle/ResourceHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_data/ResourceData/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_index/ResourceIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configuration_data/ConfigurationData/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validation_flags/ValidationFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/result_buffer/ResultBuffer/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/object_handle/ObjectHandle/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_pool/ResourcePool/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_array/ResourceArray/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/context_context/ContextContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/callback_index/CallbackIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/hash_table_pointer/HashTablePtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_hash_pointer/ResourceHashPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_data_pointer/ResourceDataPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resource_pool/ResourcePool/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/search_key/SearchKey/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/extended_resource_pool/ExtendedResourcePool/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operation_flags/OperationFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/entry_index/EntryIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/reserved_param/ReservedParam/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/pool_data_pointer/PoolDataPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/array_pointer/ArrayPtr/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/new_size/NewSize/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/data_context/DataContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operation_type/OperationType/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validation_flags/ValidationFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/extended_context/ExtendedContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/context_flags/ContextFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/operation_index/OperationIndex/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/hash_value/HashValue/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/systemContext/SystemContext/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/configurationData/ConfigurationData/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/validationFlags/ValidationFlags/g' TaleWorlds.Native/src/06_utilities.c
sed -i 's/resultBuffer/ResultBuffer/g' TaleWorlds.Native/src/06_utilities.c

echo "变量名替换完成"