#!/bin/bash

# UI系统变量美化脚本
# 用于重命名04_ui_system.c中的未知变量为语义化名称

# 创建备份
cp /dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c /dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c.vars_backup

# 变量映射 - 参数变量
declare -A param_mappings=(
    ["参数一"]="uiContext"
    ["参数二"]="resourceHandle"
    ["参数三"]="widgetId"
    ["参数四"]="renderFlags"
    ["参数五"]="bufferSize"
    ["参数六"]="textureFormat"
    ["参数七"]="animationType"
    ["参数八"]="eventFlags"
    ["参数九"]="layoutMode"
    ["参数一0"]="windowStyle"
    ["参数一一"]="widgetType"
    ["参数一二"]="blendMode"
    ["参数一三"]="shaderProgram"
    ["参数一4"]="vertexFormat"
    ["参数一5"]="depthTest"
    ["参数一6"]="stencilTest"
    ["参数一7"]="scissorTest"
    ["参数一8"]="alphaBlend"
    ["参数一9"]="cullMode"
    ["参数二0"]="fillMode"
    ["参数二一"]="samplerState"
    ["参数二二"]="filterMode"
    ["参数二三"]="wrapMode"
    ["参数二4"]="compareFunc"
    ["参数二5"]="stencilOp"
    ["参数二6"]="blendOp"
    ["参数二7"]="blendFunc"
    ["参数二8"]="colorMask"
    ["参数二9"]="depthMask"
    ["参数三0"]="stencilMask"
    ["参数三一"]="renderTarget"
    ["参数三二"]="frameBuffer"
    ["参数三三"]="vertexBuffer"
    ["参数三四"]="indexBuffer"
    ["参数三五"]="uniformBuffer"
    ["参数三六"]="shaderStorage"
    ["参数三七"]="atomicCounter"
    ["参数三八"]="transformFeedback"
    ["参数三9"]="queryObject"
    ["参数四0"]="syncObject"
    ["参数四一"]="fenceObject"
    ["参数四二"]="eventObject"
    ["参数四三"]="semaphoreObject"
    ["参数四四"]="memoryBarrier"
    ["参数四五"]="textureBarrier"
    ["参数四六"]="bufferBarrier"
    ["参数四七"]="imageBarrier"
    ["参数四八"]="globalBarrier"
    ["参数四九"]="commandBuffer"
    ["参数五0"]="drawCommand"
    ["参数五一"]="dispatchCommand"
    ["参数五二"]="copyCommand"
    ["参数五三"]="blitCommand"
    ["参数五四"]="resolveCommand"
    ["参数五五"]="clearCommand"
    ["参数五六"]="fillCommand"
    ["参数五七"]="updateCommand"
    ["参数五八"]="pipelineBarrier"
    ["参数五九"]="memoryBarrier"
    ["参数六0"]="executionBarrier"
    ["参数六一"]="memoryDependency"
    ["参数六二"]="subpassDependency"
    ["参数六三"]="renderPass"
    ["参数六四"]="framebuffer"
    ["参数六五"]="renderArea"
    ["参数六六"]="clearValue"
    ["参数六七"]="loadOp"
    ["参数六八"]="storeOp"
    ["参数六九"]="initialLayout"
    ["参数七0"]="finalLayout"
    ["参数七一"]="imageLayout"
    ["参数七二"]="accessMask"
    ["参数七三"]="stageMask"
    ["参数七四"]="pipelineStage"
    ["参数七五"]="commandPool"
    ["参数七六"]="descriptorPool"
    ["参数七七"]="descriptorSet"
    ["参数七八"]="descriptorLayout"
    ["参数七九"]="pipelineLayout"
    ["参数八0"]="renderPass"
    ["参数八一"]="graphicsPipeline"
    ["参数八二"]="computePipeline"
    ["参数八三"]="rayTracingPipeline"
    ["参数八四"]="sampler"
    ["参数八五"]="image"
    ["参数八六"]="imageView"
    ["参数八七"]="bufferView"
    ["参数八八"]="accelerationStructure"
    ["参数八九"]="buffer"
    ["参数九0"]="deviceMemory"
    ["参数九一"]="commandBuffer"
    ["参数九二"]="fence"
    ["参数九三"]="semaphore"
    ["参数九四"]="event"
    ["参数九五"]="queryPool"
    ["参数九六"]="shaderModule"
    ["参数九七"]="pipelineCache"
    ["参数九八"]="pipeline"
    ["参数九九"]="descriptorSetLayout"
)

# 变量映射 - 未知变量
declare -A unknown_mappings=(
    ["无符号整型变量1"]="resourceIndex"
    ["无符号整型变量2"]="textureHandle"
    ["无符号整型变量3"]="bufferHandle"
    ["无符号整型变量4"]="shaderHandle"
    ["无符号整型变量5"]="programHandle"
    ["无符号整型变量6"]="vertexHandle"
    ["无符号整型变量7"]="indexHandle"
    ["无符号整型变量8"]="uniformHandle"
    ["无符号整型变量9"]="samplerHandle"
    ["无符号整型变量10"]="framebufferHandle"
    ["无符号整型变量11"]="renderbufferHandle"
    ["无符号整型变量12"]="textureHandle"
    ["无符号整型变量13"]="bufferHandle"
    ["无符号整型变量14"]="shaderHandle"
    ["无符号整型变量15"]="programHandle"
    ["无符号整型变量16"]="vertexHandle"
    ["无符号整型变量17"]="indexHandle"
    ["无符号整型变量18"]="uniformHandle"
    ["无符号整型变量19"]="samplerHandle"
    ["无符号整型变量20"]="framebufferHandle"
    ["无符号整型变量21"]="renderbufferHandle"
    ["无符号整型变量22"]="textureHandle"
    ["无符号整型变量23"]="bufferHandle"
    ["无符号整型变量24"]="shaderHandle"
    ["无符号整型变量25"]="programHandle"
    ["无符号整型变量26"]="vertexHandle"
    ["无符号整型变量27"]="indexHandle"
    ["无符号整型变量28"]="uniformHandle"
    ["无符号整型变量29"]="samplerHandle"
    ["无符号整型变量30"]="framebufferHandle"
    ["无符号整型变量31"]="renderbufferHandle"
    ["无符号整型变量32"]="textureHandle"
    ["无符号整型变量33"]="bufferHandle"
    ["无符号整型变量34"]="shaderHandle"
    ["无符号整型变量35"]="programHandle"
    ["无符号整型变量36"]="vertexHandle"
    ["无符号整型变量37"]="indexHandle"
    ["无符号整型变量38"]="uniformHandle"
    ["无符号整型变量39"]="samplerHandle"
    ["无符号整型变量40"]="framebufferHandle"
    ["无符号整型变量41"]="renderbufferHandle"
    ["无符号整型变量42"]="textureHandle"
    ["无符号整型变量43"]="bufferHandle"
    ["无符号整型变量44"]="shaderHandle"
    ["无符号整型变量45"]="programHandle"
    ["无符号整型变量46"]="vertexHandle"
    ["无符号整型变量47"]="indexHandle"
    ["无符号整型变量48"]="uniformHandle"
    ["无符号整型变量49"]="samplerHandle"
    ["无符号整型变量50"]="framebufferHandle"
)

# 局部变量映射
declare -A local_mappings=(
    ["lVar1"]="localResource"
    ["lVar2"]="localTexture"
    ["lVar3"]="localBuffer"
    ["lVar4"]="localShader"
    ["lVar5"]="localProgram"
    ["lVar6"]="localVertex"
    ["lVar7"]="localIndex"
    ["lVar8"]="localUniform"
    ["lVar9"]="localSampler"
    ["lVar10"]="localFramebuffer"
    ["iVar1"]="localIntResource"
    ["iVar2"]="localIntTexture"
    ["iVar3"]="localIntBuffer"
    ["iVar4"]="localIntShader"
    ["iVar5"]="localIntProgram"
    ["iVar6"]="localIntVertex"
    ["iVar7"]="localIntIndex"
    ["iVar8"]="localIntUniform"
    ["iVar9"]="localIntSampler"
    ["iVar10"]="localIntFramebuffer"
    ["pfVar1"]="localFloatResource"
    ["pfVar2"]="localFloatTexture"
    ["pfVar3"]="localFloatBuffer"
    ["pfVar4"]="localFloatShader"
    ["pfVar5"]="localFloatProgram"
    ["pfVar6"]="localFloatVertex"
    ["pfVar7"]="localFloatIndex"
    ["pfVar8"]="localFloatUniform"
    ["pfVar9"]="localFloatSampler"
    ["pfVar10"]="localFloatFramebuffer"
    ["puVar1"]="localPtrResource"
    ["puVar2"]="localPtrTexture"
    ["puVar3"]="localPtrBuffer"
    ["puVar4"]="localPtrShader"
    ["puVar5"]="localPtrProgram"
    ["puVar6"]="localPtrVertex"
    ["puVar7"]="localPtrIndex"
    ["puVar8"]="localPtrUniform"
    ["puVar9"]="localPtrSampler"
    ["puVar10"]="localPtrFramebuffer"
    ["pcVar1"]="localCharResource"
    ["pcVar2"]="localCharTexture"
    ["pcVar3"]="localCharBuffer"
    ["pcVar4"]="localCharShader"
    ["pcVar5"]="localCharProgram"
    ["pcVar6"]="localCharVertex"
    ["pcVar7"]="localCharIndex"
    ["pcVar8"]="localCharUniform"
    ["pcVar9"]="localCharSampler"
    ["pcVar10"]="localCharFramebuffer"
    ["bVar1"]="localByteResource"
    ["bVar2"]="localByteTexture"
    ["bVar3"]="localByteBuffer"
    ["bVar4"]="localByteShader"
    ["bVar5"]="localByteProgram"
    ["bVar6"]="localByteVertex"
    ["bVar7"]="localByteIndex"
    ["bVar8"]="localByteUniform"
    ["bVar9"]="localByteSampler"
    ["bVar10"]="localByteFramebuffer"
    ["uVar1"]="localUIntResource"
    ["uVar2"]="localUIntTexture"
    ["uVar3"]="localUIntBuffer"
    ["uVar4"]="localUIntShader"
    ["uVar5"]="localUIntProgram"
    ["uVar6"]="localUIntVertex"
    ["uVar7"]="localUIntIndex"
    ["uVar8"]="localUIntUniform"
    ["uVar9"]="localUIntSampler"
    ["uVar10"]="localUIntFramebuffer"
)

# 执行参数变量替换
for old_name in "${!param_mappings[@]}"; do
    new_name="${param_mappings[$old_name]}"
    sed -i "s/\b$old_name\b/$new_name/g" /dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c
    echo "已替换参数: $old_name -> $new_name"
done

# 执行未知变量替换
for old_name in "${!unknown_mappings[@]}"; do
    new_name="${unknown_mappings[$old_name]}"
    sed -i "s/\b$old_name\b/$new_name/g" /dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c
    echo "已替换未知变量: $old_name -> $new_name"
done

# 执行局部变量替换
for old_name in "${!local_mappings[@]}"; do
    new_name="${local_mappings[$old_name]}"
    sed -i "s/\b$old_name\b/$new_name/g" /dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c
    echo "已替换局部变量: $old_name -> $new_name"
done

echo "UI系统变量美化完成"