#!/bin/bash

# 网络系统变量名美化脚本
# 用于将 05_networking.c 文件中的变量名改为 PascalCase 命名规范

FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c"

# 备份原文件
cp "$FILE" "$FILE.bak"

echo "开始美化网络系统变量名..."

# 常见变量名替换
sed -i 's/\bnetworkConnectionPrimaryStatus\b/NetworkConnectionPrimaryStatus/g' "$FILE"
sed -i 's/\bnetworkPacketProcessingResult\b/NetworkPacketProcessingResult/g' "$FILE"
sed -i 's/\bnetworkConnectionStatus\b/NetworkConnectionStatus/g' "$FILE"
sed -i 's/\bnetworkContext\b/NetworkContext/g' "$FILE"
sed -i 's/\bnetworkContextArray\b/NetworkContextArray/g' "$FILE"
sed -i 's/\bnetworkContextIndex\b/NetworkContextIndex/g' "$FILE"
sed -i 's/\bnetworkConnectionData\b/NetworkConnectionData/g' "$FILE"
sed -i 's/\bnetworkFloatValue\b/NetworkFloatValue/g' "$FILE"
sed -i 's/\bnetworkSecurityKey\b/NetworkSecurityKey/g' "$FILE"
sed -i 's/\bnetworkConnectionTable\b/NetworkConnectionTable/g' "$FILE"
sed -i 's/\bnetworkConnectionHandle\b/NetworkConnectionHandle/g' "$FILE"
sed -i 's/\bnetworkConnectionStatusCode\b/NetworkConnectionStatusCode/g' "$FILE"
sed -i 's/\bnetworkConnectionProgress\b/NetworkConnectionProgress/g' "$FILE"
sed -i 's/\bnetworkErrorDetails\b/NetworkErrorDetails/g' "$FILE"
sed -i 's/\bnetworkContextBufferData\b/NetworkContextBufferData/g' "$FILE"
sed -i 's/\bnetworkSecurityValidationGuard\b/NetworkSecurityValidationGuard/g' "$FILE"
sed -i 's/\bnetworkConnectionValidationResult\b/NetworkConnectionValidationResult/g' "$FILE"
sed -i 's/\bnetworkConnectionDetailedStatus\b/NetworkConnectionDetailedStatus/g' "$FILE"
sed -i 's/\bnetworkPacketTableRecord\b/NetworkPacketTableRecord/g' "$FILE"
sed -i 's/\bnetworkPacketDataBuffer\b/NetworkPacketDataBuffer/g' "$FILE"
sed -i 's/\bnetworkTableIndex\b/NetworkTableIndex/g' "$FILE"
sed -i 's/\bnetworkInfoLogPointer\b/NetworkInfoLogPointer/g' "$FILE"
sed -i 's/\bnetworkStackDataBufferPrimary\b/NetworkStackDataBufferPrimary/g' "$FILE"
sed -i 's/\bnetworkDataProcessingResult\b/NetworkDataProcessingResult/g' "$FILE"
sed -i 's/\bnetworkPacketProcessingProgress\b/NetworkPacketProcessingProgress/g' "$FILE"
sed -i 's/\bnetworkSecurityContextData\b/NetworkSecurityContextData/g' "$FILE"
sed -i 's/\bnetworkInitializationStatusCode\b/NetworkInitializationStatusCode/g' "$FILE"
sed -i 's/\bnetworkSystemContext\b/NetworkSystemContext/g' "$FILE"
sed -i 's/\bnetworkConnectionCurrentStatus\b/NetworkConnectionCurrentStatus/g' "$FILE"
sed -i 's/\bnetworkPacketEntry\b/NetworkPacketEntry/g' "$FILE"
sed -i 's/\bnetworkPacketIndex\b/NetworkPacketIndex/g' "$FILE"
sed -i 's/\bnetworkPacketArray\b/NetworkPacketArray/g' "$FILE"
sed -i 's/\bnetworkOperationStatusParameter\b/NetworkOperationStatusParameter/g' "$FILE"
sed -i 's/\bnetworkConnectionFlags\b/NetworkConnectionFlags/g' "$FILE"
sed -i 's/\bnetworkErrorFlag\b/NetworkErrorFlag/g' "$FILE"
sed -i 's/\bnetworkPacketProcessingStep\b/NetworkPacketProcessingStep/g' "$FILE"
sed -i 's/\bnetworkParameterValidationResult\b/NetworkParameterValidationResult/g' "$FILE"
sed -i 's/\bnetworkStatusValidationResult\b/NetworkStatusValidationResult/g' "$FILE"
sed -i 's/\bnetworkConnectionDataPointer\b/NetworkConnectionDataPointer/g' "$FILE"
sed -i 's/\bnetworkContextEntry\b/NetworkContextEntry/g' "$FILE"
sed -i 's/\bnetworkParameterFlag\b/NetworkParameterFlag/g' "$FILE"
sed -i 's/\bnetworkStatusFlag\b/NetworkStatusFlag/g' "$FILE"
sed -i 's/\bnetworkStackDataHigh\b/NetworkStackDataHigh/g' "$FILE"
sed -i 's/\bnetworkValidationResult\b/NetworkValidationResult/g' "$FILE"
sed -i 's/\bnetworkFloatValue2\b/NetworkFloatValue2/g' "$FILE"
sed -i 's/\bnetworkConnectionHandleId\b/NetworkConnectionHandleId/g' "$FILE"
sed -i 's/\bnetworkSessionIdentifier\b/NetworkSessionIdentifier/g' "$FILE"
sed -i 's/\bnetworkActiveConnectionCount\b/NetworkActiveConnectionCount/g' "$FILE"
sed -i 's/\bnetworkProcessingStatusCode\b/NetworkProcessingStatusCode/g' "$FILE"
sed -i 's/\bnetworkValidationStatusCode\b/NetworkValidationStatusCode/g' "$FILE"
sed -i 's/\bnetworkActiveConnectionsCount\b/NetworkActiveConnectionsCount/g' "$FILE"
sed -i 's/\bnetworkPacketProcessingStatusCode\b/NetworkPacketProcessingStatusCode/g' "$FILE"

# 函数名替换
sed -i 's/\bconnectionStatusProcessor\b/ConnectionStatusProcessor/g' "$FILE"
sed -i 's/\bconnectionStatusSender\b/ConnectionStatusSender/g' "$FILE"
sed -i 's/\bconnectionStatusChecker\b/ConnectionStatusChecker/g' "$FILE"
sed -i 's/\bconnectionStatusValidator\b/ConnectionStatusValidator/g' "$FILE"
sed -i 's/\bconnectionStatusUpdater\b/ConnectionStatusUpdater/g' "$FILE"
sed -i 's/\bconnectionStatusValidator\b/ConnectionStatusValidator/g' "$FILE"
sed -i 's/\bnetworkConnectionStatusChecker\b/NetworkConnectionStatusChecker/g' "$FILE"
sed -i 's/\bnetworkConnectionStatusPlaceholder\b/NetworkConnectionStatusPlaceholder/g' "$FILE"
sed -i 's/\bnetworkConnectionStatusValidator\b/NetworkConnectionStatusValidator/g' "$FILE"

# LAB_标签替换
sed -i 's/\bLAB_NetworkProcessingCompleteSecondary\b/NetworkProcessingCompleteSecondary/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionDataProcessing\b/NetworkConnectionDataProcessing/g' "$FILE"
sed -i 's/\bLAB_NetworkSecurityValidation\b/NetworkSecurityValidation/g' "$FILE"
sed -i 's/\bLAB_ContextProcessingComplete\b/ContextProcessingComplete/g' "$FILE"
sed -i 's/\bLAB_NetworkOperationError\b/NetworkOperationError/g' "$FILE"
sed -i 's/\bLAB_NetworkOperationSuccess\b/NetworkOperationSuccess/g' "$FILE"
sed -i 's/\bLAB_NetworkContextValidationComplete\b/NetworkContextValidationComplete/g' "$FILE"
sed -i 's/\bLAB_NetworkContextValidationError\b/NetworkContextValidationError/g' "$FILE"
sed -i 's/\bLAB_ContextDataSearchStart\b/ContextDataSearchStart/g' "$FILE"
sed -i 's/\bLAB_ContextDataFound\b/ContextDataFound/g' "$FILE"
sed -i 's/\bLAB_NetworkContextMatchFound\b/NetworkContextMatchFound/g' "$FILE"
sed -i 's/\bLAB_ContextSearchRestart\b/ContextSearchRestart/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionProcessingComplete\b/NetworkConnectionProcessingComplete/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionSecurityValidationStart\b/NetworkConnectionSecurityValidationStart/g' "$FILE"
sed -i 's/\bLAB_NetworkParameterConfigurationProcessingStart\b/NetworkParameterConfigurationProcessingStart/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionTimestampUpdateLoop\b/NetworkConnectionTimestampUpdateLoop/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionTimestampComparisonStart\b/NetworkConnectionTimestampComparisonStart/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionHandleValidationFailure\b/NetworkConnectionHandleValidationFailure/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionHandleProcessingLoop\b/NetworkConnectionHandleProcessingLoop/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionOperationComplete\b/NetworkConnectionOperationComplete/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionContextValidation\b/NetworkConnectionContextValidation/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionContextProcessing\b/NetworkConnectionContextProcessing/g' "$FILE"
sed -i 's/\bLAB_networkConnectionStatusCheck\b/NetworkConnectionStatusCheck/g' "$FILE"
sed -i 's/\bLAB_NetworkSecurityValidationComplete\b/NetworkSecurityValidationComplete/g' "$FILE"
sed -i 's/\bLAB_NetworkSecurityValidationError\b/NetworkSecurityValidationError/g' "$FILE"
sed -i 's/\bLAB_NetworkSecurityValidationSuccess\b/NetworkSecurityValidationSuccess/g' "$FILE"
sed -i 's/\bLAB_NetworkSessionCleanupComplete\b/NetworkSessionCleanupComplete/g' "$FILE"
sed -i 's/\bLAB_NetworkSessionCleanupError\b/NetworkSessionCleanupError/g' "$FILE"
sed -i 's/\bLAB_NetworkSessionCleanupSuccess\b/NetworkSessionCleanupSuccess/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionDataValidation\b/NetworkConnectionDataValidation/g' "$FILE"
sed -i 's/\bLAB_NetworkStatusCheck\b/NetworkStatusCheck/g' "$FILE"
sed -i 's/\bLAB_NetworkConnectionStatusCheckExit\b/NetworkConnectionStatusCheckExit/g' "$FILE"

# 参数名替换
sed -i 's/\bconnectionContext\b/ConnectionContext/g' "$FILE"
sed -i 's/\bpacketData\b/PacketData/g' "$FILE"
sed -i 's/\bconnectionHandle\b/ConnectionHandle/g' "$FILE"
sed -i 's/\bconnectionHandleId\b/ConnectionHandleId/g' "$FILE"
sed -i 's/\bsessionIdentifier\b/SessionIdentifier/g' "$FILE"
sed -i 's/\bactiveConnectionCount\b/ActiveConnectionCount/g' "$FILE"
sed -i 's/\bparameterCount\b/ParameterCount/g' "$FILE"
sed -i 's/\bmaximumParameterLimit\b/MaximumParameterLimit/g' "$FILE"
sed -i 's/\bprocessingStatusCode\b/ProcessingStatusCode/g' "$FILE"
sed -i 's/\bvalidationStatusCode\b/ValidationStatusCode/g' "$FILE"
sed -i 's/\bactiveConnectionsCount\b/ActiveConnectionsCount/g' "$FILE"
sed -i 's/\bmaximumResourceLimit\b/MaximumResourceLimit/g' "$FILE"
sed -i 's/\bnetworkConnectionProgress\b/NetworkConnectionProgress/g' "$FILE"
sed -i 's/\bnetworkErrorDetails\b/NetworkErrorDetails/g' "$FILE"
sed -i 's/\bnetworkConnectionStatusCode\b/NetworkConnectionStatusCode/g' "$FILE"
sed -i 's/\bconnectionDetails\b/ConnectionDetails/g' "$FILE"
sed -i 's/\bconnectionParameters\b/ConnectionParameters/g' "$FILE"
sed -i 's/\bnetworkConnectionValidationResult\b/NetworkConnectionValidationResult/g' "$FILE"
sed -i 's/\bnetworkConnectionDetailedStatus\b/NetworkConnectionDetailedStatus/g' "$FILE"
sed -i 's/\bpacketProcessingStatusCode\b/PacketProcessingStatusCode/g' "$FILE"
sed -i 's/\bnetworkPacketTableRecord\b/NetworkPacketTableRecord/g' "$FILE"
sed -i 's/\bnetworkPacketDataBuffer\b/NetworkPacketDataBuffer/g' "$FILE"
sed -i 's/\bnetworkContext\b/NetworkContext/g' "$FILE"
sed -i 's/\bpacketDataReferenceTable\b/PacketDataReferenceTable/g' "$FILE"
sed -i 's/\bpacketDetailsInformation\b/PacketDetailsInformation/g' "$FILE"
sed -i 's/\bpacketSecurityGuard\b/PacketSecurityGuard/g' "$FILE"
sed -i 's/\bnetworkConnectionCurrentStatus\b/NetworkConnectionCurrentStatus/g' "$FILE"
sed -i 's/\bpacketEntry\b/PacketEntry/g' "$FILE"
sed -i 's/\bpacketIndex\b/PacketIndex/g' "$FILE"
sed -i 's/\bpacketArray\b/PacketArray/g' "$FILE"
sed -i 's/\bnetworkTableIndex\b/NetworkTableIndex/g' "$FILE"
sed -i 's/\bcontextParam\b/ContextParam/g' "$FILE"

echo "变量名美化完成！"
echo "修改后的文件已保存到: $FILE"
echo "原文件备份在: $FILE.bak"