#!/usr/bin/env python3
"""
清理网络系统代码中的未定义变量
"""

import re

# 读取文件
with open('/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c', 'r', encoding='utf-8') as f:
    content = f.read()

# 需要替换的未定义变量映射
undefined_vars = {
    'networkValidationResult': 'validationResult',
    'NetworkProcessingStatus': 'processingStatus',
    'NetworkPacketProcessingResult': 'packetProcessingResult',
    'NetworkQueueProcessingResult': 'queueProcessingResult',
    'NetworkPacketProcessingProgress': 'packetProcessingProgress',
    'NetworkPacketProcessingStepResult': 'packetStepResult',
    'NetworkOperationStatus': 'operationStatus',
    'NetworkConnectionNetworkContextBuffer': 'networkContextBuffer',
    'NetworkBuffer': 'networkBuffer',
    'NetworkBufferArray': 'networkBufferArray',
    'NetworkBufferTemplate': 'networkBufferTemplate',
    'PacketProcessingTemplate': 'packetProcessingTemplate',
    'ConnectionPhaseOneTemplate': 'connectionPhaseOneTemplate',
    'ConnectionPhaseTwoTemplate': 'connectionPhaseTwoTemplate',
    'ConnectionTemplate': 'connectionTemplate',
    'SecurityTemplate': 'securityTemplate',
    'NetworkProcessingBufferTemplate': 'networkProcessingBufferTemplate',
    'NetworkAdvancedProcessingBuffer': 'networkAdvancedProcessingBuffer',
    'PacketDataBuffer': 'packetDataBuffer',
    'NetworkConnectionTable': 'networkConnectionTable',
    'SecurityValidationData': 'securityValidationData',
    'NetworkSecurityValidationData': 'networkSecurityValidationData',
    'NetworkConnectionPrimaryStatus': 'connectionPrimaryStatus',
    'firstNetworkFlag': 'primaryNetworkFlag',
    'secondNetworkFlag': 'secondaryNetworkFlag',
    'thirdNetworkFlag': 'tertiaryNetworkFlag',
    'ValidationStatus': 'validationStatus',
    'connectionCompressionStatus': 'connectionCompressionStatus',
    'packetValidationStatus': 'packetValidationStatus',
    'networkProcessingResult': 'processingResult',
    'networkFlag': 'networkFlag',
    'primaryNetworkHandle': 'primaryNetworkHandle',
    'cumulativeProcessedSize': 'cumulativeProcessedSize',
    'processedBytes': 'processedBytes',
    'currentOffset': 'currentOffset',
    'networkOperationStatus': 'networkOperationStatus',
    'networkOperationProgress': 'networkOperationProgress',
    'networkPrimaryStatus': 'networkPrimaryStatus',
    'networkContext': 'networkContext',
    'connectionHandle': 'connectionHandle',
    'packetId': 'packetId',
    'packetInformation': 'packetInformation',
    'MaxTableEntries': 'maxTableEntries',
    'validationResult': 'validationResult',
    'networkContextIndex': 'networkContextIndex',
    'networkContextArray': 'networkContextArray',
    'networkContextEntry': 'networkContextEntry',
    'firstNetworkProcessingStatus': 'firstNetworkProcessingStatus',
    'secondNetworkProcessingStatus': 'secondNetworkProcessingStatus',
    'bufferNetworkProcessingStatus': 'bufferNetworkProcessingStatus',
    'initialNetworkProcessingStatus': 'initialNetworkProcessingStatus',
    'InitialNetworkProcessingStatus': 'initialNetworkProcessingStatus',
    'BufferNetworkProcessingStatus': 'bufferNetworkProcessingStatus',
    'encryptionNetworkProcessingStatus': 'encryptionNetworkProcessingStatus',
    'validationNetworkProcessingStatus': 'validationNetworkProcessingStatus',
    'compressionNetworkProcessingStatus': 'compressionNetworkProcessingStatus',
    'fourthNetworkProcessingStatus': 'fourthNetworkProcessingStatus',
    'thirdNetworkProcessingStatus': 'thirdNetworkProcessingStatus',
    'FirstNetworkProcessingStatus': 'firstNetworkProcessingStatus',
    'SecondNetworkProcessingStatus': 'secondNetworkProcessingStatus',
    'NetworkNetworkProcessingStatus': 'networkProcessingStatus',
    'primaryNetworkProcessingStatus': 'primaryNetworkProcessingStatus',
    'secondaryNetworkProcessingStatus': 'secondaryNetworkProcessingStatus',
    'networkPrimaryNetworkProcessingStatus': 'primaryNetworkProcessingStatus',
    'networkSecondaryNetworkProcessingStatus': 'secondaryNetworkProcessingStatus',
    'networkDataNetworkProcessingStatus': 'dataNetworkProcessingStatus',
    'networknetworkDataBuffer': 'networkDataBuffer',
    'PacketNetworkProcessingStatus': 'packetNetworkProcessingStatus',
    'packetNetworkProcessingStatus': 'packetNetworkProcessingStatus',
    'PacketDataBuffer': 'packetDataBuffer',
    'packetData': 'packetData',
    'dataSize': 'dataSize',
    'connectionContext': 'connectionContext',
    'networkConnectionContext': 'networkConnectionContext',
    'networkPacketData': 'networkPacketData',
    'processingBufferSize': 'processingBufferSize',
    'socketContext': 'socketContext',
    'networkConnectionHandle': 'networkConnectionHandle',
    'packetBuffer': 'packetBuffer',
    'requestBuffer': 'requestBuffer',
    'sourceBuffer': 'sourceBuffer',
    'transferSize': 'transferSize',
    'destinationBuffer': 'destinationBuffer',
    'transferFlags': 'transferFlags',
    'hasPriorityFlag': 'hasPriorityFlag',
    'stackBuffer': 'stackBuffer',
    'contextData': 'contextData',
    'connectionParameters': 'connectionParameters',
    'activeConnectionCount': 'activeConnectionCount',
    'networkConnectionParameterCount': 'networkConnectionParameterCount',
    'networkConnectionMaximumParameterValue': 'networkConnectionMaximumParameterValue',
    'networkTimeoutStatus': 'networkTimeoutStatus',
    'networkConnectionStatus': 'networkConnectionStatus',
    'networkContextCleanupCounter': 'networkContextCleanupCounter',
    'networkContextIndex': 'networkContextIndex',
    'networkProcessingOffset': 'networkProcessingOffset',
    'processingStatus': 'processingStatus',
    'NetworkConnectionPrimaryStatus': 'networkConnectionPrimaryStatus',
    'NetworkProcessingStatus': 'networkProcessingStatus',
    'NetworkPacketProcessingResult': 'networkPacketProcessingResult',
    'NetworkQueueProcessingResult': 'networkQueueProcessingResult',
    'networkConnectionTable': 'networkConnectionTable',
    'SecurityValidationData': 'securityValidationData',
    'NetworkSecurityValidationData': 'networkSecurityValidationData',
    'NetworkConnectionPrimaryStatus': 'networkConnectionPrimaryStatus',
    'firstNetworkFlag': 'firstNetworkFlag',
    'secondNetworkFlag': 'secondNetworkFlag',
    'thirdNetworkFlag': 'thirdNetworkFlag',
    'ValidationStatus': 'validationStatus',
    'connectionCompressionStatus': 'connectionCompressionStatus',
    'packetValidationStatus': 'packetValidationStatus',
    'networkProcessingResult': 'networkProcessingResult',
    'networkFlag': 'networkFlag',
    'primaryNetworkHandle': 'primaryNetworkHandle',
    'cumulativeProcessedSize': 'cumulativeProcessedSize',
    'processedBytes': 'processedBytes',
    'currentOffset': 'currentOffset',
    'networkOperationStatus': 'networkOperationStatus',
    'networkOperationProgress': 'networkOperationProgress',
    'networkPrimaryStatus': 'networkPrimaryStatus',
    'networkContext': 'networkContext',
    'connectionHandle': 'connectionHandle',
    'packetId': 'packetId',
    'packetInformation': 'packetInformation',
    'MaxTableEntries': 'maxTableEntries',
    'validationResult': 'validationResult',
    'networkContextIndex': 'networkContextIndex',
    'networkContextArray': 'networkContextArray',
    'networkContextEntry': 'networkContextEntry',
    'firstNetworkProcessingStatus': 'firstNetworkProcessingStatus',
    'secondNetworkProcessingStatus': 'secondNetworkProcessingStatus',
    'bufferNetworkProcessingStatus': 'bufferNetworkProcessingStatus',
    'initialNetworkProcessingStatus': 'initialNetworkProcessingStatus',
    'InitialNetworkProcessingStatus': 'initialNetworkProcessingStatus',
    'BufferNetworkProcessingStatus': 'bufferNetworkProcessingStatus',
    'encryptionNetworkProcessingStatus': 'encryptionNetworkProcessingStatus',
    'validationNetworkProcessingStatus': 'validationNetworkProcessingStatus',
    'compressionNetworkProcessingStatus': 'compressionNetworkProcessingStatus',
    'fourthNetworkProcessingStatus': 'fourthNetworkProcessingStatus',
    'thirdNetworkProcessingStatus': 'thirdNetworkProcessingStatus',
    'FirstNetworkProcessingStatus': 'firstNetworkProcessingStatus',
    'SecondNetworkProcessingStatus': 'secondNetworkProcessingStatus',
    'NetworkNetworkProcessingStatus': 'networkProcessingStatus',
    'primaryNetworkProcessingStatus': 'primaryNetworkProcessingStatus',
    'secondaryNetworkProcessingStatus': 'secondaryNetworkProcessingStatus',
    'networkPrimaryNetworkProcessingStatus': 'primaryNetworkProcessingStatus',
    'networkSecondaryNetworkProcessingStatus': 'secondaryNetworkProcessingStatus',
    'networkDataNetworkProcessingStatus': 'dataNetworkProcessingStatus',
    'networknetworkDataBuffer': 'networkDataBuffer',
    'PacketNetworkProcessingStatus': 'packetNetworkProcessingStatus',
    'packetNetworkProcessingStatus': 'packetNetworkProcessingStatus',
    'PacketDataBuffer': 'packetDataBuffer',
    'PacketProcessingBuffer': 'packetProcessingBuffer',
    'ConnectionFoundLabel': 'connectionFoundLabel',
    'dataProcessingOffset': 'dataProcessingOffset',
    'NetworkByte': 'networkByte',
    'NetworkHandle': 'networkHandle',
    'NetworkStatus': 'networkStatus',
    'ulong': 'unsigned long',
    'ConnectionFoundLabel': 'connectionFoundLabel',
}

# 执行替换
for old_var, new_var in undefined_vars.items():
    # 使用单词边界确保只替换完整的变量名
    pattern = r'\b' + re.escape(old_var) + r'\b'
    content = re.sub(pattern, new_var, content)

# 写回文件
with open('/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c', 'w', encoding='utf-8') as f:
    f.write(content)

print("未定义变量清理完成")