#!/bin/bash

# 网络配置验证参数重命名脚本
# 为NetworkConfigValidationParameter变量提供语义化名称

# 创建重命名映射文件
cat > /tmp/network_config_rename_map.txt << 'EOF'
NetworkConfigValidationParameter1=NetworkConfigAuthenticationType
NetworkConfigValidationParameter2=NetworkConfigEncryptionAlgorithm
NetworkConfigValidationParameter3=NetworkConfigCompressionMethod
NetworkConfigValidationParameter4=NetworkConfigConnectionTimeout
NetworkConfigValidationParameter5=NetworkConfigMaxRetries
NetworkConfigValidationParameter6=NetworkConfigBufferSize
NetworkConfigValidationParameter7=NetworkConfigPacketSize
NetworkConfigValidationParameter8=NetworkConfigPortRange
NetworkConfigValidationParameter9=NetworkConfigProtocolVersion
NetworkConfigValidationParameter10=NetworkConfigSecurityLevel
NetworkConfigValidationParameter11=NetworkConfigSessionTimeout
NetworkConfigValidationParameter12=NetworkConfigKeepAliveInterval
NetworkConfigValidationParameter13=NetworkConfigMaxConnections
NetworkConfigValidationParameter14=NetworkConfigBandwidthLimit
NetworkConfigValidationParameter15=NetworkConfigLatencyThreshold
NetworkConfigValidationParameter16=NetworkConfigPacketLossThreshold
NetworkConfigValidationParameter17=NetworkConfigQoSLevel
NetworkConfigValidationParameter18=NetworkConfigPriorityClass
NetworkConfigValidationParameter19=NetworkConfigTrafficShaping
NetworkConfigValidationParameter20=NetworkConfigLoadBalancing
NetworkConfigValidationParameter21=NetworkConfigRedundancyLevel
NetworkConfigValidationParameter22=NetworkConfigFailoverStrategy
NetworkConfigValidationParameter23=NetworkConfigHealthCheckInterval
NetworkConfigValidationParameter24=NetworkConfigMonitoringEnabled
NetworkConfigValidationParameter25=NetworkConfigLoggingLevel
NetworkConfigValidationParameter26=NetworkConfigDebugMode
NetworkConfigValidationParameter27=NetworkConfigPerformanceMetrics
NetworkConfigValidationParameter28=NetworkConfigStatisticsCollection
NetworkConfigValidationParameter29=NetworkConfigAlertThresholds
NetworkConfigValidationParameter30=NetworkConfigNotificationSettings
NetworkConfigValidationParameter31=NetworkConfigBackupInterval
NetworkConfigValidationParameter32=NetworkConfigRecoveryStrategy
NetworkConfigValidationParameter33=NetworkConfigMaintenanceWindow
NetworkConfigValidationParameter34=NetworkConfigUpdateSchedule
NetworkConfigValidationParameter35=NetworkConfigVersionControl
NetworkConfigValidationParameter36=NetworkConfigCompatibilityMode
NetworkConfigValidationParameter37=NetworkConfigLegacySupport
NetworkConfigValidationParameter38=NetworkConfigFutureProofing
NetworkConfigValidationParameter39=NetworkConfigCustomizationOptions
NetworkConfigValidationParameter40=NetworkConfigUserProfile
NetworkConfigValidationParameter41=NetworkConfigRegionalSettings
NetworkConfigValidationParameter42=NetworkConfigLocalization
NetworkConfigValidationParameter43=NetworkConfigTimezoneSupport
NetworkConfigValidationParameter44=NetworkConfigDateFormatting
NetworkConfigValidationParameter45=NetworkConfigLanguagePreferences
NetworkConfigValidationParameter46=NetworkConfigAccessibilityOptions
NetworkConfigValidationParameter47=NetworkConfigUserInterface
NetworkConfigValidationParameter48=NetworkConfigThemeSelection
NetworkConfigValidationParameter49=NetworkConfigDisplaySettings
NetworkConfigValidationParameter50=NetworkConfigInputDevices
NetworkConfigValidationParameter51=NetworkConfigAudioSettings
NetworkConfigValidationParameter52=NetworkConfigVideoSettings
NetworkConfigValidationParameter53=NetworkConfigGraphicsOptions
NetworkConfigValidationParameter54=NetworkConfigRenderingQuality
NetworkConfigValidationParameter55=NetworkConfigFrameRate
NetworkConfigValidationParameter56=NetworkConfigResolutionSettings
NetworkConfigValidationParameter57=NetworkConfigAspectRatio
NetworkConfigValidationParameter58=NetworkConfigColorDepth
NetworkConfigValidationParameter59=NetworkConfigRefreshRate
NetworkConfigValidationParameter60=NetworkConfigMultiMonitorSupport
NetworkConfigValidationParameter61=NetworkConfigVRSettings
NetworkConfigValidationParameter62=NetworkConfigAROptions
NetworkConfigValidationParameter63=NetworkConfigMotionControls
NetworkConfigValidationParameter64=NetworkConfigHapticFeedback
NetworkConfigValidationParameter65=NetworkConfigCameraSettings
NetworkConfigValidationParameter66=NetworkConfigMicrophoneConfig
NetworkConfigValidationParameter67=NetworkConfigSpeakerSetup
NetworkConfigValidationParameter68=NetworkConfigAudioEffects
NetworkConfigValidationParameter69=NetworkConfigVolumeControl
NetworkConfigValidationParameter70=NetworkConfigSoundProfile
NetworkConfigValidationParameter71=NetworkConfigNoiseCancellation
NetworkConfigValidationParameter72=NetworkConfigEchoReduction
NetworkConfigValidationParameter73=NetworkConfigVoiceChat
NetworkConfigValidationParameter74=NetworkConfigVideoChat
NetworkConfigValidationParameter75=NetworkConfigScreenSharing
NetworkConfigValidationParameter76=NetworkConfigFileTransfer
NetworkConfigValidationParameter77=NetworkConfigRemoteDesktop
NetworkConfigValidationParameter78=NetworkConfigCloudSync
NetworkConfigValidationParameter79=NetworkConfigBackupService
NetworkConfigValidationParameter80=NetworkConfigRecoveryService
NetworkConfigValidationParameter81=NetworkConfigUpdateService
NetworkConfigValidationParameter82=NetworkConfigPatchManagement
NetworkConfigValidationParameter83=NetworkConfigSecurityPatches
NetworkConfigValidationParameter84=NetworkConfigVirusScanning
NetworkConfigValidationParameter85=NetworkConfigFirewallRules
NetworkConfigValidationParameter86=NetworkConfigIntrusionDetection
NetworkConfigValidationParameter87=NetworkConfigDataEncryption
NetworkConfigValidationParameter88=NetworkConfigAccessControl
NetworkConfigValidationParameter89=NetworkConfigAuthenticationMethod
NetworkConfigValidationParameter90=NetworkConfigAuthorizationPolicy
NetworkConfigValidationParameter91=NetworkConfigAuditTrail
NetworkConfigValidationParameter92=NetworkConfigComplianceCheck
NetworkConfigValidationParameter93=NetworkConfigRegulatoryCompliance
NetworkConfigValidationParameter94=NetworkConfigDataPrivacy
NetworkConfigValidationParameter95=NetworkConfigUserConsent
NetworkConfigValidationParameter96=NetworkConfigDataRetention
NetworkConfigValidationParameter97=NetworkConfigDataPurge
NetworkConfigValidationParameter98=NetworkConfigArchivePolicy
NetworkConfigValidationParameter99=NetworkConfigDocumentManagement
NetworkConfigValidationParameter100=NetworkConfigKnowledgeBase
EOF

# 执行重命名操作
cd /dev/shm/mountblade-code/TaleWorlds.Native/src

while IFS='=' read -r old_name new_name; do
    if [[ -n "$old_name" && -n "$new_name" ]]; then
        echo "重命名: $old_name -> $new_name"
        sed -i "s/$old_name/$new_name/g" 00_data_definitions.h
    fi
done < /tmp/network_config_rename_map.txt

echo "网络配置验证参数重命名完成"