using System;
using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Issues
{
	// Token: 0x020002FB RID: 763
	public class HeroRelatedIssueCoolDownData : IssueCoolDownData
	{
		// Token: 0x06002CC2 RID: 11458 RVA: 0x000BBE06 File Offset: 0x000BA006
		internal static void AutoGeneratedStaticCollectObjectsHeroRelatedIssueCoolDownData(object o, List<object> collectedObjects)
		{
			((HeroRelatedIssueCoolDownData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x06002CC3 RID: 11459 RVA: 0x000BBE14 File Offset: 0x000BA014
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
			collectedObjects.Add(this.RelatedHero);
		}

		// Token: 0x06002CC4 RID: 11460 RVA: 0x000BBE29 File Offset: 0x000BA029
		internal static object AutoGeneratedGetMemberValueRelatedHero(object o)
		{
			return ((HeroRelatedIssueCoolDownData)o).RelatedHero;
		}

		// Token: 0x06002CC5 RID: 11461 RVA: 0x000BBE36 File Offset: 0x000BA036
		public HeroRelatedIssueCoolDownData(Hero hero, CampaignTime expireTime) : base(expireTime)
		{
			this.RelatedHero = hero;
		}

		// Token: 0x06002CC6 RID: 11462 RVA: 0x000BBE48 File Offset: 0x000BA048
		public override bool IsRelatedTo(object obj)
		{
			Hero hero;
			return (hero = (obj as Hero)) != null && this.RelatedHero == hero;
		}

		// Token: 0x06002CC7 RID: 11463 RVA: 0x000BBE6A File Offset: 0x000BA06A
		public override bool IsValid()
		{
			return base.IsValid() && this.RelatedHero != null;
		}

		// Token: 0x04000D6D RID: 3437
		[SaveableField(1)]
		public readonly Hero RelatedHero;
	}
}
