// Decompiled with JetBrains decompiler
// Type: TaleWorlds.CampaignSystem.Issues.GangLeaderNeedsToOffloadStolenGoodsIssueBehavior
// Assembly: TaleWorlds.CampaignSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E85F8C15-4DF6-4E9C-A58A-29177E40D07A
// Assembly location: D:\steam\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll

using Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Conversation;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.CampaignSystem.GameMenus;
using TaleWorlds.CampaignSystem.GameState;
using TaleWorlds.CampaignSystem.MapEvents;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

#nullable disable
namespace TaleWorlds.CampaignSystem.Issues
{
  public class GangLeaderNeedsToOffloadStolenGoodsIssueBehavior : CampaignBehaviorBase
  {
    private const int IssueDuration = 15;
    private const int MaxHideoutDistance = 60;
    private const IssueBase.IssueFrequency GangLeaderNeedsToOffloadStolenGoodsIssueFrequency = IssueBase.IssueFrequency.Common;

    public override void RegisterEvents()
    {
      CampaignEvents.OnCheckForIssueEvent.AddNonSerializedListener((object) this, new Action<Hero>(this.OnCheckForIssue));
    }

    public override void SyncData(IDataStore dataStore)
    {
    }

    private bool ConditionsHold(Hero issueGiver, out Settlement selectedHideout)
    {
      selectedHideout = (Settlement) null;
      int num = !issueGiver.IsGangLeader || (double) issueGiver.CurrentSettlement.Town.Security >= 70.0 ? 0 : (issueGiver.CurrentSettlement.Notables.Any<Hero>((Func<Hero, bool>) (x => x.CharacterObject.IsHero && x.CharacterObject.HeroObject != issueGiver && x.CharacterObject.HeroObject.IsMerchant)) ? 1 : 0);
      selectedHideout = issueGiver.CurrentSettlement == null || !issueGiver.CurrentSettlement.IsTown ? (Settlement) null : GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.FindSuitableHideout(issueGiver.CurrentSettlement);
      return num != 0 && selectedHideout != null;
    }

    public void OnCheckForIssue(Hero hero)
    {
      Settlement selectedHideout;
      Campaign.Current.IssueManager.AddPotentialIssueData(hero, this.ConditionsHold(hero, out selectedHideout) ? new PotentialIssueData(new PotentialIssueData.StartIssueDelegate(this.OnSelected), typeof (GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue), IssueBase.IssueFrequency.Common, (object) selectedHideout) : new PotentialIssueData(typeof (GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue), IssueBase.IssueFrequency.Common));
    }

    private static Settlement FindSuitableHideout(Settlement settlement)
    {
      Settlement suitableHideout = (Settlement) null;
      float num1 = float.MaxValue;
      foreach (Hideout hideout in Campaign.Current.AllHideouts.Where<Hideout>((Func<Hideout, bool>) (t => t.IsInfested)))
      {
        if (!Campaign.Current.BusyHideouts.Contains(hideout.Settlement))
        {
          float num2 = hideout.Settlement.GatePosition.DistanceSquared(settlement.Position2D);
          if ((double) num2 <= 3600.0 && (double) num2 < (double) num1)
          {
            num1 = num2;
            suitableHideout = hideout.Settlement;
          }
        }
      }
      return suitableHideout;
    }

    private IssueBase OnSelected(in PotentialIssueData pid, Hero issueOwner)
    {
      return (IssueBase) new GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue(issueOwner, pid.RelatedObject as Settlement);
    }

    public class GangLeaderNeedsToOffloadStolenGoodsIssue : IssueBase
    {
      private const int QuestDurationInDays = 20;
      private static readonly string[] PossibleStolenItems = new string[4]
      {
        "jewelry",
        "fur",
        "silver",
        "velvet"
      };
      [SaveableField(20)]
      private readonly int _randomForStolenTradeGood;
      [SaveableField(30)]
      private readonly Settlement _issueHideout;
      private const int AlternativeSolutionMinimumTroopLevel = 2;
      private const int CompanionRequiredSkillLevel = 120;

      internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsToOffloadStolenGoodsIssue(
        object o,
        List<object> collectedObjects)
      {
        ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
      }

      protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
      {
        base.AutoGeneratedInstanceCollectObjects(collectedObjects);
        collectedObjects.Add((object) this._issueHideout);
        collectedObjects.Add((object) this.CounterOfferHero);
      }

      internal static object AutoGeneratedGetMemberValueCounterOfferHero(object o)
      {
        return (object) ((IssueBase) o).CounterOfferHero;
      }

      internal static object AutoGeneratedGetMemberValue_randomForStolenTradeGood(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue) o)._randomForStolenTradeGood;
      }

      internal static object AutoGeneratedGetMemberValue_issueHideout(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue) o)._issueHideout;
      }

      private ItemObject StolenTradeGood
      {
        get
        {
          return Game.Current.ObjectManager.GetObject<ItemObject>(GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue.PossibleStolenItems[this._randomForStolenTradeGood]);
        }
      }

      private int StolenTradeGoodAmount
      {
        get
        {
          return MathF.Ceiling(10000f / (float) this.IssueOwner.CurrentSettlement.Town.GetItemPrice(this.StolenTradeGood, (MobileParty) null, false) * this.IssueDifficultyMultiplier);
        }
      }

      private int StolenTradeGoodPrice
      {
        get
        {
          return MathF.Round((float) this.IssueOwner.CurrentSettlement.Town.GetItemPrice(this.StolenTradeGood, (MobileParty) null, false) * 0.5f * (float) this.StolenTradeGoodAmount);
        }
      }

      protected override int RewardGold
      {
        get
        {
          return MathF.Round((float) this.IssueOwner.CurrentSettlement.Town.GetItemPrice(this.StolenTradeGood, (MobileParty) null, false) * 0.4f * (float) this.StolenTradeGoodAmount);
        }
      }

      [SaveableProperty(10)]
      public override Hero CounterOfferHero { get; protected set; }

      public override bool IsThereAlternativeSolution => true;

      protected override bool IssueQuestCanBeDuplicated => false;

      public override TextObject IssueAlternativeSolutionExplanationByIssueGiver
      {
        get
        {
          TextObject explanationByIssueGiver = new TextObject("{=cODzH0Ke}Well, if you don't want to go yourself to meet them, I'm sure you can send a trusted aide with 10 or so men to load and guard those {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}. I am sure our people can seal the deal by themselves.");
          explanationByIssueGiver.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
          explanationByIssueGiver.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
          return explanationByIssueGiver;
        }
      }

      public override TextObject IssueAlternativeSolutionAcceptByPlayer
      {
        get
        {
          return new TextObject("{=ltiz6e11}Let them know my companion will be meeting them shortly.");
        }
      }

      public override bool IsThereLordSolution => false;

      public override TextObject IssueQuestSolutionExplanationByIssueGiver
      {
        get
        {
          TextObject explanationByIssueGiver = new TextObject("{=qh1Ot0F9}They have {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}. They're asking {REQUESTED_PRICE}{GOLD_ICON}. You know that this is the best price you can find anywhere in this district.");
          explanationByIssueGiver.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
          explanationByIssueGiver.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
          explanationByIssueGiver.SetTextVariable("REQUESTED_PRICE", this.StolenTradeGoodPrice);
          explanationByIssueGiver.SetTextVariable("GOLD_ICON", "{=!}<img src=\"General\\Icons\\Coin@2x\" extend=\"8\">");
          return explanationByIssueGiver;
        }
      }

      public override TextObject IssueBriefByIssueGiver
      {
        get
        {
          return new TextObject("{=babDRxdu}I am trying to help some friends. They want a buyer for some goods, that, well, let's say that my friends might not have paid for these goods. These lads are camped close by, but would prefer not to come into town. You see?[if:convo_mocking_aristocratic][ib:hip]");
        }
      }

      public override TextObject IssueAcceptByPlayer
      {
        get => new TextObject("{=rMySUGLu}I am interested. What are they selling?");
      }

      public override TextObject IssueQuestSolutionAcceptByPlayer
      {
        get => new TextObject("{=t1tNPPNf}I can go meet them and seal this deal myself.");
      }

      public override TextObject IssueAlternativeSolutionResponseByIssueGiver
      {
        get => new TextObject("{=ov0u6ahh}All right. It was a pleasure doing business with you.");
      }

      public override TextObject IssueDiscussAlternativeSolution
      {
        get => new TextObject("{=A2JWExWL}I hope our respective friends come to an agreement.");
      }

      public override TextObject Title
      {
        get
        {
          TextObject to = new TextObject("{=izuhKnXy}Purchase stolen goods from {ISSUE_GIVER.NAME}");
          to.SetCharacterProperties("ISSUE_GIVER", this.IssueOwner.CharacterObject);
          return to;
        }
      }

      public override TextObject Description
      {
        get
        {
          TextObject to = new TextObject("{=3WFgPigk}{ISSUE_GIVER.NAME} wants to sell you stolen goods. The price is low because of the added risk.");
          to.SetCharacterProperties("ISSUE_GIVER", this.IssueOwner.CharacterObject);
          return to;
        }
      }

      protected override TextObject AlternativeSolutionStartLog
      {
        get
        {
          TextObject to = new TextObject("{=riKyIyaa}{QUEST_GIVER.LINK}, a gang leader from {QUEST_GIVER_SETTLEMENT}, has offered you to sell {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} for half the normal price, because they were stolen... {?QUEST_GIVER.GENDER}She{?}He{\\?} says they are hidden in a remote location. You asked your companion to go buy the goods.");
          to.SetCharacterProperties("QUEST_GIVER", this.IssueOwner.CharacterObject);
          to.SetTextVariable("QUEST_GIVER_SETTLEMENT", this.IssueOwner.CurrentSettlement.EncyclopediaLinkWithName);
          to.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
          to.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
          return to;
        }
      }

      public override TextObject IssueAlternativeSolutionSuccessLog
      {
        get
        {
          TextObject to = new TextObject("{=XOB0SMXC}{COMPANION.LINK} has successfully offloaded the stolen goods. {?QUEST_GIVER.GENDER}She{?}He{\\?} returned to the party with {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}.");
          to.SetCharacterProperties("COMPANION", this.AlternativeSolutionHero.CharacterObject);
          to.SetCharacterProperties("QUEST_GIVER", this.IssueOwner.CharacterObject);
          to.SetTextVariable("STOLEN_GOODS_SIZE", this.StolenTradeGoodAmount);
          to.SetTextVariable("STOLEN_GOOD", this.StolenTradeGood.Name);
          return to;
        }
      }

      protected override int CompanionSkillRewardXP
      {
        get => 1000 + (int) (1250.0 * (double) this.IssueDifficultyMultiplier);
      }

      protected override int AlternativeSolutionBaseDurationInDaysInternal
      {
        get => (int) (7.0 + 10.0 * (double) this.IssueDifficultyMultiplier);
      }

      public override int AlternativeSolutionBaseNeededMenCount => 10;

      public override (SkillObject, int) GetAlternativeSolutionSkill(Hero hero)
      {
        List<SkillObject> solutionMeleeSkills = QuestHelper.GetAlternativeSolutionMeleeSkills();
        solutionMeleeSkills.Add(DefaultSkills.Roguery);
        solutionMeleeSkills.Add(DefaultSkills.Tactics);
        return (solutionMeleeSkills.MaxBy<SkillObject, int>(new Func<SkillObject, int>(hero.GetSkillValue)), 120);
      }

      public override bool AlternativeSolutionCondition(out TextObject explanation)
      {
        explanation = TextObject.Empty;
        return QuestHelper.CheckRosterForAlternativeSolution(MobileParty.MainParty.MemberRoster, this.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2);
      }

      protected override void AlternativeSolutionEndWithSuccessConsequence()
      {
        GiveGoldAction.ApplyBetweenCharacters((Hero) null, Hero.MainHero, this.RewardGold);
        this.RelationshipChangeWithIssueOwner = 10;
        this.IssueOwner.AddPower(5f);
        this.CounterOfferHero.AddPower(-5f);
        foreach (Hero hero in this.IssueOwner.CurrentSettlement.Notables.WhereQ<Hero>((Func<Hero, bool>) (notable => notable.IsMerchant)))
          hero.AddPower(-3f);
        MobileParty.MainParty.ItemRoster.AddToCounts(this.StolenTradeGood, this.StolenTradeGoodAmount);
        TraitLevelingHelper.OnIssueSolvedThroughAlternativeSolution(Hero.MainHero, new Tuple<TraitObject, int>[1]
        {
          new Tuple<TraitObject, int>(DefaultTraits.Calculating, 50)
        });
      }

      public override bool DoTroopsSatisfyAlternativeSolution(
        TroopRoster troopRoster,
        out TextObject explanation)
      {
        explanation = TextObject.Empty;
        return QuestHelper.CheckRosterForAlternativeSolution(troopRoster, this.GetTotalAlternativeSolutionNeededMenCount(), ref explanation, 2);
      }

      public GangLeaderNeedsToOffloadStolenGoodsIssue(Hero issueOwner, Settlement hideout)
        : base(issueOwner, CampaignTime.DaysFromNow(15f))
      {
        this._randomForStolenTradeGood = MBRandom.RandomInt(0, GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue.PossibleStolenItems.Length);
        this._issueHideout = hideout;
        Campaign.Current.BusyHideouts.Add(hideout);
      }

      protected override float GetIssueEffectAmountInternal(IssueEffect issueEffect)
      {
        if (issueEffect == DefaultIssueEffects.IssueOwnerPower)
          return -1f;
        return issueEffect == DefaultIssueEffects.SettlementSecurity ? 1f : 0.0f;
      }

      public override bool IssueStayAliveConditions()
      {
        return (double) this.IssueOwner.CurrentSettlement.Town.Security < 90.0 && this.CounterOfferHero.IsActive && this.CounterOfferHero.CurrentSettlement == this.IssueSettlement && this._issueHideout != null && this._issueHideout.Hideout.IsInfested;
      }

      protected override void CompleteIssueWithTimedOutConsequences()
      {
      }

      protected override void AfterIssueCreation()
      {
        this.CounterOfferHero = this.IssueOwner.CurrentSettlement.Notables.FirstOrDefault<Hero>((Func<Hero, bool>) (x => x != this.IssueOwner && x.IsMerchant)) ?? this.IssueOwner.CurrentSettlement.Notables.FirstOrDefault<Hero>();
      }

      protected override void OnGameLoad()
      {
        if (MBSaveLoad.IsUpdatingGameVersion && MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.0"))
          Campaign.Current.IssueManager.DeactivateIssue((IssueBase) this);
        if (!MBSaveLoad.IsUpdatingGameVersion || !(MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.9")) || Campaign.Current.BusyHideouts.Contains(this._issueHideout))
          return;
        Campaign.Current.BusyHideouts.Add(this._issueHideout);
      }

      protected override void HourlyTick()
      {
      }

      protected override QuestBase GenerateIssueQuest(string questId)
      {
        return (QuestBase) new GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest(questId, this.IssueOwner, CampaignTime.DaysFromNow(20f), this.StolenTradeGood, this._issueHideout, this.StolenTradeGoodPrice, this.RewardGold, this.StolenTradeGoodAmount, this.CounterOfferHero);
      }

      public override IssueBase.IssueFrequency GetFrequency() => IssueBase.IssueFrequency.Common;

      protected override bool CanPlayerTakeQuestConditions(
        Hero issueGiver,
        out IssueBase.PreconditionFlags flag,
        out Hero relationHero,
        out SkillObject skill)
      {
        flag = IssueBase.PreconditionFlags.None;
        relationHero = (Hero) null;
        skill = (SkillObject) null;
        if ((double) issueGiver.GetRelationWithPlayer() < -10.0)
        {
          flag |= IssueBase.PreconditionFlags.Relation;
          relationHero = issueGiver;
        }
        if (issueGiver.CurrentSettlement.MapFaction.IsAtWarWith(Hero.MainHero.MapFaction))
          flag |= IssueBase.PreconditionFlags.AtWar;
        if (Clan.PlayerClan == issueGiver.CurrentSettlement.OwnerClan)
          flag |= IssueBase.PreconditionFlags.PlayerIsOwnerOfSettlement;
        return flag == IssueBase.PreconditionFlags.None;
      }

      protected override void OnIssueFinalized()
      {
        Campaign.Current.BusyHideouts.Remove(this._issueHideout);
      }
    }

    public class GangLeaderNeedsToOffloadStolenGoodsIssueQuest : QuestBase
    {
      [SaveableField(105)]
      private readonly ItemObject _stolenTradeGood;
      [SaveableField(106)]
      private readonly int _stolenTradeGoodAmount;
      [SaveableField(107)]
      private readonly int _stolenTradeGoodPrice;
      [SaveableField(109)]
      private bool _counterOfferGiven;
      [SaveableField(111)]
      private readonly int _counterOfferGold;
      [SaveableField(112)]
      private JournalLog _playerStartsQuestLog;
      [SaveableField(113)]
      private readonly Hero _counterOfferHero;
      [SaveableField(114)]
      private bool _talkedWithBanditLeader;
      [SaveableField(115)]
      private bool _isPayingForGoods;
      [SaveableField(116)]
      private bool _isFightingForGoods;
      [SaveableField(117)]
      private readonly Settlement _questHideout;
      [SaveableField(118)]
      private bool _playerHasTheGoods;

      internal static void AutoGeneratedStaticCollectObjectsGangLeaderNeedsToOffloadStolenGoodsIssueQuest(
        object o,
        List<object> collectedObjects)
      {
        ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
      }

      protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
      {
        base.AutoGeneratedInstanceCollectObjects(collectedObjects);
        collectedObjects.Add((object) this._stolenTradeGood);
        collectedObjects.Add((object) this._playerStartsQuestLog);
        collectedObjects.Add((object) this._counterOfferHero);
        collectedObjects.Add((object) this._questHideout);
      }

      internal static object AutoGeneratedGetMemberValue_stolenTradeGood(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._stolenTradeGood;
      }

      internal static object AutoGeneratedGetMemberValue_stolenTradeGoodAmount(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._stolenTradeGoodAmount;
      }

      internal static object AutoGeneratedGetMemberValue_stolenTradeGoodPrice(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._stolenTradeGoodPrice;
      }

      internal static object AutoGeneratedGetMemberValue_counterOfferGiven(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._counterOfferGiven;
      }

      internal static object AutoGeneratedGetMemberValue_counterOfferGold(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._counterOfferGold;
      }

      internal static object AutoGeneratedGetMemberValue_playerStartsQuestLog(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._playerStartsQuestLog;
      }

      internal static object AutoGeneratedGetMemberValue_counterOfferHero(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._counterOfferHero;
      }

      internal static object AutoGeneratedGetMemberValue_talkedWithBanditLeader(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._talkedWithBanditLeader;
      }

      internal static object AutoGeneratedGetMemberValue_isPayingForGoods(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._isPayingForGoods;
      }

      internal static object AutoGeneratedGetMemberValue_isFightingForGoods(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._isFightingForGoods;
      }

      internal static object AutoGeneratedGetMemberValue_questHideout(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._questHideout;
      }

      internal static object AutoGeneratedGetMemberValue_playerHasTheGoods(object o)
      {
        return (object) ((GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest) o)._playerHasTheGoods;
      }

      public override bool IsRemainingTimeHidden => false;

      private CharacterObject BanditLeader => this._questHideout.Culture.BanditChief;

      private TextObject PlayerStartsQuestLogText
      {
        get
        {
          TextObject parent = new TextObject("{=uaYGZUDs}{QUEST_GIVER.LINK}, a gang leader from {QUEST_GIVER_SETTLEMENT}, has offered you to sell {STOLEN_GOODS_SIZE} {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} for half the normal price, because they were stolen.. {?QUEST_GIVER.GENDER}She{?}He{\\?} says they are hidden in a remote location. You agreed to buy the goods.");
          StringHelpers.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject, parent);
          parent.SetTextVariable("QUEST_GIVER_SETTLEMENT", this.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
          parent.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
          parent.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
          return parent;
        }
      }

      private TextObject SuccessQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=mrNdB0Hh}You refused the {MERCHANT.LINK}'s request and kept the goods.");
          to.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject);
          return to;
        }
      }

      private TextObject SuccessByGivingBackTheGoodsQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=jO9cGnCK}You bought the goods from the bandits and handed over them to the {MERCHANT.LINK}.");
          to.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject);
          return to;
        }
      }

      private TextObject FailBetrayQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=v1bkAxmK}You accepted {MERCHANT.LINK}'s request. You've handed over the goods.");
          to.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject);
          return to;
        }
      }

      private TextObject FailBetrayTakeGoodsQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=7q0vbVdN}You betrayed the gang leader and refused the {MERCHANT.LINK}'s request. The goods stayed with you.");
          to.SetCharacterProperties("MERCHANT", this._counterOfferHero.CharacterObject);
          return to;
        }
      }

      public override TextObject Title
      {
        get
        {
          TextObject to = new TextObject("{=AtHjW2lY}Purchase stolen goods from {QUEST_GIVER.NAME}");
          to.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject);
          return to;
        }
      }

      private TextObject FailLoseHideoutFightQuestLogText
      {
        get => new TextObject("{=g7atkzxO}You failed to clear the hideout.");
      }

      private TextObject FailTimeOutQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=JwNTcFLA}You failed to make the deal with {QUEST_GIVER.LINK}'s associates in time.");
          to.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject);
          return to;
        }
      }

      public GangLeaderNeedsToOffloadStolenGoodsIssueQuest(
        string questId,
        Hero questGiver,
        CampaignTime duration,
        ItemObject stolenTradeGood,
        Settlement questHideout,
        int stolenTradeGoodPrice,
        int rewardGold,
        int stolenGoodAmount,
        Hero counterOfferHero)
        : base(questId, questGiver, duration, rewardGold)
      {
        this._stolenTradeGood = stolenTradeGood;
        this._stolenTradeGoodPrice = stolenTradeGoodPrice;
        this._stolenTradeGoodAmount = stolenGoodAmount;
        this._counterOfferGold = MathF.Round((float) (questGiver.CurrentSettlement.Town.GetItemPrice(this._stolenTradeGood, (MobileParty) null, false) * this._stolenTradeGoodAmount) * 0.4f);
        this._counterOfferHero = counterOfferHero;
        this._questHideout = questHideout;
        Campaign.Current.BusyHideouts.Add(questHideout);
        this.SetDialogs();
        this.InitializeQuestOnCreation();
        this.AddGameMenuOptions();
      }

      private TextObject CancelSettlementOwnerChangedQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=0YwZsiT4}Your clan is now owner of the town from which the goods were stolen. As the lord of the settlement you cannot get involved in deals of this kind. Your agreement with {QUEST_GIVER.LINK} is canceled.");
          to.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject);
          return to;
        }
      }

      protected override void SetDialogs()
      {
        this.OfferDialogFlow = DialogFlow.CreateDialogFlow("issue_classic_quest_start").NpcLine(new TextObject("{=iKYd8PQc}Excellent. I'll have the whereabouts of the goods delivered to you right away...[if:convo_nonchalant][ib:confident]")).Condition((ConversationSentence.OnConditionDelegate) (() => Hero.OneToOneConversationHero == this.QuestGiver)).Consequence(new ConversationSentence.OnConsequenceDelegate(this.QuestAcceptedConsequences)).CloseDialog();
        this.DiscussDialogFlow = DialogFlow.CreateDialogFlow("quest_discuss").NpcLine(new TextObject("{=RmjvSKVq}My colleagues are waiting for your arrival. They won't be happy waiting too long with so many valuables at hand.")).Condition((ConversationSentence.OnConditionDelegate) (() => Hero.OneToOneConversationHero == this.QuestGiver)).BeginPlayerOptions().PlayerOption(new TextObject("{=D4CsJMLE}Don't worry, I'll get there soon enough.")).NpcLine(new TextObject("{=2D4EdZVK}All right, but if this falls through because you took too long, I won't be too happy with that.")).PlayerOption(new TextObject("{=ErKDfLWJ}I have more urgent business to handle. I will get there when I can.")).NpcLine(new TextObject("{=qLdchkGU}Yeah... Well, a lot can go wrong if you don't move on these things quickly.")).EndPlayerOptions().CloseDialog();
        Campaign.Current.ConversationManager.AddDialogFlow(this.GetCounterOfferDialogFlow(), (object) this);
        Campaign.Current.ConversationManager.AddDialogFlow(this.GetHideoutLeaderDialogFlow(), (object) this);
        Campaign.Current.ConversationManager.AddDialogFlow(this.GetAfterHideoutMerchantDialogFlow(), (object) this);
      }

      private TextObject BeforeAttackHideoutQuestLogText
      {
        get
        {
          TextObject to = new TextObject("{=sVL8Z0lg}You met {QUEST_GIVER.LINK}'s associates near their hideout and demanded they turn over the goods to you, refusing to pay. They refused, and your only option now is to attack the hideout under cover of darkness and take the goods by force.");
          to.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject);
          return to;
        }
      }

      private void QuestAcceptedConsequences()
      {
        this.StartQuest();
        this._playerStartsQuestLog = this.AddLog(this.PlayerStartsQuestLogText, true);
        this._questHideout.Hideout.IsSpotted = true;
        this._questHideout.IsVisible = true;
        this.AddTrackedObject((ITrackableCampaignObject) this._questHideout);
      }

      protected override void InitializeQuestOnGameLoad()
      {
        this.SetDialogs();
        this.AddGameMenuOptions();
      }

      protected override void HourlyTick()
      {
      }

      protected override void OnFinalize()
      {
        Campaign.Current.BusyHideouts.Remove(this._questHideout);
      }

      private DialogFlow GetCounterOfferDialogFlow()
      {
        TextObject textObject = new TextObject("{=WJPAWHM9}A moment of your time, {?PLAYER.GENDER}ma'am{?}sir{\\?}. I hear you've been talking with a well-known scoundrel named {QUEST_GIVER.LINK}. A while ago, a caravan of mine carrying some {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} was robbed. Now {?QUEST_GIVER.GENDER}she's{?}he's{\\?} going around offering to sell the exact same merchandise. The guards won't go beyond the walls to get it back, but you can. I will reward you, and you'll earn the gratitude of all law-abiding townsfolk.[if:convo_nonchalant][ib:normal2]");
        textObject.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter);
        textObject.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject);
        textObject.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
        textObject.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
        return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject).Condition((ConversationSentence.OnConditionDelegate) (() => this._counterOfferHero == Hero.OneToOneConversationHero && !this._talkedWithBanditLeader && !this._playerHasTheGoods)).BeginPlayerOptions().PlayerOption(new TextObject("{=Fk9nVX8t}Yes... Well, I will see what I can do.")).NpcLine(new TextObject("{=WotPuijV}That's the right decision. Thank you.[if:convo_calm_friendly][ib:closed]")).CloseDialog().PlayerOption(new TextObject("{=1fXYQ7XG}My deals are none of your business, merchant.")).NpcLine(new TextObject("{=u0pofzPq}Please reconsider. Whether you help me or not, I will make sure other merchants will hear of your decision.[if:convo_very_stern][ib:closed2]")).CloseDialog().EndPlayerOptions().CloseDialog();
      }

      protected override void OnTimedOut() => this.AddLog(this.FailTimeOutQuestLogText);

      private void AddGameMenuOptions()
      {
        this.AddGameMenuOption("hideout_place", "talk_to_boss", new TextObject("{=wbSXI6iq}Approach to the meeting point"), new GameMenuOption.OnConditionDelegate(this.game_menu_approach_meeting_on_condition), new GameMenuOption.OnConsequenceDelegate(this.game_menu_approach_meeting_on_consequence), index: 2);
      }

      private DialogFlow GetHideoutLeaderDialogFlow()
      {
        TextObject banditBrief = new TextObject("{=!}{BANDIT_BRIEF}");
        TextObject banditFirstInteraction = new TextObject("{=2dWvwc0T}You must be the nice {?PLAYER.GENDER}lady{?}lord{\\?} who {QUEST_GIVER.NAME} has been telling us about. We have been expecting you. The goods are nearby. I will tell my friends to bring them out as soon as you pay up.");
        banditFirstInteraction.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter);
        banditFirstInteraction.SetCharacterProperties("QUEST_GIVER", this.QuestGiver.CharacterObject);
        TextObject banditSecondInteraction = new TextObject("{=n17USCaH}Well well... Do you have our money yet?");
        TextObject text1 = new TextObject("{=hXmmofDN}Here are the denars. You can tell your friends to bring out the {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%}.");
        text1.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
        text1.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
        TextObject text2 = new TextObject("{=Bvb0AmW7}Unfortunately, I do not have enough denars on me.");
        TextObject npcText = new TextObject("{=7kTipmjp}Then why are you here? We're not the sort who does business on credit. Come back when you have the money.");
        return DialogFlow.CreateDialogFlow("start", 125).NpcLine(banditBrief).Condition((ConversationSentence.OnConditionDelegate) (() =>
        {
          banditBrief.SetTextVariable("BANDIT_BRIEF", !this._talkedWithBanditLeader ? banditFirstInteraction : banditSecondInteraction);
          return this.BanditLeader == CharacterObject.OneToOneConversationCharacter && Game.Current.GameStateManager.ActiveState is MapState && Settlement.CurrentSettlement == this._questHideout;
        })).Consequence((ConversationSentence.OnConsequenceDelegate) (() => this._talkedWithBanditLeader = true)).NpcLine(banditSecondInteraction).Condition((ConversationSentence.OnConditionDelegate) (() => this.BanditLeader == CharacterObject.OneToOneConversationCharacter && this._talkedWithBanditLeader && Game.Current.GameStateManager.ActiveState is MapState)).BeginPlayerOptions().PlayerOption(text1).ClickableCondition((ConversationSentence.OnClickableConditionDelegate) ((out TextObject explanation) =>
        {
          bool leaderDialogFlow = false;
          if (Hero.MainHero.Gold >= this._stolenTradeGoodPrice)
          {
            explanation = new TextObject("{=!}{GOLD_AMOUNT}{GOLD_ICON}");
            explanation.SetTextVariable("GOLD_AMOUNT", this._stolenTradeGoodPrice);
            leaderDialogFlow = true;
          }
          else
          {
            explanation = new TextObject("{=YuLLsAUb}You don't have {GOLD_AMOUNT}{GOLD_ICON}.");
            explanation.SetTextVariable("GOLD_AMOUNT", this._stolenTradeGoodPrice);
          }
          return leaderDialogFlow;
        })).NpcLine(new TextObject("{=21Y4tWE9}Good, good. All the best to you, friend.")).Consequence((ConversationSentence.OnConsequenceDelegate) (() =>
        {
          GiveGoldAction.ApplyForQuestBetweenCharacters(Hero.MainHero, (Hero) null, this._stolenTradeGoodPrice);
          this._isPayingForGoods = true;
          this._playerHasTheGoods = true;
        })).CloseDialog().PlayerOption(new TextObject("{=H7FpMR0O}I'm not buying them from you, thief. Bring them out now.")).NpcLine(new TextObject("{=M8j6J8aN}Really? Very well, I'll send word to my lads that you intended to take our loot by force. They'll get things ready for you, have no fear. Just maybe not in the way you're hoping...")).Consequence((ConversationSentence.OnConsequenceDelegate) (() =>
        {
          this.AddLog(this.BeforeAttackHideoutQuestLogText);
          this._isFightingForGoods = true;
        })).CloseDialog().PlayerOption(text2).Condition((ConversationSentence.OnConditionDelegate) (() => Hero.MainHero.Gold < this._stolenTradeGoodPrice)).NpcLine(npcText).CloseDialog().EndPlayerOptions().CloseDialog();
      }

      private DialogFlow GetAfterHideoutMerchantDialogFlow()
      {
        TextObject textObject = new TextObject("{=8nq0TbMZ}{?PLAYER.GENDER}Ma'am{?}Sir{\\?}! I saw your party from a distance. I hope you don't mind me catching up to you. I am glad to see you safe - and, from the looks of it, in possession of some fine new goods. Please tell me, would they be mine?");
        textObject.SetCharacterProperties("PLAYER", CharacterObject.PlayerCharacter);
        TextObject npcText1 = new TextObject("{=Utq4svjd}Splendid. I will be sure that everyone in {MERCHANT_TOWN} hears of your honesty.");
        npcText1.SetTextVariable("MERCHANT_TOWN", this.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
        TextObject npcText2 = new TextObject("{=dtghhz46}Well... You have swords. You can do what you like. Just don't expect anyone in {MERCHANT_TOWN} to think well of you. Good day, {?PLAYER.GENDER}ma'am{?}sir{\\?}.");
        npcText2.SetTextVariable("MERCHANT_TOWN", this.QuestGiver.CurrentSettlement.EncyclopediaLinkWithName);
        return DialogFlow.CreateDialogFlow("start", 125).NpcLine(textObject).Condition((ConversationSentence.OnConditionDelegate) (() => Settlement.CurrentSettlement == this._questHideout && this._counterOfferHero == Hero.OneToOneConversationHero)).BeginPlayerOptions().PlayerOption(new TextObject("{=peUxzLsY}\"Your\" goods? These are my goods now.")).NpcLine(npcText2).Consequence((ConversationSentence.OnConsequenceDelegate) (() =>
        {
          if (this._isPayingForGoods)
            this.SucceedQuestByPayingAndKeepingTheGoods();
          else
            this.FailQuestByKeepingTheGoods();
        })).CloseDialog().PlayerOption(new TextObject("{=1lOSJ29M}Yes, they are here. Tell your men to come pick them up.")).NpcLine(npcText1).Consequence((ConversationSentence.OnConsequenceDelegate) (() =>
        {
          if (this._isPayingForGoods)
            this.SucceedQuestByPayingAndGivingTheGoodsBack();
          else
            this.FailQuestByGivingBackTheGoods();
        })).CloseDialog().EndPlayerOptions().CloseDialog();
      }

      private void SucceedQuestByPayingAndKeepingTheGoods()
      {
        this.AddLog(this.SuccessQuestLogText);
        TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[1]
        {
          new Tuple<TraitObject, int>(DefaultTraits.Calculating, 100)
        });
        MobileParty.MainParty.ItemRoster.AddToCounts(this._stolenTradeGood, this._stolenTradeGoodAmount);
        this.QuestGiver.AddPower(5f);
        this._counterOfferHero.AddPower(-5f);
        ChangeRelationAction.ApplyPlayerRelation(this.QuestGiver, 10);
        foreach (Hero gainedRelationWith in this.QuestGiver.CurrentSettlement.Notables.WhereQ<Hero>((Func<Hero, bool>) (notable => notable.IsMerchant)))
          ChangeRelationAction.ApplyPlayerRelation(gainedRelationWith, -3);
        this.CompleteQuestWithSuccess();
      }

      private void SucceedQuestByPayingAndGivingTheGoodsBack()
      {
        this.AddLog(this.SuccessByGivingBackTheGoodsQuestLogText);
        GiveGoldAction.ApplyForQuestBetweenCharacters(this._counterOfferHero, Hero.MainHero, this._counterOfferGold);
        TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[1]
        {
          new Tuple<TraitObject, int>(DefaultTraits.Calculating, 150)
        });
        this.QuestGiver.AddPower(5f);
        this._counterOfferHero.AddPower(5f);
        ChangeRelationAction.ApplyPlayerRelation(this.QuestGiver, 10);
        foreach (Hero gainedRelationWith in this.QuestGiver.CurrentSettlement.Notables.WhereQ<Hero>((Func<Hero, bool>) (notable => notable != this.QuestGiver)))
          ChangeRelationAction.ApplyPlayerRelation(gainedRelationWith, 3);
        this.CompleteQuestWithSuccess();
      }

      private void FailQuestByKeepingTheGoods()
      {
        this.QuestGiver.AddPower(-5f);
        this._counterOfferHero.AddPower(-5f);
        TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[1]
        {
          new Tuple<TraitObject, int>(DefaultTraits.Calculating, 100)
        });
        MobileParty.MainParty.ItemRoster.AddToCounts(this._stolenTradeGood, this._stolenTradeGoodAmount);
        ChangeRelationAction.ApplyPlayerRelation(this.QuestGiver, -5);
        foreach (Hero gainedRelationWith in this.QuestGiver.CurrentSettlement.Notables.WhereQ<Hero>((Func<Hero, bool>) (notable => notable.IsMerchant)))
          ChangeRelationAction.ApplyPlayerRelation(gainedRelationWith, -3);
        this.CompleteQuestWithBetrayal(this.FailBetrayTakeGoodsQuestLogText);
      }

      private void FailQuestByGivingBackTheGoods()
      {
        GiveGoldAction.ApplyForQuestBetweenCharacters(this._counterOfferHero, Hero.MainHero, this._counterOfferGold);
        this.QuestGiver.AddPower(-5f);
        this._counterOfferHero.AddPower(5f);
        TraitLevelingHelper.OnIssueSolvedThroughQuest(Hero.MainHero, new Tuple<TraitObject, int>[1]
        {
          new Tuple<TraitObject, int>(DefaultTraits.Honor, 100)
        });
        ChangeRelationAction.ApplyPlayerRelation(this.QuestGiver, -5);
        foreach (Hero gainedRelationWith in this.QuestGiver.CurrentSettlement.Notables.WhereQ<Hero>((Func<Hero, bool>) (notable => notable != this.QuestGiver)))
          ChangeRelationAction.ApplyPlayerRelation(gainedRelationWith, 3);
        this.CompleteQuestWithBetrayal(this.FailBetrayQuestLogText);
      }

      private void FailQuestByLosingHideoutBattle()
      {
        this.QuestGiver.AddPower(-5f);
        this._counterOfferHero.AddPower(-5f);
        ChangeRelationAction.ApplyPlayerRelation(this.QuestGiver, -5);
        this.CompleteQuestWithFail(this.FailLoseHideoutFightQuestLogText);
      }

      protected override void RegisterEvents()
      {
        CampaignEvents.OnSessionLaunchedEvent.AddNonSerializedListener((object) this, new Action<CampaignGameStarter>(this.OnSessionStarted));
        CampaignEvents.GameMenuOpened.AddNonSerializedListener((object) this, new Action<MenuCallbackArgs>(this.GameMenuOpened));
        CampaignEvents.OnSettlementLeftEvent.AddNonSerializedListener((object) this, new Action<MobileParty, Settlement>(this.OnSettlementLeft));
        CampaignEvents.OnHideoutBattleCompletedEvent.AddNonSerializedListener((object) this, new Action<BattleSideEnum, HideoutEventComponent>(this.OnHideoutBattleCompleted));
        CampaignEvents.OnSettlementOwnerChangedEvent.AddNonSerializedListener((object) this, new Action<Settlement, bool, Hero, Hero, Hero, ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail>(this.OnSettlementOwnerChanged));
        CampaignEvents.MapEventStarted.AddNonSerializedListener((object) this, new Action<MapEvent, PartyBase, PartyBase>(this.OnMapEventStarted));
      }

      private void OnSessionStarted(CampaignGameStarter campaignGameStarter)
      {
        if (!MBSaveLoad.IsUpdatingGameVersion || !(MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.9")))
          return;
        if (!Campaign.Current.BusyHideouts.Contains(this._questHideout))
        {
          Campaign.Current.BusyHideouts.Add(this._questHideout);
        }
        else
        {
          this.CompleteQuestWithCancel();
          Campaign.Current.BusyHideouts.Add(this._questHideout);
        }
      }

      private void OnMapEventStarted(
        MapEvent mapEvent,
        PartyBase attackerParty,
        PartyBase defenderParty)
      {
        if (mapEvent.MapEventSettlement != this._questHideout || attackerParty != PartyBase.MainParty)
          return;
        this._isFightingForGoods = true;
      }

      private void OnSettlementOwnerChanged(
        Settlement settlement,
        bool openToClaim,
        Hero newOwner,
        Hero oldOwner,
        Hero capturerHero,
        ChangeOwnerOfSettlementAction.ChangeOwnerOfSettlementDetail detail)
      {
        if (settlement != this.QuestGiver.CurrentSettlement || newOwner != Hero.MainHero)
          return;
        this.CompleteQuestWithCancel(this.CancelSettlementOwnerChangedQuestLogText);
      }

      private void OnHideoutBattleCompleted(
        BattleSideEnum winnerSide,
        HideoutEventComponent hideoutEventComponent)
      {
        if (hideoutEventComponent.MapEvent.PlayerSide != winnerSide)
        {
          this.FailQuestByLosingHideoutBattle();
        }
        else
        {
          if (hideoutEventComponent.MapEvent.MapEventSettlement != this._questHideout)
            return;
          this._playerHasTheGoods = true;
          TextObject message = new TextObject("{=9bFAsGmp}You have cleared the hideout. Your men found the {.%}{?(STOLEN_GOODS_SIZE > 1)}{PLURAL(STOLEN_GOOD)}{?}{STOLEN_GOOD}{\\?}{.%} stashed nearby.");
          message.SetTextVariable("STOLEN_GOODS_SIZE", this._stolenTradeGoodAmount);
          message.SetTextVariable("STOLEN_GOOD", this._stolenTradeGood.Name);
          MBInformationManager.AddQuickInformation(message);
        }
      }

      private void GameMenuOpened(MenuCallbackArgs args)
      {
        if (Settlement.CurrentSettlement != this._questHideout || this._isFightingForGoods)
          return;
        GameTexts.SetVariable("HIDEOUT_DESCRIPTION", "{=b14v853a}As you approach the gang's camp, you can see a single man out in the open waiting for you, pacing and kicking stones around.");
      }

      private void OnSettlementLeft(MobileParty party, Settlement settlement)
      {
        if (party != MobileParty.MainParty)
          return;
        if (settlement == this._questHideout)
        {
          if (!this._playerHasTheGoods)
            return;
          CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter), new ConversationCharacterData(this._counterOfferHero.CharacterObject));
        }
        else
        {
          if (settlement != this._counterOfferHero.CurrentSettlement || this._counterOfferGiven)
            return;
          CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter), new ConversationCharacterData(this._counterOfferHero.CharacterObject));
          this._counterOfferGiven = true;
        }
      }

      private void game_menu_approach_meeting_on_consequence(MenuCallbackArgs args)
      {
        CampaignMapConversation.OpenConversation(new ConversationCharacterData(CharacterObject.PlayerCharacter), new ConversationCharacterData(this.BanditLeader));
      }

      private bool game_menu_approach_meeting_on_condition(MenuCallbackArgs args)
      {
        args.optionLeaveType = GameMenuOption.LeaveType.Conversation;
        args.OptionQuestData = GameMenuOption.IssueQuestFlags.ActiveIssue;
        return Settlement.CurrentSettlement == this._questHideout && !this._isFightingForGoods && !this._isPayingForGoods;
      }

      public override void OnHeroCanHaveQuestOrIssueInfoIsRequested(Hero hero, ref bool result)
      {
        if (hero != this._counterOfferHero)
          return;
        result = false;
      }
    }

    public class GangLeaderNeedsToOffloadStolenGoodsIssueTypeDefiner : SaveableTypeDefiner
    {
      public GangLeaderNeedsToOffloadStolenGoodsIssueTypeDefiner()
        : base(460000)
      {
      }

      protected override void DefineClassTypes()
      {
        this.AddClassDefinition(typeof (GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssue), 1);
        this.AddClassDefinition(typeof (GangLeaderNeedsToOffloadStolenGoodsIssueBehavior.GangLeaderNeedsToOffloadStolenGoodsIssueQuest), 2);
      }
    }
  }
}
