using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Party.PartyComponents;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Settlements
{
	// Token: 0x0200035D RID: 861
	public abstract class Fief : SettlementComponent
	{
		// Token: 0x060031E8 RID: 12776 RVA: 0x000D100C File Offset: 0x000CF20C
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x060031E9 RID: 12777 RVA: 0x000D1015 File Offset: 0x000CF215
		internal static object AutoGeneratedGetMemberValueFoodStocks(object o)
		{
			return ((Fief)o).FoodStocks;
		}

		// Token: 0x17000C0C RID: 3084
		// (get) Token: 0x060031EA RID: 12778 RVA: 0x000D1027 File Offset: 0x000CF227
		// (set) Token: 0x060031EB RID: 12779 RVA: 0x000D102F File Offset: 0x000CF22F
		[SaveableProperty(100)]
		public float FoodStocks { get; set; }

		// Token: 0x17000C0D RID: 3085
		// (get) Token: 0x060031EC RID: 12780 RVA: 0x000D1038 File Offset: 0x000CF238
		public float Militia
		{
			get
			{
				return base.Owner.Settlement.Militia;
			}
		}

		// Token: 0x17000C0E RID: 3086
		// (get) Token: 0x060031ED RID: 12781 RVA: 0x000D104A File Offset: 0x000CF24A
		public MobileParty GarrisonParty
		{
			get
			{
				GarrisonPartyComponent garrisonPartyComponent = this.GarrisonPartyComponent;
				if (garrisonPartyComponent == null)
				{
					return null;
				}
				return garrisonPartyComponent.MobileParty;
			}
		}

		// Token: 0x04001026 RID: 4134
		[CachedData]
		public GarrisonPartyComponent GarrisonPartyComponent;
	}
}
