using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;

namespace TaleWorlds.CampaignSystem.MapEvents
{
	// Token: 0x020002BC RID: 700
	public class ForceVolunteersEventComponent : MapEventComponent
	{
		// Token: 0x0600298A RID: 10634 RVA: 0x000B26F6 File Offset: 0x000B08F6
		internal static void AutoGeneratedStaticCollectObjectsForceVolunteersEventComponent(object o, List<object> collectedObjects)
		{
			((ForceVolunteersEventComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600298B RID: 10635 RVA: 0x000B2704 File Offset: 0x000B0904
		protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		// Token: 0x0600298C RID: 10636 RVA: 0x000B270D File Offset: 0x000B090D
		protected ForceVolunteersEventComponent(MapEvent mapEvent) : base(mapEvent)
		{
		}

		// Token: 0x0600298D RID: 10637 RVA: 0x000B2718 File Offset: 0x000B0918
		public static ForceVolunteersEventComponent CreateForceSuppliesEvent(PartyBase attackerParty, PartyBase defenderParty)
		{
			MapEvent mapEvent = new MapEvent();
			ForceVolunteersEventComponent forceVolunteersEventComponent = new ForceVolunteersEventComponent(mapEvent);
			mapEvent.Initialize(attackerParty, defenderParty, forceVolunteersEventComponent, MapEvent.BattleTypes.IsForcingVolunteers);
			Settlement settlement = defenderParty.Settlement;
			if (((settlement != null) ? settlement.MilitiaPartyComponent : null) != null)
			{
				defenderParty.Settlement.MilitiaPartyComponent.MobileParty.MapEventSide = mapEvent.DefenderSide;
			}
			Campaign.Current.MapEventManager.OnMapEventCreated(mapEvent);
			return forceVolunteersEventComponent;
		}

		// Token: 0x0600298E RID: 10638 RVA: 0x000B277C File Offset: 0x000B097C
		public static ForceVolunteersEventComponent CreateComponentForOldSaves(MapEvent mapEvent)
		{
			return new ForceVolunteersEventComponent(mapEvent);
		}

		// Token: 0x0600298F RID: 10639 RVA: 0x000B2784 File Offset: 0x000B0984
		protected override void OnInitialize()
		{
			ChangeVillageStateAction.ApplyBySettingToBeingForcedForVolunteers(base.MapEvent.MapEventSettlement, base.MapEvent.AttackerSide.LeaderParty.MobileParty);
		}

		// Token: 0x06002990 RID: 10640 RVA: 0x000B27AB File Offset: 0x000B09AB
		protected override void OnFinalize()
		{
			CampaignEventDispatcher.Instance.ForceVolunteersCompleted((base.MapEvent.BattleState == BattleState.AttackerVictory) ? BattleSideEnum.Attacker : BattleSideEnum.Defender, this);
			ChangeVillageStateAction.ApplyBySettingToNormal(base.MapEvent.MapEventSettlement);
		}
	}
}
