#!/bin/bash

# 继续美化01_initialization.c文件中的变量名
# 将剩余的带有内存地址的变量名替换为语义化的名称

INPUT_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/01_initialization.c"

# 替换更多全局数据变量（按功能分组）
sed -i 's/g_global_data_1809fee00/g_global_texture_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fee18/g_global_shader_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fee30/g_global_mesh_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fee48/g_global_material_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fee60/g_global_animation_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fee78/g_global_skeleton_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fee90/g_global_audio_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809feea8/g_global_music_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809feec0/g_global_sound_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809feed8/g_global_font_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809feef0/g_global_ui_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef08/g_global_widget_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef20/g_global_layout_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef38/g_global_theme_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef50/g_global_input_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef68/g_global_keyboard_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef80/g_global_mouse_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fef98/g_global_gamepad_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fefb0/g_global_touch_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fefc8/g_global_network_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809fefe0/g_global_socket_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809feff8/g_global_connection_manager/g' "$INPUT_FILE"

# 替换静态数据变量
sed -i 's/g_static_data_1809ff010/g_static_render_target/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff028/g_static_frame_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff040/g_static_depth_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff058/g_static_stencil_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff070/g_static_vertex_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff088/g_static_index_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff0a0/g_static_uniform_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff0b8/g_static_shader_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff0d0/g_static_texture_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff0e8/g_static_compute_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff100/g_static_indirect_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff118/g_static_query_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff130/g_static_feedback_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff148/g_static_transform_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff160/g_static_instance_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff178/g_static_batch_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff190/g_static_cull_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff1a8/g_static_occlusion_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff1c0/g_static_shadow_buffer/g' "$INPUT_FILE"
sed -i 's/g_static_data_1809ff1d8/g_static_light_buffer/g' "$INPUT_FILE"

# 替换更多全局数据变量
sed -i 's/g_global_data_1809ff1f0/g_global_camera_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff208/g_global_light_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff220/g_global_shadow_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff238/g_global_postprocess_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff250/g_global_particle_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff268/g_global_effect_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff280/g_global_water_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff298/g_global_terrain_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff2b0/g_global_vegetation_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff2c8/g_global_sky_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff2e0/g_global_weather_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff2f8/g_global_time_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff310/g_global_physics_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff328/g_global_collision_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff340/g_global_raycast_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff358/g_global_trigger_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff370/g_global_constraint_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff388/g_global_joint_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff3a0/g_global_spring_manager/g' "$INPUT_FILE"
sed -i 's/g_global_data_1809ff3b8/g_global_force_manager/g' "$INPUT_FILE"

echo "第二轮变量名美化完成"