#!/usr/bin/env bash

# 脚本：美化变量名 - 将变量名改为更具语义的名称
# 注意：这是一个简化实现，用于批量替换变量名

# 定义要替换的变量映射
declare -A variable_map=(
    ["global_configuration_data"]="global_configuration_settings"
    ["global_configuration_flags"]="global_configuration_options"
    ["engine_init_func"]="engine_initialization_procedure"
    ["engine_state_flags"]="engine_runtime_flags"
    ["engine_state_data"]="engine_runtime_data"
    ["render_context_flags"]="rendering_context_flags"
    ["render_context_data"]="rendering_context_data"
    ["physics_system_flags"]="physics_engine_flags"
    ["physics_system_data"]="physics_engine_data"
    ["audio_system_flags"]="audio_system_flags"
    ["audio_system_data"]="audio_system_data"
    ["audio_engine_data"]="audio_engine_instance"
    ["input_system_data"]="input_handler_data"
    ["input_engine_data"]="input_engine_instance"
    ["script_system_data"]="script_execution_data"
    ["network_module_data"]="network_system_data"
    ["engine_update_function"]="engine_update_procedure"
    ["memory_allocator_data"]="memory_management_data"
    ["game_engine_instance"]="game_engine_object"
    ["game_engine_flags"]="game_engine_state"
    ["game_world_data"]="game_world_instance"
    ["game_world_flags"]="game_world_state"
    ["render_system_initialize"]="render_system_initializer"
    ["render_system_data1"]="render_system_buffer1"
    ["render_system_data2"]="render_system_buffer2"
    ["game_player_data"]="game_player_instance"
    ["game_player_flags"]="game_player_state"
    ["game_camera_data"]="game_camera_instance"
    ["game_camera_flags"]="game_camera_state"
    ["game_ui_flag1"]="game_ui_enabled_flag"
    ["game_ui_data"]="game_ui_instance"
    ["game_ui_flags"]="game_ui_state"
    ["game_ui_flag2"]="game_ui_visible_flag"
    ["network_module_data1"]="network_connection_data"
    ["network_module_data2"]="network_session_data"
    ["game_render_data"]="game_rendering_data"
    ["game_render_flags"]="game_rendering_state"
    ["game_physics_data"]="game_physics_data"
    ["game_physics_flags"]="game_physics_state"
    ["audio_system_initialize"]="audio_system_initializer"
    ["game_audio_system_data"]="game_audio_system_data"
    ["game_audio_flags"]="game_audio_state"
    ["game_input_data"]="game_input_handler_data"
    ["game_input_flags"]="game_input_handler_state"
    ["engine_init_subsystem"]="engine_subsystem_initializer"
    ["engine_config_data_1"]="engine_config_parameter1"
    ["engine_config_data_2"]="engine_config_parameter2"
    ["engine_config_data_3"]="engine_config_parameter3"
    ["engine_config_data_4"]="engine_config_parameter4"
    ["game_module_handle"]="game_module_reference"
    ["engine_load_module"]="engine_module_loader"
    ["engine_config_data_5"]="engine_config_parameter5"
    ["engine_config_data_6"]="engine_config_parameter6"
    ["engine_config_data_7"]="engine_config_parameter7"
    ["engine_config_data_8"]="engine_config_parameter8"
    ["game_world_handle"]="game_world_reference"
    ["engine_create_world"]="engine_world_creator"
    ["engine_state_data_1"]="engine_runtime_data1"
    ["engine_state_data_2"]="engine_runtime_data2"
    ["engine_state_data_3"]="engine_runtime_data3"
    ["engine_state_data_4"]="engine_runtime_data4"
    ["engine_init_renderer"]="engine_renderer_initializer"
    ["engine_render_data_1"]="engine_rendering_data1"
    ["engine_render_data_2"]="engine_rendering_data2"
    ["engine_render_data_3"]="engine_rendering_data3"
    ["renderer_config_data"]="renderer_configuration_data"
    ["engine_init_audio"]="engine_audio_initializer"
    ["engine_init_physics"]="engine_physics_initializer"
    ["game_save_func"]="game_save_handler"
    ["game_load_func"]="game_load_handler"
    ["game_get_state_function"]="game_state_getter"
    ["game_world_data_ptr"]="game_world_pointer"
    ["game_handle_input_function"]="game_input_processor"
    ["game_event_handler"]="game_event_manager"
    ["game_process_events_function"]="game_event_processor"
    ["game_cleanup_func"]="game_cleanup_handler"
    ["game_create_object_func"]="game_object_creator"
    ["game_destroy_object_function"]="game_object_destroyer"
    ["game_destroy_entity"]="game_entity_destroyer"
    ["object_destruction_data"]="object_destruction_info"
    ["unknown_data_1809ff990"]="unknown_object_creation_flag"
)

# 备份原文件
cp "TaleWorlds.Native.dll.c" "TaleWorlds.Native.dll.c.backup"

# 执行替换
for old_name in "${!variable_map[@]}"; do
    new_name="${variable_map[$old_name]}"
    sed -i "s/\bundefined $old_name\b/undefined $new_name/g" "TaleWorlds.Native.dll.c"
    echo "替换: $old_name -> $new_name"
done

echo "变量名替换完成"