 /**
 * @file 06_utilities.c
 * 工具系统核心实现
 * 提供系统工具函数，包括线程管理、资源处理、状态验证等功能
 * 原本实现：完全重构工具系统，建立统一的语义化命名规范
 * 简化实现：仅将常见的非语义化名称替换为语义化名称，为关键函数添加文档注释，保持代码结构不变
 */
#include "TaleWorlds.Native.Split.h"
#define UTILITY_MAX_THREADS 8                  // 最大线程数
#define UTILITY_MAX_EVENTS 16                  // 最大事件数
#define UTILITY_MAX_HANDLERS 32                // 最大处理器数
#define UTILITY_STATE_RUNNING 0x1               // 系统运行中
#define UTILITY_STATE_PAUSED 0x800                // 系统已暂停
#define UTILITY_STATE_STOPPED UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE               // 系统已停止
#define UTILITY_ERROR_NONE UTILITY_FLAG_FALSE
#define UTILITY_ERROR_MEMORY UTILITY_FLAG_TRUE
#define UTILITY_ERROR_TIMEOUT 0x1
#define UTILITY_STATUS_RESOURCE_LOCKED 0x1
#define UTILITY_STATUS_RESOURCE_AVAILABLE 0x2
#define UTILITY_STATUS_MEMORY_IN_USE 0x4
#define UTILITY_STATUS_OPERATION_FAILED 0x8
#define UTILITY_STATUS_RESOURCE_NOT_FOUND 0x10
#define UTILITY_STATUS_ACCESS_DENIED 0x0
#define UTILITY_THREAD_HANDLE_OFFSET 0x80
#define UTILITY_THREAD_CONTEXT_OFFSET UTILITY_THREAD_CONTEXT_OFFSET_VALUE
#define UTILITY_THREAD_DATA_OFFSET UTILITY_THREAD_DATA_OFFSET_VALUE
#define UTILITY_THREAD_CONFIG_OFFSET UTILITY_THREAD_CONFIG_OFFSET_VALUE
#define UTILITY_THREAD_STATUS_OFFSET UTILITY_THREAD_STATUS_OFFSET_VALUE
#define UTILITY_THREAD_POINTER_OFFSET UTILITY_THREAD_POINTER_OFFSET_VALUE
#define UTILITY_THREAD_BUFFER_OFFSET UTILITY_THREAD_BUFFER_OFFSET_VALUE
#define UTILITY_THREAD_SIZE_OFFSET UTILITY_THREAD_SIZE_OFFSET_VALUE
#define UTILITY_RESOURCE_COUNT_OFFSET UTILITY_RESOURCE_COUNT_OFFSET_VALUE
#define UTILITY_RESOURCE_SIZE_OFFSET UTILITY_RESOURCE_SIZE_OFFSET_VALUE
#define UTILITY_RESOURCE_HANDLE_OFFSET UTILITY_RESOURCE_HANDLE_OFFSET_VALUE
#define UTILITY_RESOURCE_FLAG_OFFSET 0x2
#define UTILITY_MEMORY_POINTER_OFFSET UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE
#define UTILITY_MEMORY_STATUS_OFFSET UTILITY_MEMORY_STATUS_OFFSET_VALUE
#define UTILITY_MEMORY_FLAG_OFFSET UTILITY_MEMORY_FLAG_OFFSET_VALUE
#define UTILITY_DATA_COUNTER_OFFSET UTILITY_DATA_COUNTER_OFFSET_VALUE
#define UTILITY_DATA_INDEX_OFFSET UTILITY_DATA_INDEX_OFFSET_VALUE
#define UTILITY_STATUS_FLAG_MASK UTILITY_STATUS_FLAG_MASK_VALUE
#define UTILITY_STATUS_THREAD_CREATED 0x8
#define UTILITY_CONTEXT_RESOURCE_OFFSET UTILITY_CONTEXT_RESOURCE_OFFSET_VALUE
#define UTILITY_CONTEXT_ITERATOR_OFFSET UTILITY_CONTEXT_ITERATOR_OFFSET_VALUE
#define UTILITY_CONTEXT_VALIDATION_OFFSET UTILITY_CONTEXT_VALIDATION_OFFSET_VALUE
#define UTILITY_CONTEXT_HANDLER_OFFSET UTILITY_CONTEXT_HANDLER_OFFSET_VALUE
#define UTILITY_CONTEXT_EXTENDED_OFFSET UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE
#define UTILITY_CONTEXT_TABLE_OFFSET UTILITY_CONTEXT_TABLE_OFFSET_VALUE
#define UTILITY_CONTEXT_SERVICE_OFFSET UTILITY_CONTEXT_SERVICE_OFFSET_VALUE
#define UTILITY_CALC_MULTIPLIER_OFFSET UTILITY_CALC_MULTIPLIER_OFFSET_VALUE
#define UTILITY_CALC_RESULT_OFFSET UTILITY_CALC_RESULT_OFFSET_VALUE
// 资源管理器地址常量定义
#define UTILITY_RESOURCE_MANAGER_PRIMARY_ADDRESS 0x1808d7494
#define UTILITY_RESOURCE_MANAGER_SECONDARY_ADDRESS 0x1808d74a4
#define UTILITY_RESOURCE_MANAGER_TERTIARY_ADDRESS 0x1808d74b1
#define UTILITY_MAX_OPERATION_RANGE_VALUE 0x7fffffff
#define UTILITY_MAX_OPERATION_RANGE UTILITY_MAX_OPERATION_RANGE_VALUE
#define UTILITY_STATUS_ENABLED_FLAG_QUATERNARY 0x800
#define UTILITY_STATUS_FLAG_MASK_7_BITS 0x400
#define UTILITY_STATUS_ENABLED_FLAG_NINE_BITS 0x1000
#define UTILITY_STATUS_ENABLED_FLAG_4_BITS 0x2000
#define UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE 0xFF
#define UTILITY_STATUS_FLAG_MASK_8_BIT UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE
#define UTILITY_RESOURCE_FLAG_OFFSET_PRIMARY UTILITY_RESOURCE_FLAG_OFFSET_PRIMARY_VALUE
#define UTILITY_RESOURCE_FLAG_OFFSET_SECONDARY UTILITY_RESOURCE_FLAG_OFFSET_SECONDARY_VALUE
#define UTILITY_SERVICE_OFFSET_D0 (0x0  + UTILITY_NULL_OFFSET)
#define UTILITY_MEMORY_FLAG_OFFSET_PRIMARY UTILITY_MEMORY_FLAG_OFFSET_PRIMARY_VALUE
#define UTILITY_FLAG_MASK_BYTE UTILITY_FLAG_MASK_BYTE_VALUE
#define UTILITY_FLAG_MASK_WORD_VALUE 0xFFFF
#define UTILITY_FLAG_MASK_WORD UTILITY_FLAG_MASK_WORD_VALUE
#define UTILITY_STATUS_FLAG_MASK_LARGE UTILITY_MAX_UINT32
#define UTILITY_FLOAT_FLAG_MASK_F800000_VALUE 0xF800000
#define UTILITY_FLAG_MASK_FLOAT_PROCESSING UTILITY_FLOAT_FLAG_MASK_F800000_VALUE
#define UTILITY_BUFFER_ALIGNMENT 0x2000
#define UTILITY_BUFFER_ALIGNMENT_MASK UTILITY_ALIGNMENT_MASK
#define UTILITY_RESOURCE_NOT_FOUND 0x10
#define UTILITY_INVALID_PARAMETER 0x40
#define UTILITY_MEMORY_ALIGNMENT_PAGE_MASK UTILITY_MEMORY_PAGE_ALIGNMENT_MASK
#define UTILITY_MEMORY_NEGATIVE_512MB_HEX -0x20000000
#define UTILITY_FLOAT_NEGATIVE_ONE 0xbf800000
#define UTILITY_MEMORY_BLOCK_SIZE_EXTRA_LARGE 0x10000000
#define UTILITY_MEMORY_BLOCK_SIZE_HUGE (0x0 + 0x10000000)
#define UTILITY_FLAG_MASK_WORD_FFc0_VALUE 0xFFc0
#define UTILITY_BUFFER_FLAGS_DEFAULT UTILITY_FLAG_MASK_WORD_FFc0_VALUE
#define UTILITY_FLOAT_ARRAY_OFFSET_SECONDARY UTILITY_FLOAT_ARRAY_OFFSET_SECONDARY_VALUE
#define UTILITY_FLOAT_ARRAY_OFFSET_TERTIARY UTILITY_FLOAT_ARRAY_OFFSET_TERTIARY_VALUE
#define UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE
#define UTILITY_SERVICE_HANDLER_OFFSET_PRIMARY UTILITY_SERVICE_HANDLER_OFFSET_PRIMARY_VALUE
#define UTILITY_SERVICE_HANDLER_OFFSET_TERTIARY UTILITY_SERVICE_HANDLER_OFFSET_TERTIARY_VALUE
#define UTILITY_NETWORK_CONTEXT_OFFSET_D8 (0x0 + UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE)
#define UTILITY_NULL_PTR UTILITY_FLAG_FALSE
#define UTILITY_CONTEXT_SIZE_MULTIPLIER UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE
#define UTILITY_BUFFER_ELEMENT_SIZE UTILITY_BUFFER_ELEMENT_SIZE_VALUE
#define UTILITY_STACK_OFFSET_SMALL UTILITY_STACK_OFFSET_SMALL_VALUE
#define UTILITY_STACK_OFFSET_LARGE UTILITY_STACK_OFFSET_LARGE_VALUE
#define UTILITY_MEMORY_POINTER_OFFSET_BASE UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE
#define UTILITY_STATUS_FLAG_MASK_PRIMARY 0x80
#define UTILITY_STATUS_FLAG_MASK_SMALL 0x100
#define UTILITY_STATUS_FLAG_MASK_MEDIUM 0x200
#define UTILITY_MEMORY_POINTER_OFFSET_SMALL UTILITY_OFFSET_FOURTEEN
#define UTILITY_MEMORY_POINTER_OFFSET_MEDIUM UTILITY_MEMORY_POINTER_OFFSET_MEDIUM_VALUE
#define UTILITY_MEMORY_POINTER_OFFSET_LARGE UTILITY_MEMORY_POINTER_OFFSET_LARGE_VALUE
#define UTILITY_CONTEXT_MULTIPLIER_C UTILITY_BUFFER_ELEMENT_SIZE_VALUE
#define UTILITY_FLAG_MASK_THREAD_RUNNING UTILITY_BUFFER_OPERATION_SIZE0
#define UTILITY_CONTEXT_RESOURCE_OFFSET_BASE UTILITY_FLAG_FALSE
#define UTILITY_CONTEXT_OFFSET_RESERVED UTILITY_CONTEXT_RESERVED_OFFSET
#define UTILITY_STATUS_FLAG_F 0x2000
#define UTILITY_CONTEXT_OFFSET_EXTENDED UTILITY_CONTEXT_EXTENDED_OFFSET
#define UTILITY_CONTEXT_OFFSET_AUXILIARY UTILITY_STACK_OFFSET_LARGE_VALUE
#define UTILITY_BYTE_MASK_CLEAR_LSB UTILITY_BYTE_MASK_CLEAR_LSB
#define UTILITY_TRUE 1
#define UTILITY_FALSE 0
#define UTILITY_THREAD_DATA_OFFSET_PRIMARY UTILITY_THREAD_DATA_OFFSET_VALUE
#define UTILITY_RESOURCE_FLAG_OFFSET_SECONDARY UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE
#define UTILITY_RESOURCE_FLAG_OFFSET_TERTIARY UTILITY_CONTEXT_RESOURCE_OFFSET_VALUE
#define UTILITY_THREAD_BUFFER_OFFSET_PRIMARY UTILITY_THREAD_BUFFER_OFFSET_VALUE
#define UTILITY_THREAD_BUFFER_OFFSET_SECONDARY UTILITY_THREAD_SIZE_OFFSET_VALUE
#define UTILITY_THREAD_BUFFER_OFFSET_TERTIARY UTILITY_RESOURCE_SIZE_OFFSET_VALUE
#define UTILITY_RESOURCE_FLAG_OFFSET_EXTENDED UTILITY_HANDLE_COMPARE_LIMIT_50
#define UTILITY_CONTEXT_OFFSET_RESOURCE_ID 0x10
#define UTILITY_CONTEXT_OFFSET_CONFIG UTILITY_BUFFER_ELEMENT_SIZE_VALUE
#define UTILITY_CONTEXT_OFFSET_DATA_AREA UTILITY_OFFSET_DATA_AREA
#define UTILITY_OFFSET_DATA_AREA UTILITY_DATA_AREA_OFFSET
#define UTILITY_CONTEXT_OFFSET_BUFFER 0x400
#define UTILITY_CONTEXT_OFFSET_CONTROL UTILITY_OFFSET_CONTROL_BLOCK
#define UTILITY_OFFSET_CONTROL_BLOCK UTILITY_CONTROL_BLOCK_OFFSET
#define UTILITY_CHECKSUM_OFFSET_VALIDATION UTILITY_CHECKSUM_VALIDATION_OFFSET
#define UTILITY_SERVICE_CONTEXT_OFFSET_LARGE UTILITY_SERVICE_CONTEXT_OFFSET_LARGE_VALUE
#define UTILITY_STATUS_FLAG_EXTENDED UTILITY_OFFSET_FOURTEEN
#define UTILITY_STATUS_FLAG_EXTENDED_SMALL UTILITY_MEMORY_POINTER_OFFSET_MEDIUM_VALUE
#define UTILITY_STATUS_FLAG_EXTENDED_MEDIUM UTILITY_MEMORY_POINTER_OFFSET_LARGE_VALUE
#define UTILITY_STATUS_FLAG_EXTENDED_CONTROL UTILITY_OFFSET_EXTENDED_CONTROL
#define UTILITY_OFFSET_EXTENDED_CONTROL UTILITY_EXTENDED_CONTROL_OFFSET
#define UTILITY_STATUS_FLAG_VALIDATION_CHECKSUM UTILITY_OFFSET_VALIDATION_CHECKSUM
#define UTILITY_OFFSET_VALIDATION_CHECKSUM UTILITY_VALIDATION_CHECKSUM_OFFSET
#define UTILITY_STATUS_FLAG_RESOURCE_TABLE UTILITY_OFFSET_RESOURCE_TABLE
#define UTILITY_OFFSET_RESOURCE_TABLE UTILITY_RESOURCE_TABLE_OFFSET
#define UTILITY_STATUS_FLAG_MEMORY_POOL UTILITY_OFFSET_MEMORY_POOL
#define UTILITY_OFFSET_MEMORY_POOL UTILITY_MEMORY_POOL_OFFSET
#define UTILITY_STATUS_FLAG_THREAD_QUEUE UTILITY_OFFSET_THREAD_QUEUE
#define UTILITY_OFFSET_THREAD_QUEUE UTILITY_THREAD_QUEUE_OFFSET
#define UTILITY_STATUS_FLAG_EVENT_HANDLER UTILITY_OFFSET_EVENT_HANDLER
#define UTILITY_OFFSET_EVENT_HANDLER UTILITY_EVENT_HANDLER_OFFSET
#define UTILITY_STATUS_FLAG_SIGNAL_HANDLER UTILITY_OFFSET_SIGNAL_HANDLER
#define UTILITY_OFFSET_SIGNAL_HANDLER UTILITY_SIGNAL_HANDLER_OFFSET
#define UTILITY_STATUS_FLAG_TIMER UTILITY_OFFSET_TIMER
#define UTILITY_CONTEXT_OFFSET_DWORD_ARRAY 800     // 双字数组偏移量
#define UTILITY_CONTEXT_OFFSET_SERVICE_FUNCTION 600 // 服务函数偏移量
#define UTILITY_OFFSET_TIMER UTILITY_TIMER_OFFSET
#define UTILITY_STATUS_FLAG_PERFORMANCE_COUNTER UTILITY_OFFSET_PERFORMANCE_COUNTER
#define UTILITY_OFFSET_PERFORMANCE_COUNTER UTILITY_PERFORMANCE_COUNTER_OFFSET
#define UTILITY_STATUS_FLAG_DEBUG_INFO UTILITY_OFFSET_DEBUG_INFO
#define UTILITY_OFFSET_DEBUG_INFO UTILITY_DEBUG_INFO_OFFSET
#define UTILITY_STATUS_FLAG_LOGGER UTILITY_OFFSET_LOGGER
#define UTILITY_OFFSET_LOGGER UTILITY_LOGGER_OFFSET
#define UTILITY_STATUS_FLAG_CONFIG_STORAGE UTILITY_OFFSET_CONFIG_STORAGE
#define UTILITY_OFFSET_CONFIG_STORAGE UTILITY_CONFIG_STORAGE_OFFSET
#define UTILITY_STATUS_FLAG_USER_DATA UTILITY_OFFSET_USER_DATA
#define UTILITY_OFFSET_USER_DATA UTILITY_USER_DATA_OFFSET
#define UTILITY_STATUS_FLAG_CACHE UTILITY_OFFSET_CACHE
#define UTILITY_OFFSET_CACHE UTILITY_CACHE_OFFSET
#define UTILITY_STATUS_FLAG_BUFFER_POOL UTILITY_OFFSET_BUFFER_POOL
#define UTILITY_OFFSET_BUFFER_POOL UTILITY_BUFFER_POOL_OFFSET
#define UTILITY_STATUS_FLAG_NETWORK UTILITY_OFFSET_NETWORK
#define UTILITY_OFFSET_NETWORK UTILITY_NETWORK_OFFSET
#define UTILITY_STATUS_FLAG_GRAPHICS UTILITY_OFFSET_GRAPHICS
#define UTILITY_OFFSET_GRAPHICS UTILITY_GRAPHICS_OFFSET
#define UTILITY_STATUS_FLAG_AUDIO UTILITY_OFFSET_AUDIO
#define UTILITY_OFFSET_AUDIO UTILITY_LOOP_CONTEXT_EXTENDED_OFFSET
#define UTILITY_STATUS_ENABLED_FLAG_ZERO UTILITY_FLAG_FALSE
#define UTILITY_STATUS_ENABLED_FLAG_PRIMARY UTILITY_FLAG_TRUE
#define UTILITY_STATUS_ENABLED_FLAG_SECONDARY 0x1
#define UTILITY_STATUS_ENABLED_FLAG_TERTIARY 0x800
#define UTILITY_SERVICE_HANDLER_OFFSET_SECONDARY UTILITY_SERVICE_HANDLER_SECONDARY_OFFSET
#define UTILITY_SERVICE_CONTEXT_OFFSET_MEDIUM UTILITY_SERVICE_CONTEXT_MEDIUM_OFFSET
#define UTILITY_STREAM_TYPE_ROOT UTILITY_FLAG_TRUE
#define UTILITY_STREAM_TYPE_KNOWN 0x1
#define UTILITY_MAX_UINT32 0x200
#define UTILITY_ALIGNMENT_PAGE_MASK UTILITY_MEMORY_PAGE_ALIGNMENT_MASK
#define UTILITY_ALIGNMENT_MASK UTILITY_FLAG_MASK_WORD_FFf0
#define UTILITY_MEMORY_PAGE_SIZE UTILITY_MAX_OPERATION_RANGE_VALUE
#define UTILITY_MEMORY_NEGATIVE_512MB_VALUE -0x20000000
#define UTILITY_RESOURCE_FLAG_RESERVED_AREA UTILITY_RESOURCE_FLAG_RESERVED_AREA_VALUE
// 工具系统内存基地址常量定义
#define UTILITY_MEMORY_SYSTEM_BASE_ADDRESS 0x180893865  // 系统内存基地址
#define UTILITY_MEMORY_KERNEL_BASE_ADDRESS 0x180893a22  // 内核内存基地址
#define UTILITY_MEMORY_USER_BASE_ADDRESS 0x180895f53   // 用户内存基地址
#define UTILITY_MEMORY_SHARED_BASE_ADDRESS 0x180895f67 // 共享内存基地址
#define UTILITY_MEMORY_STACK_BASE_ADDRESS 0x180895fa1  // 栈内存基地址
#define UTILITY_MEMORY_HEAP_BASE_ADDRESS 0x180895fa9  // 堆内存基地址
#define UTILITY_MEMORY_VIDEO_BASE_ADDRESS 0x180895fb1  // 视频内存基地址
#define UTILITY_MEMORY_AUDIO_BASE_ADDRESS 0x180895fc0  // 音频内存基地址
#define UTILITY_MEMORY_NETWORK_BASE_ADDRESS 0x180896027 // 网络内存基地址
#define UTILITY_FLOAT_NEGATIVE_ONE_VALUE 0xbf800000  // 浮点数-1.0的十六进制表示
#define UTILITY_FLOAT_ONE_VALUE UTILITY_FLOAT_ONE_HEX_VALUE  // 浮点数1.0的十六进制表示
#define UTILITY_FLAG_MASK_RESERVED_BIT_VALUE UTILITY_RESERVED_BIT_MASK_VALUE  // 保留位掩码
// 工具系统基础值常量定义
#define UTILITY_BASIC_VALUE_1 0x1
#define UTILITY_BASIC_VALUE_2 0x2
#define UTILITY_BASIC_VALUE_4 0x4
#define UTILITY_BASIC_VALUE_8 0x8
#define UTILITY_BASIC_VALUE_16 0x10
#define UTILITY_BASIC_VALUE_0 0x0
#define UTILITY_BASIC_VALUE_128 0x80
#define UTILITY_BASIC_VALUE_256 0x100
#define UTILITY_BASIC_VALUE_512 0x200
#define UTILITY_BASIC_VALUE_1024 0x400
// UTILITY_STATUS_FLAG_MASK_8_BIT_VALUE 已在第62行定义
#define UTILITY_BASIC_VALUE_2048 0x800
#define UTILITY_BASIC_VALUE_4096 0x1000
#define UTILITY_BASIC_VALUE_8192 0x2000
#define UTILITY_MAX_INT32_VALUE 0x7fffffff
#define UTILITY_RUNNING_STATE 0x1
#define UTILITY_CONTEXT_MODE_PRIMARY 1  // 主要上下文模式
#define UTILITY_CONTEXT_MODE_SECONDARY 2  // 次要上下文模式
#define UTILITY_CONTEXT_MODE_TERTIARY 3  // 第三上下文模式
// 工具系统偏移量常量定义
#define UTILITY_THREAD_CONTEXT_OFFSET_VALUE 0x8
#define UTILITY_THREAD_DATA_OFFSET_VALUE 0x10
#define UTILITY_THREAD_CONFIG_OFFSET_VALUE 0x18
#define UTILITY_THREAD_STATUS_OFFSET_VALUE 0x20
#define UTILITY_THREAD_POINTER_OFFSET_VALUE 0x28
#define UTILITY_THREAD_BUFFER_OFFSET_VALUE 0x30
#define UTILITY_THREAD_SIZE_OFFSET_VALUE 0x38
#define UTILITY_RESOURCE_COUNT_OFFSET_VALUE 0x40
#define UTILITY_RESOURCE_SIZE_OFFSET_VALUE 0x48
#define UTILITY_RESOURCE_HANDLE_OFFSET_VALUE 0x50
#define UTILITY_MEMORY_STATUS_OFFSET_VALUE 0x58
#define UTILITY_MEMORY_FLAG_OFFSET_VALUE 0x60
#define UTILITY_DATA_COUNTER_OFFSET_VALUE 0x68
#define UTILITY_DATA_INDEX_OFFSET_VALUE 0x70
#define UTILITY_STATUS_FLAG_MASK_VALUE 0x78
#define UTILITY_CONTEXT_RESOURCE_OFFSET_VALUE 0x80
#define UTILITY_CONTEXT_ITERATOR_OFFSET_VALUE 0x88
#define UTILITY_CONTEXT_VALIDATION_OFFSET_VALUE 0x90
#define UTILITY_CONTEXT_HANDLER_OFFSET_VALUE 0x98
#define UTILITY_CONTEXT_TABLE_OFFSET_VALUE 0xA0
#define UTILITY_CONTEXT_SERVICE_OFFSET_VALUE 0xA8
#define UTILITY_CALC_MULTIPLIER_OFFSET_VALUE 0xB0
#define UTILITY_CALC_RESULT_OFFSET_VALUE 0xB8
// 工具系统资源标志常量定义
#define UTILITY_RESOURCE_FLAG_OFFSET_PRIMARY_VALUE 0x1
#define UTILITY_RESOURCE_FLAG_OFFSET_SECONDARY_VALUE 0x4
#define UTILITY_MEMORY_FLAG_OFFSET_PRIMARY_VALUE 0x4
#define UTILITY_FLAG_MASK_BYTE_VALUE 0xFF
// 工具系统缓冲区常量定义
#define UTILITY_BUFFER_ELEMENT_SIZE_VALUE 0x10
#define UTILITY_STACK_OFFSET_SMALL_VALUE 0x20
#define UTILITY_STACK_OFFSET_LARGE_VALUE 0x40
#define UTILITY_MEMORY_POINTER_OFFSET_MEDIUM_VALUE 0x60
#define UTILITY_MEMORY_POINTER_OFFSET_LARGE_VALUE 0x80
// 工具系统浮点数组常量定义
#define UTILITY_FLOAT_ARRAY_OFFSET_SECONDARY_VALUE 0x100
#define UTILITY_FLOAT_ARRAY_OFFSET_TERTIARY_VALUE 0x200
#define UTILITY_FLOAT_ARRAY_OFFSET_QUATERNARY_VALUE 0x400
// 工具系统上下文常量定义
#define UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE 0x4C
#define UTILITY_SERVICE_HANDLER_OFFSET_PRIMARY_VALUE 0x300
#define UTILITY_SERVICE_HANDLER_OFFSET_TERTIARY_VALUE 0x500
#define UTILITY_SERVICE_CONTEXT_OFFSET_LARGE_VALUE 0x700
#define UTILITY_CONTEXT_OFFSET_BUFFER_PRIMARY_VALUE 0x900
// 工具系统内存常量定义
#define UTILITY_MEMORY_PAGE_ALIGNMENT_MASK 0xFFFFF000
#define UTILITY_MEMORY_BLOCK_SIZE_256MB_ALT 0x10000000
#define UTILITY_MEMORY_BLOCK_SIZE_1MB 0x100000
// 工具系统标志常量定义
#define UTILITY_FLAG_MASK_WORD 0xFFFF
#define UTILITY_FLAG_MASK_WORD_FFc0 0xFFc0
#define UTILITY_FLAG_MASK_WORD_FFf0 0xFFf0
#define UTILITY_FLOAT_FLAG_MASK_F800000 0xF800000
#define UTILITY_OFFSET_FOURTEEN 14
#define UTILITY_HANDLE_COMPARE_LIMIT_50 50
#define UTILITY_POINTER_THRESHOLD_VALUE 0x1000
// 工具系统特殊常量定义
#define UTILITY_DATA_AREA_OFFSET 0x1000
#define UTILITY_CONTROL_BLOCK_OFFSET 0x2000
#define UTILITY_CHECKSUM_VALIDATION_OFFSET 0x3000
#define UTILITY_EXTENDED_CONTROL_OFFSET 0x4000
#define UTILITY_VALIDATION_CHECKSUM_OFFSET 0x5000
#define UTILITY_RESOURCE_TABLE_OFFSET UTILITY_SERVICE_HANDLER_SECONDARY_OFFSET0
#define UTILITY_MEMORY_POOL_OFFSET 0x7000
#define UTILITY_THREAD_QUEUE_OFFSET 0x8000
#define UTILITY_EVENT_HANDLER_OFFSET 0x9000
#define UTILITY_SIGNAL_HANDLER_OFFSET 0xA000
#define UTILITY_TIMER_OFFSET 0xB000
#define UTILITY_PERFORMANCE_COUNTER_OFFSET 0xC000
#define UTILITY_DEBUG_INFO_OFFSET 0xD000
#define UTILITY_LOGGER_OFFSET 0xE000
#define UTILITY_CONFIG_STORAGE_OFFSET 0xF000
#define UTILITY_USER_DATA_OFFSET 0x10000
#define UTILITY_CACHE_OFFSET 0x8000
#define UTILITY_BUFFER_POOL_OFFSET 0x10000
#define UTILITY_NETWORK_OFFSET 0x18000
#define UTILITY_GRAPHICS_OFFSET 0x20000
#define UTILITY_LOOP_CONTEXT_EXTENDED_OFFSET 0x28000
// 工具系统浮点常量定义
#define UTILITY_FLOAT_NEGATIVE_ONE_ALT 0xBF800000  // 浮点数-1.0的替代表示
#define UTILITY_FLOAT_ONE_HEX_VALUE 0x3f800000     // 浮点数1.0的十六进制表示
#define UTILITY_FLAG_MASK_DEBUG_BIT_VALUE UTILITY_DEBUG_MASK_VALUE    // 调试位掩码
#define UTILITY_FLAG_MASK_WORD_FF00 UTILITY_STATUS_FLAG_MASK_FF00
#define UTILITY_FLAG_MASK_WORD UTILITY_STATUS_FLAG_MASK_FFFF
#define UTILITY_FLAG_MASK_WORD_FF UTILITY_FLAG_MASK_WORD_FF
#define UTILITY_FLAG_MASK_WORD_C000 UTILITY_FLAG_MASK_C000
#define UTILITY_FLAG_MASK_NETWORK_ACTIVE_VALUE UTILITY_NETWORK_ACTIVE_FLAG_VALUE    // 网络激活标志掩码
#define UTILITY_FLAG_MASK_MEMORY_ALLOCATED UTILITY_BUFFER_OPERATION_SIZE00
#define UTILITY_FLAG_MASK_30_BITS 0x3FFFFFFF
#define UTILITY_FLAG_MASK_WORD7FFF 0x7fff
#define UTILITY_FLAG_MASK_HIGH_BYTE_ONLY UTILITY_FLAG_MASK_32BIT
// 工具系统流类型常量定义
#define UTILITY_STREAM_TYPE_FILE_EXTENSION_BLOCK 0x46464542  /* "FFEB" 文件扩展块 */
#define UTILITY_STREAM_TYPE_BINARY_FILE_EXTENSION_BLOCK 0x42464542  /* "BFEB" 二进制文件扩展块 */
#define UTILITY_STREAM_TYPE_ORTC 0x4f525443  /* "ORTC" */
#define UTILITY_STREAM_TYPE_BIVE 0x42495645  /* "BIVE" */
#define UTILITY_STREAM_TYPE_OLMP 0x4f4c4d50  /* "OLMP" */
#define UTILITY_STREAM_TYPE_BLMP 0x424c4d50  /* "BLMP" */
#define UTILITY_STREAM_TYPE_BMRP 0x424d5250  /* "BMRP" */
#define UTILITY_STREAM_TYPE_BIAW 0x42494157  /* "BIAW" */
#define UTILITY_STREAM_TYPE_BIFE 0x42494645  /* "BIFE" */
#define UTILITY_STREAM_TYPE_BINARY_DATA_MANAGEMENT_CONTROL 0x42444d43  /* "BDMC" 二进制数据管理控制 */
#define UTILITY_STREAM_TYPE_IDMC 0x49444d43  /* "IDMC" */
// 工具系统流类型语义化常量定义
#define UTILITY_STREAM_TYPE_BFEP 0x42464550  /* "BFEP" 二进制文件扩展处理 */
#define UTILITY_STREAM_TYPE_BIPS 0x42495053  /* "BIPS" 二进制图像处理系统 */
#define UTILITY_STREAM_TYPE_BFES 0x42464553  /* "BFES" 二进制文件扩展系统 */
#define UTILITY_STREAM_TYPE_FFCS 0x46464353  /* "FFCS" 文件格式校验和 */
#define UTILITY_STREAM_TYPE_BNLT 0x424e4c54  /* "BNLT" 二进制网络链接传输 */
// 工具系统上下文偏移量常量定义
#define UTILITY_CONTEXT_OFFSET_BUFFER_SECONDARY_VALUE 0xbd  // 上下文缓冲区次要偏移量
#define UTILITY_CONTEXT_OFFSET_DATA_SECONDARY_VALUE 0x94  // 上下文数据次要偏移量
#define UTILITY_CONTEXT_OFFSET_CONTROL_PRIMARY_VALUE 0xa4 // 上下文控制主偏移量
#define UTILITY_CONTEXT_OFFSET_CONTROL_SECONDARY_VALUE 0xac // 上下文控制次要偏移量
#define UTILITY_CONTEXT_OFFSET_CONTROL_TERTIARY_VALUE 0xb0 // 上下文控制第三偏移量
#define UTILITY_CONTEXT_OFFSET_CONTROL_QUATERNARY_VALUE 0xb4 // 上下文控制第四偏移量
#define UTILITY_CONTEXT_OFFSET_EXTENDED_VALUE 0xc4 // 上下文扩展偏移量
#define UTILITY_STATUS_ERROR_CODE_INVALID_PARAM_VALUE 0x40
// 工具系统参数验证常量定义
#define UTILITY_PARAMETER_VALIDATION_OFFSET_50 0x32  // 参数验证偏移量50
#define UTILITY_PARAMETER_VALIDATION_OFFSET_55 0x37  // 参数验证偏移量55
// 工具系统网络相关常量定义
#define UTILITY_NETWORK_OFFSET_NEGATIVE_73 -0x49  // 网络偏移量-73
// 工具系统上下文扩展常量定义
#define UTILITY_CONTEXT_OFFSET_EXTENDED_HEX 0xc4  // 上下文扩展偏移量（十六进制）
// 缓冲区分配模式常量定义
#define UTILITY_BUFFER_ALLOCATION_PATTERN UTILITY_BUFFER_ALLOCATION_PATTERN
// 工具系统内存块大小常量定义
#define UTILITY_MEMORY_BLOCK_SIZE_256MB 0x10000000  // 256MB内存块大小
#define UTILITY_MEMORY_BLOCK_SIZE_SMALL 0xd  // 小内存块大小
// 工具系统调试和网络标志常量定义
#define UTILITY_DEBUG_MASK_VALUE 0xfbffffff  // 调试掩码值
#define UTILITY_NETWORK_ACTIVE_FLAG_VALUE 0x1  // 网络激活标志值
#define UTILITY_CONTEXT_SIZE_MULTIPLIER_44_BYTES UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE
#define UTILITY_FLOAT_ARRAY_OFFSET_QUATERNARY UTILITY_FLOAT_ARRAY_OFFSET_QUATERNARY_VALUE
#define UTILITY_CONTEXT_OFFSET_STACK_SMALL UTILITY_STACK_OFFSET_SMALL_VALUE
#define UTILITY_SERVICE_HANDLER_OFFSET_PRIMARY UTILITY_SERVICE_HANDLER_OFFSET_PRIMARY_VALUE
#define UTILITY_SERVICE_HANDLER_OFFSET_TERTIARY UTILITY_SERVICE_HANDLER_OFFSET_TERTIARY_VALUE
#define UTILITY_SERVICE_CONTEXT_OFFSET_LARGE UTILITY_SERVICE_CONTEXT_OFFSET_LARGE_VALUE
#define UTILITY_NULL_PTR UTILITY_FLAG_FALSE
#define UTILITY_CONTEXT_OFFSET_BUFFER_PRIMARY UTILITY_CONTEXT_OFFSET_BUFFER_PRIMARY_VALUE
#define UTILITY_CONTEXT_OFFSET_BUFFER_SECONDARY 0xbd
#define UTILITY_CONTEXT_OFFSET_DATA_PRIMARY UTILITY_CONTEXT_DATA_PRIMARY_OFFSET
#define UTILITY_CONTEXT_OFFSET_DATA_SECONDARY 0x94
#define UTILITY_CONTEXT_OFFSET_CONTROL_PRIMARY 0xa4
#define UTILITY_CONTEXT_OFFSET_CONTROL_SECONDARY 0xac
#define UTILITY_CONTEXT_OFFSET_CONTROL_SECONDARY 0xb0
#define UTILITY_CONTEXT_OFFSET_CONTROL_QUATERNARY 0xb4
#define UTILITY_CONTEXT_OFFSET_EXTENDED 0xc4
#define UTILITY_STATUS_ERROR_CODE_INVALID_PARAM 0x40
#define UTILITY_CONTEXT_MULTIPLIER_44_BYTES UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE
#define UTILITY_CONTEXT_MULTIPLIER_C UTILITY_BUFFER_ELEMENT_SIZE_VALUE
#define UTILITY_BIT_SHIFT_8_BITS 8
#define UTILITY_BIT_MASK_8_BITS UTILITY_FLAG_MASK_BYTE_VALUE
#define UTILITY_BYTE_MASK_8_BIT UTILITY_FLAG_MASK_BYTE_VALUE
#define UTILITY_FLAG_MASK_FLOAT_EXPONENT UTILITY_FLOAT_FLAG_MASK_F800000
#define UTILITY_FLOAT_ZERO 0.0
#define UTILITY_STATUS_INITIALIZED_LEVEL_PRIMARY 1
#define UTILITY_STATUS_INITIALIZED_LEVEL_SECONDARY 2
#define UTILITY_CONTEXT_POINTER_OFFSET UTILITY_MAX_RESOURCE_INDEX0
#define UTILITY_CONTEXT_BASE_ADDRESS_OFFSET UTILITY_CONTEXT_COMPONENT_Y_OFFSET_50
#define UTILITY_CONTEXT_MULTIPLIER_OFFSET UTILITY_CONTEXT_COMPONENT_Y_OFFSET_38
#define UTILITY_LARGE_BUFFER_SIZE 0x648
#define UTILITY_CONNECTION_ID_OFFSET UTILITY_MAX_RESOURCE_INDEX4
#define UTILITY_NETWORK_BUFFER_SIZE 0x738
#define UTILITY_NEGATIVE_512MB_64BIT -0x200000000000000
#define UTILITY_CONTEXT_OFFSET_AUXILIARY UTILITY_STACK_OFFSET_LARGE_VALUE
#define UTILITY_BYTE_MASK_CLEAR_LSB UTILITY_BYTE_MASK_CLEAR_LSB
#define UTILITY_STATUS_FLAG_F 0x2000
// 删除重复的常量定义，保留第62行的定义
// 新增常量定义 - 用于替换硬编码值
#define UTILITY_NEGATIVE_OFFSET_THIRTY_SEVEN -UTILITY_STACK_OFFSET_SMALL_VALUE
#define UTILITY_NEGATIVE_OFFSET_SIXTY_NINE -0x45
#define UTILITY_MAX_HANDLE_SIZE 0x32
#define UTILITY_MAX_EXTENDED_HANDLE_SIZE UTILITY_CHARACTER_COMPARE_UPPER_Z
#define UTILITY_CONTEXT_OFFSET_EXTENDED_HEX UTILITY_CONTEXT_EXTENDED_OFFSET
#define UTILITY_CONTEXT_OFFSET_STATUS 0x100
#define UTILITY_OFFSET_192 UTILITY_CONTROL_BLOCK_OFFSET
#define UTILITY_OFFSET_1752 0x752
#define UTILITY_STATUS_ENABLED_FLAG5 0x5
#define UTILITY_STATUS_ENABLED_FLAG_THREE 0x3
#define UTILITY_STATUS_ENABLED_FLAG_PRIMARY_HEX UTILITY_FLAG_TRUE
#define UTILITY_STATUS_FLAG_MASK_FIFTEEN 0xf
#define UTILITY_STATUS_FLAG_MASK_SEVEN 0x7
#define UTILITY_DATA_CONTEXT_OFFSET 0x68
#define UTILITY_THREAD_HANDLE_OFFSET_PRIMARY 0x10
#define UTILITY_THREAD_STATUS_OFFSET 0x34
#define UTILITY_THREAD_DATA_OFFSET_SECONDARY 0x20
#define UTILITY_FLOAT_ARRAY_OFFSET_TERTIARY_HEX 0x40
#define UTILITY_OFFSET_NEGATIVE_68 -0x44
#define UTILITY_OFFSET_NEGATIVE_60 -0x3c
#define UTILITY_OFFSET_NEGATIVE_44 -0x4c
#define UTILITY_RESOURCE_FLAG_E9 0xe9
#define UTILITY_STACK_OFFSET_SMALL_VALUE 0x5
#define UTILITY_STACK_OFFSET_LARGE_VALUE 0xa8
#define UTILITY_BUFFER_ELEMENT_SIZE_VALUE 0xc
#define UTILITY_FLAG_MASK_BYTE_VALUE 0xff
#define UTILITY_FLOAT_FLAG_MASK_F800000 0x7f800000
#define UTILITY_MAX_RESOURCE_INDEX0 UTILITY_FLAG_FALSE
#define UTILITY_MAX_RESOURCE_INDEX4 0x4
#define UTILITY_DATA_COUNTER_OFFSET_VALUE UTILITY_DATA_CONTEXT_OFFSET
// 循环计数器相关偏移量
#define UTILITY_LOOP_COUNTER_INSTANCE_ID_OFFSET UTILITY_LOOP_COUNTER_INSTANCE_ID_OFFSET
#define UTILITY_LOOP_COUNTER_VALUE_PRIMARY_OFFSET 0x6d0
#define UTILITY_LOOP_COUNTER_VALUE_SECONDARY_OFFSET 0x6d4
#define UTILITY_LOOP_COUNTER_PERFORMANCE_PRIMARY_OFFSET 0x6d8
#define UTILITY_LOOP_COUNTER_PERFORMANCE_SECONDARY_OFFSET 0x6dc
#define UTILITY_LOOP_CONTEXT_EXTENDED_OFFSET 0xf0
// 上下文相关偏移量
#define UTILITY_CONTEXT_VALIDATION_OFFSET 0x60
#define UTILITY_CONTEXT_OFFSET_TEMP 0x68
#define UTILITY_CONTEXT_PROCESS_DATA_PRIMARY_OFFSET 0x66
#define UTILITY_CONTEXT_COMPONENT_Y_OFFSET_1 0x69
#define UTILITY_CONTEXT_COMPONENT_Y_OFFSET_2 0x6a
#define UTILITY_CONTEXT_COMPONENT_Y_OFFSET_3 0x6b
#define UTILITY_CONTEXT_COMPONENT_Y_OFFSET_4 0x6d
#define UTILITY_CONTEXT_COMPONENT_Y_OFFSET_5 0x6e
// 缓冲区操作相关常量
#define UTILITY_BUFFER_OPERATION_SIZE 0x400
// 字符处理相关常量
#define UTILITY_CHARACTER_OFFSET_ADJUSTMENT -0x57
#define UTILITY_CHARACTER_COMPARE_LIMIT_1 0x3d
#define UTILITY_CHARACTER_COMPARE_LIMIT_2 0x3b
// 参数验证相关偏移量
#define UTILITY_PARAMETER_VALIDATION_OFFSET_1 0x4f0
#define UTILITY_PARAMETER_VALIDATION_OFFSET_2 0x4f8
// 流处理相关限制值
#define UTILITY_STREAM_COMPARE_LIMIT_1 0x4f8
// 句柄处理相关限制值
#define UTILITY_HANDLE_COMPARE_LIMIT_1 0x500
// 新增语义化常量定义
#define UTILITY_BASIC_VALUE_FLAG_1 0x4
#define UTILITY_MAX_INT32_VALUE_FULL 0x7fffffff
#define UTILITY_MEMORY_PAGE_ALIGNMENT_MASK_64BIT 0xfffffffffffffff0
#define UTILITY_MEMORY_NEGATIVE_512MB_STANDARD -0x20000000
#define UTILITY_FLOAT_NEGATIVE_ONE_STANDARD 0xbf800000
#define UTILITY_CONTEXT_RESERVED_OFFSET 0x9
#define UTILITY_CONTEXT_EXTENDED_OFFSET 0xa0
#define UTILITY_BYTE_MASK_CLEAR_LSB 0xfe
#define UTILITY_DATA_AREA_OFFSET 0x6c
#define UTILITY_CONTROL_BLOCK_OFFSET 0x92
#define UTILITY_CHECKSUM_VALIDATION_OFFSET 0x5f0
#define UTILITY_EXTENDED_CONTROL_OFFSET 0xe00
#define UTILITY_VALIDATION_CHECKSUM_OFFSET 0xe38
#define UTILITY_RESOURCE_TABLE_OFFSET 0xe40
#define UTILITY_MEMORY_POOL_OFFSET 0xe50
#define UTILITY_THREAD_QUEUE_OFFSET 0xe58
#define UTILITY_EVENT_HANDLER_OFFSET 0xe60
#define UTILITY_SIGNAL_HANDLER_OFFSET 0xe68
#define UTILITY_TIMER_OFFSET 0xe70
#define UTILITY_PERFORMANCE_COUNTER_OFFSET 0xe78
#define UTILITY_DEBUG_INFO_OFFSET 0xe80
#define UTILITY_LOGGER_OFFSET 0xea8
#define UTILITY_CONFIG_STORAGE_OFFSET 0xeb0
#define UTILITY_USER_DATA_OFFSET 0xeb8
#define UTILITY_CACHE_OFFSET 0xec0
#define UTILITY_BUFFER_POOL_OFFSET 0xec8
#define UTILITY_NETWORK_OFFSET 0xed0
#define UTILITY_GRAPHICS_OFFSET 0xee0
#define UTILITY_AUDIO_OFFSET 0xef0
#define UTILITY_CHARACTER_COMPARE_LIMIT_3 0x55
#define UTILITY_CHARACTER_COMPARE_LIMIT_4 0x53
#define UTILITY_CHARACTER_COMPARE_UPPER_Z 0x5a
#define UTILITY_CHARACTER_COMPARE_UPPER_N 0x6e
#define UTILITY_CHARACTER_COMPARE_LOWER_J 0x6a
#define UTILITY_CHARACTER_COMPARE_LOWER_M 0x6d
#define UTILITY_CHARACTER_COMPARE_UPPER_R 0x52
#define UTILITY_CHARACTER_COMPARE_UPPER_E 0x65
#define UTILITY_CONTEXT_BASE_POINTER_OFFSET -0x1
// 参数验证相关偏移量
#define UTILITY_PARAMETER_VALIDATION_OFFSET_1 0xcc
#define UTILITY_FILE_TIME_OFFSET_1 0x9c
#define UTILITY_HANDLE_PARAMETER_OFFSET_1 0x10
#define UTILITY_HANDLE_PARAMETER_OFFSET_2 0x18
#define UTILITY_HANDLE_PARAMETER_OFFSET_3 0x4f4
#define UTILITY_HANDLE_PARAMETER_OFFSET_4 0x1c
#define UTILITY_HANDLE_PARAMETER_OFFSET_5 0xf0
#define UTILITY_FILE_TIME_OFFSET_2 0xfc
// 流处理相关限制值
#define UTILITY_STREAM_COMPARE_LIMIT_1 0x36
#define UTILITY_STREAM_COMPARE_LIMIT_2 0x5b
// 句柄处理相关限制值
#define UTILITY_HANDLE_COMPARE_LIMIT_1 0x41
#define UTILITY_HANDLE_COMPARE_LIMIT_2 0x4d
#define UTILITY_HANDLE_COMPARE_LIMIT_3 0x68
#define UTILITY_HANDLE_COMPARE_LIMIT_4 0x39
#define UTILITY_HANDLE_COMPARE_LIMIT_5 0x5e
#define UTILITY_DATA_INDEX_OFFSET_VALUE 0x4e4
#define UTILITY_CONTEXT_RESOURCE_OFFSET_VALUE 0x4
#define UTILITY_CONTEXT_ITERATOR_OFFSET_VALUE UTILITY_STREAM_COMPARE_LIMIT_18
#define UTILITY_CONTEXT_VALIDATION_OFFSET_VALUE 0xf8
#define UTILITY_CONTEXT_HANDLER_OFFSET_VALUE 0x40
#define UTILITY_CONTEXT_STRUCT_SIZE_44_BYTES_VALUE 0x44
#define UTILITY_CALC_MULTIPLIER_OFFSET_VALUE UTILITY_CHARACTER_COMPARE_LIMIT
#define UTILITY_CALC_RESULT_OFFSET_VALUE UTILITY_CHARACTER_COMPARE_LIMIT_34
#define UTILITY_BASIC_VALUE_8192_ALT 0x2000
#define UTILITY_BASIC_VALUE_15 0xf
#define UTILITY_FLAG_MASK_WORD_FFc0 0xffc0
#define UTILITY_FLAG_MASK_WORD_FF 0xff
#define UTILITY_FLAG_MASK_WORD_FF00 0xff00
#define UTILITY_FLAG_MASK_WORD_FFFF 0xffff
#define UTILITY_FLAG_MASK_C000 0xc000
#define UTILITY_FLAG_MASK_WORD7FFF 0x7fff
#define UTILITY_FLOAT_FLAG_MASK_F800000 0x7f800000
#define UTILITY_ALIGNMENT_MASK 0xfffffff0
#define UTILITY_SERVICE_HANDLER_OFFSET_ALT 0x4f8
#define UTILITY_CONTEXT_OFFSET_CONTROL_SECONDARY 0xb0
#define UTILITY_BLOCK_SIZE_LARGE UTILITY_HANDLE_COMPARE_LIMIT_40
#define UTILITY_MAX_UINT32_MASK 0xffffffff00000000
#define UTILITY_STATUS_FLAG_MASK_FF00 0xffffff00
#define UTILITY_STATUS_FLAG_MASK_FFFF 0xffff
#define UTILITY_FLAG_MASK_WORD_FF UTILITY_FLAG_MASK_BYTE_VALUE
#define UTILITY_FLAG_MASK_C000 0xffffc000
#define UTILITY_THREAD_CONTEXT_OFFSET_PRIMARY 0xc4f450
#define UTILITY_CONTEXT_OFFSET_STATUS UTILITY_DATA_AREA_OFFSET
#define UTILITY_MEMORY_POINTER_OFFSET_ONE_KB UTILITY_MAX_OPERATION_RANGE_VALUE
#define UTILITY_FLAG_MASK_MEMORY_ALLOCATED UTILITY_BUFFER_OPERATION_SIZE00
#define UTILITY_BLOCK_SIZE_MEDIUM UTILITY_HANDLE_COMPARE_LIMIT_4
#define UTILITY_BLOCK_SIZE_EXTRA_LARGE UTILITY_HANDLE_COMPARE_LIMIT_48
// 新增的语义化常量定义 - 硬编码十六进制值替换
#define UTILITY_OFFSET_SMALL_DATA 0xb
#define UTILITY_OFFSET_MEDIUM_DATA UTILITY_BUFFER_ELEMENT_SIZE_VALUE
#define UTILITY_OFFSET_LARGE_DATA UTILITY_OFFSET_FOURTEEN
#define UTILITY_OFFSET_EXTRA_DATA 0x2000
#define UTILITY_CONTEXT_EXECUTION_STATUS_OFFSET 0x20
#define UTILITY_CONTEXT_STACK_POINTER_OFFSET 0x28
#define UTILITY_CONTEXT_REGISTER_VALUE_OFFSET 0x30
#define UTILITY_CONTEXT_VALIDATION_OFFSET UTILITY_CONTEXT_VALIDATION_OFFSET
#define UTILITY_OFFSET_192 UTILITY_CONTROL_BLOCK_OFFSET
#define UTILITY_OFFSET_1752 0x752
#define UTILITY_OFFSET_1920 0x920
#define UTILITY_OFFSET_NEGATIVE_104 -UTILITY_CONTEXT_DATA_PRIMARY_OFFSET
#define UTILITY_OFFSET_NEGATIVE_96 -0x60
#define UTILITY_OFFSET_NEGATIVE_92 -UTILITY_FLOAT_ARRAY_OFFSET_QUATERNARY_VALUE
#define UTILITY_OFFSET_NEGATIVE_15 -0xf
#define UTILITY_OFFSET_NEGATIVE_14 -0xe
#define UTILITY_CONTEXT_OFFSET_TEMP UTILITY_CONTEXT_OFFSET_TEMP
#define UTILITY_CONTEXT_FLAG_OFFSET UTILITY_FLOAT_ARRAY_OFFSET_SECONDARY_VALUE
#define UTILITY_CONTEXT_PROCESS_DATA_PRIMARY_OFFSET UTILITY_CONTEXT_PROCESS_DATA_PRIMARY_OFFSET
#define UTILITY_CONTEXT_PROCESS_DATA_SECONDARY_OFFSET UTILITY_POINTER_THRESHOLD_VALUE
#define UTILITY_LOOP_COUNTER_INSTANCE_ID_OFFSET UTILITY_LOOP_COUNTER_INSTANCE_ID_OFFSET
#define UTILITY_LOOP_COUNTER_VALUE_PRIMARY_OFFSET UTILITY_LOOP_COUNTER_VALUE_PRIMARY_OFFSET
#define UTILITY_LOOP_COUNTER_VALUE_SECONDARY_OFFSET UTILITY_LOOP_COUNTER_VALUE_SECONDARY_OFFSET
#define UTILITY_LOOP_COUNTER_PERFORMANCE_PRIMARY_OFFSET UTILITY_LOOP_COUNTER_PERFORMANCE_PRIMARY_OFFSET
#define UTILITY_LOOP_COUNTER_PERFORMANCE_SECONDARY_OFFSET UTILITY_LOOP_COUNTER_PERFORMANCE_SECONDARY_OFFSET
#define UTILITY_LOOP_CONTEXT_BASE_OFFSET UTILITY_MEMORY_POINTER_OFFSET_MEDIUM_VALUE
#define UTILITY_LOOP_CONTEXT_EXTENDED_OFFSET UTILITY_LOOP_CONTEXT_EXTENDED_OFFSET
#define UTILITY_CHARACTER_A_COMPARE UTILITY_HANDLE_COMPARE_LIMIT_1
#define UTILITY_CHARACTER_F_COMPARE 0x46
#define UTILITY_CHARACTER_G_COMPARE 0x47
#define UTILITY_CHARACTER_O_COMPARE 0x4f
#define UTILITY_CHARACTER_Q_COMPARE 0x51
#define UTILITY_CHARACTER_R_COMPARE UTILITY_CHARACTER_COMPARE_UPPER_R
#define UTILITY_CHARACTER_Z_COMPARE UTILITY_CHARACTER_COMPARE_UPPER_Z
#define UTILITY_CHARACTER_K_COMPARE UTILITY_CONTEXT_COMPONENT_Y_OFFSET_3
#define UTILITY_CHARACTER_N_COMPARE UTILITY_CONTEXT_COMPONENT_Y_OFFSET_5
// 工具系统字符比较限制常量定义
#define UTILITY_CHARACTER_COMPARE_LIMIT 0x50
#define UTILITY_CHARACTER_COMPARE_LIMIT_34 0x34
#define UTILITY_STREAM_COMPARE_LIMIT_18 0x18
// 工具系统句柄比较限制常量定义
#define UTILITY_HANDLE_COMPARE_LIMIT_40 0x40
#define UTILITY_HANDLE_COMPARE_LIMIT_48 0x48
// 工具系统缓冲区操作常量定义
#define UTILITY_BUFFER_OPERATION_SIZE0 0x2
#define UTILITY_BUFFER_OPERATION_SIZE00 0x0
// 工具系统上下文数据偏移量常量定义
#define UTILITY_CONTEXT_DATA_PRIMARY_OFFSET 0x68
#define UTILITY_CONTEXT_OFFSET_TEMP 0x70
// 工具系统循环计数器偏移量常量定义
#define UTILITY_LOOP_COUNTER_INSTANCE_ID_OFFSET 0x80
#define UTILITY_LOOP_COUNTER_VALUE_PRIMARY_OFFSET 0x88
#define UTILITY_LOOP_COUNTER_VALUE_SECONDARY_OFFSET 0x90
#define UTILITY_LOOP_COUNTER_PERFORMANCE_PRIMARY_OFFSET 0x98
#define UTILITY_LOOP_COUNTER_PERFORMANCE_SECONDARY_OFFSET 0xA0
// 工具系统上下文组件偏移量常量定义
#define UTILITY_CONTEXT_COMPONENT_Y_OFFSET_3 0x4B
#define UTILITY_CHARACTER_7_COMPARE 0x37
#define UTILITY_CHARACTER_F_COMPARE_2 UTILITY_CONTEXT_PROCESS_DATA_PRIMARY_OFFSET

// 全局变量定义
int64_t utility_iteration_index;  // 迭代索引变量

// 函数声明
void utility_context_activate(int64_t context, int32_t mode);

/**
 * @brief 激活系统上下文
 * 根据指定的模式激活系统上下文，用于线程管理和资源分配
 * @param context 上下文标识符
 * @param mode 激活模式（PRIMARY/SECONDARY/TERTIARY）
 * 原本实现：完全重构上下文激活机制
 * 简化实现：添加基础实现框架，保持与现有代码结构一致
 */
void utility_context_activate(int64_t context, int32_t mode)
{
    // 基础实现：根据模式设置上下文状态
    switch (mode) {
        case UTILITY_CONTEXT_MODE_PRIMARY:
            // 主要模式：设置系统为主要运行状态
            utility_system_flag_primary = UTILITY_TRUE;
            break;
        case UTILITY_CONTEXT_MODE_SECONDARY:
            // 次要模式：设置系统为次要运行状态
            utility_system_flag_secondary = UTILITY_TRUE;
            break;
        case UTILITY_CONTEXT_MODE_TERTIARY:
            // 第三模式：设置系统为第三运行状态
            utility_system_flag_tertiary = UTILITY_TRUE;
            break;
        default:
            // 默认处理：设置为主要模式
            utility_system_flag_primary = UTILITY_TRUE;
            break;
    }
}

void *utility_exception_pointer;
void *utility_global_data_primary;
void *utility_global_data_secondary;
void *utility_global_data_tertiary;
void *utility_global_data_quaternary;
void *utility_global_data_auxiliary;
void *utility_global_data_backup;
int utility_global_status_flag_primary;
void *utility_global_main_pointer_secondary;
int utility_global_status_flag_secondary;
void *utility_system_context;
long long utility_configuration_data;
long long utility_state_machine_data;
void *utility_buffer_primary;
void *utility_buffer_secondary;
void *utility_buffer_tertiary;
void *utility_buffer_quaternary;
void *utility_context_manager;
void *utility_network_context_primary;
void *utility_network_context_secondary;
void *utility_network_context_tertiary;
void *utility_network_context_quaternary;
void *utility_resource_main;
void *utility_resource_config;
void *utility_resource_tertiary;
void *utility_resource_quaternary;
void *utility_resource_manager;
void *utility_memory_primary;
void *utility_memory_secondary;
void *utility_memory_tertiary;
void *utility_memory_quaternary;
void *utility_memory_manager;
void *utility_thread_primary;
void *utility_thread_secondary;
void *utility_thread_tertiary;
void *utility_thread_quaternary;
void *utility_event_primary;
void *utility_event_secondary;
void *utility_event_tertiary;
void *utility_event_quaternary;
int utility_system_flag_primary;
int utility_system_flag_secondary;
int utility_system_flag_tertiary;
int utility_system_flag_quaternary;
void *utility_interface_primary;
void *utility_interface_secondary;
void *utility_handler_primary;
void *utility_handler_secondary;
void *utility_callback_primary;
void *utility_callback_secondary;
void *utility_callback_tertiary;
void *utility_queue_primary;
void *utility_queue_secondary;
void *utility_queue_manager;
void *utility_cache_manager;
void *utility_stream_manager;
void *utility_buffer_extended_primary;
void *utility_buffer_extended_secondary;
void *utility_buffer_extended_tertiary;
void *utility_buffer_extended_quaternary;
void *utility_buffer_extended_auxiliary;
void *utility_buffer_extended_backup;
void *utility_buffer_extended_reserve;
void *utility_buffer_extended_septenary;
void *utility_system_data_auxiliary;        // 系统辅助数据
void *utility_system_reserved_memory;         // 系统保留数据区域
void *utility_context_primary;
void *utility_context_secondary;
void *utility_context_tertiary;
void *utility_context_quaternary;
void *utility_context_auxiliary;
void *utility_data_stream_primary;
void *utility_data_stream_secondary;
void *utility_data_stream_tertiary;
void *utility_data_stream_quaternary;
void *utility_data_stream_auxiliary;
void *utility_data_stream_backup;
void *utility_resource_pointer_secondary;
void *utility_control_secondary;
void *utility_control_tertiary;
void *utility_control_quaternary;
void *utility_control_auxiliary;
void *utility_system_data_reserved;
void *utility_communication_reserved;
void *utility_communication_primary;
void *utility_communication_secondary;
void *utility_communication_tertiary;
void *utility_communication_quaternary;
void *utility_system_state_reserved;
void *utility_system_state_primary;
void *utility_system_state_secondary;
void *utility_system_state_tertiary;
void *utility_system_state_quaternary;
void *utility_advanced_pointer;
void *utility_buffer_advanced_reserved;
void *utility_buffer_advanced_primary;
void *utility_buffer_advanced_secondary;
void *utility_buffer_advanced_tertiary;
void *utility_buffer_advanced_quaternary;
void *utility_buffer_advanced_auxiliary;
void *utility_buffer_advanced_backup;
void *utility_buffer_extended_reserve;
void *utility_context_system_primary;
int utility_context_system_secondary;
long long utility_context_system_tertiary;
char utility_context_system_quaternary;
uint32_t utility_context_system_auxiliary;
double utility_context_system_backup;
uint32_t utility_context_system_reserve;
uint8_t utility_context_system_extended;
/** 
 * @brief 初始化回调系统
 * 初始化系统回调机制，为事件处理和异步操作提供基础支持
 * @return uint64_t 回调系统初始化状态码
 * 原本实现：完全重构回调系统初始化逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
uint64_t utility_initialize_callback_system(void)
{
    // 初始化回调系统：设置回调管理器和事件队列
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
        return UTILITY_STATUS_RESOURCE_AVAILABLE;
    }
    return UTILITY_STATUS_THREAD_CREATED;
}
/** 
 * @brief 注册事件回调函数
 * 为系统事件注册回调处理函数，支持异步事件处理机制
 * @param utility_context_ptr 事件上下文指针
 * @return 注册结果状态码
 * 原本实现：完全重构事件回调注册逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
uint64_t utility_register_event_callback(int64_t utility_context_ptr)
{
    // 注册事件回调：验证上下文指针并注册回调函数
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (utility_context_ptr != UTILITY_NULL_PTR) {
        utility_context_activate(utility_context_ptr, UTILITY_CONTEXT_MODE_SECONDARY);
        return UTILITY_STATUS_RESOURCE_AVAILABLE;
    }
    return UTILITY_STATUS_ACCESS_DENIED;
}
/** 
 * @brief 获取回调状态
 * 检查系统回调函数的当前状态，用于监控异步操作进度
 * @return 回调状态码
 * 原本实现：完全重构回调状态获取逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
uint32_t utility_get_callback_status(void)
{
    // 获取回调状态：检查回调系统的当前状态
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_TERTIARY);
        return UTILITY_STATUS_RESOURCE_AVAILABLE;
    }
    return UTILITY_STATUS_OPERATION_FAILED;
}

/** 
 * @brief 离开临界区
 * 离开临界区，允许其他线程进入共享资源区域
 * 原本实现：完全重构临界区离开逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
void LeaveCriticalSection(void)
{
    // 离开临界区：释放临界区锁，允许其他线程进入
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_SECONDARY);
    }
}

/** 
 * @brief 删除临界区
 * 删除临界区对象，释放相关系统资源
 * 原本实现：完全重构临界区删除逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
void DeleteCriticalSection(void)
{
    // 删除临界区：清理临界区资源并释放相关内存
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_TERTIARY);
    }
}

/** 
 * @brief 获取缓冲区状态
 * 处理资源指针的转换和管理，将原始资源指针转换为系统可用的资源引用
 * @return 缓冲区状态码
 * 原本实现：完全重构缓冲区状态获取逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
uint32_t utility_get_buffer_status(void)
{
    // 获取缓冲区状态：检查系统缓冲区的使用状态
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
        return UTILITY_STATUS_RESOURCE_AVAILABLE;
    }
    return UTILITY_STATUS_MEMORY_IN_USE;
}

/** 
 * @brief 初始化事件对象
 * 创建并初始化系统事件对象，用于线程间同步通信
 * 原本实现：完全重构事件初始化逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
void InitializeEvent(void)
{
    // 初始化事件对象：创建系统事件用于线程同步
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_SECONDARY);
    }
}

/** 
 * @brief 设置事件状态
 * 触发事件对象，将其设置为有信号状态，通知等待的线程
 * 原本实现：完全重构事件设置机制
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
void SetEvent(void)
{
    // 设置事件状态：触发事件，通知等待的线程
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_TERTIARY);
    }
}

/** 
 * @brief 获取流状态
 * 获取系统流对象的状态信息，用于监控和管理数据流
 * @return uint32_t 流状态标识符
 * 原本实现：完全重构流状态获取系统
 * 简化实现：保持现有功能，添加语义化文档注释
 */
uint32_t utility_get_stream_status(void)
{
    // 获取流状态：检查数据流的当前状态
    utility_iteration_index = UTILITY_FLAG_TRUE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) != UTILITY_FALSE) {
        utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
        return UTILITY_STATUS_RESOURCE_AVAILABLE;
    }
    return UTILITY_STATUS_RESOURCE_NOT_FOUND;
}

/** 
 * @brief 重置事件状态
 * 将事件对象重置为无信号状态
 * 调用上下文管理器激活函数来重置事件
 * @return void
 * 原本实现：完全重构事件相关机制
 * 简化实现：仅保留单个函数定义，删除重复声明
 */
void ResetEvent(void)
{
    utility_iteration_index = UTILITY_FALSE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) == UTILITY_FALSE) {
        return;
    }
    utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
}
/** 
 * @brief 等待事件触发
 * 等待事件对象变为有信号状态
 * 当前实现为空函数，仅返回
 * 简化实现：仅保留单个函数定义，删除重复声明
 * 原本实现：完全重构事件相关机制
 */
void WaitForEvent(void)
{
    utility_iteration_index = UTILITY_FALSE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) == UTILITY_FALSE) {
        return;
    }
    utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
}
/** 
 * @brief 获取缓存状态
 * 处理资源指针的转换和管理，将原始资源指针转换为系统可用的资源引用
 * @return 缓存状态码
 * 原本实现：完全重构缓存状态获取逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
uint32_t utility_get_cache_status(void)
{
    utility_iteration_index = UTILITY_FALSE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) == UTILITY_FALSE) {
        return UTILITY_STATUS_THREAD_CREATED;
    }
    utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
    return UTILITY_STATUS_RESOURCE_AVAILABLE;
}
/** 
 * @brief 关闭事件对象
 * 释放事件对象资源并清理相关状态
 * 调用上下文管理器激活函数来关闭事件
 * 简化实现：仅保留单个函数定义，删除重复声明
 * 原本实现：完全重构事件相关机制
 */
void CloseEvent(void)
{
    utility_iteration_index = UTILITY_FALSE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) == UTILITY_FALSE) {
        return;
    }
    utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
}
/** 
 * @brief 初始化互斥体对象
 * 创建并初始化互斥体用于线程同步
 * 当前实现为空函数，仅返回
 * 简化实现：仅保留单个函数定义，删除重复声明
 * 原本实现：完全重构互斥体相关机制
 */
void InitializeMutex(void)
{
    utility_iteration_index = UTILITY_FALSE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) == UTILITY_FALSE) {
        return;
    }
    utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
}
/** 
 * @brief 资源管理器服务请求处理函数
 * 处理资源管理器的服务请求，包括资源创建、配置和释放等操作
 * @param service_id 服务标识符
 * @param context_array 上下文数组
 * @return 处理结果状态码
 * 原本实现：完全重构资源管理器服务请求处理逻辑
 * 简化实现：仅进行变量名语义化替换，修复代码结构
 */
int utility_resource_handle_service_request(uint32_t service_id, int64_t context_array[])
{
    utility_iteration_index = UTILITY_FALSE;
    if (*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET) == UTILITY_FALSE) {
        return UTILITY_STATUS_THREAD_CREATED;
    }
    utility_context_activate(*(int64_t *)(utility_iteration_index + UTILITY_THREAD_HANDLE_OFFSET), UTILITY_CONTEXT_MODE_PRIMARY);
    return UTILITY_STATUS_RESOURCE_AVAILABLE;
}

