#!/bin/bash

# 美化网络模块变量名的脚本
# 用于将05_networking.c中的变量名改为符合语义的PascalCase命名

# 定义需要替换的变量名映射
declare -A variable_replacements

# 网络状态相关变量
variable_replacements["networkStatus1"]="NetworkConnectionStatus"
variable_replacements["networkStatus2"]="NetworkTransferStatus"
variable_replacements["networkStatus3"]="NetworkReceiveStatus"
variable_replacements["networkStatus4"]="NetworkSendStatus"
variable_replacements["networkStatus5"]="NetworkProcessStatus"
variable_replacements["networkStatus6"]="NetworkValidationStatus"
variable_replacements["networkStatus7"]="NetworkAuthenticationStatus"
variable_replacements["networkStatus8"]="NetworkEncryptionStatus"
variable_replacements["networkStatus9"]="NetworkCompressionStatus"
variable_replacements["networkStatus10"]="NetworkRoutingStatus"
variable_replacements["networkStatus11"]="NetworkFilterStatus"
variable_replacements["networkStatus12"]="NetworkQueueStatus"
variable_replacements["networkStatus13"]="NetworkCacheStatus"
variable_replacements["networkStatus14"]="NetworkBufferStatus"
variable_replacements["networkStatus15"]="NetworkTimeoutStatus"
variable_replacements["networkStatus16"]="NetworkErrorStatus"

# 网络结果相关变量
variable_replacements["networkResult1"]="NetworkOperationResult"
variable_replacements["networkResult2"]="NetworkTransferResult"
variable_replacements["networkResult3"]="NetworkReceiveResult"
variable_replacements["networkResult4"]="NetworkSendResult"
variable_replacements["networkResult5"]="NetworkProcessResult"
variable_replacements["networkResult6"]="NetworkValidationResult"
variable_replacements["networkResult7"]="NetworkAuthenticationResult"
variable_replacements["networkResult8"]="NetworkEncryptionResult"
variable_replacements["networkResult9"]="NetworkCompressionResult"
variable_replacements["networkResult10"]="NetworkRoutingResult"

# 网络标志相关变量
variable_replacements["primaryNetworkFlag"]="PrimaryNetworkFlag"
variable_replacements["secondaryNetworkFlag"]="SecondaryNetworkFlag"
variable_replacements["tertiaryNetworkFlag"]="TertiaryNetworkFlag"
variable_replacements["quaternaryNetworkFlag"]="QuaternaryNetworkFlag"
variable_replacements["quinaryNetworkFlag"]="QuinaryNetworkFlag"
variable_replacements["primaryNetworkFlag0"]="PrimaryNetworkConnectionFlag"
variable_replacements["primaryNetworkFlag1"]="PrimaryNetworkTransferFlag"
variable_replacements["primaryNetworkFlag2"]="PrimaryNetworkReceiveFlag"
variable_replacements["primaryNetworkFlag3"]="PrimaryNetworkSendFlag"
variable_replacements["primaryNetworkFlag4"]="PrimaryNetworkProcessFlag"
variable_replacements["primaryNetworkFlag5"]="PrimaryNetworkValidationFlag"
variable_replacements["primaryNetworkFlag6"]="PrimaryNetworkAuthenticationFlag"
variable_replacements["primaryNetworkFlag7"]="PrimaryNetworkEncryptionFlag"
variable_replacements["primaryNetworkFlag8"]="PrimaryNetworkCompressionFlag"
variable_replacements["primaryNetworkFlag9"]="PrimaryNetworkRoutingFlag"
variable_replacements["secondaryNetworkFlag0"]="SecondaryNetworkConnectionFlag"
variable_replacements["secondaryNetworkFlag1"]="SecondaryNetworkTransferFlag"
variable_replacements["secondaryNetworkFlag2"]="SecondaryNetworkReceiveFlag"
variable_replacements["secondaryNetworkFlag3"]="SecondaryNetworkSendFlag"
variable_replacements["secondaryNetworkFlag4"]="SecondaryNetworkProcessFlag"
variable_replacements["secondaryNetworkFlag5"]="SecondaryNetworkValidationFlag"
variable_replacements["secondaryNetworkFlag6"]="SecondaryNetworkAuthenticationFlag"

# 网络指针相关变量
variable_replacements["networkPointer1"]="NetworkConnectionPointer"
variable_replacements["networkPointer2"]="NetworkTransferPointer"
variable_replacements["networkPointer3"]="NetworkReceivePointer"
variable_replacements["networkPointer4"]="NetworkSendPointer"
variable_replacements["networkPointer5"]="NetworkProcessPointer"
variable_replacements["networkPointer6"]="NetworkValidationPointer"
variable_replacements["networkPointer7"]="NetworkAuthenticationPointer"
variable_replacements["networkPointer8"]="NetworkEncryptionPointer"
variable_replacements["networkPointer9"]="NetworkCompressionPointer"
variable_replacements["networkPointer10"]="NetworkRoutingPointer"
variable_replacements["networkPointer11"]="NetworkFilterPointer"
variable_replacements["networkPointer12"]="NetworkQueuePointer"
variable_replacements["networkPointer13"]="NetworkCachePointer"
variable_replacements["networkPointer14"]="NetworkBufferPointer"
variable_replacements["networkPointer15"]="NetworkTimeoutPointer"
variable_replacements["networkPointer16"]="NetworkErrorPointer"
variable_replacements["networkPointer17"]="NetworkContextPointer"
variable_replacements["networkPointer18"]="NetworkSecurityPointer"
variable_replacements["networkPointer19"]="NetworkConfigPointer"
variable_replacements["networkPointer20"]="NetworkSessionPointer"
variable_replacements["networkPointer21"]="NetworkProtocolPointer"
variable_replacements["networkPointer22"]="NetworkPacketPointer"
variable_replacements["networkPointer23"]="NetworkDataPointer"
variable_replacements["networkPointer24"]="NetworkSocketPointer"

# 通用变量类型
variable_replacements["iVar1"]="IntegerVariable1"
variable_replacements["iVar2"]="IntegerVariable2"
variable_replacements["iVar3"]="IntegerVariable3"
variable_replacements["iVar4"]="IntegerVariable4"
variable_replacements["iVar5"]="IntegerVariable5"
variable_replacements["iVar6"]="IntegerVariable6"
variable_replacements["iVar7"]="IntegerVariable7"
variable_replacements["iVar8"]="IntegerVariable8"
variable_replacements["iVar9"]="IntegerVariable9"
variable_replacements["iVar10"]="IntegerVariable10"

variable_replacements["uVar1"]="UnsignedIntegerVariable1"
variable_replacements["uVar2"]="UnsignedIntegerVariable2"
variable_replacements["uVar3"]="UnsignedIntegerVariable3"
variable_replacements["uVar4"]="UnsignedIntegerVariable4"
variable_replacements["uVar5"]="UnsignedIntegerVariable5"
variable_replacements["uVar6"]="UnsignedIntegerVariable6"
variable_replacements["uVar7"]="UnsignedIntegerVariable7"
variable_replacements["uVar8"]="UnsignedIntegerVariable8"
variable_replacements["uVar9"]="UnsignedIntegerVariable9"
variable_replacements["uVar10"]="UnsignedIntegerVariable10"

variable_replacements["bVar1"]="BooleanVariable1"
variable_replacements["bVar2"]="BooleanVariable2"
variable_replacements["bVar3"]="BooleanVariable3"
variable_replacements["bVar4"]="BooleanVariable4"
variable_replacements["bVar5"]="BooleanVariable5"
variable_replacements["bVar6"]="BooleanVariable6"
variable_replacements["bVar7"]="BooleanVariable7"
variable_replacements["bVar8"]="BooleanVariable8"
variable_replacements["bVar9"]="BooleanVariable9"
variable_replacements["bVar10"]="BooleanVariable10"

variable_replacements["cVar1"]="CharacterVariable1"
variable_replacements["cVar2"]="CharacterVariable2"
variable_replacements["cVar3"]="CharacterVariable3"
variable_replacements["cVar4"]="CharacterVariable4"
variable_replacements["cVar5"]="CharacterVariable5"

variable_replacements["lVar1"]="LongVariable1"
variable_replacements["lVar2"]="LongVariable2"
variable_replacements["lVar3"]="LongVariable3"
variable_replacements["lVar4"]="LongVariable4"
variable_replacements["lVar5"]="LongVariable5"

variable_replacements["pVar1"]="PointerVariable1"
variable_replacements["pVar2"]="PointerVariable2"
variable_replacements["pVar3"]="PointerVariable3"
variable_replacements["pVar4"]="PointerVariable4"
variable_replacements["pVar5"]="PointerVariable5"

# 执行替换
for old_name in "${!variable_replacements[@]}"; do
    new_name="${variable_replacements[$old_name]}"
    echo "替换 $old_name 为 $new_name"
    sed -i "s/\b$old_name\b/$new_name/g" "$1"
done

echo "变量名美化完成"