#!/bin/bash

# 06_utilities.c 文件美化脚本
# 功能：美化变量名和常量定义，使其更加语义化

FILE_PATH="/dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c"

# 创建临时文件
TEMP_FILE=$(mktemp)

# 处理系统常量定义部分
sed -i 's/#define DefaultSystemDataAddress/#define SystemDataDefaultAddress/g' "$FILE_PATH"
sed -i 's/#define ComponentHandleOffset/#define ComponentHandleStandardOffset/g' "$FILE_PATH"
sed -i 's/#define SystemContextOffset/#define SystemContextStandardOffset/g' "$FILE_PATH"
sed -i 's/#define DataBufferElementSize/#define DataBufferElementStandardSize/g' "$FILE_PATH"
sed -i 's/#define FloatValidationMask/#define FloatValidationStandardMask/g' "$FILE_PATH"
sed -i 's/#define IntegerMinValue/#define IntegerMinimumValue/g' "$FILE_PATH"
sed -i 's/#define ProcessingFlagMask/#define ProcessingStandardFlagMask/g' "$FILE_PATH"
sed -i 's/#define MaxSafeBufferSize/#define MaximumSafeBufferSize/g' "$FILE_PATH"
sed -i 's/#define FloatInfinityValue/#define FloatInfinityStandardValue/g' "$FILE_PATH"
sed -i 's/#define SecurityAlignment/#define SecurityStandardAlignment/g' "$FILE_PATH"
sed -i 's/#define SecurityAlignmentMask/#define SecurityStandardAlignmentMask/g' "$FILE_PATH"
sed -i 's/#define SystemCleanupFlag/#define SystemCleanupStandardFlag/g' "$FILE_PATH"
sed -i 's/#define SystemCleanupAlignmentMask/#define SystemCleanupStandardAlignmentMask/g' "$FILE_PATH"
sed -i 's/#define NegativeZeroFloat/#define NegativeZeroFloatStandardValue/g' "$FILE_PATH"
sed -i 's/#define MemoryBlockSizeAdjustment/#define MemoryBlockStandardSizeAdjustment/g' "$FILE_PATH"
sed -i 's/#define MemoryValidationThreshold/#define MemoryValidationStandardThreshold/g' "$FILE_PATH"
sed -i 's/#define MemoryOffsetValidationThreshold/#define MemoryOffsetValidationStandardThreshold/g' "$FILE_PATH"
sed -i 's/#define SignBitShiftCount/#define SignBitStandardShiftCount/g' "$FILE_PATH"
sed -i 's/#define SystemBufferConfigMultiplier/#define SystemBufferStandardConfigMultiplier/g' "$FILE_PATH"
sed -i 's/#define SystemResourceManagerMultiplier/#define SystemResourceManagerStandardMultiplier/g' "$FILE_PATH"
sed -i 's/#define SystemResourceFlagOffset/#define SystemResourceStandardFlagOffset/g' "$FILE_PATH"
sed -i 's/#define ExceptionContextPointerOffset/#define ExceptionContextStandardPointerOffset/g' "$FILE_PATH"
sed -i 's/#define InvalidMemoryOffset/#define InvalidMemoryStandardOffset/g' "$FILE_PATH"
sed -i 's/#define SecurityValidationMask/#define SecurityValidationStandardMask/g' "$FILE_PATH"
sed -i 's/#define MemoryOperationFlag/#define MemoryOperationStandardFlag/g' "$FILE_PATH"
sed -i 's/#define ThreadLocalStorageOffset/#define ThreadLocalStorageStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ThreadLocalStorageBaseAddress/#define ThreadLocalStorageStandardBaseAddress/g' "$FILE_PATH"
sed -i 's/#define ResourceCleanupAlignment/#define ResourceCleanupStandardAlignment/g' "$FILE_PATH"
sed -i 's/#define DataProcessingMultiplier/#define DataProcessingStandardMultiplier/g' "$FILE_PATH"
sed -i 's/#define OperationFlagMask/#define OperationStandardFlagMask/g' "$FILE_PATH"
sed -i 's/#define MemoryAlignmentMask/#define MemoryStandardAlignmentMask/g' "$FILE_PATH"
sed -i 's/#define SystemMemoryCleanupMask/#define SystemMemoryStandardCleanupMask/g' "$FILE_PATH"
sed -i 's/#define MemoryOffsetAdjustment/#define MemoryStandardOffsetAdjustment/g' "$FILE_PATH"
sed -i 's/#define MemoryBaseOffset/#define MemoryStandardBaseOffset/g' "$FILE_PATH"
sed -i 's/#define MemoryBlockMultiplier/#define MemoryBlockStandardMultiplier/g' "$FILE_PATH"
sed -i 's/#define MemoryReferenceOffset/#define MemoryReferenceStandardOffset/g' "$FILE_PATH"
sed -i 's/#define MemoryDataOffset/#define MemoryDataStandardOffset/g' "$FILE_PATH"
sed -i 's/#define MemoryExceptionCheckOffset/#define MemoryExceptionStandardCheckOffset/g' "$FILE_PATH"
sed -i 's/#define MemoryPointerTableOffset/#define MemoryPointerTableStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ResourceIteratorValidationOffset/#define ResourceIteratorValidationStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ResourceIteratorNextOffset/#define ResourceIteratorNextStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ExceptionDataBufferOffset/#define ExceptionDataBufferStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ResourcePointerStartOffset/#define ResourcePointerStartStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ResourcePointerStep/#define ResourcePointerStandardStep/g' "$FILE_PATH"
sed -i 's/#define ExceptionHandlerContextOffset/#define ExceptionHandlerContextStandardOffset/g' "$FILE_PATH"
sed -i 's/#define ExceptionHandlerParameterOffset/#define ExceptionHandlerParameterStandardOffset/g' "$FILE_PATH"
sed -i 's/#define SystemMutexCleanupBaseAddress/#define SystemMutexCleanupStandardBaseAddress/g' "$FILE_PATH"
sed -i 's/#define SystemExceptionInitializerA0BaseAddress/#define SystemExceptionInitializerA0StandardBaseAddress/g' "$FILE_PATH"
sed -i 's/#define SystemExceptionInitializerB0BaseAddress/#define SystemExceptionInitializerB0StandardBaseAddress/g' "$FILE_PATH"

echo "06_utilities.c 文件美化完成"
echo "主要修改："
echo "1. 将变量名标准化，添加Standard前缀"
echo "2. 统一命名规范，提高可读性"
echo "3. 保持原有的注释和功能不变"