#!/bin/bash

# 批量修改变量名脚本
# 用于去除99_unmatched_functions.c文件中的地址后缀

FILE_PATH="/dev/shm/mountblade-code/TaleWorlds.Native/src/99_unmatched_functions.c"

# 修改变量名的函数
rename_variable() {
    local old_name="$1"
    local new_name="$2"
    
    # 使用sed进行替换
    sed -i "s/${old_name}/${new_name}/g" "$FILE_PATH"
    
    echo "已将 ${old_name} 替换为 ${new_name}"
}

# 主要系统变量名修改
rename_variable "SystemMemoryManagementVariable_0c370" "SystemMemoryManagementVariable"
rename_variable "SystemConfigurationTable_0c390" "SystemConfigurationTable"
rename_variable "SystemSecurityContext_0c3b0" "SystemSecurityContext"
rename_variable "SystemResourceAllocator_0c3d0" "SystemResourceAllocator"
rename_variable "SystemThreadScheduler_05f38" "SystemThreadScheduler"
rename_variable "SystemProcessManager_05f50" "SystemProcessManager"
rename_variable "SystemEventDispatcher_05f68" "SystemEventDispatcher"
rename_variable "SystemMessageQueue_05f80" "SystemMessageQueue"
rename_variable "SystemTaskScheduler_05f98" "SystemTaskScheduler"
rename_variable "SystemJobManager_05fb0" "SystemJobManager"
rename_variable "SystemWorkQueue_05fc8" "SystemWorkQueue"
rename_variable "SystemDataProcessor_05fe0" "SystemDataProcessor"
rename_variable "SystemCommandHandler_05ff8" "SystemCommandHandler"
rename_variable "SystemRequestProcessor_06010" "SystemRequestProcessor"
rename_variable "SystemResponseGenerator_06028" "SystemResponseGenerator"
rename_variable "SystemErrorHandler_06040" "SystemErrorHandler"
rename_variable "SystemLogManager_06058" "SystemLogManager"
rename_variable "SystemAuditTrail_06078" "SystemAuditTrail"
rename_variable "SystemMonitorService_06098" "SystemMonitorService"
rename_variable "SystemPerformanceCounter_060c0" "SystemPerformanceCounter"
rename_variable "SystemResourceTracker_060e0" "SystemResourceTracker"
rename_variable "SystemMemoryPool_06110" "SystemMemoryPool"
rename_variable "SystemCacheManager_06140" "SystemCacheManager"
rename_variable "SystemBufferAllocator_06158" "SystemBufferAllocator"
rename_variable "SystemDataStorage_06180" "SystemDataStorage"
rename_variable "SystemFileHandler_06198" "SystemFileHandler"
rename_variable "SystemNetworkAdapter_061b8" "SystemNetworkAdapter"
rename_variable "SystemSecurityModule_061d0" "SystemSecurityModule"
rename_variable "SystemEncryptionEngine_061e8" "SystemEncryptionEngine"
rename_variable "SystemAuthenticationService_06208" "SystemAuthenticationService"
rename_variable "SystemAuthorizationManager_06220" "SystemAuthorizationManager"
rename_variable "SystemValidationEngine_06230" "SystemValidationEngine"
rename_variable "SystemIntegrityChecker_06260" "SystemIntegrityChecker"
rename_variable "SystemVerificationService_06248" "SystemVerificationService"
rename_variable "SystemComplianceMonitor_06280" "SystemComplianceMonitor"
rename_variable "SystemPolicyEnforcer_06288" "SystemPolicyEnforcer"
rename_variable "SystemAccessController_062b0" "SystemAccessController"
rename_variable "SystemPermissionManager_06298" "SystemPermissionManager"
rename_variable "SystemRoleProvider_062c0" "SystemRoleProvider"
rename_variable "SystemCredentialValidator_062d4" "SystemCredentialValidator"
rename_variable "SystemSessionManager_0c750" "SystemSessionManager"
rename_variable "SystemContextHandler_0c780" "SystemContextHandler"
rename_variable "SystemStateController_0c760" "SystemStateController"
rename_variable "SystemUserInterfaceManager_0c730" "SystemUserInterfaceManager"
rename_variable "SystemGraphicsRenderer_0c700" "SystemGraphicsRenderer"
rename_variable "SystemDisplayController_0c710" "SystemDisplayController"
rename_variable "SystemAudioEngine_0c6d0" "SystemAudioEngine"
rename_variable "SystemSoundManager_0c6e0" "SystemSoundManager"
rename_variable "SystemInputProcessor_0c6b0" "SystemInputProcessor"
rename_variable "SystemControllerHandler_0c690" "SystemControllerHandler"
rename_variable "SystemMouseManager_0c670" "SystemMouseManager"
rename_variable "SystemKeyboardHandler_0c650" "SystemKeyboardHandler"
rename_variable "SystemTouchScreenProcessor_0c630" "SystemTouchScreenProcessor"
rename_variable "SystemVirtualRealityEngine_06400" "SystemVirtualRealityEngine"
rename_variable "SystemAugmentedRealityCore_06310" "SystemAugmentedRealityCore"
rename_variable "SystemMixedRealityInterface_06320" "SystemMixedRealityInterface"
rename_variable "SystemSpatialComputingUnit_06330" "SystemSpatialComputingUnit"
rename_variable "SystemGestureRecognitionSystem_0632c" "SystemGestureRecognitionSystem"
rename_variable "SystemMotionTrackingService_0633c" "SystemMotionTrackingService"
rename_variable "SystemPositionalAudioEngine_06338" "SystemPositionalAudioEngine"
rename_variable "SystemHapticFeedbackController_06348" "SystemHapticFeedbackController"
rename_variable "SystemEyeTrackingModule_06340" "SystemEyeTrackingModule"
rename_variable "SystemFacialRecognitionSystem_0634c" "SystemFacialRecognitionSystem"
rename_variable "SystemVoiceCommandProcessor_06350" "SystemVoiceCommandProcessor"
rename_variable "SystemArtificialIntelligenceCore_8d290" "SystemArtificialIntelligenceCore"
rename_variable "SystemMachineLearningEngine_06388" "SystemMachineLearningEngine"
rename_variable "SystemDeepLearningNetwork_06378" "SystemDeepLearningNetwork"
rename_variable "SystemNeuralNetworkProcessor_8d0f0" "SystemNeuralNetworkProcessor"
rename_variable "SystemQuantumComputingUnit_06768" "SystemQuantumComputingUnit"
rename_variable "SystemBlockchainProcessor_06770" "SystemBlockchainProcessor"
rename_variable "SystemCloudComputingService_063c0" "SystemCloudComputingService"
rename_variable "SystemDistributedComputingNode_114854" "SystemDistributedComputingNode"
rename_variable "SystemClusterComputingManager_11486c" "SystemClusterComputingManager"
rename_variable "SystemEdgeComputingProcessor_063b0" "SystemEdgeComputingProcessor"
rename_variable "SystemFogComputingEngine_063cc" "SystemFogComputingEngine"
rename_variable "SystemServerlessComputingUnit_063d0" "SystemServerlessComputingUnit"
rename_variable "SystemGlobalConfigurationConstant_8a9a8" "SystemGlobalConfigurationConstant"
rename_variable "SystemMicroservicesArchitecture_11ae70" "SystemMicroservicesArchitecture"
rename_variable "SystemContainerOrchestrationEngine_11ae80" "SystemContainerOrchestrationEngine"
rename_variable "SystemDevOpsAutomationTool_063f8" "SystemDevOpsAutomationTool"
rename_variable "SystemContinuousIntegrationPipeline_0640c" "SystemContinuousIntegrationPipeline"
rename_variable "SystemContinuousDeploymentService_06410" "SystemContinuousDeploymentService"
rename_variable "SystemDataStorageManager_14f510" "SystemDataStorageManager"
rename_variable "SystemXmlProcessingEngine_08850" "SystemXmlProcessingEngine"

echo "变量名修改完成"