// Unwind函数重命名映射
// 用于批量重命名06_utilities.c中的Unwind函数

const unwindFunctionMappings = {
    // 基础资源清理函数
    'Unwind_180903930': 'CleanupLocalContextResources',
    'Unwind_180903950': 'ReleaseSystemDataStructures',
    'Unwind_180903970': 'CleanupSystemResourceHandlers',
    'Unwind_180903990': 'ResetSystemResourcePointers',
    'Unwind_1809039b0': 'CleanupSystemMemoryAllocations',
    'Unwind_1809039d0': 'ReleaseSystemBufferResources',
    'Unwind_1809039f0': 'CleanupSystemCacheResources',
    'Unwind_180903a10': 'ReleaseSystemThreadResources',
    'Unwind_180903a30': 'CleanupSystemMutexResources',
    'Unwind_180903a50': 'ReleaseSystemEventResources',
    'Unwind_180903a70': 'CleanupSystemSemaphoreResources',
    'Unwind_180903a90': 'ReleaseSystemTimerResources',
    'Unwind_180903ab0': 'CleanupSystemFileResources',
    'Unwind_180903ac0': 'ReleaseSystemNetworkResources',
    'Unwind_180903ad0': 'CleanupSystemSecurityResources',
    'Unwind_180903ae0': 'ReleaseSystemDatabaseResources',
    'Unwind_180903af0': 'CleanupSystemConfigurationResources',
    'Unwind_180903b00': 'ReleaseSystemLoggingResources',
    'Unwind_180903b20': 'CleanupSystemDiagnosticResources',
    'Unwind_180903b40': 'ReleaseSystemPerformanceResources',
    'Unwind_180903b60': 'CleanupSystemMonitoringResources',
    'Unwind_180903b80': 'ReleaseSystemProfilingResources',
    'Unwind_180903ba0': 'CleanupSystemTracingResources',
    'Unwind_180903bc0': 'ReleaseSystemDebugResources',
    'Unwind_180903be0': 'CleanupSystemTestingResources',
    'Unwind_180903c00': 'ReleaseSystemValidationResources',
    'Unwind_180903c20': 'CleanupSystemVerificationResources',
    'Unwind_180903c40': 'ReleaseSystemAuthenticationResources',
    'Unwind_180903c60': 'CleanupSystemAuthorizationResources',
    'Unwind_180903c80': 'ReleaseSystemEncryptionResources',
    'Unwind_180903ca0': 'CleanupSystemCompressionResources',
    'Unwind_180903cc0': 'ReleaseSystemSerializationResources',
    'Unwind_180903cd0': 'CleanupSystemDeserializationResources',
    'Unwind_180903ce0': 'ReleaseSystemStreamingResources',
    'Unwind_180903cf0': 'CleanupSystemBufferingResources',
    'Unwind_180903d10': 'ReleaseSystemCachingResources',
    'Unwind_180903d30': 'CleanupSystemPoolingResources',
    'Unwind_180903d50': 'ReleaseSystemQueuingResources',
    'Unwind_180903d70': 'CleanupSystemSchedulingResources',
    'Unwind_180903d90': 'ReleaseSystemPrioritizationResources',
    'Unwind_180903db0': 'CleanupSystemOptimizationResources',
    'Unwind_180903dd0': 'ReleaseSystemBalancingResources',
    'Unwind_180903df0': 'CleanupSystemScalingResources',
    'Unwind_180903e10': 'ReleaseSystemDistributionResources',
    'Unwind_180903e30': 'CleanupSystemReplicationResources',
    'Unwind_180903e50': 'ReleaseSystemSynchronizationResources',
    'Unwind_180903e70': 'CleanupSystemCoordinationResources',
    'Unwind_180903e90': 'ReleaseSystemCommunicationResources',
    'Unwind_180903eb0': 'CleanupSystemNotificationResources'
};

// 函数描述模板
const functionDescriptions = {
    'CleanupLocalContextResources': '清理本地上下文资源，释放相关内存并重置状态',
    'ReleaseSystemDataStructures': '释放系统数据结构，清理相关指针和内存',
    'CleanupSystemResourceHandlers': '清理系统资源处理器，重置资源管理状态',
    'ResetSystemResourcePointers': '重置系统资源指针，清理资源引用',
    'CleanupSystemMemoryAllocations': '清理系统内存分配，释放已分配的内存块',
    'ReleaseSystemBufferResources': '释放系统缓冲区资源，清理缓冲区内存',
    'CleanupSystemCacheResources': '清理系统缓存资源，重置缓存状态',
    'ReleaseSystemThreadResources': '释放系统线程资源，清理线程相关数据',
    'CleanupSystemMutexResources': '清理系统互斥锁资源，释放互斥锁对象',
    'ReleaseSystemEventResources': '释放系统事件资源，清理事件对象',
    'CleanupSystemSemaphoreResources': '清理系统信号量资源，释放信号量对象',
    'ReleaseSystemTimerResources': '释放系统计时器资源，清理计时器对象',
    'CleanupSystemFileResources': '清理系统文件资源，关闭文件句柄',
    'ReleaseSystemNetworkResources': '释放系统网络资源，清理网络连接',
    'CleanupSystemSecurityResources': '清理系统安全资源，重置安全状态',
    'ReleaseSystemDatabaseResources': '释放系统数据库资源，清理数据库连接',
    'CleanupSystemConfigurationResources': '清理系统配置资源，重置配置状态',
    'ReleaseSystemLoggingResources': '释放系统日志资源，清理日志缓冲区',
    'CleanupSystemDiagnosticResources': '清理系统诊断资源，重置诊断状态',
    'ReleaseSystemPerformanceResources': '释放系统性能资源，清理性能计数器',
    'CleanupSystemMonitoringResources': '清理系统监控资源，重置监控状态',
    'ReleaseSystemProfilingResources': '释放系统分析资源，清理分析数据',
    'CleanupSystemTracingResources': '清理系统跟踪资源，重置跟踪状态',
    'ReleaseSystemDebugResources': '释放系统调试资源，清理调试信息',
    'CleanupSystemTestingResources': '清理系统测试资源，重置测试状态',
    'ReleaseSystemValidationResources': '释放系统验证资源，清理验证数据',
    'CleanupSystemVerificationResources': '清理系统验证资源，重置验证状态',
    'ReleaseSystemAuthenticationResources': '释放系统认证资源，清理认证数据',
    'CleanupSystemAuthorizationResources': '清理系统授权资源，重置授权状态',
    'ReleaseSystemEncryptionResources': '释放系统加密资源，清理加密上下文',
    'CleanupSystemCompressionResources': '清理系统压缩资源，重置压缩状态',
    'ReleaseSystemSerializationResources': '释放系统序列化资源，清理序列化数据',
    'CleanupSystemDeserializationResources': '清理系统反序列化资源，重置反序列化状态',
    'ReleaseSystemStreamingResources': '释放系统流资源，清理流缓冲区',
    'CleanupSystemBufferingResources': '清理系统缓冲资源，重置缓冲状态',
    'ReleaseSystemCachingResources': '释放系统缓存资源，清理缓存数据',
    'CleanupSystemPoolingResources': '清理系统池资源，重置池状态',
    'ReleaseSystemQueuingResources': '释放系统队列资源，清理队列数据',
    'CleanupSystemSchedulingResources': '清理系统调度资源，重置调度状态',
    'ReleaseSystemPrioritizationResources': '释放系统优先级资源，清理优先级数据',
    'CleanupSystemOptimizationResources': '清理系统优化资源，重置优化状态',
    'ReleaseSystemBalancingResources': '释放系统平衡资源，清理平衡数据',
    'CleanupSystemScalingResources': '清理系统扩展资源，重置扩展状态',
    'ReleaseSystemDistributionResources': '释放系统分发资源，清理分发数据',
    'CleanupSystemReplicationResources': '清理系统复制资源，重置复制状态',
    'ReleaseSystemSynchronizationResources': '释放系统同步资源，清理同步数据',
    'CleanupSystemCoordinationResources': '清理系统协调资源，重置协调状态',
    'ReleaseSystemCommunicationResources': '释放系统通信资源，清理通信数据',
    'CleanupSystemNotificationResources': '清理系统通知资源，重置通知状态'
};

module.exports = {
    unwindFunctionMappings,
    functionDescriptions
};