#!/bin/bash

# 美化06_utilities.c文件的脚本
# 对常量定义进行语义化替换

# 常量替换映射
declare -A replacements=(
    # 状态标志常量
    ["UTILITY_STATUS_FLAG_E38"]="UTILITY_STATUS_EXTENDED_OFFSET_38"
    ["UTILITY_STATUS_FLAG_E40"]="UTILITY_STATUS_EXTENDED_OFFSET_40"
    ["UTILITY_STATUS_FLAG_E50"]="UTILITY_STATUS_EXTENDED_OFFSET_50"
    ["UTILITY_STATUS_FLAG_E58"]="UTILITY_STATUS_EXTENDED_OFFSET_58"
    ["UTILITY_STATUS_FLAG_E60"]="UTILITY_STATUS_EXTENDED_OFFSET_60"
    ["UTILITY_STATUS_FLAG_E68"]="UTILITY_STATUS_EXTENDED_OFFSET_68"
    ["UTILITY_STATUS_FLAG_E70"]="UTILITY_STATUS_EXTENDED_OFFSET_70"
    ["UTILITY_STATUS_FLAG_E78"]="UTILITY_STATUS_EXTENDED_OFFSET_78"
    ["UTILITY_STATUS_FLAG_E80"]="UTILITY_STATUS_EXTENDED_OFFSET_80"
    ["UTILITY_STATUS_FLAG_Ea8"]="UTILITY_STATUS_EXTENDED_OFFSET_A8"
    ["UTILITY_STATUS_FLAG_Eb0"]="UTILITY_STATUS_EXTENDED_OFFSET_B0"
    ["UTILITY_STATUS_FLAG_Eb8"]="UTILITY_STATUS_EXTENDED_OFFSET_B8"
    ["UTILITY_STATUS_FLAG_Ec0"]="UTILITY_STATUS_EXTENDED_OFFSET_C0"
    ["UTILITY_STATUS_FLAG_Ec8"]="UTILITY_STATUS_EXTENDED_OFFSET_C8"
    ["UTILITY_STATUS_FLAG_Ed0"]="UTILITY_STATUS_EXTENDED_OFFSET_D0"
    ["UTILITY_STATUS_FLAG_Ee0"]="UTILITY_STATUS_EXTENDED_OFFSET_E0"
    ["UTILITY_STATUS_FLAG_F0"]="UTILITY_STATUS_EXTENDED_OFFSET_F0"
    
    # 流类型常量
    ["UTILITY_STREAM_TYPE_BIPS"]="UTILITY_STREAM_TYPE_BINARY_PROCESSING_SYSTEM"
    ["UTILITY_STREAM_TYPE_BFES"]="UTILITY_STREAM_TYPE_BINARY_FILE_ENCRYPTION_SYSTEM"
    ["UTILITY_STREAM_TYPE_FFCS"]="UTILITY_STREAM_TYPE_FAST_FILE_COMPRESSION_SYSTEM"
    ["UTILITY_STREAM_TYPE_BNLT"]="UTILITY_STREAM_TYPE_BINARY_NETWORK_LINK_TRANSFER"
    ["UTILITY_STREAM_TYPE_BIAW"]="UTILITY_STREAM_TYPE_BINARY_INPUT_AWARENESS_WRAPPER"
    ["UTILITY_STREAM_TYPE_BIFE"]="UTILITY_STREAM_TYPE_BINARY_INPUT_FORMAT_ENCODER"
    ["UTILITY_STREAM_TYPE_BDMC"]="UTILITY_STREAM_TYPE_BINARY_DATA_MANAGEMENT_CONTROLLER"
    ["UTILITY_STREAM_TYPE_IDMC"]="UTILITY_STREAM_TYPE_INTEGRATED_DATA_MANAGEMENT_CONTROLLER"
    
    # 上下文相关常量
    ["UTILITY_CONTEXT_SIZE_MULTIPLIER_44_BYTES"]="UTILITY_CONTEXT_STRUCTURE_SIZE_44_BYTES"
    ["UTILITY_CONTEXT_OFFSET_STACK_SMALL"]="UTILITY_CONTEXT_STACK_OFFSET_SMALL"
    ["UTILITY_CONTEXT_OFFSET_BUFFER_PRIMARY"]="UTILITY_CONTEXT_BUFFER_OFFSET_PRIMARY"
    ["UTILITY_CONTEXT_OFFSET_BUFFER_SECONDARY"]="UTILITY_CONTEXT_BUFFER_OFFSET_SECONDARY"
    ["UTILITY_CONTEXT_OFFSET_DATA_PRIMARY"]="UTILITY_CONTEXT_DATA_OFFSET_PRIMARY"
    ["UTILITY_CONTEXT_OFFSET_DATA_SECONDARY"]="UTILITY_CONTEXT_DATA_OFFSET_SECONDARY"
    ["UTILITY_CONTEXT_OFFSET_CONTROL_PRIMARY"]="UTILITY_CONTEXT_CONTROL_OFFSET_PRIMARY"
    ["UTILITY_CONTEXT_OFFSET_CONTROL_SECONDARY"]="UTILITY_CONTEXT_CONTROL_OFFSET_SECONDARY"
    ["UTILITY_CONTEXT_OFFSET_CONTROL_TERTIARY"]="UTILITY_CONTEXT_CONTROL_OFFSET_TERTIARY"
    ["UTILITY_CONTEXT_OFFSET_CONTROL_QUATERNARY"]="UTILITY_CONTEXT_CONTROL_OFFSET_QUATERNARY"
    ["UTILITY_CONTEXT_OFFSET_EXTENDED"]="UTILITY_CONTEXT_EXTENDED_OFFSET"
    
    # 状态错误码
    ["UTILITY_STATUS_ERROR_CODE_INVALID_PARAM"]="UTILITY_ERROR_INVALID_PARAMETER"
    
    # 位操作常量
    ["UTILITY_BIT_SHIFT_8_BITS"]="UTILITY_BIT_SHIFT_8"
    ["UTILITY_BIT_MASK_8_BIT"]="UTILITY_BIT_MASK_8"
    ["UTILITY_BYTE_MASK_8_BIT"]="UTILITY_BYTE_MASK_8"
    ["UTILITY_BYTE_MASK_CLEAR_LAST_BIT"]="UTILITY_BYTE_MASK_CLEAR_LSB"
    
    # 状态常量
    ["UTILITY_STATUS_INITIALIZED_LEVEL_1"]="UTILITY_STATUS_INITIALIZED_BASIC"
    ["UTILITY_STATUS_INITIALIZED_LEVEL_2"]="UTILITY_STATUS_INITIALIZED_ADVANCED"
    
    # 指针和上下文常量
    ["UTILITY_CONTEXT_POINTER_OFFSET"]="UTILITY_CONTEXT_GLOBAL_POINTER_OFFSET"
    ["UTILITY_CONTEXT_BASE_OFFSET"]="UTILITY_CONTEXT_BASE_ADDRESS_OFFSET"
    ["UTILITY_CONTEXT_MULTIPLIER_OFFSET"]="UTILITY_CONTEXT_SIZE_MULTIPLIER_OFFSET"
    ["UTILITY_CONNECTION_ID_OFFSET"]="UTILITY_NETWORK_CONNECTION_ID_OFFSET"
    
    # 缓冲区大小常量
    ["UTILITY_LARGE_BUFFER_SIZE"]="UTILITY_CONTEXT_LARGE_BUFFER_SIZE"
    ["UTILITY_NETWORK_BUFFER_SIZE"]="UTILITY_NETWORK_CONTEXT_BUFFER_SIZE"
    
    # 数值常量
    ["UTILITY_NEGATIVE_512MB_64BIT"]="UTILITY_MEMORY_SIZE_NEGATIVE_512MB"
    ["UTILITY_FLOAT_ZERO"]="UTILITY_FLOAT_VALUE_ZERO"
    
    # 布尔值
    ["UTILITY_BOOLEAN_TRUE"]="UTILITY_TRUE"
    ["UTILITY_BOOLEAN_FALSE"]="UTILITY_FALSE"
)

# 文件路径
input_file="/dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c"
temp_file="/dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities_temp.c"

# 创建临时文件
cp "$input_file" "$temp_file"

# 执行替换
for old_name in "${!replacements[@]}"; do
    new_name="${replacements[$old_name]}"
    echo "替换: $old_name -> $new_name"
    sed -i "s/\b$old_name\b/$new_name/g" "$temp_file"
done

echo "常量替换完成"
echo "请检查 $temp_file 文件，确认无误后替换原文件"