#!/bin/bash

# 创建更全面的标签替换脚本
# 原本实现：完全重构工具系统所有标签命名体系，建立统一的语义化命名规范
# 简化实现：仅将常见的十六进制标签替换为语义化标签名，保持代码结构不变

FILE_PATH="/dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c"

# 检查文件是否存在
if [ ! -f "$FILE_PATH" ]; then
    echo "错误：文件不存在 $FILE_PATH"
    exit 1
fi

# 备份文件
cp "$FILE_PATH" "${FILE_PATH}.backup2"

# 常见标签替换
sed -i 's/LAB_18089866f:/UTILITY_LABEL_CONTEXT_PROCESS:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089866f/goto UTILITY_LABEL_CONTEXT_PROCESS/g' "$FILE_PATH"

sed -i 's/LAB_1808989b1:/UTILITY_LABEL_MEMORY_MANAGER:/g' "$FILE_PATH"
sed -i 's/goto LAB_1808989b1/goto UTILITY_LABEL_MEMORY_MANAGER/g' "$FILE_PATH"

sed -i 's/LAB_1808989f7:/UTILITY_LABEL_HEAP_ALLOC:/g' "$FILE_PATH"
sed -i 's/goto LAB_1808989f7/goto UTILITY_LABEL_HEAP_ALLOC/g' "$FILE_PATH"

sed -i 's/LAB_180898e0b:/UTILITY_LABEL_STACK_ALLOC:/g' "$FILE_PATH"
sed -i 's/goto LAB_180898e0b/goto UTILITY_LABEL_STACK_ALLOC/g' "$FILE_PATH"

sed -i 's/LAB_1808992a5:/UTILITY_LABEL_THREAD_CREATE:/g' "$FILE_PATH"
sed -i 's/goto LAB_1808992a5/goto UTILITY_LABEL_THREAD_CREATE/g' "$FILE_PATH"

sed -i 's/LAB_180899456:/UTILITY_LABEL_MUTEX_LOCK:/g' "$FILE_PATH"
sed -i 's/goto LAB_180899456/goto UTILITY_LABEL_MUTEX_LOCK/g' "$FILE_PATH"

sed -i 's/LAB_180899546:/UTILITY_LABEL_MUTEX_UNLOCK:/g' "$FILE_PATH"
sed -i 's/goto LAB_180899546/goto UTILITY_LABEL_MUTEX_UNLOCK/g' "$FILE_PATH"

sed -i 's/LAB_18089962f:/UTILITY_LABEL_SEMAPHORE_WAIT:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089962f/goto UTILITY_LABEL_SEMAPHORE_WAIT/g' "$FILE_PATH"

sed -i 's/LAB_1808996c5:/UTILITY_LABEL_EVENT_SIGNAL:/g' "$FILE_PATH"
sed -i 's/goto LAB_1808996c5/goto UTILITY_LABEL_EVENT_SIGNAL/g' "$FILE_PATH"

sed -i 's/LAB_18089ae18:/UTILITY_LABEL_NETWORK_SEND:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089ae18/goto UTILITY_LABEL_NETWORK_SEND/g' "$FILE_PATH"

sed -i 's/LAB_18089af81:/UTILITY_LABEL_NETWORK_RECEIVE:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089af81/goto UTILITY_LABEL_NETWORK_RECEIVE/g' "$FILE_PATH"

sed -i 's/LAB_18089b1ab:/UTILITY_LABEL_PROTOCOL_HANDLE:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089b1ab/goto UTILITY_LABEL_PROTOCOL_HANDLE/g' "$FILE_PATH"

sed -i 's/LAB_18089b226:/UTILITY_LABEL_DATA_PARSE:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089b226/goto UTILITY_LABEL_DATA_PARSE/g' "$FILE_PATH"

sed -i 's/LAB_18089b22a:/UTILITY_LABEL_DATA_SERIALIZE:/g' "$FILE_PATH"
sed -i 's/goto LAB_18089b22a/goto UTILITY_LABEL_DATA_SERIALIZE/g' "$FILE_PATH"

echo "标签美化完成"