#!/bin/bash

# 06_utilities.c 语义化美化脚本
# 用于美化变量名、函数名和常量名

# 定义美化规则
# 美化常量名
sed -i 's/UTILITY_STATUS_FLAG_MASK_0X7C/UTILITY_STATUS_FLAG_MASK_CONTROL_BITS/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_ENABLED_FLAG_4/UTILITY_STATUS_ENABLED_FLAG_QUARTERNARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_ENABLED_FLAG_9/UTILITY_STATUS_ENABLED_FLAG_NONARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_ENABLED_FLAG_F/UTILITY_STATUS_ENABLED_FLAG_HEXADECIMAL/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_MASK_8/UTILITY_STATUS_FLAG_MASK_OCTAL/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_OFFSET_PRIMARY/UTILITY_RESOURCE_FLAG_OFFSET_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_OFFSET_SECONDARY/UTILITY_RESOURCE_FLAG_OFFSET_AUXILIARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_FLAG_OFFSET_PRIMARY/UTILITY_MEMORY_FLAG_OFFSET_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_BYTE/UTILITY_FLAG_MASK_8BIT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_WORD/UTILITY_FLAG_MASK_16BIT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_MASK_LARGE/UTILITY_STATUS_FLAG_MASK_MAXIMUM/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_FLOAT_PROCESSING/UTILITY_FLAG_MASK_FLOAT_CALCULATION/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BUFFER_ALIGNMENT/UTILITY_BUFFER_ALIGNMENT_BOUNDARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BUFFER_ALIGNMENT_MASK/UTILITY_BUFFER_ALIGNMENT_MASK_BOUNDARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_NOT_FOUND/UTILITY_ERROR_RESOURCE_NOT_FOUND/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_INVALID_PARAMETER/UTILITY_ERROR_INVALID_PARAMETER/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_BLOCK_SIZE_EXTRA_LARGE/UTILITY_MEMORY_BLOCK_SIZE_ENORMOUS/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_BLOCK_SIZE_HUGE/UTILITY_MEMORY_BLOCK_SIZE_GIANT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BUFFER_FLAGS_DEFAULT/UTILITY_BUFFER_FLAGS_STANDARD/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLOAT_ARRAY_OFFSET_SECONDARY/UTILITY_FLOAT_ARRAY_OFFSET_AUXILIARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLOAT_ARRAY_OFFSET_TERTIARY/UTILITY_FLOAT_ARRAY_OFFSET_TERTIARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_STRUCT_SIZE_44/UTILITY_CONTEXT_STRUCT_SIZE_STANDARD/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_SERVICE_HANDLER_OFFSET_PRIMARY/UTILITY_SERVICE_HANDLER_OFFSET_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_SERVICE_HANDLER_OFFSET_2F0/UTILITY_SERVICE_HANDLER_OFFSET_ALTERNATE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_NETWORK_CONTEXT_OFFSET_D8/UTILITY_NETWORK_CONTEXT_OFFSET_CONNECTION/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_NULL_PTR/UTILITY_NULL_POINTER/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_SIZE_MULTIPLIER/UTILITY_CONTEXT_SIZE_SCALING_FACTOR/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BUFFER_ELEMENT_SIZE/UTILITY_BUFFER_ITEM_SIZE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STACK_OFFSET_SMALL/UTILITY_STACK_OFFSET_COMPACT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STACK_OFFSET_LARGE/UTILITY_STACK_OFFSET_EXPANDED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_POINTER_OFFSET_0/UTILITY_MEMORY_POINTER_OFFSET_BASE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_MASK_PRIMARY/UTILITY_STATUS_FLAG_MASK_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_MASK_SMALL/UTILITY_STATUS_FLAG_MASK_COMPACT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_MASK_MEDIUM/UTILITY_STATUS_FLAG_MASK_MODERATE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_POINTER_OFFSET_SMALL/UTILITY_MEMORY_POINTER_OFFSET_COMPACT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_POINTER_OFFSET_MEDIUM/UTILITY_MEMORY_POINTER_OFFSET_MODERATE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_POINTER_OFFSET_LARGE/UTILITY_MEMORY_POINTER_OFFSET_EXPANDED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_MULTIPLIER_C/UTILITY_CONTEXT_SCALING_FACTOR_C/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_THREAD_RUNNING/UTILITY_FLAG_MASK_THREAD_ACTIVE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_RESOURCE_OFFSET_0/UTILITY_CONTEXT_RESOURCE_OFFSET_BASE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_RESERVED/UTILITY_CONTEXT_OFFSET_RESERVED_AREA/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_EXTENDED/UTILITY_CONTEXT_OFFSET_ADDITIONAL/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_AUXILIARY/UTILITY_CONTEXT_OFFSET_SECONDARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BYTE_MASK_CLEAR_LAST_BIT/UTILITY_BYTE_MASK_EXCEPT_LSB/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BOOLEAN_TRUE/UTILITY_TRUE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_BOOLEAN_FALSE/UTILITY_FALSE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_THREAD_DATA_OFFSET_PRIMARY/UTILITY_THREAD_DATA_OFFSET_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_OFFSET_PRIMARY/UTILITY_RESOURCE_FLAG_OFFSET_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_OFFSET_8/UTILITY_RESOURCE_FLAG_OFFSET_8BIT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_OFFSET_0_B/UTILITY_RESOURCE_FLAG_OFFSET_BASE_B/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_THREAD_BUFFER_OFFSET_PRIMARY/UTILITY_THREAD_BUFFER_OFFSET_MAIN/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_THREAD_BUFFER_OFFSET_SECONDARY/UTILITY_THREAD_BUFFER_OFFSET_AUXILIARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_THREAD_BUFFER_OFFSET_TERTIARY/UTILITY_THREAD_BUFFER_OFFSET_TERTIARY/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_OFFSET_EXTENDED/UTILITY_RESOURCE_FLAG_OFFSET_ADDITIONAL/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_RESOURCE_ID/UTILITY_CONTEXT_OFFSET_RESOURCE_IDENTIFIER/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_CONFIG/UTILITY_CONTEXT_OFFSET_CONFIGURATION/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_DATA_AREA/UTILITY_CONTEXT_OFFSET_DATA_REGION/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_BUFFER/UTILITY_CONTEXT_OFFSET_BUFFER_AREA/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CONTEXT_OFFSET_CONTROL/UTILITY_CONTEXT_OFFSET_CONTROL_AREA/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_CHECKSUM_OFFSET_VALIDATION/UTILITY_CHECKSUM_OFFSET_VERIFICATION/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_SERVICE_CONTEXT_OFFSET_800/UTILITY_SERVICE_CONTEXT_OFFSET_EXTENDED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_EXTENDED/UTILITY_STATUS_FLAG_ADDITIONAL/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_EXTENDED_SMALL/UTILITY_STATUS_FLAG_ADDITIONAL_COMPACT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_EXTENDED_MEDIUM/UTILITY_STATUS_FLAG_ADDITIONAL_MODERATE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_EXTENDED_LARGE/UTILITY_STATUS_FLAG_ADDITIONAL_EXPANDED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E38/UTILITY_STATUS_FLAG_OFFSET_E38/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E40/UTILITY_STATUS_FLAG_OFFSET_E40/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E50/UTILITY_STATUS_FLAG_OFFSET_E50/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E58/UTILITY_STATUS_FLAG_OFFSET_E58/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E60/UTILITY_STATUS_FLAG_OFFSET_E60/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E68/UTILITY_STATUS_FLAG_OFFSET_E68/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E70/UTILITY_STATUS_FLAG_OFFSET_E70/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E78/UTILITY_STATUS_FLAG_OFFSET_E78/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_E80/UTILITY_STATUS_FLAG_OFFSET_E80/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Ea8/UTILITY_STATUS_FLAG_OFFSET_EA8/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Eb0/UTILITY_STATUS_FLAG_OFFSET_EB0/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Eb8/UTILITY_STATUS_FLAG_OFFSET_EB8/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Ec0/UTILITY_STATUS_FLAG_OFFSET_EC0/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Ec8/UTILITY_STATUS_FLAG_OFFSET_EC8/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Ed0/UTILITY_STATUS_FLAG_OFFSET_ED0/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_Ee0/UTILITY_STATUS_FLAG_OFFSET_EE0/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_FLAG_F0/UTILITY_STATUS_FLAG_OFFSET_F0/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_ENABLED_FLAG_DECIMAL0/UTILITY_STATUS_ENABLED_FLAG_0/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STATUS_ENABLED_FLAG_DECIMAL8/UTILITY_STATUS_ENABLED_FLAG_8/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_SERVICE_HANDLER_OFFSET_600/UTILITY_SERVICE_HANDLER_OFFSET_EXTENDED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_SERVICE_CONTEXT_OFFSET_2E8/UTILITY_SERVICE_CONTEXT_OFFSET_ALTERNATE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STREAM_TYPE_ROOT/UTILITY_STREAM_TYPE_BASE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_STREAM_TYPE_KNOWN/UTILITY_STREAM_TYPE_RECOGNIZED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MAX_UINT32/UTILITY_MAXIMUM_UINT32/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_ALIGNMENT_PAGE_MASK/UTILITY_ALIGNMENT_PAGE_BOUNDARY_MASK/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_ALIGNMENT_MASK/UTILITY_ALIGNMENT_BOUNDARY_MASK/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_PAGE_SIZE/UTILITY_MEMORY_PAGE_SIZE_STANDARD/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_MEMORY_NEGATIVE_512MB/UTILITY_MEMORY_OFFSET_NEGATIVE_512MB/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_RESOURCE_FLAG_B8/UTILITY_RESOURCE_FLAG_OFFSET_B8/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLOAT_NEGATIVE_ONE/UTILITY_FLOAT_VALUE_NEGATIVE_ONE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLOAT_ONE/UTILITY_FLOAT_VALUE_POSITIVE_ONE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_RESERVED_BIT/UTILITY_FLAG_MASK_RESERVED/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_DEBUG_BIT/UTILITY_FLAG_MASK_DEBUG/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_WORDFF00/UTILITY_FLAG_MASK_16BIT_FF00/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_WORDFF/UTILITY_FLAG_MASK_16BIT_FF/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_WORDC000/UTILITY_FLAG_MASK_16BIT_C000/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_30_BITS/UTILITY_FLAG_MASK_30BIT/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_WORD7FFF/UTILITY_FLAG_MASK_16BIT_7FFF/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/UTILITY_FLAG_MASK_HIGH_BYTE_ONLY/UTILITY_FLAG_MASK_HIGH_BYTE/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c

# 美化全局变量名
sed -i 's/utility_exception_pointer/utility_global_exception_handler/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_data_primary/utility_global_primary_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_data_secondary/utility_global_secondary_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_data_tertiary/utility_global_tertiary_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_data_quaternary/utility_global_quaternary_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_data_auxiliary/utility_global_auxiliary_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_data_backup/utility_global_backup_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_status_flag_primary/utility_global_primary_status/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_main_pointer_secondary/utility_global_secondary_pointer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_global_status_flag_secondary/utility_global_secondary_status/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_context/utility_global_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_configuration_data/utility_global_configuration/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_state_machine_data/utility_global_state_machine/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_primary/utility_global_primary_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_secondary/utility_global_secondary_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_tertiary/utility_global_tertiary_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_quaternary/utility_global_quaternary_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_manager/utility_global_context_manager/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_network_context_primary/utility_global_primary_network_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_network_context_secondary/utility_global_secondary_network_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_network_context_tertiary/utility_global_tertiary_network_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_network_context_quaternary/utility_global_quaternary_network_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_resource_main/utility_global_primary_resource/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_resource_config/utility_global_resource_configuration/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_resource_tertiary/utility_global_tertiary_resource/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_resource_quaternary/utility_global_quaternary_resource/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_resource_manager/utility_global_resource_manager/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_memory_primary/utility_global_primary_memory/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_memory_secondary/utility_global_secondary_memory/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_memory_tertiary/utility_global_tertiary_memory/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_memory_quaternary/utility_global_quaternary_memory/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_memory_manager/utility_global_memory_manager/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_thread_primary/utility_global_primary_thread/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_thread_secondary/utility_global_secondary_thread/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_thread_tertiary/utility_global_tertiary_thread/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_thread_quaternary/utility_global_quaternary_thread/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_event_primary/utility_global_primary_event/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_event_secondary/utility_global_secondary_event/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_event_tertiary/utility_global_tertiary_event/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_event_quaternary/utility_global_quaternary_event/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_flag_primary/utility_global_primary_flag/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_flag_secondary/utility_global_secondary_flag/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_flag_tertiary/utility_global_tertiary_flag/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_flag_quaternary/utility_global_quaternary_flag/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_interface_primary/utility_global_primary_interface/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_interface_secondary/utility_global_secondary_interface/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_handler_primary/utility_global_primary_handler/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_handler_secondary/utility_global_secondary_handler/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_callback_primary/utility_global_primary_callback/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_callback_secondary/utility_global_secondary_callback/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_callback_tertiary/utility_global_tertiary_callback/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_queue_primary/utility_global_primary_queue/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_queue_secondary/utility_global_secondary_queue/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_queue_manager/utility_global_queue_manager/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_cache_manager/utility_global_cache_manager/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_stream_manager/utility_global_stream_manager/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_primary/utility_global_primary_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_secondary/utility_global_secondary_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_tertiary/utility_global_tertiary_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_quaternary/utility_global_quaternary_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_auxiliary/utility_global_auxiliary_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_backup/utility_global_backup_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_reserve/utility_global_reserved_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_septenary/utility_global_septenary_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_data_auxiliary/utility_global_auxiliary_system_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_reserved_area/utility_global_reserved_system_area/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_primary/utility_global_primary_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_secondary/utility_global_secondary_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_tertiary/utility_global_tertiary_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_quaternary/utility_global_quaternary_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_auxiliary/utility_global_auxiliary_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_data_stream_primary/utility_global_primary_data_stream/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_data_stream_secondary/utility_global_secondary_data_stream/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_data_stream_tertiary/utility_global_tertiary_data_stream/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_data_stream_quaternary/utility_global_quaternary_data_stream/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_data_stream_auxiliary/utility_global_auxiliary_data_stream/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_data_stream_backup/utility_global_backup_data_stream/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_resource_pointer_secondary/utility_global_secondary_resource_pointer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_control_secondary/utility_global_secondary_control/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_control_tertiary/utility_global_tertiary_control/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_control_quaternary/utility_global_quaternary_control/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_control_auxiliary/utility_global_auxiliary_control/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_data_reserved/utility_global_reserved_system_data/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_communication_reserved/utility_global_reserved_communication/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_communication_primary/utility_global_primary_communication/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_communication_secondary/utility_global_secondary_communication/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_communication_tertiary/utility_global_tertiary_communication/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_communication_quaternary/utility_global_quaternary_communication/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_state_reserved/utility_global_reserved_system_state/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_state_primary/utility_global_primary_system_state/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_state_secondary/utility_global_secondary_system_state/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_state_tertiary/utility_global_tertiary_system_state/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_system_state_quaternary/utility_global_quaternary_system_state/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_advanced_pointer/utility_global_advanced_pointer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_reserved/utility_global_reserved_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_primary/utility_global_primary_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_secondary/utility_global_secondary_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_tertiary/utility_global_tertiary_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_quaternary/utility_global_quaternary_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_auxiliary/utility_global_auxiliary_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_advanced_backup/utility_global_backup_advanced_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_buffer_extended_reserve/utility_global_reserved_extended_buffer/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_primary/utility_global_primary_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_secondary/utility_global_secondary_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_tertiary/utility_global_tertiary_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_quaternary/utility_global_quaternary_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_auxiliary/utility_global_auxiliary_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_backup/utility_global_backup_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_reserve/utility_global_reserved_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c
sed -i 's/utility_context_system_extended/utility_global_extended_system_context/g' /dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c

echo "06_utilities.c 文件语义化美化完成"