#!/bin/bash

# 美化04_ui_system.c文件脚本
# 功能：将非语义化的变量名替换为语义化名称
# 日期：2025-09-01

INPUT_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c"
TEMP_FILE="/dev/shm/mountblade-code/scripts/temp_04_ui_system.c"

# 创建临时文件
cp "$INPUT_FILE" "$TEMP_FILE"

# UI系统栈相关变量名替换
sed -i 's/ui_stack_information_buffer_size_value/ui_system_stack_buffer_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_information_buffer_large_size/ui_system_stack_buffer_large_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_validation_flag/ui_system_stack_validation_flag/g' "$TEMP_FILE"
sed -i 's/ui_stack_control_data_mask/ui_system_stack_control_mask/g' "$TEMP_FILE"
sed -i 's/ui_stack_format_storage/ui_system_stack_format_buffer/g' "$TEMP_FILE"
sed -i 's/ui_stack_parameter_value_buffer/ui_system_stack_param_buffer/g' "$TEMP_FILE"
sed -i 's/ui_stack_backup_short_pointer/ui_system_stack_backup_ptr/g' "$TEMP_FILE"
sed -i 's/ui_stack_buffer_data_extended/ui_system_stack_extended_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_handler_index/ui_system_stack_handler_index/g' "$TEMP_FILE"
sed -i 's/ui_stack_config_mask_value/ui_system_stack_config_mask/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_mask_primary/ui_system_stack_variable_mask/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_base_address/ui_system_stack_base_addr/g' "$TEMP_FILE"
sed -i 's/ui_stack_mask_data/ui_system_stack_mask_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_unsigned_data_array/ui_system_stack_unsigned_array/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_extended_ptr_long/ui_system_stack_extended_ptr/g' "$TEMP_FILE"
sed -i 's/ui_stack_mask_data/ui_system_stack_mask/g' "$TEMP_FILE"
sed -i 's/ui_stack_param/ui_system_stack_param/g' "$TEMP_FILE"
sed -i 's/ui_stack_ext_buf_size/ui_system_stack_buffer_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_extended_data_buffer_data_small/ui_system_stack_small_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_pointer_buffer_start/ui_system_stack_ptr_start/g' "$TEMP_FILE"
sed -i 's/ui_stack_pointer_buffer_end/ui_system_stack_ptr_end/g' "$TEMP_FILE"
sed -i 's/ui_stack_buffer_data_primary/ui_system_stack_primary_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_extended_data_buffer_buffer_size/ui_system_stack_ext_buffer_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_pointer_data_buffer/ui_system_stack_data_buffer/g' "$TEMP_FILE"
sed -i 's/ui_stack_operation_flag/ui_system_stack_operation_flag/g' "$TEMP_FILE"
sed -i 's/ui_stack_extended_data_buffer_pointer/ui_system_stack_ext_ptr/g' "$TEMP_FILE"
sed -i 's/ui_stack_validation_flag/ui_system_stack_validation_flag/g' "$TEMP_FILE"
sed -i 's/ui_stack_standard_buffer_size/ui_system_stack_std_buffer_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_information_buffer_small/ui_system_stack_small_buffer/g' "$TEMP_FILE"
sed -i 's/ui_stack_flag_mask_value/ui_system_stack_flag_mask/g' "$TEMP_FILE"
sed -i 's/ui_stack_information_buffer_large/ui_system_stack_large_buffer/g' "$TEMP_FILE"
sed -i 's/ui_stack_information_buffer_xor_value/ui_system_stack_xor_value/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_uint_d10/ui_system_stack_uint_d10/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_uint_d08/ui_system_stack_uint_d08/g' "$TEMP_FILE"
sed -i 's/ui_stack_mask_data_ptr/ui_system_stack_mask_ptr/g' "$TEMP_FILE"
sed -i 's/ui_stack_ctrl_data_value/ui_system_stack_ctrl_value/g' "$TEMP_FILE"
sed -i 's/ui_stack_buffer_size/ui_system_stack_buffer_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_temp_data_28/ui_system_stack_temp_28/g' "$TEMP_FILE"
sed -i 's/ui_stack_ext_buf_size/ui_system_stack_ext_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_control_data_mask/ui_system_stack_ctrl_mask/g' "$TEMP_FILE"
sed -i 's/ui_stack_return_value_16/ui_system_stack_ret_16/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_uint_c/ui_system_stack_uint_c/g' "$TEMP_FILE"
sed -i 's/ui_pointer_stack_variable_b8/ui_system_stack_var_b8/g' "$TEMP_FILE"
sed -i 's/ui_pointer_stack_variable_b0/ui_system_stack_var_b0/g' "$TEMP_FILE"
sed -i 's/ui_stack_processing_counter/ui_system_stack_counter/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_uint_a0/ui_system_stack_uint_a0/g' "$TEMP_FILE"
sed -i 's/ui_stack_buffer_size_152/ui_system_stack_size_152/g' "$TEMP_FILE"
sed -i 's/ui_stack_pointer_buffer_end/ui_system_stack_ptr_end/g' "$TEMP_FILE"
sed -i 's/ui_stack_buffer_pointer_120/ui_system_stack_ptr_120/g' "$TEMP_FILE"
sed -i 's/ui_stack_buffer_capacity_80/ui_system_stack_capacity_80/g' "$TEMP_FILE"
sed -i 's/ui_stack_unsigned_data_data_primary/ui_system_stack_primary/g' "$TEMP_FILE"
sed -i 's/ui_stack_temporary_register_value/ui_system_stack_temp_reg/g' "$TEMP_FILE"
sed -i 's/ui_stack_system_register_value/ui_system_stack_reg_value/g' "$TEMP_FILE"
sed -i 's/ui_stack_resource_config/ui_system_stack_resource_config/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_uint_2f8/ui_system_stack_var_2f8/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_uint_2f0/ui_system_stack_var_2f0/g' "$TEMP_FILE"
sed -i 's/ui_stack_data_value_2e8/ui_system_stack_value_2e8/g' "$TEMP_FILE"
sed -i 's/ui_stack_data_pointer_2e0/ui_system_stack_ptr_2e0/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_uint_2d8/ui_system_stack_var_2d8/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_uint_2d0/ui_system_stack_var_2d0/g' "$TEMP_FILE"
sed -i 's/ui_stack_unsigned_data_data_tertiary8/ui_system_stack_tertiary8/g' "$TEMP_FILE"
sed -i 's/ui_stack_unsigned_data_data_tertiary0/ui_system_stack_tertiary0/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_uint_2b8/ui_system_stack_var_2b8/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_uint_2b0/ui_system_stack_var_2b0/g' "$TEMP_FILE"
sed -i 's/ui_stack_data_value_2a8/ui_system_stack_value_2a8/g' "$TEMP_FILE"
sed -i 's/ui_stack_data_pointer_2a0/ui_system_stack_ptr_2a0/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_event_counter/ui_system_stack_event_counter/g' "$TEMP_FILE"
sed -i 's/ui_stack_pointer_callback_data_primary/ui_system_stack_callback_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_data_size/ui_system_stack_data_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_information_buffer_size_value/ui_system_stack_buffer_size_value/g' "$TEMP_FILE"
sed -i 's/ui_stack_config_mask_value/ui_system_stack_config_mask_value/g' "$TEMP_FILE"
sed -i 's/ui_stack_mask_data_value/ui_system_stack_mask_value/g' "$TEMP_FILE"
sed -i 's/pui_stack_event_handler_ptr/ui_system_stack_event_ptr/g' "$TEMP_FILE"
sed -i 's/pui_stack_variable_data_callback_data/ui_system_stack_callback_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_event_id/ui_system_stack_event_id/g' "$TEMP_FILE"
sed -i 's/ui_stack_variable_data_callback_size/ui_system_stack_callback_size/g' "$TEMP_FILE"
sed -i 's/ui_stack_mask_data/ui_system_stack_mask/g' "$TEMP_FILE"

# UI系统其他变量名替换
sed -i 's/ui_info_buffer_array/ui_system_info_buffer/g' "$TEMP_FILE"
sed -i 's/ui_callback_handle/ui_system_callback_handle/g' "$TEMP_FILE"
sed -i 's/ui_widget_manager/ui_system_widget_manager/g' "$TEMP_FILE"
sed -i 's/ui_event_data/ui_system_event_data/g' "$TEMP_FILE"
sed -i 's/ui_event_attributes/ui_system_event_attributes/g' "$TEMP_FILE"
sed -i 's/ui_loop_idx/ui_system_loop_index/g' "$TEMP_FILE"
sed -i 's/ui_event_idx/ui_system_event_index/g' "$TEMP_FILE"
sed -i 's/ui_long_counter/ui_system_long_counter/g' "$TEMP_FILE"
sed -i 's/ui_char_val/ui_system_char_value/g' "$TEMP_FILE"
sed -i 's/ui_char_pointer_array_data/ui_system_char_ptr_array/g' "$TEMP_FILE"
sed -i 's/ui_op_status/ui_system_operation_status/g' "$TEMP_FILE"
sed -i 's/ui_sys_callback_ptr/ui_system_callback_ptr/g' "$TEMP_FILE"
sed -i 's/ui_event_data_pointer_secondary/ui_system_event_data_secondary/g' "$TEMP_FILE"
sed -i 's/ui_event_parameter_stack/ui_system_event_param_stack/g' "$TEMP_FILE"
sed -i 's/ui_event_category_data/ui_system_event_category/g' "$TEMP_FILE"
sed -i 's/ui_event_data_ptr/ui_system_event_data_ptr/g' "$TEMP_FILE"
sed -i 's/ui_task_id/ui_system_task_id/g' "$TEMP_FILE"
sed -i 's/ui_task_idx_ref/ui_system_task_idx_ref/g' "$TEMP_FILE"
sed -i 's/ui_stack_fmt_temp/ui_system_stack_fmt_temp/g' "$TEMP_FILE"
sed -i 's/ui_stack_base_address/ui_system_stack_base_addr/g' "$TEMP_FILE"
sed -i 's/ui_system_register/ui_system_register/g' "$TEMP_FILE"
sed -i 's/ui_stack_protection_mask/ui_system_stack_protection_mask/g' "$TEMP_FILE"
sed -i 's/ui_parameter_value/ui_system_parameter_value/g' "$TEMP_FILE"
sed -i 's/ui_global_state/ui_system_global_state/g' "$TEMP_FILE"
sed -i 's/ui_stack_ctrl_data/ui_system_stack_ctrl_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_return_value_28/ui_system_stack_ret_28/g' "$TEMP_FILE"
sed -i 's/ui_system_configuration/ui_system_configuration/g' "$TEMP_FILE"
sed -i 's/ui_widget_manager_ptr/ui_system_widget_manager_ptr/g' "$TEMP_FILE"
sed -i 's/pui_widget_manager_ptr/ui_system_widget_manager_ptr/g' "$TEMP_FILE"
sed -i 's/ui_event_id/ui_system_event_id/g' "$TEMP_FILE"
sed -i 's/ui_system_event_context/ui_system_event_context/g' "$TEMP_FILE"
sed -i 's/pui_stack_information_buffer_mask_data/ui_system_stack_mask_data/g' "$TEMP_FILE"
sed -i 's/ui_stack_return_value_28/ui_system_stack_ret_28/g' "$TEMP_FILE"
sed -i 's/ui_layout_resource_type/ui_system_layout_resource_type/g' "$TEMP_FILE"
sed -i 's/ui_resource_load_type/ui_system_resource_load_type/g' "$TEMP_FILE"
sed -i 's/ui_system_base_address/ui_system_base_address/g' "$TEMP_FILE"
sed -i 's/ui_system_memory_allocator/ui_system_memory_allocator/g' "$TEMP_FILE"
sed -i 's/ui_system_update_state/ui_system_update_state/g' "$TEMP_FILE"

# 将修改后的文件复制回原位置
cp "$TEMP_FILE" "$INPUT_FILE"

# 删除临时文件
rm "$TEMP_FILE"

echo "04_ui_system.c文件美化完成"