#!/bin/bash

# 美化网络系统代码中的标签名
# 将非语义化的标签名替换为语义化名称

file_path="/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c"

# 创建临时文件
temp_file="${file_path}.tmp"

# 复制原文件到临时文件
cp "$file_path" "$temp_file"

# 替换主要标签名
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_CLEANUP_START/NETWORK_LABEL_CLEANUP_START/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_RETRY_PROCESS_START/NETWORK_LABEL_RETRY_PROCESS_START/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_CLEANUP/NETWORK_LABEL_CLEANUP_PROCESS/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_PROCESS_DATA/NETWORK_LABEL_CONNECTION_HANDLER_PROCESS_DATA/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_PROCESS_PACKET/NETWORK_LABEL_CONNECTION_HANDLER_PROCESS_PACKET/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_VALIDATE_PACKET/NETWORK_LABEL_CONNECTION_HANDLER_VALIDATE_PACKET/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_HANDLER_QUEUE_PACKET/NETWORK_LABEL_CONNECTION_HANDLER_QUEUE_PACKET/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_VALIDATE_PRIMARY_SUCCESS/NETWORK_LABEL_CONNECTION_VALIDATE_PRIMARY_SUCCESS/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_VALIDATE_SECONDARY_SUCCESS/NETWORK_LABEL_CONNECTION_VALIDATE_SECONDARY_SUCCESS/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_STATE_PRIMARY_FINISHED/NETWORK_LABEL_CONNECTION_STATE_PRIMARY_FINISHED/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_STATE_SECONDARY_FINISHED/NETWORK_LABEL_CONNECTION_STATE_SECONDARY_FINISHED/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_VALIDATE_SUCCESS/NETWORK_LABEL_CONNECTION_VALIDATE_SUCCESS/g' "$temp_file"
sed -i 's/LAB_NETWORK_CONNECTION_VALIDATE_FAILED/NETWORK_LABEL_CONNECTION_VALIDATE_FAILED/g' "$temp_file"
sed -i 's/LAB_NETWORK_VALIDATE_DATA_SUCCESS/NETWORK_LABEL_VALIDATE_DATA_SUCCESS/g' "$temp_file"
sed -i 's/LAB_NETWORK_VALIDATE_DATA_FAILURE/NETWORK_LABEL_VALIDATE_DATA_FAILURE/g' "$temp_file"

# 替换其他常见标签
sed -i 's/LAB_NETWORK_PACKET_PROCESS_SECONDARY_DONE/NETWORK_LABEL_PACKET_PROCESS_SECONDARY_DONE/g' "$temp_file"
sed -i 's/LAB_NETWORK_PACKET_PROCESS_PRIMARY_DONE/NETWORK_LABEL_PACKET_PROCESS_PRIMARY_DONE/g' "$temp_file"
sed -i 's/LAB_NETWORK_HANDLE_PACKET_PRIMARY_DONE/NETWORK_LABEL_HANDLE_PACKET_PRIMARY_DONE/g' "$temp_file"
sed -i 's/LAB_NETWORK_HANDLE_PACKET_SECONDARY/NETWORK_LABEL_HANDLE_PACKET_SECONDARY/g' "$temp_file"
sed -i 's/LAB_NETWORK_PACKET_HANDLER_TRANSFER_SECONDARY/NETWORK_LABEL_PACKET_HANDLER_TRANSFER_SECONDARY/g' "$temp_file"
sed -i 's/LAB_NETWORK_PACKET_HANDLER_TRANSFER_PRIMARY/NETWORK_LABEL_PACKET_HANDLER_TRANSFER_PRIMARY/g' "$temp_file"

# 替换十六进制常量（一些常见的）
sed -i 's/0xffff7eff/NETWORK_MASK_FLAG_BLOCKING_CLEAR/g' "$temp_file"
sed -i 's/0xfeffffff/NETWORK_MASK_CONNECTION_ENABLED/g' "$temp_file"
sed -i 's/0xffffbfff/NETWORK_MASK_RETURN_VALUE_TEMP/g' "$temp_file"
sed -i 's/0xffffb7ff/NETWORK_MASK_ENCRYPTION_CONFIG/g' "$temp_file"
sed -i 's/0xfffffffc/NETWORK_MASK_ALIGNMENT_4BYTE/g' "$temp_file"
sed -i 's/0x1000/NETWORK_FLAG_ENABLED_SIZE/g' "$temp_file"

# 替换文件
mv "$temp_file" "$file_path"

echo "网络系统标签美化完成"