#!/bin/bash

# 美化01_initialization.c文件中的十六进制常量
# 简化实现：仅替换常见的十六进制常量为语义化名称

INPUT_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/01_initialization.c"
TEMP_FILE="/tmp/01_initialization_temp.c"

# 备份原始文件
cp "$INPUT_FILE" "$INPUT_FILE.backup"

# 美化十六进制常量为语义化名称
sed -i 's/SYSTEM_INIT_ERROR_GENERICffffffff/SYSTEM_INIT_ERROR_GENERIC_INVALID_HANDLE/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_ERROR_GENERIC00000000/SYSTEM_INIT_ERROR_GENERIC_SUCCESS/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_ERROR_GENERICffc00000/SYSTEM_INIT_ERROR_GENERIC_MEMORY_MASK/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_ERROR_GENERICffffffe0/SYSTEM_INIT_ERROR_GENERIC_ALIGNMENT_MASK/g' "$INPUT_FILE"

# 美化标志常量
sed -i 's/SYSTEM_INIT_FLAG_INITIALIZEDe676f6c/SYSTEM_INIT_FLAG_INITIALIZED_COLOR/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_FLAG_INITIALIZEDe676966/SYSTEM_INIT_FLAG_INITIALIZED_ACTIVE/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_FLAG_INITIALIZEDf6e6f6974616d6f/SYSTEM_INIT_FLAG_INITIALIZED_MODULE/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_FLAG_INITIALIZEDe2f2e2e/SYSTEM_INIT_FLAG_INITIALIZED_ENGINE/g' "$INPUT_FILE"

# 美化警告标签
sed -i 's/SYSTEM_INIT_VALUE_CHAR_NULL00180045b59/SYSTEM_INIT_WARNING_JUMP_TABLE_45b59/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_VALUE_CHAR_NULL00180045f19/SYSTEM_INIT_WARNING_JUMP_TABLE_45f19/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_VALUE_CHAR_NULL001800460x10b7/SYSTEM_INIT_WARNING_JUMP_TABLE_460b7/g' "$INPUT_FILE"
sed -i 's/SYSTEM_INIT_VALUE_CHAR_NULL001800472a0/SYSTEM_INIT_WARNING_JUMP_TABLE_472a0/g' "$INPUT_FILE"

echo "美化完成"