#!/bin/bash

# 01_initialization.c 文件语义化美化脚本
# 2025年8月30日最终批次系统栈值和标志常量语义化美化工作

# 定义源文件路径
SOURCE_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/01_initialization.c"

# 备份原文件
cp "$SOURCE_FILE" "$SOURCE_FILE.backup"

# 替换系统栈值常量定义
sed -i 's/#define SYSTEM_INIT_VALUE_STACK_11/#define SYSTEM_INIT_STACK_VALUE_MINIMAL/g' "$SOURCE_FILE"
sed -i 's/#define SYSTEM_INIT_VALUE_STACK_12/#define SYSTEM_INIT_STACK_VALUE_SMALL/g' "$SOURCE_FILE"
sed -i 's/#define SYSTEM_INIT_VALUE_STACK_13/#define SYSTEM_INIT_STACK_VALUE_MEDIUM/g' "$SOURCE_FILE"
sed -i 's/#define SYSTEM_INIT_VALUE_STACK_14/#define SYSTEM_INIT_STACK_VALUE_LARGE/g' "$SOURCE_FILE"
sed -i 's/#define SYSTEM_INIT_VALUE_STACK_15/#define SYSTEM_INIT_STACK_VALUE_EXTENDED/g' "$SOURCE_FILE"

# 替换系统标志常量定义
sed -i 's/SYSTEM_INIT_FLAG_ENABLED1/SYSTEM_INIT_FLAG_PRIMARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED2/SYSTEM_INIT_FLAG_SECONDARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED3/SYSTEM_INIT_FLAG_TERTIARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED4/SYSTEM_INIT_FLAG_QUATERNARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED5/SYSTEM_INIT_FLAG_QUINARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED6/SYSTEM_INIT_FLAG_SENARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED7/SYSTEM_INIT_FLAG_SEPTENARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLED8/SYSTEM_INIT_FLAG_OCTONARY_ENABLED/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLEDa/SYSTEM_INIT_FLAG_INITIALIZED_CONFIG/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLEDb/SYSTEM_INIT_FLAG_INITIALIZED_PRIMARY/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLEDc/SYSTEM_INIT_FLAG_INITIALIZED_SECONDARY/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLEDd/SYSTEM_INIT_FLAG_INITIALIZED_TERTIARY/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_FLAG_ENABLEDe/SYSTEM_INIT_FLAG_INITIALIZED_QUATERNARY/g' "$SOURCE_FILE"

# 替换系统栈值常量使用
sed -i 's/SYSTEM_INIT_VALUE_STACK_11/SYSTEM_INIT_STACK_VALUE_MINIMAL/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_VALUE_STACK_12/SYSTEM_INIT_STACK_VALUE_SMALL/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_VALUE_STACK_13/SYSTEM_INIT_STACK_VALUE_MEDIUM/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_VALUE_STACK_14/SYSTEM_INIT_STACK_VALUE_LARGE/g' "$SOURCE_FILE"
sed -i 's/SYSTEM_INIT_VALUE_STACK_15/SYSTEM_INIT_STACK_VALUE_EXTENDED/g' "$SOURCE_FILE"

echo "01_initialization.c 文件语义化美化完成"