#!/bin/bash

# UI系统第三阶段美化脚本
# 替换布尔变量和其他特殊变量

# 布尔变量名替换模式
REPLACE_PATTERNS=(
    "booluiui_stack_var_b08:ui_stack_bool_flag_b08"
    "booluiui_stack_var_a48:ui_stack_bool_flag_a48"
    "ui_bool_flag:ui_boolean_flag"
    "ui_system_bool_flag:ui_system_boolean_flag"
    "ui_event_bool_flag:ui_event_boolean_flag"
    "ui_task_bool_flag:ui_task_boolean_flag"
    "ui_widget_bool_flag:ui_widget_boolean_flag"
    "ui_handler_bool_flag:ui_handler_boolean_flag"
    "ui_context_bool_flag:ui_context_boolean_flag"
    "ui_data_bool_flag:ui_data_boolean_flag"
    "ui_flag_bool_flag:ui_flag_boolean_flag"
    "ui_buffer_bool_flag:ui_buffer_boolean_flag"
    "ui_config_bool_flag:ui_config_boolean_flag"
    "ui_stack_bool_flag:ui_stack_boolean_flag"
    "ui_ptr_bool_flag:ui_ptr_boolean_flag"
    "ui_id_bool_flag:ui_id_boolean_flag"
    "ui_index_bool_flag:ui_index_boolean_flag"
    "ui_count_bool_flag:ui_count_boolean_flag"
    "ui_size_bool_flag:ui_size_boolean_flag"
    "ui_length_bool_flag:ui_length_boolean_flag"
    "ui_offset_bool_flag:ui_offset_boolean_flag"
    "ui_address_bool_flag:ui_address_boolean_flag"
    "ui_value_bool_flag:ui_value_boolean_flag"
    "ui_state_bool_flag:ui_state_boolean_flag"
    "ui_status_bool_flag:ui_status_boolean_flag"
    "ui_result_bool_flag:ui_result_boolean_flag"
    "ui_error_bool_flag:ui_error_boolean_flag"
    "ui_success_bool_flag:ui_success_boolean_flag"
    "ui_failure_bool_flag:ui_failure_boolean_flag"
    "ui_active_bool_flag:ui_active_boolean_flag"
    "ui_inactive_bool_flag:ui_inactive_boolean_flag"
    "ui_enabled_bool_flag:ui_enabled_boolean_flag"
    "ui_disabled_bool_flag:ui_disabled_boolean_flag"
    "ui_visible_bool_flag:ui_visible_boolean_flag"
    "ui_hidden_bool_flag:ui_hidden_boolean_flag"
    "ui_focus_bool_flag:ui_focus_boolean_flag"
    "ui_blur_bool_flag:ui_blur_boolean_flag"
    "ui_hover_bool_flag:ui_hover_boolean_flag"
    "ui_click_bool_flag:ui_click_boolean_flag"
    "ui_drag_bool_flag:ui_drag_boolean_flag"
    "ui_drop_bool_flag:ui_drop_boolean_flag"
    "ui_scroll_bool_flag:ui_scroll_boolean_flag"
    "ui_resize_bool_flag:ui_resize_boolean_flag"
    "ui_move_bool_flag:ui_move_boolean_flag"
    "ui_create_bool_flag:ui_create_boolean_flag"
    "ui_destroy_bool_flag:ui_destroy_boolean_flag"
    "ui_update_bool_flag:ui_update_boolean_flag"
    "ui_render_bool_flag:ui_render_boolean_flag"
    "ui_draw_bool_flag:ui_draw_boolean_flag"
    "ui_paint_bool_flag:ui_paint_boolean_flag"
    "ui_clear_bool_flag:ui_clear_boolean_flag"
    "ui_fill_bool_flag:ui_fill_boolean_flag"
    "ui_stroke_bool_flag:ui_stroke_boolean_flag"
    "ui_text_bool_flag:ui_text_boolean_flag"
    "ui_image_bool_flag:ui_image_boolean_flag"
    "ui_icon_bool_flag:ui_icon_boolean_flag"
    "ui_button_bool_flag:ui_button_boolean_flag"
    "ui_input_bool_flag:ui_input_boolean_flag"
    "ui_select_bool_flag:ui_select_boolean_flag"
    "ui_checkbox_bool_flag:ui_checkbox_boolean_flag"
    "ui_radio_bool_flag:ui_radio_boolean_flag"
    "ui_slider_bool_flag:ui_slider_boolean_flag"
    "ui_progress_bool_flag:ui_progress_boolean_flag"
    "ui_dialog_bool_flag:ui_dialog_boolean_flag"
    "ui_window_bool_flag:ui_window_boolean_flag"
    "ui_panel_bool_flag:ui_panel_boolean_flag"
    "ui_container_bool_flag:ui_container_boolean_flag"
    "ui_layout_bool_flag:ui_layout_boolean_flag"
    "ui_grid_bool_flag:ui_grid_boolean_flag"
    "ui_flex_bool_flag:ui_flex_boolean_flag"
    "ui_absolute_bool_flag:ui_absolute_boolean_flag"
    "ui_relative_bool_flag:ui_relative_boolean_flag"
    "ui_fixed_bool_flag:ui_fixed_boolean_flag"
    "ui_fluid_bool_flag:ui_fluid_boolean_flag"
    "ui_responsive_bool_flag:ui_responsive_boolean_flag"
    "ui_adaptive_bool_flag:ui_adaptive_boolean_flag"
    "ui_dynamic_bool_flag:ui_dynamic_boolean_flag"
    "ui_static_bool_flag:ui_static_boolean_flag"
    "ui_constant_bool_flag:ui_constant_boolean_flag"
    "ui_variable_bool_flag:ui_variable_boolean_flag"
    "ui_global_bool_flag:ui_global_boolean_flag"
    "ui_local_bool_flag:ui_local_boolean_flag"
    "ui_member_bool_flag:ui_member_boolean_flag"
    "ui_static_bool_flag:ui_static_boolean_flag"
    "ui_auto_bool_flag:ui_auto_boolean_flag"
    "ui_manual_bool_flag:ui_manual_boolean_flag"
)

# 执行替换
for pattern in "${REPLACE_PATTERNS[@]}"; do
    old_name=$(echo "$pattern" | cut -d':' -f1)
    new_name=$(echo "$pattern" | cut -d':' -f2)
    
    # 使用sed进行替换，只替换整个单词匹配
    sed -i "s/\b$old_name\b/$new_name/g" /dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c
    echo "替换: $old_name -> $new_name"
done

echo "布尔变量名替换完成"