#!/bin/bash

# 01_initialization.c 常量美化脚本
# 用于替换通用常量值为具体语义化值

# 定义输入文件
INPUT_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/01_initialization.c"
TEMP_FILE="/tmp/initialization_temp.c"

# 创建临时文件
cp "$INPUT_FILE" "$TEMP_FILE"

# 1. 替换SYSTEM_INIT_STANDARD_SIZE为合适的值
# 对于魔法数字，使用合理的默认值
sed -i 's/SYSTEM_INIT_STANDARD_SIZE/0x100/g' "$TEMP_FILE"

# 2. 修复不规范的常量名
# 修复十六进制常量名
sed -i 's/^#define 0x100_F7SYSTEM_INIT_STANDARD_SIZE65 0xF7SYSTEM_INIT_STANDARD_SIZE65/#define SYSTEM_INIT_FLAG_EXTENDED_F7 0xF765/g' "$TEMP_FILE"
sed -i 's/^#define 0x100_F7SYSTEM_INIT_STANDARD_SIZE6568701061726010 0xF7SYSTEM_INIT_STANDARD_SIZE6568701061726010/#define SYSTEM_INIT_FLAG_EXTENDED_F7_STRING 0xF76568701061726010/g' "$TEMP_FILE"
sed -i 's/^#define 0x100_DSYSTEM_INIT_STANDARD_SIZE 0xDSYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_FLAG_EXTENDED_D 0xD100/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_FLAG_INITIALIZEDe6f6SYSTEM_INIT_STANDARD_SIZE7010 0xe6f6SYSTEM_INIT_STANDARD_SIZE7010/#define SYSTEM_INIT_FLAG_INITIALIZED_E6F6 0xe6f61007010/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_FLAG_INITIALIZEDSYSTEM_INIT_STANDARD_SIZE SYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_FLAG_INITIALIZED_STANDARD 0x100/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_FLAG_SECONDARY_ENABLEDSYSTEM_INIT_STANDARD_SIZE SYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_FLAG_SECONDARY_ENABLED_STANDARD 0x100/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_SIZE_POINTERSYSTEM_INIT_STANDARD_SIZE SYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_SIZE_POINTER_STANDARD 0x100/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_SIZE_MEMORY_CHUNK_STANDARD SYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_SIZE_MEMORY_CHUNK_STANDARD 0x100/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_VALUE_DEFAULT_TEMP SYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_VALUE_DEFAULT_TEMP 0x100/g' "$TEMP_FILE"
sed -i 's/^#define SYSTEM_INIT_VALUE_CONFIG_PRIMARY 0x65747SYSTEM_INIT_STANDARD_SIZE/#define SYSTEM_INIT_VALUE_CONFIG_PRIMARY 0x65747100/g' "$TEMP_FILE"
sed -i 's/^#define 0x100 0x1002/#define SYSTEM_INIT_SIZE_STANDARD_BUFFER 0x1002/g' "$TEMP_FILE"
sed -i 's/^#define 0x200 0x1002/#define SYSTEM_INIT_SIZE_EXTENDED_BUFFER 0x1002/g' "$TEMP_FILE"
sed -i 's/^#define 0x01_PRIMARY   0x80c91700/#define SYSTEM_INIT_FLAG_GRAPHICS_PRIMARY 0x80c91700/g' "$TEMP_FILE"
sed -i 's/^#define 0x01_SECONDARY   0x80c91800/#define SYSTEM_INIT_FLAG_GRAPHICS_SECONDARY 0x80c91800/g' "$TEMP_FILE"
sed -i 's/^#define 0x01   0x80c91910/#define SYSTEM_INIT_FLAG_GRAPHICS_EXTENDED 0x80c91910/g' "$TEMP_FILE"
sed -i 's/^#define 0            0/#define SYSTEM_INIT_ARRAY_INDEX_PRIMARY 0/g' "$TEMP_FILE"
sed -i 's/^#define 0x07          7/#define SYSTEM_INIT_STACK_VALUE_SEVEN 7/g' "$TEMP_FILE"

# 3. 修复一些特殊的常量定义
sed -i 's/SYSTEM_INIT_OFFSET_STACK_FRAME_SYSTEM_INIT_OFFSET_STACK_FRAME_0xD0/SYSTEM_INIT_OFFSET_STACK_FRAME_D0/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_PRIMARY0/SYSTEM_INIT_CONTEXT_INDEX_PRIMARY_0/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_PRIMARY4/SYSTEM_INIT_CONTEXT_INDEX_PRIMARY_4/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_PRIMARY5/SYSTEM_INIT_CONTEXT_INDEX_PRIMARY_5/g' "$TEMP_FILE"
sed -i 's/0x0100/0x100/g' "$TEMP_FILE"
sed -i 's/0x010/0x10/g' "$TEMP_FILE"
sed -i 's/0x014/0x14/g' "$TEMP_FILE"
sed -i 's/0x0A/0x0a/g' "$TEMP_FILE"
sed -i 's/0x0F0/0x0f0/g' "$TEMP_FILE"
sed -i 's/0x0F4/0x0f4/g' "$TEMP_FILE"
sed -i 's/0x0C8/0x0c8/g' "$TEMP_FILE"
sed -i 's/0x0C/0x0c/g' "$TEMP_FILE"

# 4. 修复一些错误的魔法数字替换
sed -i 's/SYSTEM_INIT_MAGIC_COOKIE_ENGINE_SYSTEM_INIT_STANDARD_SIZE/SYSTEM_INIT_MAGIC_COOKIE_ENGINE_STANDARD/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_MAGIC_COOKIE_PREFAB_SYSTEM_INIT_STANDARD_SIZE/SYSTEM_INIT_MAGIC_COOKIE_PREFAB_STANDARD/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_FLOAT_COEFFICIENT_SYSTEM_INIT_STANDARD_SIZE/SYSTEM_INIT_FLOAT_COEFFICIENT_STANDARD/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_MAGIC_STRING_TERMINATOR/SYSTEM_INIT_MAGIC_STRING_TERMINATOR_STANDARD/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_OFFSET_STACK_FRAME_SYSTEM_INIT_OFFSET_STACK_FRAME_0xD0/SYSTEM_INIT_OFFSET_STACK_FRAME_D0/g' "$TEMP_FILE"

# 5. 替换文件中的其他错误引用
sed -i 's/SYSTEM_INIT_OFFSET_STACK_A4/SYSTEM_INIT_OFFSET_STACK_A4/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_CENTER_X/SYSTEM_INIT_CONTEXT_INDEX_CENTER_X/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_CENTER_Y/SYSTEM_INIT_CONTEXT_INDEX_CENTER_Y/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_CENTER_Z/SYSTEM_INIT_CONTEXT_INDEX_CENTER_Z/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_CONTEXT_INDEX_RADIUS/SYSTEM_INIT_CONTEXT_INDEX_RADIUS/g' "$TEMP_FILE"

# 6. 修复一些特殊的魔法字符串
sed -i 's/SYSTEM_INIT_OFFSET_GLOBAL_PRIMARY/SYSTEM_INIT_OFFSET_GLOBAL_7AB8/g' "$TEMP_FILE"
sed -i 's/SYSTEM_INIT_OFFSET_GLOBAL_SECONDARY/SYSTEM_INIT_OFFSET_GLOBAL_560/g' "$TEMP_FILE"

# 7. 修复一些特殊的值
sed -i 's/0x100201012e01022e010176/0x100201012e01022e010176/g' "$TEMP_FILE"
sed -i 's/1.8446744070x100709552e+19/1.8446744073709552e+19/g' "$TEMP_FILE"

# 替换原文件
mv "$TEMP_FILE" "$INPUT_FILE"

echo "01_initialization.c 常量美化完成"