#!/bin/bash

# 美化05_networking.c文件中的十六进制常量
# 将十六进制常量替换为语义化名称

FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c"

# 备份原始文件
cp "$FILE" "$FILE.bak"

# 添加语义化常量定义
sed -i '/^#define NETWORK_CONFIG_MASK 0xffffc000/a\
\
// 网络系统常量语义化定义\
#define NETWORK_MAX_SIZE_FFFFFFFF 0xffffffff\
#define NETWORK_MAX_SIZE_FFFFFFF0 0xfffffff0\
#define NETWORK_MAX_SIZE_FFFFFF01 0xffffff01\
#define NETWORK_MAX_SIZE_FFFFFF08 0xffffff08\
#define NETWORK_MAX_SIZE_FFFFFF00 0xffffff00\
#define NETWORK_MAX_SIZE_FFFFFFC0 0xffffffc0\
#define NETWORK_MAX_SIZE_FFFFFFDF 0xffffffdf\
#define NETWORK_MAX_SIZE_FFFFFFEF 0xffffffef\
#define NETWORK_MAX_SIZE_FFFFFF7E 0xffff7eff\
#define NETWORK_MAX_SIZE_FFFFFF9F 0xffffff9f\
#define NETWORK_MAX_SIZE_FFFFFFBF 0xffffffbf\
#define NETWORK_MAX_SIZE_FFFFFBFF 0xfffffbff\
#define NETWORK_MAX_SIZE_FFFFFBFA 0xfffffbfa\
#define NETWORK_MAX_SIZE_FFFFFFEFF 0xffffffef\
#define NETWORK_MAX_SIZE_3FFFFFFE 0x3ffffffe\
#define NETWORK_MAX_SIZE_3FFFFFFF 0x3fffffff\
#define NETWORK_MAX_SIZE_7F7FFFFF 0x7f7fffff\
#define NETWORK_MAX_SIZE_42F00000 0x42f00000\
#define NETWORK_MAX_SIZE_41200000 0x41200000\
#define NETWORK_MAX_SIZE_DEADFOOD 0xdeadf00d\
#define NETWORK_MAX_SIZE_54495645 0x54495645  // "TIVE"\
#define NETWORK_MAX_SIZE_42495645 0x42495645  // "BIVE"\
#define NETWORK_MAX_SIZE_48414E44 0x48414E44  // "HAND"\
#define NETWORK_MAX_SIZE_7FC00000 0x7fc00000  // NaN\
#define NETWORK_MAX_SIZE_7F800000 0x7f800000  // Inf\
#define NETWORK_MAX_SIZE_FFFFFFFB 0xfffffffb\
#define NETWORK_MAX_SIZE_FFFFFFBD 0xffffffbd\
#define NETWORK_MAX_SIZE_FFFFFFBE 0xffffffbe\
#define NETWORK_MAX_SIZE_FFFFFF7F 0xffffff7f\
#define NETWORK_MAX_SIZE_FFFFFFDD 0xffffffdd\
#define NETWORK_MAX_SIZE_FFFFFFDF 0xffffffdf\
#define NETWORK_MAX_SIZE_FFFFFFE7 0xffffffe7\
#define NETWORK_MAX_SIZE_FFFFFFEF 0xffffffef\
#define NETWORK_MAX_SIZE_FFFFFFF7 0xfffffff7\
#define NETWORK_MAX_SIZE_FFFFFFFD 0xfffffffd\
#define NETWORK_MAX_SIZE_FFFFFFFE 0xfffffffe\
#define NETWORK_MAX_SIZE_FFFFFFFF 0xffffffff\
#define NETWORK_MAX_SIZE_7F7FFFFF 0x7f7fffff\
#define NETWORK_MAX_SIZE_7FFFFFFF 0x7fffffff\
#define NETWORK_MAX_SIZE_80000000 0x80000000\
#define NETWORK_MAX_SIZE_C0000000 0xc0000000\
#define NETWORK_MAX_SIZE_E0000000 0xe0000000\
#define NETWORK_MAX_SIZE_F0000000 0xf0000000\
#define NETWORK_MAX_SIZE_F8000000 0xf8000000\
#define NETWORK_MAX_SIZE_FC000000 0xfc000000\
#define NETWORK_MAX_SIZE_FE000000 0xfe000000\
#define NETWORK_MAX_SIZE_FF000000 0xff000000\
#define NETWORK_MAX_SIZE_FF800000 0xff800000\
#define NETWORK_MAX_SIZE_FFC00000 0xffc00000\
#define NETWORK_MAX_SIZE_FFE00000 0xffe00000\
#define NETWORK_MAX_SIZE_FFF00000 0xfff00000\
#define NETWORK_MAX_SIZE_FFF80000 0xfff80000\
#define NETWORK_MAX_SIZE_FFFC0000 0xfffc0000\
#define NETWORK_MAX_SIZE_FFFE0000 0xfffe0000\
#define NETWORK_MAX_SIZE_FFFF0000 0xffff0000\
#define NETWORK_MAX_SIZE_FFFF8000 0xffff8000\
#define NETWORK_MAX_SIZE_FFFFC000 0xffffc000\
#define NETWORK_MAX_SIZE_FFFFE000 0xffffe000\
#define NETWORK_MAX_SIZE_FFFFF000 0xfffff000\
#define NETWORK_MAX_SIZE_FFFFF800 0xfffff800\
#define NETWORK_MAX_SIZE_FFFFFC00 0xfffffc00\
#define NETWORK_MAX_SIZE_FFFFFE00 0xfffffe00\
#define NETWORK_MAX_SIZE_FFFFFF00 0xffffff00\
#define NETWORK_MAX_SIZE_FFFFFF80 0xffffff80\
#define NETWORK_MAX_SIZE_FFFFFFC0 0xffffffc0\
#define NETWORK_MAX_SIZE_FFFFFFE0 0xffffffe0\
#define NETWORK_MAX_SIZE_FFFFFFF0 0xfffffff0\
#define NETWORK_MAX_SIZE_FFFFFFF8 0xfffffff8\
#define NETWORK_MAX_SIZE_FFFFFFFC 0xfffffffc\
#define NETWORK_MAX_SIZE_FFFFFFFE 0xfffffffe\
#define NETWORK_MAX_SIZE_FFFFFFFF 0xffffffff' "$FILE"

# 替换十六进制常量为语义化名称
sed -i 's/NETWORK_MAX_SIZEffffffff/NETWORK_MAX_SIZE_FFFFFFFF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffff0/NETWORK_MAX_SIZE_FFFFFFF0/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffff01/NETWORK_MAX_SIZE_FFFFFF01/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffff08/NETWORK_MAX_SIZE_FFFFFF08/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE00000000/NETWORK_MAX_SIZE_00000000/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffff00/NETWORK_MAX_SIZE_FFFFFF00/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffc0/NETWORK_MAX_SIZE_FFFFFFC0/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffdf/NETWORK_MAX_SIZE_FFFFFFDF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffef/NETWORK_MAX_SIZE_FFFFFFEF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffff7eff/NETWORK_MAX_SIZE_FFFFFF7E/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffff9f/NETWORK_MAX_SIZE_FFFFFF9F/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffbf/NETWORK_MAX_SIZE_FFFFFFBF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEfffffbff/NETWORK_MAX_SIZE_FFFFFBFF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEfffffbfa/NETWORK_MAX_SIZE_FFFFFBFA/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffef/NETWORK_MAX_SIZE_FFFFFFEF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE3ffffffe/NETWORK_MAX_SIZE_3FFFFFFE/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE3fffffff/NETWORK_MAX_SIZE_3FFFFFFF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE7f7fffff/NETWORK_MAX_SIZE_7F7FFFFF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE42f00000/NETWORK_MAX_SIZE_42F00000/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE41200000/NETWORK_MAX_SIZE_41200000/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEdeadf00d/NETWORK_MAX_SIZE_DEADFOOD/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE54495645/NETWORK_MAX_SIZE_54495645/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE42495645/NETWORK_MAX_SIZE_42495645/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE48414E44/NETWORK_MAX_SIZE_48414E44/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE7fc00000/NETWORK_MAX_SIZE_7FC00000/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZE7f800000/NETWORK_MAX_SIZE_7F800000/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEfffffffb/NETWORK_MAX_SIZE_FFFFFFFB/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffbd/NETWORK_MAX_SIZE_FFFFFFBD/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffbe/NETWORK_MAX_SIZE_FFFFFFBE/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffff7f/NETWORK_MAX_SIZE_FFFFFF7F/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffdd/NETWORK_MAX_SIZE_FFFFFFDD/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffdf/NETWORK_MAX_SIZE_FFFFFFDF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffe7/NETWORK_MAX_SIZE_FFFFFFE7/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffef/NETWORK_MAX_SIZE_FFFFFFEF/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEfffffff7/NETWORK_MAX_SIZE_FFFFFFF7/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEfffffffd/NETWORK_MAX_SIZE_FFFFFFFD/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEfffffffe/NETWORK_MAX_SIZE_FFFFFFFE/g' "$FILE"
sed -i 's/NETWORK_MAX_SIZEffffffff/NETWORK_MAX_SIZE_FFFFFFFF/g' "$FILE"

# 替换栈变量名
sed -i 's/network_stack_int0000000000000040/network_stack_int_offset_40/g' "$FILE"
sed -i 's/network_stack_int00000000000000a4/network_stack_int_offset_a4/g' "$FILE"

# 替换寄存器变量名
sed -i 's/network_xmm_register_qword_0a_04/network_xmm_register_qword_primary_04/g' "$FILE"
sed -i 's/network_xmm_register_qword_0a_05/network_xmm_register_qword_primary_05/g' "$FILE"
sed -i 's/network_xmm_register_qword_0a_06/network_xmm_register_qword_primary_06/g' "$FILE"

# 替换特殊常量
sed -i 's/NETWORK_STATUS_READY_MASK00000000000000/NETWORK_STATUS_READY_MASK_EXTENDED/g' "$FILE"
sed -i 's/NETWORK_CONTROL_PACKET_TYPE_HANDSHAKEf800000/NETWORK_CONTROL_PACKET_TYPE_HANDSHAKE_EXTENDED/g' "$FILE"

echo "美化完成"