#!/bin/bash

# 标签名美化脚本
# 用于批量替换网络系统中的标签名

# 进入源码目录
cd /dev/shm/mountblade-code/TaleWorlds.Native/src

# 备份原文件
cp 05_networking.c 05_networking.c.backup_labels

# 美化网络系统标签名
sed -i 's/LAB_NETWORK_CHECKSUM_COMPLETE/LAB_NETWORK_CHECKSUM_COMPLETE/g' 05_networking.c
sed -i 's/LAB_NETWORK_CHECKSUM_SUCCESS/LAB_NETWORK_CHECKSUM_SUCCESS/g' 05_networking.c
sed -i 's/LAB_NETWORK_COMPARE_SUCCESS/LAB_NETWORK_COMPARE_SUCCESS/g' 05_networking.c
sed -i 's/LAB_NETWORK_COMPARE_OK/LAB_NETWORK_COMPARE_OK/g' 05_networking.c
sed -i 's/LAB_NETWORK_PRIMARY_HANDLER/LAB_NETWORK_PRIMARY_HANDLER/g' 05_networking.c
sed -i 's/LAB_NETWORK_SECONDARY_HANDLER/LAB_NETWORK_SECONDARY_HANDLER/g' 05_networking.c
sed -i 's/LAB_NETWORK_FINAL_CHECK/LAB_NETWORK_FINAL_CHECK/g' 05_networking.c
sed -i 's/LAB_NETWORK_CLEANUP/LAB_NETWORK_CLEANUP/g' 05_networking.c
sed -i 's/LAB_NETWORK_VALIDATION_START/LAB_NETWORK_VALIDATION_START/g' 05_networking.c
sed -i 's/LAB_NETWORK_TRANSFER_COMPLETE/LAB_NETWORK_TRANSFER_COMPLETE/g' 05_networking.c
sed -i 's/LAB_NETWORK_PACKET_START/LAB_NETWORK_PACKET_START/g' 05_networking.c
sed -i 's/LAB_NETWORK_PACKET_SIZE_VALIDATION/LAB_NETWORK_PACKET_SIZE_VALIDATION/g' 05_networking.c
sed -i 's/LAB_NETWORK_SEND_OPERATION_COMPLETE/LAB_NETWORK_SEND_OPERATION_COMPLETE/g' 05_networking.c
sed -i 's/LAB_NETWORK_RECEIVE_PACKET_START/LAB_NETWORK_RECEIVE_PACKET_START/g' 05_networking.c
sed -i 's/LAB_NETWORK_RECEIVE_SIZE_CHECK/LAB_NETWORK_RECEIVE_SIZE_CHECK/g' 05_networking.c
sed -i 's/LAB_NETWORK_PACKET_INDEX_ZERO/LAB_NETWORK_PACKET_INDEX_ZERO/g' 05_networking.c
sed -i 's/LAB_NETWORK_PACKET_DATA_CHECK/LAB_NETWORK_PACKET_DATA_CHECK/g' 05_networking.c
sed -i 's/LAB_NETWORK_CONNECTION_STATUS_CHECK/LAB_NETWORK_CONNECTION_STATUS_CHECK/g' 05_networking.c
sed -i 's/LAB_NETWORK_PACKET_COUNTER_CHECK/LAB_NETWORK_PACKET_COUNTER_CHECK/g' 05_networking.c
sed -i 's/LAB_NETWORK_CONNECTION_TIMEOUT/LAB_NETWORK_CONNECTION_TIMEOUT/g' 05_networking.c

echo "标签名美化完成"