#!/bin/bash

# 06_utilities.c 语义化美化脚本
# 替换十六进制常量为语义化名称

cd /dev/shm/mountblade-code/TaleWorlds.Native/src

# 备份原始文件
cp 06_utilities.c 06_utilities.c.backup

# 定义替换规则
declare -A replacements=(
    # 大小阈值常量
    ["UTILITY_SIZE_THRESHOLD_LARGE_HEX_8C"]="UTILITY_SIZE_THRESHOLD_VALIDATION_MAXIMUM"
    ["UTILITY_SIZE_THRESHOLD_LARGE_HEX_8B"]="UTILITY_SIZE_THRESHOLD_VALIDATION_LARGE"
    ["UTILITY_SIZE_THRESHOLD_MEDIUM_HEX_6E"]="UTILITY_SIZE_THRESHOLD_VALIDATION_MEDIUM"
    ["UTILITY_SIZE_THRESHOLD_MEDIUM_HEX_55"]="UTILITY_SIZE_THRESHOLD_OPERATION_MEDIUM"
    ["UTILITY_SIZE_THRESHOLD_SMALL_HEX_53"]="UTILITY_SIZE_THRESHOLD_OPERATION_SMALL"
    ["UTILITY_SIZE_THRESHOLD_MEDIUM_HEX_82"]="UTILITY_SIZE_THRESHOLD_PROCESSING_MEDIUM"
    ["UTILITY_SIZE_THRESHOLD_6B"]="UTILITY_SIZE_THRESHOLD_BUFFER_MINIMUM"
    ["UTILITY_SIZE_THRESHOLD_81"]="UTILITY_SIZE_THRESHOLD_CPU_MAXIMUM"
    ["UTILITY_CPU_REGISTER_LIMIT_LARGE_81"]="UTILITY_CPU_REGISTER_LIMIT_MAXIMUM"
    ["UTILITY_SIZE_THRESHOLD_51"]="UTILITY_SIZE_THRESHOLD_MEMORY_MINIMUM"
    ["UTILITY_SIZE_THRESHOLD_8A"]="UTILITY_SIZE_THRESHOLD_SYSTEM_MAXIMUM"
    ["UTILITY_CPU_REGISTER_LIMIT_MEDIUM_51"]="UTILITY_CPU_REGISTER_LIMIT_MEDIUM"
    ["UTILITY_SIZE_THRESHOLD_3F"]="UTILITY_SIZE_THRESHOLD_STACK_MINIMUM"
    ["UTILITY_SIZE_THRESHOLD_5B"]="UTILITY_SIZE_THRESHOLD_RESOURCE_MINIMUM"
    ["UTILITY_SIZE_THRESHOLD_37"]="UTILITY_SIZE_THRESHOLD_DATA_MINIMUM"
    ["UTILITY_SIZE_THRESHOLD_39"]="UTILITY_SIZE_THRESHOLD_VALIDATION_MINIMUM"
    ["UTILITY_SIZE_THRESHOLD_5E"]="UTILITY_SIZE_THRESHOLD_OPERATION_MAXIMUM"
    ["UTILITY_SIZE_THRESHOLD_85"]="UTILITY_SIZE_THRESHOLD_PROCESSING_MAXIMUM"
    ["UTILITY_SIZE_THRESHOLD_84"]="UTILITY_SIZE_THRESHOLD_TRANSFER_MAXIMUM"
    ["UTILITY_CPU_REGISTER_LIMIT_LARGE_84"]="UTILITY_CPU_REGISTER_LIMIT_TRANSFER_MAXIMUM"
    ["UTILITY_CPU_REGISTER_LIMIT_LARGE_8A"]="UTILITY_CPU_REGISTER_LIMIT_SYSTEM_MAXIMUM"
    
    # 栈偏移量常量
    ["UTILITY_STACK_OFFSET_NEGATIVE_EXTENDED_21"]="UTILITY_STACK_OFFSET_NEGATIVE_EXTENDED_PRIMARY"
    
    # 资源属性偏移量
    ["UTILITY_RESOURCE_PROP_OFFSET_454D50"]="UTILITY_RESOURCE_PROPERTY_OFFSET_PRIMARY"
    ["UTILITY_RESOURCE_PROPERTY_OFFSET_QUINARY_464550"]="UTILITY_RESOURCE_PROPERTY_OFFSET_SECONDARY"
    ["UTILITY_RESOURCE_PROPERTY_OFFSET_QUINARY_464553"]="UTILITY_RESOURCE_PROPERTY_OFFSET_TERTIARY"
    ["UTILITY_RESOURCE_OP_OFFSET_94B4E42"]="UTILITY_RESOURCE_OPERATION_OFFSET_PRIMARY"
    
    # 栈数组常量
    ["UTILITY_STACK_ARRAY_1C"]="UTILITY_STACK_ARRAY_STANDARD"
)

# 执行替换
for old in "${!replacements[@]}"; do
    new="${replacements[$old]}"
    echo "替换: $old -> $new"
    sed -i "s/\b$old\b/$new/g" 06_utilities.c
done

echo "语义化替换完成"