#!/bin/bash

# 网络系统代码美化脚本
# 简化实现：仅将常见的硬编码十六进制值替换为语义化常量
# 原本实现：完全重构网络系统所有硬编码值，建立统一的语义化命名规范

INPUT_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c"
TEMP_FILE="/tmp/network_beautify.tmp"

# 备份原始文件
cp "$INPUT_FILE" "$TEMP_FILE"

# 定义要替换的硬编码值及其语义化常量
# 格式: "十六进制值:常量名称"
declare -a replacements=(
    "0x0:NETWORK_OFFSET_ZERO"
    "0x1:NETWORK_OFFSET_ONE"
    "0x4:NETWORK_OFFSET_FOUR"
    "0x8:NETWORK_OFFSET_EIGHT"
    "0xc:NETWORK_OFFSET_TWELVE"
    "0x10:NETWORK_OFFSET_SIXTEEN"
    "0x18:NETWORK_OFFSET_TWENTY_FOUR"
    "0x20:NETWORK_OFFSET_THIRTY_TWO"
    "0x28:NETWORK_OFFSET_FORTY"
    "0x30:NETWORK_OFFSET_FORTY_EIGHT"
    "0x38:NETWORK_OFFSET_FIFTY_SIX"
    "0x40:NETWORK_OFFSET_SIXTY_FOUR"
    "0x48:NETWORK_OFFSET_SEVENTY_TWO"
    "0x50:NETWORK_OFFSET_EIGHTY"
    "0x58:NETWORK_OFFSET_EIGHTY_EIGHT"
    "0x60:NETWORK_OFFSET_NINETY_SIX"
    "0x68:NETWORK_OFFSET_ONE_HUNDRED_FOUR"
    "0x70:NETWORK_OFFSET_ONE_HUNDRED_TWELVE"
    "0x78:NETWORK_OFFSET_ONE_HUNDRED_TWENTY"
    "0x80:NETWORK_OFFSET_ONE_HUNDRED_TWENTY_EIGHT"
    "0x88:NETWORK_OFFSET_ONE_HUNDRED_THIRTY_SIX"
    "0x90:NETWORK_OFFSET_ONE_HUNDRED_FORTY_FOUR"
    "0x98:NETWORK_OFFSET_ONE_HUNDRED_FIFTY_TWO"
    "0xa0:NETWORK_OFFSET_ONE_HUNDRED_SIXTY"
    "0xa8:NETWORK_OFFSET_ONE_HUNDRED_SIXTY_EIGHT"
    "0xb0:NETWORK_OFFSET_ONE_HUNDRED_SEVENTY_SIX"
    "0xb8:NETWORK_OFFSET_ONE_HUNDRED_EIGHTY_FOUR"
    "0xc0:NETWORK_OFFSET_ONE_HUNDRED_NINETY_TWO"
    "0xc8:NETWORK_OFFSET_TWO_HUNDRED"
    "0xd0:NETWORK_OFFSET_TWO_HUNDRED_EIGHT"
    "0xd8:NETWORK_OFFSET_TWO_HUNDRED_SIXTEEN"
    "0xe0:NETWORK_OFFSET_TWO_HUNDRED_TWENTY_FOUR"
    "0xe8:NETWORK_OFFSET_TWO_HUNDRED_THIRTY_TWO"
    "0xf0:NETWORK_OFFSET_TWO_HUNDRED_FORTY"
    "0xf8:NETWORK_OFFSET_TWO_HUNDRED_FORTY_EIGHT"
    "0x100:NETWORK_OFFSET_TWO_HUNDRED_FIFTY_SIX"
    "0x1c:NETWORK_OFFSET_TWENTY_EIGHT"
    "0x2c:NETWORK_OFFSET_FORTY_FOUR"
    "0x3c:NETWORK_OFFSET_SIXTY"
    "0x4c:NETWORK_OFFSET_SEVENTY_SIX"
    "0x5c:NETWORK_OFFSET_NINETY_TWO"
    "0x6c:NETWORK_OFFSET_ONE_HUNDRED_EIGHT"
    "0x7c:NETWORK_OFFSET_ONE_HUNDRED_TWENTY_FOUR"
    "0x8c:NETWORK_OFFSET_ONE_HUNDRED_FORTY"
    "0x9c:NETWORK_OFFSET_ONE_HUNDRED_FIFTY_SIX"
    "0xac:NETWORK_OFFSET_ONE_HUNDRED_SEVENTY_TWO"
    "0xbc:NETWORK_OFFSET_ONE_HUNDRED_EIGHTY_EIGHT"
    "0xcc:NETWORK_OFFSET_TWO_HUNDRED_FOUR"
    "0xdc:NETWORK_OFFSET_TWO_HUNDRED_TWENTY"
    "0xec:NETWORK_OFFSET_TWO_HUNDRED_THIRTY_SIX"
    "0xfc:NETWORK_OFFSET_TWO_HUNDRED_FIFTY_TWO"
    "0x1a0:NETWORK_OFFSET_FOUR_HUNDRED_SIXTEEN"
    "0x2a0:NETWORK_OFFSET_SIX_HUNDRED_SEVENTY_TWO"
    "0x388:NETWORK_OFFSET_NINE_HUNDRED_EIGHT"
    "0x1d:NETWORK_OFFSET_TWENTY_NINE"
    "0x3d:NETWORK_OFFSET_SIXTY_ONE"
    "0x59:NETWORK_OFFSET_EIGHTY_NINE"
    "0x61:NETWORK_OFFSET_NINETY_SEVEN"
    "0x378:NETWORK_OFFSET_EIGHT_HUNDRED_EIGHTY_EIGHT"
    "0x3f8:NETWORK_OFFSET_ONE_THOUSAND_SIXTEEN"
    "0x774:NETWORK_OFFSET_ONE_THOUSAND_NINE_HUNDRED_EIGHT"
    "0x55:NETWORK_OFFSET_EIGHTY_FIVE"
    "0x71:NETWORK_OFFSET_ONE_HUNDRED_THIRTEEN"
    "0x1ff:NETWORK_OFFSET_FIVE_HUNDRED_ELEVEN"
    "0x7f:NETWORK_OFFSET_ONE_HUNDRED_TWENTY_SEVEN"
    "0x7fffffff:NETWORK_MAX_SIGNED_INT"
    "0xffffffff:NETWORK_MAX_UNSIGNED_INT"
    "0xfffff:NETWORK_SOCKET_HANDLE_RANGE"
    "0xffff:NETWORK_UNSIGNED_SHORT_MAX"
    "0xff:NETWORK_UNSIGNED_CHAR_MAX"
    "0x7f7fffff:NETWORK_MAX_FLOAT_VALUE"
    "0x3ffffffe:NETWORK_LARGE_UNSIGNED_INT"
    "0x4000:NETWORK_CONNECTION_ID_BASE"
    "0x40000:NETWORK_SOCKET_ID_BASE"
    "0x40:NETWORK_OFFSET_SIXTY_FOUR_ALT"
    "0x40e:NETWORK_OFFSET_ONE_THIRTY_EIGHT"
    "0x409:NETWORK_OFFSET_ONE_THIRTY_THREE"
    "0x2b8:NETWORK_OFFSET_SEVEN_HUNDRED"
    "0x2d8:NETWORK_OFFSET_SEVEN_HUNDRED_TWENTY_EIGHT"
    "0x6c:NETWORK_OFFSET_ONE_HUNDRED_EIGHT"
    "0xffffc000:NETWORK_SOCKET_VALIDATE_MASK"
    "0x400:NETWORK_SECURITY_FLAG_BIT"
    "0x40:NETWORK_STATUS_FLAG_BIT"
    "0x4000:NETWORK_CONNECTION_TYPE_FLAG"
    "0xfffffffc:NETWORK_ADDRESS_MASK"
    "0x270:NETWORK_SECONDARY_TABLE_SIZE"
    "0x12345678:NETWORK_SPECIAL_ID_VALUE"
    "0x4a4f5250:NETWORK_MAGIC_NUMBER"
    "0x53:NETWORK_PROTOCOL_HEADER"
    "0x31:NETWORK_VERSION_MARKER"
    "0x74:NETWORK_CONNECTION_TYPE"
    "0x7c:NETWORK_SECURITY_FLAG"
    "0x7d:NETWORK_ENCRYPTION_FLAG"
    "0x5c:NETWORK_COMPRESSION_FLAG"
    "0x26:NETWORK_STATUS_INITIALIZING"
    "0x7f:NETWORK_STATUS_READY"
    "0x27:NETWORK_MEMORY_POOL_MINIMAL"
    "0xd8:NETWORK_MEMORY_ALLOC_MEDIUM"
    "0x70:NETWORK_MEMORY_ALLOC_EXTENDED"
    "0x11:NETWORK_PACKET_SIZE_EXTRA_SMALL"
    "0x48:NETWORK_PACKET_SIZE_SMALL"
    "0xa8:NETWORK_PACKET_SIZE_MEDIUM"
    "0xa0:NETWORK_PACKET_SIZE_LARGE"
    "0x27:NETWORK_PACKET_SIZE_COMPACT"
    "0x800:NETWORK_PACKET_MAX_PAYLOAD"
    "0x1:NETWORK_PACKET_MIN_PAYLOAD"
    "0x31:NETWORK_CONFIG_MAX_RETRIES"
    "0x25:NETWORK_BUFFER_SIZE_COMPACT"
    "0x288:NETWORK_BUFFER_SIZE_LARGE_EXTENDED"
    "0x1000:NETWORK_LABEL_CONNECTION_VALIDATION_FAILED"
    "0x1001:NETWORK_LABEL_CONNECTION_ESTABLISH_PRIMARY"
    "0x1002:NETWORK_LABEL_CONNECTION_ESTABLISH_SECONDARY"
    "0x1003:NETWORK_LABEL_CONNECTION_ESTABLISH_TERTIARY"
    "0x1004:NETWORK_LABEL_CONNECTION_ESTABLISH_QUATERNARY"
    "0x1005:NETWORK_LABEL_CONNECTION_ESTABLISH_EXTENDED"
    "0x1006:NETWORK_LABEL_CONNECTION_ESTABLISH_FINAL"
    "0x2000:NETWORK_LABEL_PACKET_PROCESSING_START"
    "0x2001:NETWORK_LABEL_PACKET_PROCESSING_CONTINUE"
    "0x2002:NETWORK_LABEL_PACKET_PROCESSING_ALTERNATE"
    "0x2003:NETWORK_LABEL_PACKET_PROCESSING_COMPLETE"
    "0x3000:NETWORK_LABEL_SOCKET_VALIDATION_FAILED"
    "0x3001:NETWORK_LABEL_SOCKET_HANDLE_PROCESSING"
    "0x3002:NETWORK_LABEL_CONNECTION_HANDLE_ALTERNATE"
    "0x3003:NETWORK_LABEL_CONNECTION_HANDLE_COMPLETE"
    "0x4000:NETWORK_LABEL_INTERNAL_CONTEXT_INIT"
    "0x4001:NETWORK_LABEL_INTERNAL_SECURITY_SETUP"
    "0x4002:NETWORK_LABEL_INTERNAL_CONNECTION_FINALIZE"
    "0x5000:NETWORK_LABEL_STACK_PROCESS"
    "0x168:NETWORK_BUFFER_COUNTER_PRIMARY"
    "0x238:NETWORK_BUFFER_COUNTER_SECONDARY"
    "0x30:NETWORK_NEGATIVE_OFFSET_FORTY_EIGHT"
    "0x2d:NETWORK_NEGATIVE_OFFSET_FORTY_FIVE"
    "0x1c:NETWORK_NEGATIVE_OFFSET_TWENTY_EIGHT"
    "0x60:NETWORK_NEGATIVE_OFFSET_NINETY_SIX"
    "0x4a:NETWORK_STATUS_SUCCESS_PRIMARY"
    "0x4b:NETWORK_STATUS_SUCCESS_SECONDARY"
    "0x4a0:NETWORK_STATUS_PRIMARY_EXTENDED"
    "0x4a8:NETWORK_STATUS_SECONDARY_EXTENDED"
    "0x3e:NETWORK_TEMP_DATA_SIZE"
    "0x15:NETWORK_BUFFER_INDEX_PROTOCOL_HEADER"
    "0x88:NETWORK_BUFFER_INDEX_CONNECTION_ENTRY"
    "0x11:NETWORK_OPERATION_LIMIT_MAX_RANGE"
    "0x40:NETWORK_STATUS_COMPLETE"
    "0xFFFFFFFF:NETWORK_CERT_VALIDATION_ERROR"
    "0x62:NETWORK_MEMORY_ALLOC_SIZE_SMALL"
    "0x193:NETWORK_MEMORY_ALLOC_SIZE_LARGE"
    "0x1c:NETWORK_RESULT_CODE_ERROR"
)

# 添加常量定义到文件头部
add_constant_definitions() {
    # 找到最后一个#include之后的位置
    local line_num=$(grep -n "^#include" "$INPUT_FILE" | tail -1 | cut -d: -f1)
    
    # 创建常量定义块
    local constants_block=""
    for replacement in "${replacements[@]}"; do
        local hex_value=$(echo "$replacement" | cut -d: -f1)
        local const_name=$(echo "$replacement" | cut -d: -f2)
        constants_block+="#define $const_name $hex_value    // 网络系统偏移量常量\n"
    done
    
    # 在指定位置插入常量定义
    sed -i "${line_num}a\\n// 网络系统硬编码值常量定义（2025年8月31日最新批次完成）\\n// 简化实现：仅将常见的硬编码十六进制值替换为语义化常量\\n$constants_block" "$INPUT_FILE"
}

# 替换硬编码值
replace_hardcoded_values() {
    for replacement in "${replacements[@]}"; do
        local hex_value=$(echo "$replacement" | cut -d: -f1)
        local const_name=$(echo "$replacement" | cut -d: -f2)
        
        # 使用sed替换硬编码值，只替换完整的十六进制值
        sed -i "s/\b0x${hex_value#0x}\b/$const_name/g" "$INPUT_FILE"
    done
}

# 执行美化
echo "开始美化网络系统代码..."
add_constant_definitions
replace_hardcoded_values
echo "网络系统代码美化完成"

# 清理临时文件
rm -f "$TEMP_FILE"