#!/bin/bash

# 修复自引用宏定义的脚本
FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/05_networking.c"

# 备份原文件
cp "$FILE" "$FILE.backup"

# 修复自引用的宏定义
sed -i 's/#define NETWORK_SOCKET_BASE_OFFSET NETWORK_SOCKET_BASE_OFFSET/#define NETWORK_SOCKET_BASE_OFFSET 0x48/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_CHECKSUM_OFFSET NETWORK_CHECKSUM_OFFSET_BYTES/#define NETWORK_SOCKET_CHECKSUM_OFFSET 0x10/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_CLEANUP_OFFSET NETWORK_SOCKET_CLEANUP_OFFSET/#define NETWORK_SOCKET_CLEANUP_OFFSET 0x65/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_CONNECTION_DATA_OFFSET NETWORK_SOCKET_CONNECTION_DATA_OFFSET/#define NETWORK_SOCKET_CONNECTION_DATA_OFFSET 0x56/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_CONTEXT_OFFSET NETWORK_SOCKET_CONTEXT_OFFSET/#define NETWORK_SOCKET_CONTEXT_OFFSET 0x8a/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_CONTROL_OFFSET NETWORK_SOCKET_CONTROL_OFFSET/#define NETWORK_SOCKET_CONTROL_OFFSET 0x5b/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_DATA_OFFSET NETWORK_SOCKET_DATA_OFFSET/#define NETWORK_SOCKET_DATA_OFFSET_PRIMARY 0x8f/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_ERROR_OFFSET_ALT NETWORK_SOCKET_ERROR_OFFSET_ALT/#define NETWORK_SOCKET_ERROR_OFFSET_ALT 0x9d/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_ERROR_OFFSET_NEG NETWORK_SOCKET_ERROR_OFFSET_NEG/#define NETWORK_SOCKET_ERROR_OFFSET_NEG -0x9b/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_EVENT_OFFSET NETWORK_SOCKET_EVENT_OFFSET/#define NETWORK_SOCKET_EVENT_OFFSET 0x94/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_EXTENDED_OFFSET NETWORK_SOCKET_EXTENDED_OFFSET/#define NETWORK_SOCKET_EXTENDED_OFFSET 0x88/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_HANDLE_OFFSET_5D NETWORK_SOCKET_HANDLE_OFFSET_5D/#define NETWORK_SOCKET_HANDLE_OFFSET_5D 0x5d/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_HANDSHAKE_TYPE_OFFSET NETWORK_SOCKET_HANDSHAKE_TYPE_OFFSET/#define NETWORK_SOCKET_HANDSHAKE_TYPE_OFFSET 0x55/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_PRIORITY_OFFSET NETWORK_SOCKET_PRIORITY_OFFSET/#define NETWORK_SOCKET_PRIORITY_OFFSET 0x6f/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_RESOURCE_OFFSET NETWORK_SOCKET_RESOURCE_OFFSET/#define NETWORK_SOCKET_RESOURCE_OFFSET 0x5e/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_SESSION_OFFSET NETWORK_SOCKET_SESSION_OFFSET/#define NETWORK_SOCKET_SESSION_OFFSET 0x57/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_STATE_OFFSET NETWORK_SOCKET_STATE_OFFSET/#define NETWORK_SOCKET_STATE_OFFSET 0x4a/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_STATE_SIZE_OFFSET NETWORK_SOCKET_STATE_SIZE_OFFSET/#define NETWORK_SOCKET_STATE_SIZE_OFFSET 0x9c/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_TERMINATE_OFFSET NETWORK_SOCKET_TERMINATE_OFFSET/#define NETWORK_SOCKET_TERMINATE_OFFSET 0x5c/' "$FILE"
sed -i 's/#define NETWORK_SOCKET_TIMEOUT_DATA_OFFSET NETWORK_SOCKET_TIMEOUT_DATA_OFFSET/#define NETWORK_SOCKET_TIMEOUT_DATA_OFFSET 0x7a/' "$FILE"

echo "自引用宏定义修复完成"