#!/bin/bash

# 修复常量定义问题
FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/06_utilities.c"

# 修复常量定义
sed -i 's/#define UTILITY_FLOAT_NEGATIVE_ONE UTILITY_FLOAT_NEGATIVE_ONE/#define UTILITY_FLOAT_NEGATIVE_ONE 0xbf800000/g' "$FILE"
sed -i 's/#define UTILITY_FLOAT_ONE UTILITY_FLOAT_ONE/#define UTILITY_FLOAT_ONE 0x3f800000/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFDFFFFFF UTILITY_FLAG_MASK_0XFDFFFFFF/#define UTILITY_FLAG_MASK_0XFDFFFFFF 0xfdffffff/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFBFFFFFF UTILITY_FLAG_MASK_0XFBFFFFFF/#define UTILITY_FLAG_MASK_0XFBFFFFFF 0xfbffffff/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFFFFFF00 UTILITY_FLAG_MASK_0XFFFFFF00/#define UTILITY_FLAG_MASK_0XFFFFFF00 0xffffff00/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFFFF UTILITY_FLAG_MASK_0XFFFF/#define UTILITY_FLAG_MASK_0XFFFF 0xffff/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFFFFFF UTILITY_FLAG_MASK_0XFFFFFF/#define UTILITY_FLAG_MASK_0XFFFFFF 0xffffff/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFFFFC000 UTILITY_FLAG_MASK_0XFFFFC000/#define UTILITY_FLAG_MASK_0XFFFFC000 0xffffc000/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0X4000 UTILITY_FLAG_MASK_0X4000/#define UTILITY_FLAG_MASK_0X4000 0x4000/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0X6000000 UTILITY_FLAG_MASK_0X6000000/#define UTILITY_FLAG_MASK_0X6000000 0x6000000/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0X40000 UTILITY_FLAG_MASK_0X40000/#define UTILITY_FLAG_MASK_0X40000 0x40000/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0X3FFFFFFF UTILITY_FLAG_MASK_0X3FFFFFFF/#define UTILITY_FLAG_MASK_0X3FFFFFFF 0x3fffffff/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFFFF7FFF UTILITY_FLAG_MASK_0XFFFF7FFF/#define UTILITY_FLAG_MASK_0XFFFF7FFF 0xffff7fff/g' "$FILE"
sed -i 's/#define UTILITY_FLAG_MASK_0XFF000000 UTILITY_FLAG_MASK_0XFF000000/#define UTILITY_FLAG_MASK_0XFF000000 0xff000000/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_FEBE UTILITY_STREAM_TYPE_FEBE/#define UTILITY_STREAM_TYPE_FEBE 0x46464542/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_BFEB UTILITY_STREAM_TYPE_BFEB/#define UTILITY_STREAM_TYPE_BFEB 0x42464542/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_ORTC UTILITY_STREAM_TYPE_ORTC/#define UTILITY_STREAM_TYPE_ORTC 0x4f525443/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_BIVE UTILITY_STREAM_TYPE_BIVE/#define UTILITY_STREAM_TYPE_BIVE 0x42495645/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_OLMP UTILITY_STREAM_TYPE_OLMP/#define UTILITY_STREAM_TYPE_OLMP 0x4f4c4d50/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_BLMP UTILITY_STREAM_TYPE_BLMP/#define UTILITY_STREAM_TYPE_BLMP 0x424c4d50/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_MRAP UTILITY_STREAM_TYPE_MRAP/#define UTILITY_STREAM_TYPE_MRAP 0x4d524150/g' "$FILE"
sed -i 's/#define UTILITY_STREAM_TYPE_BMRP UTILITY_STREAM_TYPE_BMRP/#define UTILITY_STREAM_TYPE_BMRP 0x424d5250/g' "$FILE"

echo "常量定义修复完成"