#!/bin/bash

# 脚本：美化02_core_engine.c中的网络状态偏移量常量
# 简化实现：将ENGINE_NETWORK_STATE_OFFSET_[0-9]替换为语义化常量

FILE_PATH="/dev/shm/mountblade-code/TaleWorlds.Native/src/02_core_engine.c"

# 备份原始文件
cp "$FILE_PATH" "$FILE_PATH.backup_$(date +%Y%m%d_%H%M%S)"

# 替换网络状态偏移量常量
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_3/ENGINE_NETWORK_STATE_OFFSET_AUTHENTICATE/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_4/ENGINE_NETWORK_STATE_OFFSET_ESTABLISH/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_5/ENGINE_NETWORK_STATE_OFFSET_COMMUNICATE/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_6/ENGINE_NETWORK_STATE_OFFSET_TRANSFER/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_7/ENGINE_NETWORK_STATE_OFFSET_VALIDATE/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_8/ENGINE_NETWORK_STATE_OFFSET_PROCESS/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_9/ENGINE_NETWORK_STATE_OFFSET_COMPLETE/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_10/ENGINE_NETWORK_STATE_OFFSET_ERROR/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_11/ENGINE_NETWORK_STATE_OFFSET_RETRY/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_12/ENGINE_NETWORK_STATE_OFFSET_TIMEOUT/g' "$FILE_PATH"
sed -i 's/ENGINE_NETWORK_STATE_OFFSET_13/ENGINE_NETWORK_STATE_OFFSET_DISCONNECT/g' "$FILE_PATH"

echo "网络状态偏移量常量替换完成"