#!/bin/bash
# 渲染系统代码美化修复脚本（2025年8月30日最终批次）
# 修复脚本执行问题

FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/03_rendering.c"

echo "修复标签语义化常量定义..."

# 修复循环定义问题
sed -i 's/#define RENDER_LABEL_STRING_PROCESS_CONTINUE RENDER_LABEL_STRING_PROCESS_CONTINUE/#define RENDER_LABEL_STRING_PROCESS_CONTINUE LAB_1804170b5/g' "$FILE"
sed -i 's/#define RENDER_LABEL_DATA_PROCESS_CONTINUE RENDER_LABEL_DATA_PROCESS_CONTINUE/#define RENDER_LABEL_DATA_PROCESS_CONTINUE LAB_1802abea0/g' "$FILE"
sed -i 's/#define RENDER_LABEL_DATA_PROCESS_COMPLETE RENDER_LABEL_DATA_PROCESS_COMPLETE/#define RENDER_LABEL_DATA_PROCESS_COMPLETE LAB_1802abf36/g' "$FILE"
sed -i 's/#define RENDER_LABEL_STATE_CHECK_CONTINUE RENDER_LABEL_STATE_CHECK_CONTINUE/#define RENDER_LABEL_STATE_CHECK_CONTINUE LAB_180272cfe/g' "$FILE"

# 修复注释格式问题
sed -i 's/等语义化标签名\\\\n\\\\ - 将LAB_1804170b5等十六进制标签替换为RENDER_LABEL_STRING_PROCESS_CONTINUE等语义化标签名\\\\n\\\\ - 将LAB_1802abea0等十六进制标签替换为RENDER_LABEL_DATA_PROCESS_CONTINUE等语义化标签名\\\\n\\\\ - 将LAB_1802abf36等十六进制标签替换为RENDER_LABEL_DATA_PROCESS_COMPLETE等语义化标签名\\\\n\\\\ - 将LAB_180272cfe等十六进制标签替换为RENDER_LABEL_STATE_CHECK_CONTINUE等语义化标签名/等语义化标签名\\n - 将LAB_1804170b5等十六进制标签替换为RENDER_LABEL_STRING_PROCESS_CONTINUE等语义化标签名\\n - 将LAB_1802abea0等十六进制标签替换为RENDER_LABEL_DATA_PROCESS_CONTINUE等语义化标签名\\n - 将LAB_1802abf36等十六进制标签替换为RENDER_LABEL_DATA_PROCESS_COMPLETE等语义化标签名\\n - 将LAB_180272cfe等十六进制标签替换为RENDER_LABEL_STATE_CHECK_CONTINUE等语义化标签名/g' "$FILE"

echo "修复完成"