#!/bin/bash

# 渲染系统标签名语义化美化脚本
# 美化03_rendering.c文件中的非语义化标签名

# 定义要替换的标签映射
declare -A label_mappings=(
    # 渲染管线相关标签
    ["rendering_label_27c7b0"]="rendering_label_pipeline_setup_start"
    ["rendering_label_27c7b4"]="rendering_label_pipeline_setup_continue"
    ["rendering_label_27c7bb"]="rendering_label_pipeline_setup_complete"
    ["rendering_label_27c733"]="rendering_label_pipeline_validation_start"
    ["rendering_label_27c73b"]="rendering_label_pipeline_validation_check"
    ["rendering_label_27c801"]="rendering_label_pipeline_validation_complete"
    
    # 渲染缓冲区相关标签
    ["rendering_label_27cd22"]="rendering_label_buffer_init_start"
    ["rendering_label_27cd90"]="rendering_label_buffer_init_process"
    ["rendering_label_27cd98"]="rendering_label_buffer_init_complete"
    
    # 渲染状态相关标签
    ["rendering_label_27d492"]="rendering_label_state_setup_start"
    ["rendering_label_27d773"]="rendering_label_state_setup_process"
    ["rendering_label_27de2e"]="rendering_label_state_setup_complete"
    ["rendering_label_27e092"]="rendering_label_state_validation_start"
    ["rendering_label_27e4b2"]="rendering_label_state_validation_check"
    ["rendering_label_27e6bc"]="rendering_label_state_validation_complete"
    
    # 渲染上下文相关标签
    ["rendering_label_27ed63"]="rendering_label_context_create_start"
    ["rendering_label_27ee93"]="rendering_label_context_create_process"
    ["rendering_label_27ef7d"]="rendering_label_context_create_complete"
    ["rendering_label_27f217"]="rendering_label_context_validation_start"
    
    # 渲染着色器相关标签
    ["rendering_label_27fce8"]="rendering_label_shader_compile_start"
    ["rendering_label_27fe05"]="rendering_label_shader_compile_process"
    ["rendering_label_27feed"]="rendering_label_shader_compile_complete"
    ["rendering_label_280225"]="rendering_label_shader_link_start"
    ["rendering_label_2802a3"]="rendering_label_shader_link_complete"
    
    # 渲染纹理相关标签
    ["rendering_label_280743"]="rendering_label_texture_load_start"
    ["rendering_label_280894"]="rendering_label_texture_load_process"
    ["rendering_label_280958"]="rendering_label_texture_load_complete"
    
    # 渲染材质相关标签
    ["rendering_label_280e02"]="rendering_label_material_create_start"
    ["rendering_label_28135c"]="rendering_label_material_create_process"
    ["rendering_label_281d06"]="rendering_label_material_create_complete"
    ["rendering_label_281fed"]="rendering_label_material_validation_start"
    ["rendering_label_281ff6"]="rendering_label_material_validation_complete"
    
    # 渲染网格相关标签
    ["rendering_label_283e1f"]="rendering_label_mesh_load_start"
    ["rendering_label_283f92"]="rendering_label_mesh_load_process"
    ["rendering_label_283f92_2"]="rendering_label_mesh_load_continue"
    ["rendering_label_284385"]="rendering_label_mesh_load_complete"
    ["rendering_label_284ade"]="rendering_label_mesh_validation_start"
    
    # 渲染相机相关标签
    ["rendering_label_28834f"]="rendering_label_camera_setup_start"
    ["rendering_label_28843a"]="rendering_label_camera_setup_complete"
    
    # 渲染视口相关标签
    ["rendering_label_2890ba"]="rendering_label_viewport_setup_start"
    ["rendering_label_2891fc"]="rendering_label_viewport_setup_process"
    ["rendering_label_289516"]="rendering_label_viewport_setup_check"
    ["rendering_label_289571"]="rendering_label_viewport_setup_continue"
    ["rendering_label_2899a4"]="rendering_label_viewport_setup_complete"
    
    # 渲染清除相关标签
    ["rendering_label_289bc9"]="rendering_label_clear_color_start"
    ["rendering_label_289c37"]="rendering_label_clear_color_process"
    ["rendering_label_289daa"]="rendering_label_clear_color_complete"
    ["rendering_label_289e47"]="rendering_label_clear_depth_start"
    ["rendering_label_2895b3"]="rendering_label_clear_depth_process"
    ["rendering_label_2895c4"]="rendering_label_clear_depth_continue"
    ["rendering_label_2895ce"]="rendering_label_clear_depth_check"
    ["rendering_label_2895f6"]="rendering_label_clear_depth_complete"
    ["rendering_label_289618"]="rendering_label_clear_stencil_start"
    ["rendering_label_2896e8"]="rendering_label_clear_stencil_process"
    ["rendering_label_28988d"]="rendering_label_clear_stencil_check"
    ["rendering_label_2898d6"]="rendering_label_clear_stencil_complete"
    
    # 渲染绘制相关标签
    ["rendering_label_28a721"]="rendering_label_draw_start"
    ["rendering_label_28a721_2"]="rendering_label_draw_continue"
    ["rendering_label_28abe5"]="rendering_label_draw_setup_start"
    ["rendering_label_28ac26"]="rendering_label_draw_setup_complete"
    ["rendering_label_28b387"]="rendering_label_draw_elements_start"
    ["rendering_label_28b456"]="rendering_label_draw_elements_process"
    ["rendering_label_28b460"]="rendering_label_draw_elements_complete"
    ["rendering_label_28b946"]="rendering_label_draw_arrays_start"
    ["rendering_label_28bce1"]="rendering_label_draw_arrays_process"
    ["rendering_label_28bd4c"]="rendering_label_draw_arrays_continue"
    ["rendering_label_28bd64"]="rendering_label_draw_arrays_complete"
    
    # 渲染混合相关标签
    ["rendering_label_28d060"]="rendering_label_blend_setup_start"
    ["rendering_label_28c839"]="rendering_label_blend_setup_process"
    ["rendering_label_28d788"]="rendering_label_blend_setup_complete"
    ["rendering_label_28e1e4"]="rendering_label_blend_validation_start"
    
    # 渲染深度测试相关标签
    ["rendering_label_28ffb2"]="rendering_label_depth_test_start"
    ["rendering_label_29020c"]="rendering_label_depth_test_process"
    ["rendering_label_29020c_2"]="rendering_label_depth_test_continue"
    ["rendering_label_29020c_3"]="rendering_label_depth_test_check"
    ["rendering_label_290cc2"]="rendering_label_depth_test_complete"
    ["rendering_label_290cc2_2"]="rendering_label_depth_test_continue_2"
    ["rendering_label_290cc2_3"]="rendering_label_depth_test_continue_3"
    
    # 渲染模板测试相关标签
    ["rendering_label_29726b"]="rendering_label_stencil_test_start"
    ["rendering_label_2972e6"]="rendering_label_stencil_test_process"
    ["rendering_label_29726b_2"]="rendering_label_stencil_test_continue"
    ["rendering_label_2972e6_2"]="rendering_label_stencil_test_continue_2"
    ["rendering_label_297469"]="rendering_label_stencil_test_setup"
    ["rendering_label_2974d0"]="rendering_label_stencil_test_complete"
    ["rendering_label_297469_2"]="rendering_label_stencil_test_setup_2"
    ["rendering_label_2974d0_2"]="rendering_label_stencil_test_complete_2"
    ["rendering_label_297469_3"]="rendering_label_stencil_test_setup_3"
    ["rendering_label_2974d0_3"]="rendering_label_stencil_test_complete_3"
    ["rendering_label_297508"]="rendering_label_stencil_test_validation"
    
    # 渲染裁剪相关标签
    ["rendering_label_2978c4"]="rendering_label_scissor_test_start"
    ["rendering_label_297b2c"]="rendering_label_scissor_test_process"
    ["rendering_label_2978c4_2"]="rendering_label_scissor_test_continue"
    ["rendering_label_297b2c_2"]="rendering_label_scissor_test_continue_2"
    ["rendering_label_297858"]="rendering_label_scissor_test_setup"
    ["rendering_label_2978c4_3"]="rendering_label_scissor_test_setup_2"
    ["rendering_label_297b2c_3"]="rendering_label_scissor_test_complete"
    ["rendering_label_297858_2"]="rendering_label_scissor_test_setup_3"
    ["rendering_label_2978c4_4"]="rendering_label_scissor_test_setup_4"
    ["rendering_label_297b2c_4"]="rendering_label_scissor_test_complete_2"
    ["rendering_label_297b63"]="rendering_label_scissor_test_validation"
    
    # 渲染多边形相关标签
    ["rendering_label_299abc"]="rendering_label_polygon_mode_start"
    ["rendering_label_299abc_2"]="rendering_label_polygon_mode_continue"
    ["rendering_label_299abc_3"]="rendering_label_polygon_mode_continue_2"
    ["rendering_label_299f92"]="rendering_label_polygon_mode_process"
    ["rendering_label_29a2da"]="rendering_label_polygon_mode_complete"
    ["rendering_label_29a7f6"]="rendering_label_polygon_validation_start"
    
    # 渲染线宽相关标签
    ["rendering_label_29f52c"]="rendering_label_line_width_start"
    ["rendering_label_29fd67"]="rendering_label_line_width_process"
    ["rendering_label_29fdb7"]="rendering_label_line_width_continue"
    ["rendering_label_29fd67_2"]="rendering_label_line_width_continue_2"
    ["rendering_label_29fdb7_2"]="rendering_label_line_width_continue_3"
    ["rendering_label_29fef7"]="rendering_label_line_width_check"
    ["rendering_label_29fefa"]="rendering_label_line_width_complete"
    ["rendering_label_29ff14"]="rendering_label_line_width_validation_start"
    ["rendering_label_29ff32"]="rendering_label_line_width_validation_complete"
    ["rendering_label_29ff52"]="rendering_label_line_width_setup_start"
    ["rendering_label_2a0071"]="rendering_label_line_width_setup_complete"
    ["rendering_label_29ffc7"]="rendering_label_line_width_cleanup_start"
    ["rendering_label_2a0010"]="rendering_label_line_width_cleanup_complete"
    
    # 渲染点大小相关标签
    ["rendering_label_3007a9"]="rendering_label_point_size_start"
    ["rendering_label_300827"]="rendering_label_point_size_process"
    ["rendering_label_30083c"]="rendering_label_point_size_complete"
    
    # 渲染多边形偏移相关标签
    ["rendering_label_301bf4"]="rendering_label_polygon_offset_start"
    ["rendering_label_301c02"]="rendering_label_polygon_offset_setup"
    ["rendering_label_301ce4"]="rendering_label_polygon_offset_process"
    ["rendering_label_301de0"]="rendering_label_polygon_offset_complete"
    ["rendering_label_30200e"]="rendering_label_polygon_offset_validation"
    
    # 渲染逻辑操作相关标签
    ["rendering_label_3039b0"]="rendering_label_logic_op_start"
    
    # 渲染帧缓冲区相关标签
    ["rendering_label_3066f9"]="rendering_label_framebuffer_start"
    ["rendering_label_3066f9_2"]="rendering_label_framebuffer_continue"
    ["rendering_label_306bfe"]="rendering_label_framebuffer_setup"
    ["rendering_label_3075e0"]="rendering_label_framebuffer_process"
    ["rendering_label_307880"]="rendering_label_framebuffer_validation_start"
    ["rendering_label_3078fd"]="rendering_label_framebuffer_validation_process"
    ["rendering_label_307986"]="rendering_label_framebuffer_validation_complete"
    ["rendering_label_3084bf"]="rendering_label_framebuffer_complete"
    
    # 渲染渲染缓冲区相关标签
    ["rendering_label_30a42d"]="rendering_label_renderbuffer_start"
    ["rendering_label_30a65e"]="rendering_label_renderbuffer_process"
    ["rendering_label_30a662"]="rendering_label_renderbuffer_complete"
    
    # 渲染纹理对象相关标签
    ["rendering_label_30b860"]="rendering_label_texture_object_start"
    ["rendering_label_30be84"]="rendering_label_texture_object_setup"
    ["rendering_label_30bf14"]="rendering_label_texture_object_process"
    ["rendering_label_30bfe4"]="rendering_label_texture_object_continue"
    ["rendering_label_30c071"]="rendering_label_texture_object_check"
    ["rendering_label_30c0c0"]="rendering_label_texture_object_complete"
    ["rendering_label_30c93f"]="rendering_label_texture_object_validation"
    ["rendering_label_30c136"]="rendering_label_texture_object_cleanup_start"
    ["rendering_label_30c154"]="rendering_label_texture_object_cleanup_process"
    ["rendering_label_30c270"]="rendering_label_texture_object_cleanup_continue"
    ["rendering_label_30c2f0"]="rendering_label_texture_object_cleanup_check"
    ["rendering_label_30c347"]="rendering_label_texture_object_cleanup_complete"
    ["rendering_label_30c3ca"]="rendering_label_texture_object_finalize_start"
    ["rendering_label_30c390"]="rendering_label_texture_object_finalize_process"
    ["rendering_label_30c400"]="rendering_label_texture_object_finalize_continue"
    ["rendering_label_30c410"]="rendering_label_texture_object_finalize_complete"
    ["rendering_label_30c490"]="rendering_label_texture_object_error_start"
    ["rendering_label_30c4af"]="rendering_label_texture_object_error_process"
    ["rendering_label_30c4f0"]="rendering_label_texture_object_error_complete"
    ["rendering_label_30c530"]="rendering_label_texture_object_status_start"
    ["rendering_label_30c5a4"]="rendering_label_texture_object_status_process"
    ["rendering_label_30c5a6"]="rendering_label_texture_object_status_complete"
    ["rendering_label_30c631"]="rendering_label_texture_object_binding_start"
    ["rendering_label_30c6d0"]="rendering_label_texture_object_binding_process"
    ["rendering_label_30c6f3"]="rendering_label_texture_object_binding_complete"
    ["rendering_label_30c834"]="rendering_label_texture_object_unbind_start"
    ["rendering_label_30c89f"]="rendering_label_texture_object_unbind_process"
    ["rendering_label_30c575"]="rendering_label_texture_object_unbind_complete"
    ["rendering_label_30cb58"]="rendering_label_texture_object_delete_start"
    ["rendering_label_30d0ba"]="rendering_label_texture_object_delete_process"
    ["rendering_label_30d7a4"]="rendering_label_texture_object_delete_complete"
    ["rendering_label_30d811"]="rendering_label_texture_object_validation_start"
    ["rendering_label_30dd85"]="rendering_label_texture_object_validation_process"
    ["rendering_label_30e1fe"]="rendering_label_texture_object_validation_complete"
    ["rendering_label_30e1b3"]="rendering_label_texture_object_copy_start"
    ["rendering_label_30e535"]="rendering_label_texture_object_copy_process"
    ["rendering_label_30e7dc"]="rendering_label_texture_object_copy_complete"
    
    # 渲染采样器相关标签
    ["rendering_label_316e53"]="rendering_label_sampler_start"
    ["rendering_label_316799"]="rendering_label_sampler_complete"
    
    # 渲染着色器程序相关标签
    ["rendering_label_319258"]="rendering_label_shader_program_start"
    ["rendering_label_3192f8"]="rendering_label_shader_program_setup"
    ["rendering_label_3197a7"]="rendering_label_shader_program_process"
    ["rendering_label_319bc0"]="rendering_label_shader_program_complete"
    
    # 渲染查询对象相关标签
    ["rendering_label_31d4d2"]="rendering_label_query_object_start"
    ["rendering_label_31df5a"]="rendering_label_query_object_setup"
    ["rendering_label_31e20e"]="rendering_label_query_object_process"
    ["rendering_label_31eaf0"]="rendering_label_query_object_continue"
    ["rendering_label_31ebd1"]="rendering_label_query_object_check"
    ["rendering_label_31ee56"]="rendering_label_query_object_complete"
    ["rendering_label_31f63b"]="rendering_label_query_object_result_start"
    ["rendering_label_31f56e"]="rendering_label_query_object_result_process"
    ["rendering_label_31f63b_2"]="rendering_label_query_object_result_continue"
    ["rendering_label_31f56e_2"]="rendering_label_query_object_result_continue_2"
    ["rendering_label_31f56e_3"]="rendering_label_query_object_result_complete"
    ["rendering_label_31f8bd"]="rendering_label_query_object_validation_start"
    ["rendering_label_31f8f7"]="rendering_label_query_object_validation_complete"
    
    # 渲染同步对象相关标签
    ["rendering_label_32285f"]="rendering_label_sync_object_start"
    ["rendering_label_322608"]="rendering_label_sync_object_setup"
    ["rendering_label_322b1e"]="rendering_label_sync_object_process"
    ["rendering_label_322b26"]="rendering_label_sync_object_continue"
    ["rendering_label_322c61"]="rendering_label_sync_object_check"
    ["rendering_label_322d80"]="rendering_label_sync_object_complete"
    ["rendering_label_322fe3"]="rendering_label_sync_object_validation_start"
    ["rendering_label_32321b"]="rendering_label_sync_object_validation_process"
    ["rendering_label_322fe3_2"]="rendering_label_sync_object_validation_continue"
    ["rendering_label_32321b_2"]="rendering_label_sync_object_validation_continue_2"
    ["rendering_label_3234fc"]="rendering_label_sync_object_validation_complete"
    ["rendering_label_323a8e"]="rendering_label_sync_object_cleanup_start"
    ["rendering_label_323be7"]="rendering_label_sync_object_cleanup_process"
    ["rendering_label_323c2a"]="rendering_label_sync_object_cleanup_complete"
    
    # 渲染缓冲区映射相关标签
    ["rendering_label_324489"]="rendering_label_buffer_mapping_start"
    ["rendering_label_324528"]="rendering_label_buffer_mapping_setup"
    ["rendering_label_3246bb"]="rendering_label_buffer_mapping_process"
    ["rendering_label_32510e"]="rendering_label_buffer_mapping_continue"
    ["rendering_label_325116"]="rendering_label_buffer_mapping_check"
    ["rendering_label_325204"]="rendering_label_buffer_mapping_complete"
    ["rendering_label_3251e4"]="rendering_label_buffer_mapping_error"
    ["rendering_label_3258ac"]="rendering_label_buffer_mapping_unmap_start"
    ["rendering_label_3265ac"]="rendering_label_buffer_mapping_unmap_process"
    ["rendering_label_3268c5"]="rendering_label_buffer_mapping_unmap_continue"
    ["rendering_label_32693e"]="rendering_label_buffer_mapping_unmap_complete"
    ["rendering_label_326da7"]="rendering_label_buffer_mapping_validation_start"
    ["rendering_label_326e7a"]="rendering_label_buffer_mapping_validation_complete"
    ["rendering_label_326f61"]="rendering_label_buffer_mapping_flush_start"
    ["rendering_label_327199"]="rendering_label_buffer_mapping_flush_process"
    ["rendering_label_327215"]="rendering_label_buffer_mapping_flush_complete"
    
    # 渲染缓冲区复制相关标签
    ["rendering_label_328172"]="rendering_label_buffer_copy_start"
    ["rendering_label_328174"]="rendering_label_buffer_copy_setup"
    ["rendering_label_3281b0"]="rendering_label_buffer_copy_process"
    ["rendering_label_3281b2"]="rendering_label_buffer_copy_continue"
    ["rendering_label_328601"]="rendering_label_buffer_copy_complete"
    
    # 渲染缓冲区子数据相关标签
    ["rendering_label_3290bf"]="rendering_label_buffer_subdata_start"
    ["rendering_label_32967d"]="rendering_label_buffer_subdata_setup"
    ["rendering_label_32967f"]="rendering_label_buffer_subdata_continue"
    ["rendering_label_32967d_2"]="rendering_label_buffer_subdata_process"
    ["rendering_label_32967f_2"]="rendering_label_buffer_subdata_continue_2"
    ["rendering_label_329ed7"]="rendering_label_buffer_subdata_complete"
    
    # 渲染纹理图像相关标签
    ["rendering_label_333594"]="rendering_label_texture_image_start"
    ["rendering_label_32b0f4"]="rendering_label_texture_image_setup"
    ["rendering_label_32b314"]="rendering_label_texture_image_process"
    ["rendering_label_32b522"]="rendering_label_texture_image_continue"
    ["rendering_label_32b629"]="rendering_label_texture_image_check"
    ["rendering_label_32b6ff"]="rendering_label_texture_image_complete"
    ["rendering_label_32b82c"]="rendering_label_texture_image_validation"
    ["rendering_label_32c711"]="rendering_label_texture_image_subdata_start"
    ["rendering_label_32c882"]="rendering_label_texture_image_subdata_process"
    ["rendering_label_32d19c"]="rendering_label_texture_image_subdata_complete"
    ["rendering_label_32d06c"]="rendering_label_texture_image_copy_start"
    ["rendering_label_32d78f"]="rendering_label_texture_image_copy_process"
    ["rendering_label_32e50f"]="rendering_label_texture_image_copy_continue"
    ["rendering_label_32e5ed"]="rendering_label_texture_image_copy_check"
    ["rendering_label_32e696"]="rendering_label_texture_image_copy_complete"
    ["rendering_label_32e74e"]="rendering_label_texture_image_validation_start"
    ["rendering_label_32f27b"]="rendering_label_texture_image_validation_process"
    ["rendering_label_32f333"]="rendering_label_texture_image_validation_complete"
    
    # 渲染纹理参数相关标签
    ["rendering_label_330378"]="rendering_label_texture_parameter_start"
    ["rendering_label_33084a"]="rendering_label_texture_parameter_setup"
    ["rendering_label_3310be"]="rendering_label_texture_parameter_process"
    ["rendering_label_330e61"]="rendering_label_texture_parameter_continue"
    ["rendering_label_330f00"]="rendering_label_texture_parameter_check"
    ["rendering_label_331625"]="rendering_label_texture_parameter_complete"
    ["rendering_label_331688"]="rendering_label_texture_parameter_validation_start"
    ["rendering_label_33173f"]="rendering_label_texture_parameter_validation_process"
    ["rendering_label_331a35"]="rendering_label_texture_parameter_validation_complete"
    ["rendering_label_331a9e"]="rendering_label_texture_parameter_cleanup_start"
    ["rendering_label_331b54"]="rendering_label_texture_parameter_cleanup_process"
    ["rendering_label_332267"]="rendering_label_texture_parameter_cleanup_complete"
    
    # 渲染纹理层级相关标签
    ["rendering_label_332829"]="rendering_label_texture_level_start"
    ["rendering_label_33290a"]="rendering_label_texture_level_setup"
    ["rendering_label_3329a3"]="rendering_label_texture_level_process"
    ["rendering_label_332f24"]="rendering_label_texture_level_complete"
    ["rendering_label_333054"]="rendering_label_texture_level_validation"
    ["rendering_label_3330f8"]="rendering_label_texture_level_generate_start"
    ["rendering_label_333594_2"]="rendering_label_texture_level_generate_process"
    ["rendering_label_3337df"]="rendering_label_texture_level_generate_continue"
    ["rendering_label_333bb3"]="rendering_label_texture_level_generate_check"
    ["rendering_label_333bee"]="rendering_label_texture_level_generate_complete"
    ["rendering_label_333cae"]="rendering_label_texture_level_generate_validation"
    ["rendering_label_333e7e"]="rendering_label_texture_level_generate_cleanup_start"
    ["rendering_label_333eb9"]="rendering_label_texture_level_generate_cleanup_process"
    ["rendering_label_333fbc"]="rendering_label_texture_level_generate_cleanup_complete"
    
    # 渲染纹理绑定相关标签
    ["rendering_label_334893"]="rendering_label_texture_bind_start"
    ["rendering_label_334893_2"]="rendering_label_texture_bind_continue"
    ["rendering_label_3349b9"]="rendering_label_texture_bind_process"
    ["rendering_label_3358a2"]="rendering_label_texture_bind_complete"
    ["rendering_label_33615b"]="rendering_label_texture_bind_validation"
    ["rendering_label_3367cd"]="rendering_label_texture_bind_unbind_start"
    ["rendering_label_333bb3_2"]="rendering_label_texture_bind_unbind_process"
    ["rendering_label_333bee_2"]="rendering_label_texture_bind_unbind_continue"
    ["rendering_label_333cae_2"]="rendering_label_texture_bind_unbind_check"
    ["rendering_label_333e7e_2"]="rendering_label_texture_bind_unbind_complete"
    ["rendering_label_333eb9_2"]="rendering_label_texture_bind_unbind_cleanup"
    ["rendering_label_333fbc_2"]="rendering_label_texture_bind_unbind_validation"
    
    # 渲染纹理单元相关标签
    ["rendering_label_336f0c"]="rendering_label_texture_unit_start"
    ["rendering_label_337007"]="rendering_label_texture_unit_setup"
    ["rendering_label_336f0c_2"]="rendering_label_texture_unit_continue"
    ["rendering_label_337007_2"]="rendering_label_texture_unit_setup_2"
    ["rendering_label_337537"]="rendering_label_texture_unit_process"
    ["rendering_label_337537_2"]="rendering_label_texture_unit_continue_2"
    ["rendering_label_337706"]="rendering_label_texture_unit_complete"
    ["rendering_label_337706_2"]="rendering_label_texture_unit_continue_3"
    ["rendering_label_337de9"]="rendering_label_texture_unit_validation"
    ["rendering_label_337de9_2"]="rendering_label_texture_unit_validation_2"
    ["rendering_label_337feb"]="rendering_label_texture_unit_cleanup_start"
    ["rendering_label_337feb_2"]="rendering_label_texture_unit_cleanup_continue"
    ["rendering_label_338b93"]="rendering_label_texture_unit_cleanup_complete"
    ["rendering_label_338d21"]="rendering_label_texture_unit_error_start"
    ["rendering_label_33928d"]="rendering_label_texture_unit_error_process"
    ["rendering_label_339296"]="rendering_label_texture_unit_error_complete"
    ["rendering_label_339fdc"]="rendering_label_texture_unit_status_start"
    ["rendering_label_339fdc_2"]="rendering_label_texture_unit_status_continue"
    ["rendering_label_33a781"]="rendering_label_texture_unit_status_complete"
    
    # 渲染着色器统一变量相关标签
    ["rendering_label_33b2fa"]="rendering_label_shader_uniform_start"
    ["rendering_label_33b418"]="rendering_label_shader_uniform_setup"
    ["rendering_label_33bb62"]="rendering_label_shader_uniform_process"
    ["rendering_label_33bb65"]="rendering_label_shader_uniform_continue"
    ["rendering_label_33bbd2"]="rendering_label_shader_uniform_complete"
    ["rendering_label_33c21b"]="rendering_label_shader_uniform_validation_start"
    ["rendering_label_33c588"]="rendering_label_shader_uniform_validation_process"
    ["rendering_label_33c6c0"]="rendering_label_shader_uniform_validation_continue"
    ["rendering_label_33c6e9"]="rendering_label_shader_uniform_validation_check"
    ["rendering_label_33c811"]="rendering_label_shader_uniform_validation_complete"
    ["rendering_label_33c7d1"]="rendering_label_shader_uniform_cleanup_start"
    ["rendering_label_33e4da"]="rendering_label_shader_uniform_cleanup_process"
    ["rendering_label_33e55d"]="rendering_label_shader_uniform_cleanup_continue"
    ["rendering_label_33e648"]="rendering_label_shader_uniform_cleanup_check"
    ["rendering_label_33e6d2"]="rendering_label_shader_uniform_cleanup_complete"
    ["rendering_label_33e7b1"]="rendering_label_shader_uniform_finalize_start"
    ["rendering_label_33e834"]="rendering_label_shader_uniform_finalize_complete"
    
    # 渲染顶点属性相关标签
    ["rendering_label_346068"]="rendering_label_vertex_attribute_start"
    ["rendering_label_3464ba"]="rendering_label_vertex_attribute_setup"
    ["rendering_label_346795"]="rendering_label_vertex_attribute_process"
    ["rendering_label_347b86"]="rendering_label_vertex_attribute_complete"
    ["rendering_label_34826e"]="rendering_label_vertex_attribute_validation"
    ["rendering_label_348b85"]="rendering_label_vertex_attribute_cleanup"
    
    # 渲染顶点缓冲区相关标签
    ["rendering_label_34a4ee"]="rendering_label_vertex_buffer_start"
    ["rendering_label_34b77d"]="rendering_label_vertex_buffer_setup"
    ["rendering_label_34bcb4"]="rendering_label_vertex_buffer_process"
    ["rendering_label_34c020"]="rendering_label_vertex_buffer_continue"
    ["rendering_label_34bfb2"]="rendering_label_vertex_buffer_complete"
    ["rendering_label_34da6e"]="rendering_label_vertex_buffer_validation_start"
    ["rendering_label_34da95"]="rendering_label_vertex_buffer_validation_process"
    ["rendering_label_34eafd"]="rendering_label_vertex_buffer_validation_complete"
    
    # 渲染索引缓冲区相关标签
    ["rendering_label_3513a7"]="rendering_label_index_buffer_start"
    ["rendering_label_351429"]="rendering_label_index_buffer_setup"
    ["rendering_label_3514da"]="rendering_label_index_buffer_process"
    ["rendering_label_35163a"]="rendering_label_index_buffer_continue"
    ["rendering_label_351c06"]="rendering_label_index_buffer_check"
    ["rendering_label_35179a"]="rendering_label_index_buffer_complete"
    ["rendering_label_351b84"]="rendering_label_index_buffer_validation"
    
    # 渲染顶点数组对象相关标签
    ["rendering_label_353f85"]="rendering_label_vertex_array_start"
    ["rendering_label_35436c"]="rendering_label_vertex_array_setup"
    ["rendering_label_3550fe"]="rendering_label_vertex_array_process"
    ["rendering_label_35510c"]="rendering_label_vertex_array_continue"
    ["rendering_label_355291"]="rendering_label_vertex_array_complete"
    ["rendering_label_358c7e"]="rendering_label_vertex_array_validation_start"
    ["rendering_label_358c86"]="rendering_label_vertex_array_validation_process"
    ["rendering_label_359b5e"]="rendering_label_vertex_array_validation_continue"
    ["rendering_label_359b66"]="rendering_label_vertex_array_validation_complete"
    ["rendering_label_35a6fd"]="rendering_label_vertex_array_cleanup"
    
    # 渲染绘制缓冲区相关标签
    ["rendering_label_35cc63"]="rendering_label_draw_buffer_start"
    ["rendering_label_35dfab"]="rendering_label_draw_buffer_setup"
    ["rendering_label_35de70"]="rendering_label_draw_buffer_process"
    ["rendering_label_35dfab_2"]="rendering_label_draw_buffer_continue"
    ["rendering_label_35de70_2"]="rendering_label_draw_buffer_continue_2"
    ["rendering_label_35f156"]="rendering_label_draw_buffer_complete"
    ["rendering_label_35f156_2"]="rendering_label_draw_buffer_continue_3"
    ["rendering_label_35f156_3"]="rendering_label_draw_buffer_validation"
    
    # 渲染读取缓冲区相关标签
    ["rendering_label_361877"]="rendering_label_read_buffer_start"
    ["rendering_label_361882"]="rendering_label_read_buffer_setup"
    ["rendering_label_362e84"]="rendering_label_read_buffer_process"
    ["rendering_label_363542"]="rendering_label_read_buffer_continue"
    ["rendering_label_3660ff"]="rendering_label_read_buffer_complete"
    ["rendering_label_3660ff_2"]="rendering_label_read_buffer_continue_2"
    ["rendering_label_3660ff_3"]="rendering_label_read_buffer_validation_start"
    ["rendering_label_363fdd"]="rendering_label_read_buffer_validation_process"
    ["rendering_label_36405b"]="rendering_label_read_buffer_validation_continue"
    ["rendering_label_3640e8"]="rendering_label_read_buffer_validation_complete"
    ["rendering_label_3660ff_4"]="rendering_label_read_buffer_cleanup_start"
    ["rendering_label_36460e"]="rendering_label_read_buffer_cleanup_process"
    ["rendering_label_3652ed"]="rendering_label_read_buffer_cleanup_continue"
    ["rendering_label_365176"]="rendering_label_read_buffer_cleanup_continue_2"
    ["rendering_label_364a9b"]="rendering_label_read_buffer_cleanup_check"
    ["rendering_label_364b3d"]="rendering_label_read_buffer_cleanup_continue_3"
    ["rendering_label_364c1e"]="rendering_label_read_buffer_cleanup_complete"
    ["rendering_label_364d42"]="rendering_label_read_buffer_error_start"
    ["rendering_label_3652ed_2"]="rendering_label_read_buffer_error_process"
    ["rendering_label_365176_2"]="rendering_label_read_buffer_error_continue"
    ["rendering_label_3652ed_3"]="rendering_label_read_buffer_error_continue_2"
    ["rendering_label_365176_3"]="rendering_label_read_buffer_error_continue_3"
    ["rendering_label_365659"]="rendering_label_read_buffer_error_complete"
    ["rendering_label_365659_2"]="rendering_label_read_buffer_error_continue_4"
    ["rendering_label_365659_3"]="rendering_label_read_buffer_validation_2"
    ["rendering_label_365e4a"]="rendering_label_read_buffer_finalize_start"
    ["rendering_label_3660ff_5"]="rendering_label_read_buffer_finalize_process"
    ["rendering_label_3660ff_6"]="rendering_label_read_buffer_finalize_continue"
    ["rendering_label_3660ff_7"]="rendering_label_read_buffer_finalize_complete"
    ["rendering_label_366d62"]="rendering_label_read_buffer_status_start"
    ["rendering_label_3672a8"]="rendering_label_read_buffer_status_process"
    ["rendering_label_36764f"]="rendering_label_read_buffer_status_continue"
    ["rendering_label_3678fd"]="rendering_label_read_buffer_status_complete"
    ["rendering_label_367be6"]="rendering_label_read_buffer_status_validation"
    ["rendering_label_367d65"]="rendering_label_read_buffer_status_cleanup_start"
    ["rendering_label_367fe6"]="rendering_label_read_buffer_status_cleanup_process"
    ["rendering_label_36813f"]="rendering_label_read_buffer_status_cleanup_continue"
    ["rendering_label_368378"]="rendering_label_read_buffer_status_cleanup_complete"
    ["rendering_label_366f7d"]="rendering_label_read_buffer_error_handling_start"
    ["rendering_label_366fc4"]="rendering_label_read_buffer_error_handling_process"
    ["rendering_label_3688af"]="rendering_label_read_buffer_error_handling_continue"
    ["rendering_label_3689cb"]="rendering_label_read_buffer_error_handling_complete"
    ["rendering_label_368be1"]="rendering_label_read_buffer_error_handling_validation"
    ["rendering_label_368d81"]="rendering_label_read_buffer_error_handling_cleanup_start"
    ["rendering_label_368ddf"]="rendering_label_read_buffer_error_handling_cleanup_complete"
    
    # 渲染像素操作相关标签
    ["rendering_label_36c07e"]="rendering_label_pixel_operation_start"
    ["rendering_label_36c17c"]="rendering_label_pixel_operation_setup"
    ["rendering_label_36c3f5"]="rendering_label_pixel_operation_process"
    ["rendering_label_36c2fc"]="rendering_label_pixel_operation_continue"
    ["rendering_label_36c470"]="rendering_label_pixel_operation_complete"
    ["rendering_label_36d227"]="rendering_label_pixel_operation_validation"
    ["rendering_label_36d232"]="rendering_label_pixel_operation_cleanup"
    ["rendering_label_36d8be"]="rendering_label_pixel_operation_error_start"
    ["rendering_label_36dafe"]="rendering_label_pixel_operation_error_process"
    ["rendering_label_36dafe_2"]="rendering_label_pixel_operation_error_continue"
    ["rendering_label_37198e"]="rendering_label_pixel_operation_error_complete"
    
    # 渲染像素传输相关标签
    ["rendering_label_3725b4"]="rendering_label_pixel_transfer_start"
    ["rendering_label_372c0c"]="rendering_label_pixel_transfer_setup"
    ["rendering_label_372cf0"]="rendering_label_pixel_transfer_process"
    ["rendering_label_372de8"]="rendering_label_pixel_transfer_continue"
    ["rendering_label_372e98"]="rendering_label_pixel_transfer_complete"
    ["rendering_label_37309e"]="rendering_label_pixel_transfer_validation_start"
    ["rendering_label_37321d"]="rendering_label_pixel_transfer_validation_process"
    ["rendering_label_37336c"]="rendering_label_pixel_transfer_validation_continue"
    ["rendering_label_373428"]="rendering_label_pixel_transfer_validation_complete"
    ["rendering_label_373580"]="rendering_label_pixel_transfer_cleanup_start"
    ["rendering_label_373799"]="rendering_label_pixel_transfer_cleanup_process"
    ["rendering_label_373878"]="rendering_label_pixel_transfer_cleanup_complete"
    ["rendering_label_372c0c_2"]="rendering_label_pixel_transfer_continue_2"
    ["rendering_label_372cf0_2"]="rendering_label_pixel_transfer_process_2"
    ["rendering_label_372de8_2"]="rendering_label_pixel_transfer_continue_3"
    ["rendering_label_372e98_2"]="rendering_label_pixel_transfer_complete_2"
    ["rendering_label_37309e_2"]="rendering_label_pixel_transfer_validation_start_2"
    ["rendering_label_37321d_2"]="rendering_label_pixel_transfer_validation_process_2"
    ["rendering_label_37336c_2"]="rendering_label_pixel_transfer_validation_continue_2"
    ["rendering_label_373428_2"]="rendering_label_pixel_transfer_validation_complete_2"
    ["rendering_label_373580_2"]="rendering_label_pixel_transfer_cleanup_start_2"
    ["rendering_label_373799_2"]="rendering_label_pixel_transfer_cleanup_process_2"
    ["rendering_label_373878_2"]="rendering_label_pixel_transfer_cleanup_complete_2"
    ["rendering_label_37309e_3"]="rendering_label_pixel_transfer_validation_start_3"
    ["rendering_label_37321d_3"]="rendering_label_pixel_transfer_validation_process_3"
    ["rendering_label_37336c_3"]="rendering_label_pixel_transfer_validation_continue_3"
    ["rendering_label_373428_3"]="rendering_label_pixel_transfer_validation_complete_3"
    ["rendering_label_373580_3"]="rendering_label_pixel_transfer_cleanup_start_3"
    ["rendering_label_373799_3"]="rendering_label_pixel_transfer_cleanup_process_3"
    ["rendering_label_373878_3"]="rendering_label_pixel_transfer_cleanup_complete_3"
    ["rendering_label_373580_4"]="rendering_label_pixel_transfer_cleanup_start_4"
    ["rendering_label_373799_4"]="rendering_label_pixel_transfer_cleanup_process_4"
    ["rendering_label_373878_4"]="rendering_label_pixel_transfer_cleanup_complete_4"
    ["rendering_label_373428_4"]="rendering_label_pixel_transfer_validation_complete_4"
    ["rendering_label_37309e_4"]="rendering_label_pixel_transfer_validation_start_4"
    ["rendering_label_37321d_4"]="rendering_label_pixel_transfer_validation_process_4"
    ["rendering_label_37336c_4"]="rendering_label_pixel_transfer_validation_continue_4"
    ["rendering_label_373510"]="rendering_label_pixel_transfer_error_handling_start"
    ["rendering_label_373580_5"]="rendering_label_pixel_transfer_error_handling_process"
    ["rendering_label_373799_5"]="rendering_label_pixel_transfer_error_handling_continue"
    ["rendering_label_373878_5"]="rendering_label_pixel_transfer_error_handling_complete"
    ["rendering_label_37397f"]="rendering_label_pixel_transfer_error_handling_validation"
    ["rendering_label_373799_6"]="rendering_label_pixel_transfer_finalize_start"
    ["rendering_label_373878_6"]="rendering_label_pixel_transfer_finalize_process"
    ["rendering_label_373562"]="rendering_label_pixel_transfer_finalize_continue"
    ["rendering_label_37321d_5"]="rendering_label_pixel_transfer_finalize_process_2"
    ["rendering_label_37336c_5"]="rendering_label_pixel_transfer_finalize_continue_2"
    ["rendering_label_373428_5"]="rendering_label_pixel_transfer_finalize_complete"
    ["rendering_label_37309e_5"]="rendering_label_pixel_transfer_finalize_validation_start"
    ["rendering_label_373510_2"]="rendering_label_pixel_transfer_finalize_validation_process"
    ["rendering_label_373580_6"]="rendering_label_pixel_transfer_finalize_validation_continue"
    ["rendering_label_373799_7"]="rendering_label_pixel_transfer_finalize_validation_complete"
    ["rendering_label_373878_7"]="rendering_label_pixel_transfer_finalize_validation_cleanup"
    
    # 渲染像素映射相关标签
    ["rendering_label_374230"]="rendering_label_pixel_mapping_start"
    ["rendering_label_374a51"]="rendering_label_pixel_mapping_setup"
    ["rendering_label_374a51_2"]="rendering_label_pixel_mapping_continue"
    ["rendering_label_3760d1"]="rendering_label_pixel_mapping_process"
    ["rendering_label_375e41"]="rendering_label_pixel_mapping_continue_2"
    ["rendering_label_37619a"]="rendering_label_pixel_mapping_check"
    ["rendering_label_37624d"]="rendering_label_pixel_mapping_complete"
    ["rendering_label_3763e0"]="rendering_label_pixel_mapping_validation"
    ["rendering_label_376825"]="rendering_label_pixel_mapping_cleanup_start"
    ["rendering_label_3768c9"]="rendering_label_pixel_mapping_cleanup_complete"
    ["rendering_label_3760d1_2"]="rendering_label_pixel_mapping_continue_3"
    ["rendering_label_375e41_2"]="rendering_label_pixel_mapping_continue_4"
    ["rendering_label_37619a_2"]="rendering_label_pixel_mapping_check_2"
    ["rendering_label_37624d_2"]="rendering_label_pixel_mapping_complete_2"
    ["rendering_label_3763e0_2"]="rendering_label_pixel_mapping_validation_2"
    ["rendering_label_376825_2"]="rendering_label_pixel_mapping_cleanup_start_2"
    ["rendering_label_3768c5"]="rendering_label_pixel_mapping_cleanup_continue"
    ["rendering_label_3760d1_3"]="rendering_label_pixel_mapping_continue_5"
    ["rendering_label_375e41_3"]="rendering_label_pixel_mapping_continue_6"
    ["rendering_label_37619a_3"]="rendering_label_pixel_mapping_check_3"
    ["rendering_label_37624d_3"]="rendering_label_pixel_mapping_complete_3"
    ["rendering_label_3763e0_3"]="rendering_label_pixel_mapping_validation_3"
    ["rendering_label_376825_3"]="rendering_label_pixel_mapping_cleanup_start_3"
    ["rendering_label_3768c5_2"]="rendering_label_pixel_mapping_cleanup_continue_2"
    ["rendering_label_3768c5_3"]="rendering_label_pixel_mapping_cleanup_complete_2"
    ["rendering_label_3760d1_4"]="rendering_label_pixel_mapping_continue_7"
    ["rendering_label_375e41_4"]="rendering_label_pixel_mapping_continue_8"
    ["rendering_label_37619a_4"]="rendering_label_pixel_mapping_check_4"
    ["rendering_label_37624d_4"]="rendering_label_pixel_mapping_complete_4"
    ["rendering_label_3763e0_4"]="rendering_label_pixel_mapping_validation_4"
    ["rendering_label_376825_4"]="rendering_label_pixel_mapping_cleanup_start_4"
    ["rendering_label_3768c5_4"]="rendering_label_pixel_mapping_cleanup_continue_3"
    ["rendering_label_3768c5_5"]="rendering_label_pixel_mapping_cleanup_complete_3"
    ["rendering_label_3768c5_6"]="rendering_label_pixel_mapping_finalize"
    
    # 渲染像素存储相关标签
    ["rendering_label_377195"]="rendering_label_pixel_storage_start"
    ["rendering_label_377666"]="rendering_label_pixel_storage_setup"
    ["rendering_label_377829"]="rendering_label_pixel_storage_process"
    ["rendering_label_37777e"]="rendering_label_pixel_storage_continue"
    ["rendering_label_377195_2"]="rendering_label_pixel_storage_continue_2"
    ["rendering_label_377666_2"]="rendering_label_pixel_storage_setup_2"
    ["rendering_label_377829_2"]="rendering_label_pixel_storage_process_2"
    ["rendering_label_37777e_2"]="rendering_label_pixel_storage_continue_3"
    ["rendering_label_377195_3"]="rendering_label_pixel_storage_continue_4"
    ["rendering_label_377666_3"]="rendering_label_pixel_storage_setup_3"
    ["rendering_label_377829_3"]="rendering_label_pixel_storage_process_3"
    ["rendering_label_37777e_3"]="rendering_label_pixel_storage_continue_5"
    ["rendering_label_377195_4"]="rendering_label_pixel_storage_continue_6"
    ["rendering_label_377666_4"]="rendering_label_pixel_storage_setup_4"
    ["rendering_label_3777ad"]="rendering_label_pixel_storage_continue_7"
    ["rendering_label_3782ba"]="rendering_label_pixel_storage_complete"
    ["rendering_label_377195_5"]="rendering_label_pixel_storage_continue_8"
    ["rendering_label_377666_5"]="rendering_label_pixel_storage_setup_5"
    ["rendering_label_3777ad_2"]="rendering_label_pixel_storage_continue_9"
    ["rendering_label_377666_6"]="rendering_label_pixel_storage_continue_10"
    ["rendering_label_3777ad_3"]="rendering_label_pixel_storage_continue_11"
    ["rendering_label_3782ba_2"]="rendering_label_pixel_storage_continue_12"
    ["rendering_label_377195_6"]="rendering_label_pixel_storage_validation_start"
    ["rendering_label_377666_7"]="rendering_label_pixel_storage_validation_process"
    ["rendering_label_378603"]="rendering_label_pixel_storage_validation_continue"
    ["rendering_label_378603_2"]="rendering_label_pixel_storage_validation_continue_2"
    ["rendering_label_378a14"]="rendering_label_pixel_storage_validation_complete"
    ["rendering_label_378e96"]="rendering_label_pixel_storage_cleanup_start"
    ["rendering_label_379446"]="rendering_label_pixel_storage_cleanup_process"
    ["rendering_label_379a3f"]="rendering_label_pixel_storage_cleanup_continue"
    ["rendering_label_379c5f"]="rendering_label_pixel_storage_cleanup_complete"
    ["rendering_label_37a051"]="rendering_label_pixel_storage_finalize_start"
    ["rendering_label_37a1d9"]="rendering_label_pixel_storage_finalize_process"
    ["rendering_label_37a2de"]="rendering_label_pixel_storage_finalize_continue"
    ["rendering_label_37a35a"]="rendering_label_pixel_storage_finalize_complete"
    ["rendering_label_37a524"]="rendering_label_pixel_storage_validation_2"
    
    # 渲染光栅化相关标签
    ["rendering_label_37b5a5"]="rendering_label_rasterization_start"
    ["rendering_label_37b81a"]="rendering_label_rasterization_setup"
    ["rendering_label_37b8b4"]="rendering_label_rasterization_process"
    ["rendering_label_37b943"]="rendering_label_rasterization_continue"
    ["rendering_label_37b9e3"]="rendering_label_rasterization_check"
    ["rendering_label_37bab0"]="rendering_label_rasterization_complete"
    ["rendering_label_37bb4c"]="rendering_label_rasterization_validation"
    
    # 渲染片元操作相关标签
    ["rendering_label_37cbba"]="rendering_label_fragment_operation_start"
    ["rendering_label_37cdee"]="rendering_label_fragment_operation_setup"
    ["rendering_label_37cfde"]="rendering_label_fragment_operation_process"
    ["rendering_label_37d26b"]="rendering_label_fragment_operation_continue"
    ["rendering_label_37d51b"]="rendering_label_fragment_operation_check"
    ["rendering_label_37da2d"]="rendering_label_fragment_operation_complete"
    ["rendering_label_37da9b"]="rendering_label_fragment_operation_validation"
    ["rendering_label_37dd34"]="rendering_label_fragment_operation_cleanup_start"
    ["rendering_label_37de35"]="rendering_label_fragment_operation_cleanup_process"
    ["rendering_label_37de7b"]="rendering_label_fragment_operation_cleanup_continue"
    ["rendering_label_37dee0"]="rendering_label_fragment_operation_cleanup_complete"
    ["rendering_label_37dfa4"]="rendering_label_fragment_operation_error_start"
    ["rendering_label_37e056"]="rendering_label_fragment_operation_error_process"
    ["rendering_label_37e0f4"]="rendering_label_fragment_operation_error_continue"
    ["rendering_label_37e219"]="rendering_label_fragment_operation_error_complete"
    ["rendering_label_37e1f0"]="rendering_label_fragment_operation_error_handling_start"
    ["rendering_label_37e3a1"]="rendering_label_fragment_operation_error_handling_process"
    ["rendering_label_37e3c4"]="rendering_label_fragment_operation_error_handling_complete"
    ["rendering_label_37e5ea"]="rendering_label_fragment_operation_finalize_start"
    ["rendering_label_37ea1e"]="rendering_label_fragment_operation_finalize_process"
    ["rendering_label_37eb8c"]="rendering_label_fragment_operation_finalize_continue"
    ["rendering_label_37f0fe"]="rendering_label_fragment_operation_finalize_complete"
    ["rendering_label_37f493"]="rendering_label_fragment_operation_validation_start"
    ["rendering_label_37f493_2"]="rendering_label_fragment_operation_validation_continue"
    ["rendering_label_37f5a2"]="rendering_label_fragment_operation_validation_process"
    ["rendering_label_37f5a5"]="rendering_label_fragment_operation_validation_continue_2"
    ["rendering_label_37f612"]="rendering_label_fragment_operation_validation_complete"
    ["rendering_label_37f716"]="rendering_label_fragment_operation_validation_cleanup"
    
    # 渲染帧缓冲区操作相关标签
    ["rendering_label_380a8a"]="rendering_label_framebuffer_operation_start"
    ["rendering_label_381183"]="rendering_label_framebuffer_operation_setup"
    ["rendering_label_381521"]="rendering_label_framebuffer_operation_process"
    ["rendering_label_381523"]="rendering_label_framebuffer_operation_continue"
    ["rendering_label_38159d"]="rendering_label_framebuffer_operation_check"
    ["rendering_label_3815a1"]="rendering_label_framebuffer_operation_complete"
    ["rendering_label_3815a5"]="rendering_label_framebuffer_operation_validation"
    ["rendering_label_38175b"]="rendering_label_framebuffer_operation_cleanup_start"
    ["rendering_label_381826"]="rendering_label_framebuffer_operation_cleanup_process"
    ["rendering_label_381874"]="rendering_label_framebuffer_operation_cleanup_continue"
    ["rendering_label_381921"]="rendering_label_framebuffer_operation_cleanup_complete"
    ["rendering_label_38199b"]="rendering_label_framebuffer_operation_error_start"
    ["rendering_label_381a10"]="rendering_label_framebuffer_operation_error_process"
    ["rendering_label_381a49"]="rendering_label_framebuffer_operation_error_continue"
    ["rendering_label_381ad4"]="rendering_label_framebuffer_operation_error_complete"
    ["rendering_label_381b06"]="rendering_label_framebuffer_operation_error_handling_start"
    ["rendering_label_381b0b"]="rendering_label_framebuffer_operation_error_handling_process"
    ["rendering_label_381c05"]="rendering_label_framebuffer_operation_error_handling_continue"
    ["rendering_label_381cc0"]="rendering_label_framebuffer_operation_error_handling_complete"
    ["rendering_label_381d06"]="rendering_label_framebuffer_operation_error_handling_validation"
    ["rendering_label_3818ee"]="rendering_label_framebuffer_operation_finalize_start"
    ["rendering_label_381dd0"]="rendering_label_framebuffer_operation_finalize_process"
    ["rendering_label_381e4e"]="rendering_label_framebuffer_operation_finalize_continue"
    ["rendering_label_381f08"]="rendering_label_framebuffer_operation_finalize_complete"
    ["rendering_label_3821e7"]="rendering_label_framebuffer_operation_validation_start"
    ["rendering_label_382055"]="rendering_label_framebuffer_operation_validation_process"
    ["rendering_label_3820d4"]="rendering_label_framebuffer_operation_validation_continue"
    ["rendering_label_3820b0"]="rendering_label_framebuffer_operation_validation_check"
    ["rendering_label_382172"]="rendering_label_framebuffer_operation_validation_complete"
    ["rendering_label_382245"]="rendering_label_framebuffer_operation_validation_cleanup"
    ["rendering_label_382298"]="rendering_label_framebuffer_operation_validation_finalize"
    
    # 渲染同步相关标签
    ["rendering_label_383325"]="rendering_label_synchronization_start"
    ["rendering_label_383399"]="rendering_label_synchronization_setup"
    ["rendering_label_3833bf"]="rendering_label_synchronization_process"
    ["rendering_label_383325_2"]="rendering_label_synchronization_continue"
    ["rendering_label_383399_2"]="rendering_label_synchronization_setup_2"
    ["rendering_label_3833bf_2"]="rendering_label_synchronization_process_2"
    ["rendering_label_3836dc"]="rendering_label_synchronization_complete"
    ["rendering_label_38375c"]="rendering_label_synchronization_validation"
    
    # 渲染状态查询相关标签
    ["rendering_label_3851ae"]="rendering_label_state_query_start"
    ["rendering_label_385551"]="rendering_label_state_query_process"
    ["rendering_label_3863b6"]="rendering_label_state_query_complete"
    ["rendering_label_3868bb"]="rendering_label_state_query_validation"
    ["rendering_label_3863b6_2"]="rendering_label_state_query_continue"
    ["rendering_label_386a1b"]="rendering_label_state_query_continue_2"
    ["rendering_label_386ae7"]="rendering_label_state_query_check"
    ["rendering_label_386d6a"]="rendering_label_state_query_cleanup_start"
    ["rendering_label_386d68"]="rendering_label_state_query_cleanup_process"
    ["rendering_label_386d88"]="rendering_label_state_query_cleanup_complete"
    ["rendering_label_3870a3"]="rendering_label_state_query_error_start"
    ["rendering_label_38706d"]="rendering_label_state_query_error_process"
    ["rendering_label_3870a3_2"]="rendering_label_state_query_error_continue"
    ["rendering_label_38706d_2"]="rendering_label_state_query_error_continue_2"
    ["rendering_label_38776f"]="rendering_label_state_query_error_complete"
    ["rendering_label_387772"]="rendering_label_state_query_error_handling_start"
    ["rendering_label_3870a3_3"]="rendering_label_state_query_error_handling_process"
    ["rendering_label_38706d_3"]="rendering_label_state_query_error_handling_continue"
    ["rendering_label_3870a3_4"]="rendering_label_state_query_error_handling_complete"
)

# 要处理的文件
input_file="/dev/shm/mountblade-code/TaleWorlds.Native/src/03_rendering.c"

# 创建临时文件
temp_file=$(mktemp)

# 复制原文件到临时文件
cp "$input_file" "$temp_file"

# 执行替换操作
for old_label in "${!label_mappings[@]}"; do
    new_label="${label_mappings[$old_label]}"
    echo "替换: $old_label -> $new_label"
    sed -i "s/$old_label/$new_label/g" "$temp_file"
done

# 替换回原文件
mv "$temp_file" "$input_file"

echo "标签名语义化美化完成"