#!/bin/bash

# 批量替换UI系统偏移量常量的脚本
# 这个脚本用于将04_ui_system.c文件中的数字偏移量常量替换为语义化的常量名

INPUT_FILE="/dev/shm/mountblade-code/TaleWorlds.Native/src/04_ui_system.c"
TEMP_FILE="/tmp/ui_system_temp.c"

# 创建临时文件
cp "$INPUT_FILE" "$TEMP_FILE"

# 替换偏移量常量
sed -i 's/UI_OFFSET_22/UI_OFFSET_CALLBACK_DATA/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_28/UI_OFFSET_WIDGET_CONFIG/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_32/UI_OFFSET_RENDER_DATA/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_60/UI_OFFSET_EVENT_QUEUE/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_68/UI_OFFSET_INPUT_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_72/UI_OFFSET_LAYOUT_CONFIG/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_80/UI_OFFSET_ANIMATION_CONFIG/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_88/UI_OFFSET_THEME_CONFIG/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_104/UI_OFFSET_RESOURCE_HANDLE/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_120/UI_OFFSET_TEXTURE_HANDLE/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_136/UI_OFFSET_SHADER_HANDLE/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_152/UI_OFFSET_VERTEX_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_160/UI_OFFSET_INDEX_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_168/UI_OFFSET_UNIFORM_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_172/UI_OFFSET_FRAME_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_184/UI_OFFSET_RENDER_TARGET/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_188/UI_OFFSET_DEPTH_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_220/UI_OFFSET_STENCIL_BUFFER/g' "$TEMP_FILE"
sed -i 's/UI_OFFSET_228/UI_OFFSET_COMMAND_BUFFER/g' "$TEMP_FILE"

# 更新原文件
mv "$TEMP_FILE" "$INPUT_FILE"

echo "UI系统偏移量常量替换完成"