using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;
using TaleWorlds.Localization;

namespace TaleWorlds.CampaignSystem.Party.PartyComponents
{
	// Token: 0x020002AC RID: 684
	public abstract class PartyComponent
	{
		// Token: 0x060027A9 RID: 10153 RVA: 0x000AA50C File Offset: 0x000A870C
		protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
		}

		// Token: 0x170009F4 RID: 2548
		// (get) Token: 0x060027AA RID: 10154 RVA: 0x000AA50E File Offset: 0x000A870E
		// (set) Token: 0x060027AB RID: 10155 RVA: 0x000AA516 File Offset: 0x000A8716
		public MobileParty MobileParty { get; private set; }

		// Token: 0x170009F5 RID: 2549
		// (get) Token: 0x060027AC RID: 10156 RVA: 0x000AA51F File Offset: 0x000A871F
		public PartyBase Party
		{
			get
			{
				return this.MobileParty.Party;
			}
		}

		// Token: 0x170009F6 RID: 2550
		// (get) Token: 0x060027AD RID: 10157
		public abstract Hero PartyOwner { get; }

		// Token: 0x170009F7 RID: 2551
		// (get) Token: 0x060027AE RID: 10158
		public abstract TextObject Name { get; }

		// Token: 0x170009F8 RID: 2552
		// (get) Token: 0x060027AF RID: 10159
		public abstract Settlement HomeSettlement { get; }

		// Token: 0x170009F9 RID: 2553
		// (get) Token: 0x060027B0 RID: 10160 RVA: 0x000AA52C File Offset: 0x000A872C
		public virtual bool AvoidHostileActions
		{
			get
			{
				return false;
			}
		}

		// Token: 0x170009FA RID: 2554
		// (get) Token: 0x060027B1 RID: 10161 RVA: 0x000AA52F File Offset: 0x000A872F
		public virtual int WagePaymentLimit
		{
			get
			{
				return Campaign.Current.Models.PartyWageModel.MaxWage;
			}
		}

		// Token: 0x060027B2 RID: 10162 RVA: 0x000AA545 File Offset: 0x000A8745
		public virtual void SetWagePaymentLimit(int newLimit)
		{
			Debug.FailedAssert("Invalid set wage payment limit function usage!", "C:\\Develop\\MB3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyComponents\\PartyComponent.cs", "SetWagePaymentLimit", 28);
		}

		// Token: 0x170009FB RID: 2555
		// (get) Token: 0x060027B3 RID: 10163 RVA: 0x000AA55D File Offset: 0x000A875D
		public virtual Hero Leader
		{
			get
			{
				return null;
			}
		}

		// Token: 0x060027B4 RID: 10164 RVA: 0x000AA560 File Offset: 0x000A8760
		internal void SetMobilePartyInternal(MobileParty party)
		{
			this.MobileParty = party;
		}

		// Token: 0x060027B5 RID: 10165 RVA: 0x000AA569 File Offset: 0x000A8769
		internal void Initialize(MobileParty party)
		{
			this.SetMobilePartyInternal(party);
			this.OnInitialize();
		}

		// Token: 0x060027B6 RID: 10166 RVA: 0x000AA578 File Offset: 0x000A8778
		internal void Finish()
		{
			this.OnFinalize();
		}

		// Token: 0x060027B7 RID: 10167 RVA: 0x000AA580 File Offset: 0x000A8780
		protected virtual void OnInitialize()
		{
		}

		// Token: 0x060027B8 RID: 10168 RVA: 0x000AA582 File Offset: 0x000A8782
		protected virtual void OnFinalize()
		{
		}

		// Token: 0x060027B9 RID: 10169 RVA: 0x000AA584 File Offset: 0x000A8784
		public virtual void ClearCachedName()
		{
		}

		// Token: 0x060027BA RID: 10170 RVA: 0x000AA586 File Offset: 0x000A8786
		public virtual void ChangePartyLeader(Hero newLeader)
		{
		}

		// Token: 0x060027BB RID: 10171 RVA: 0x000AA588 File Offset: 0x000A8788
		public virtual void GetMountAndHarnessVisualIdsForPartyIcon(PartyBase party, out string mountStringId, out string harnessStringId)
		{
			mountStringId = "";
			harnessStringId = "";
		}

		// Token: 0x020005D2 RID: 1490
		// (Invoke) Token: 0x06004772 RID: 18290
		public delegate void OnPartyComponentCreatedDelegate(MobileParty mobileParty);
	}
}
